#!/usr/bin/env python3
"""Audit Suno/AI-music methodology transfer before prompt compile.

The goal is not to reward more prompt lore. This gate checks whether the
project explains which methodology sources are being used, how those ideas were
translated into this specific song, which community tricks remain experimental,
and why the selected Suno/provider route fits the human-likeness goal.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from audit_music_external_method_claims import (
    OUTPUT as EXTERNAL_METHOD_CLAIM_AUDIT,
    external_method_claim_audit_ready,
)


PLAN_FILE = "04_prompt/methodology-transfer-plan.md"
DEFAULT_OUTPUT = "04_prompt/methodology-transfer-audit.md"
DEFAULT_SOURCE_ROOT = Path("/path/to/suno-prompt-methodology")
MARKER = "Generated by: tools/audit_music_methodology_transfer.py"

REQUIRED_LOCAL_SOURCE_RELS = [
    "资料索引.md",
    "local Suno prompt methodology知识笔记.md",
    "templates/suno-prompt-template.md",
    "templates/suno-prompt-review-checklist.md",
    "sources/official-clean-md/official-detailed-style-instructions.md",
    "sources/official-clean-md/official-better-prompts-lyrics.md",
    "sources/official-clean-md/official-creative-sliders.md",
    "sources/official-clean-md/official-exclude-elements.md",
]

OPTIONAL_HIGH_VALUE_RELS = [
    "sources/official-clean-md/official-upload-audio.md",
    "sources/official-clean-md/official-personas.md",
    "sources/official-clean-md/official-song-editor.md",
    "sources/official-clean-md/official-replace-section.md",
    "GitHub/suno-song-creator-plugin/skills/suno-song-creator/references/model-comparison.md",
    "GitHub/suno-song-creator-plugin/skills/suno-song-creator/references/realism-descriptors.md",
    "GitHub/suno-song-creator-plugin/skills/suno-song-creator/references/genre-clouds.md",
    "GitHub/suno-song-creator-plugin/skills/suno-song-creator/references/meta-tags-reference.md",
]

EMPTY_VALUES = {
    "",
    '""',
    "''",
    "todo",
    "tbd",
    "pending",
    "unknown",
    "unclear",
    "missing",
    "n/a",
    "na",
    "none",
    "yes/no",
    "pass/fail",
    "-",
    "--",
}

OFFICIAL_SURFACE_PATTERNS = {
    "style": r"\bstyle\b|style of music|风格",
    "lyrics": r"\blyrics?\b|lyrics box|歌词",
    "exclude": r"\bexclude\b|排除",
    "sliders": r"weirdness|style influence|audio influence|creative sliders|滑杆|参数",
    "audio_upload": r"audio upload|uploaded audio|audio influence|cover|上传音频|音频上传",
    "voice": r"\bvoice\b|voices|声线|声音",
    "persona": r"persona|人设",
    "custom_model": r"custom model|自定义模型",
    "my_taste": r"my taste|taste|偏好",
    "prompt_boost": r"prompt boost|boosted|增强",
    "editor": r"song editor|studio|replace section|extend|add vocals|局部|编辑|替换|延长",
    "remi": r"\bremi\b|lyric model|歌词模型",
}

PROTECTED_IDENTITY_NAMES = [
    "米津玄师",
    "YOASOBI",
    "Ado",
    "Official髭男dism",
    "King Gnu",
    "宇多田光",
    "Perfume",
    "あいみょん",
    "当山",
    "KOKIA",
    "周杰伦",
    "林俊杰",
    "陈奕迅",
    "邓紫棋",
    "薛之谦",
    "毛不易",
    "蔡徐坤",
    "BTS",
    "BLACKPINK",
    "IU",
    "EXO",
    "Stray Kids",
    "NewJeans",
    "aespa",
    "SEVENTEEN",
    "Taylor Swift",
    "The Weeknd",
    "Billie Eilish",
    "Dua Lipa",
    "Olivia Rodrigo",
    "Harry Styles",
    "Drake",
    "Ed Sheeran",
    "ONE OK ROCK",
    "MY FIRST STORY",
    "RADWIMPS",
    "Mrs. GREEN APPLE",
    "BUMP OF CHICKEN",
    "凛として時雨",
    "ASIAN KUNG-FU GENERATION",
    "Babymetal",
    "五月天",
    "万能青年旅店",
    "草东没有派对",
    "痛仰",
    "告五人",
    "回春丹",
    "DAY6",
    "FTISLAND",
    "CNBLUE",
    "JANNABI",
    "The Rose",
    "N.Flying",
    "Xdinary Heroes",
    "LUCY",
    "Arctic Monkeys",
    "Imagine Dragons",
    "Twenty One Pilots",
    "Foo Fighters",
    "Radiohead",
    "Måneskin",
    "Green Day",
    "The 1975",
]


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


def read_project(project_root: Path) -> dict[str, str]:
    docs: dict[str, str] = {}
    for path in project_root.rglob("*.md"):
        rel = path.relative_to(project_root).as_posix()
        try:
            docs[rel] = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            docs[rel] = path.read_text(errors="replace")
    return docs


def normalize_value(raw: str) -> str:
    value = raw.strip().strip("`")
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1].strip()
    value = re.sub(r"\s+", " ", value)
    if value.casefold() in EMPTY_VALUES:
        return ""
    if value.startswith("[") and value.endswith("]") and ":" in value:
        return ""
    return value


def scan_key_values(text: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|"):
            continue
        stripped = re.sub(r"^[-*]\s+", "", stripped)
        match = re.match(r"^([^:]{1,110}):\s*(.*)$", stripped)
        if not match:
            continue
        label = re.sub(r"\s+", " ", match.group(1).strip()).casefold()
        value = normalize_value(match.group(2))
        pairs.append((label, value))
    return pairs


def extract_value(docs: dict[str, str], paths: list[str], labels: list[str]) -> str:
    wanted = {re.sub(r"\s+", " ", label.strip()).casefold() for label in labels}
    for rel in paths:
        for label, value in scan_key_values(docs.get(rel, "")):
            if label in wanted and value:
                return value
    return ""


def positive_value(value: str) -> bool:
    return bool(re.search(r"\b(yes|enabled|on|true|use|active)\b|开启|使用|启用", value, re.I))


def protected_identity_hits(text: str) -> list[str]:
    hits: list[str] = []
    for name in PROTECTED_IDENTITY_NAMES:
        if re.fullmatch(r"[A-Za-z0-9 .'\-&]+", name):
            pattern = rf"(?<![A-Za-z0-9]){re.escape(name)}(?![A-Za-z0-9])"
            found = re.search(pattern, text, flags=re.I)
        else:
            found = name.casefold() in text.casefold()
        if found:
            hits.append(name)
    return hits


def unresolved_protected_identity(text: str) -> list[str]:
    hits: list[str] = []
    lowered = text.casefold()
    for name in protected_identity_hits(text):
        pattern = re.escape(name)
        match = re.search(pattern, text, flags=re.I)
        window = ""
        if match:
            start = max(0, match.start() - 80)
            end = min(len(text), match.end() + 80)
            window = text[start:end].casefold()
        safe_context = bool(
            re.search(
                r"remove|removed|reject|rejected|not use|do not use|avoid|forbidden|neutral|style dna|去身份|移除|拒绝|不用|禁止|中性|抽象",
                window or lowered,
                re.I,
            )
        )
        if not safe_context:
            hits.append(name)
    return hits


def surfaces_from_text(text: str) -> list[str]:
    found: list[str] = []
    for key, pattern in OFFICIAL_SURFACE_PATTERNS.items():
        if re.search(pattern, text, re.I):
            found.append(key)
    return found


def term_is_negated(text: str, pattern: str) -> bool:
    for match in re.finditer(pattern, text, flags=re.I):
        start = max(0, match.start() - 80)
        end = min(len(text), match.end() + 80)
        window = text[start:end]
        if re.search(r"\b(no|not|without|inactive|unused|disabled|off|none|avoid|reject|rejected|do not|don't)\b|不使用|不用|未启用|关闭|拒绝|避免", window, re.I):
            return True
    return False


def active_route(text: str, pattern: str) -> bool:
    return bool(re.search(pattern, text, re.I)) and not term_is_negated(text, pattern)


def unrejected_magic_claim(text: str) -> bool:
    pattern = r"guarantee|guaranteed|secret|magic|viral|100%|必爆|神 prompt|万能|绝对"
    return active_route(text, pattern)


def has_date_like(value: str) -> bool:
    return bool(re.search(r"\b20\d{2}[-/年.]\d{1,2}([-/.月]\d{1,2})?\b|最近|本轮|current|latest|二次检索", value, re.I))


def check_source_root(source_root: Path) -> tuple[list[Finding], list[str], list[str]]:
    findings: list[Finding] = []
    ready: list[str] = []
    optional_ready: list[str] = []

    if not source_root.exists() or not source_root.is_dir():
        findings.append(
            Finding(
                "blocker",
                "local_method_source_root_missing",
                f"local Suno methodology source root does not exist: {source_root}",
                "restore /path/to/suno-prompt-methodology or pass --source-root",
            )
        )
        return findings, ready, optional_ready

    for rel in REQUIRED_LOCAL_SOURCE_RELS:
        path = source_root / rel
        if path.exists():
            ready.append(rel)
        else:
            findings.append(
                Finding(
                    "blocker",
                    "local_method_source_missing",
                    f"local methodology source is not available: {rel}",
                    "refresh the local Suno prompt methodology source folder",
                )
            )

    for rel in OPTIONAL_HIGH_VALUE_RELS:
        if (source_root / rel).exists():
            optional_ready.append(rel)

    if len(optional_ready) < 3:
        findings.append(
            Finding(
                "warning",
                "local_method_optional_sources_thin",
                "high-value optional methodology references are thin; model/tool route may lack local comparison context.",
                "refresh GitHub/plugin references and official clean-md snapshots when possible",
            )
        )

    return findings, ready, optional_ready


def analyze(project_root: Path, docs: dict[str, str], source_root: Path) -> tuple[dict[str, str], list[Finding], list[str], list[str]]:
    plan = docs.get(PLAN_FILE, "")
    source_findings, local_ready, optional_ready = check_source_root(source_root)
    findings: list[Finding] = list(source_findings)

    if not external_method_claim_audit_ready(project_root):
        findings.append(
            Finding(
                "blocker",
                "external_method_claim_audit_not_passed",
                f"{EXTERNAL_METHOD_CLAIM_AUDIT} must be generated by tools/audit_music_external_method_claims.py with Decision: pass before methodology transfer",
                "run audit_music_external_method_claims.py",
            )
        )

    plan_paths = [PLAN_FILE]
    style_paths = ["04_prompt/style-field-map.md"]
    slider_paths = ["04_prompt/slider-intent-map.md"]
    identity_paths = ["04_prompt/persona-voice-model-routing.md"]
    reference_paths = [
        "02_references/reference-boundary.md",
        "02_references/style-dna-card.md",
        "02_references/reference-dna-audit.md",
    ]

    fields = {
        "local_method_sources": extract_value(docs, plan_paths, ["Local method sources", "Local sources", "本地方法来源"]),
        "official_control_surfaces": extract_value(docs, plan_paths, ["Official control surfaces", "Official surfaces", "官方控制面"]),
        "community_candidates": extract_value(docs, plan_paths, ["Community / external candidates", "Community candidates", "External candidates", "社区候选"]),
        "source_confidence_split": extract_value(docs, plan_paths, ["Source confidence split", "Confidence split", "可信度分层"]),
        "adopted_method": extract_value(docs, plan_paths, ["Adopted method", "Adopted methodology", "采用方法"]),
        "song_specific_transfer": extract_value(docs, plan_paths, ["Song-specific transfer", "Current-song transfer", "Song transfer", "本歌转译"]),
        "model_rationale": extract_value(docs, plan_paths, ["Model/version rationale", "Model rationale", "模型版本理由"]),
        "primary_tool_route": extract_value(docs, plan_paths + reference_paths, ["Primary Suno tool route", "Primary tool route", "Suno tool choice", "Tool choice"]),
        "human_likeness_hypothesis": extract_value(docs, plan_paths, ["Human-likeness hypothesis", "Human likeness hypothesis", "真人感假设"]),
        "variable_discipline": extract_value(docs, plan_paths, ["Variable discipline", "One-variable batch plan", "变量纪律"]),
        "anti_magic": extract_value(docs, plan_paths, ["Rejected magic prompt claims", "Anti-magic safeguards", "反玄学保护"]),
        "protected_identity_safeguard": extract_value(docs, plan_paths, ["Protected-identity safeguard", "Protected identity safeguard", "去身份保护"]),
        "validation_metric": extract_value(docs, plan_paths, ["Validation metric", "Blind validation metric", "验证指标"]),
        "rollback_condition": extract_value(docs, plan_paths, ["Drift/rollback condition", "Rollback condition", "回滚条件"]),
        "source_freshness": extract_value(docs, plan_paths, ["Source freshness", "Last checked", "资料时效"]),
        "style_genre": extract_value(docs, style_paths, ["genre"]),
        "style_vocal": extract_value(docs, style_paths, ["vocal"]),
        "style_production": extract_value(docs, style_paths, ["production"]),
        "exclude": extract_value(docs, ["04_prompt/exclude-negative-aesthetic.md"], ["Exclude", "Exclude term"]),
        "model": extract_value(docs, slider_paths, ["Model"]),
        "weirdness": extract_value(docs, slider_paths, ["Weirdness"]),
        "style_influence": extract_value(docs, slider_paths, ["Style Influence"]),
        "audio_influence": extract_value(docs, slider_paths, ["Audio Influence"]),
        "phase": extract_value(docs, slider_paths, ["Phase"]),
        "what_this_tests": extract_value(docs, slider_paths, ["What this tests"]),
        "human_anchor_lane": extract_value(docs, identity_paths + plan_paths, ["Human anchor lane", "Anchor lane", "Feature type"]),
        "voice_identity_source": extract_value(docs, identity_paths, ["Voice identity source", "Voice source"]),
        "persona_source": extract_value(docs, identity_paths, ["Persona source", "Source song"]),
        "custom_model_source": extract_value(docs, identity_paths, ["Custom Model source", "Custom model source"]),
        "custom_model_corpus": extract_value(docs, identity_paths, ["Custom model corpus", "Custom Model corpus", "Source song / voice / dataset"]),
        "my_taste_state": extract_value(docs, identity_paths, ["My Taste state", "My Taste enabled"]),
        "my_taste_summary": extract_value(docs, identity_paths, ["My Taste summary"]),
        "prompt_boost_state": extract_value(docs, identity_paths, ["Prompt boost state", "Prompt Boost enabled"]),
        "boosted_style_text": extract_value(docs, identity_paths, ["Boosted style text", "Boosted prompt"]),
    }

    if not plan:
        findings.append(Finding("blocker", "methodology_transfer_plan_missing", f"{PLAN_FILE} is not available.", "fill methodology-transfer-plan.md"))

    required = [
        ("local_method_sources_missing", fields["local_method_sources"], "Local Suno methodology sources are not named.", "fill Local method sources"),
        ("official_control_surfaces_missing", fields["official_control_surfaces"], "Official control surfaces are not named.", "fill Official control surfaces"),
        ("source_confidence_split_missing", fields["source_confidence_split"], "Source confidence split is not recorded.", "separate official/local/community evidence"),
        ("song_specific_transfer_missing", fields["song_specific_transfer"], "Methodology is not translated into this song's concrete choices.", "fill Song-specific transfer"),
        ("model_rationale_missing", fields["model_rationale"], "Model/version rationale is not recorded.", "fill Model/version rationale"),
        ("primary_tool_route_missing", fields["primary_tool_route"], "Primary Suno/provider route is not recorded.", "fill Primary tool route"),
        ("human_likeness_hypothesis_missing", fields["human_likeness_hypothesis"], "Human-likeness hypothesis is not recorded.", "fill Human-likeness hypothesis"),
        ("variable_discipline_missing", fields["variable_discipline"], "One-variable discipline is not recorded.", "fill Variable discipline"),
        ("anti_magic_missing", fields["anti_magic"], "Rejected magic-prompt claims are not recorded.", "fill Rejected magic prompt claims"),
        ("protected_identity_safeguard_missing", fields["protected_identity_safeguard"], "Protected-identity safeguard is not recorded.", "fill Protected-identity safeguard"),
        ("validation_metric_missing", fields["validation_metric"], "Blind validation metric is not recorded.", "fill Validation metric"),
        ("rollback_condition_missing", fields["rollback_condition"], "Drift/rollback condition is not recorded.", "fill rollback condition"),
        ("source_freshness_missing", fields["source_freshness"], "Source freshness is not recorded.", "record local/web source check date or freshness note"),
    ]
    for code, value, message, route in required:
        if not value:
            findings.append(Finding("blocker", code, message, route))

    if fields["local_method_sources"] and not re.search(r"local Suno prompt methodology|/path/to/suno-prompt-methodology|local|本地", fields["local_method_sources"], re.I):
        findings.append(
            Finding(
                "blocker",
                "local_method_source_not_linked",
                "Local method sources do not point back to the local Suno prompt methodology folder.",
                "include /path/to/suno-prompt-methodology in Local method sources",
            )
        )

    source_split = fields["source_confidence_split"]
    if source_split:
        for term, code in [
            (r"official|官方", "source_split_official_missing"),
            (r"local|本地|local Suno prompt methodology", "source_split_local_missing"),
            (r"community|external|video|bilibili|douyin|youtube|github|社区|外部|视频|候选", "source_split_external_missing"),
        ]:
            if not re.search(term, source_split, re.I):
                findings.append(
                    Finding(
                        "blocker",
                        code,
                        "Source confidence split must separate official, local, and community/external material.",
                        "rewrite Source confidence split",
                    )
                )

    surfaces = surfaces_from_text(fields["official_control_surfaces"] + " " + fields["adopted_method"] + " " + fields["song_specific_transfer"])
    if len(surfaces) < 3:
        findings.append(
            Finding(
                "blocker",
                "official_surfaces_too_thin",
                "Methodology transfer names fewer than three concrete control surfaces.",
                "map Style, Lyrics, Exclude, Sliders, identity, audio, or editor surfaces",
            )
        )

    combined_route = " ".join([fields["primary_tool_route"], fields["human_anchor_lane"], fields["adopted_method"], fields["song_specific_transfer"]])
    if active_route(combined_route, r"audio upload|cover|uploaded audio|audio seed|audio influence|上传音频|音频"):
        if "audio_upload" not in surfaces and not re.search(r"audio upload|audio influence|上传音频", fields["official_control_surfaces"], re.I):
            findings.append(
                Finding(
                    "blocker",
                    "audio_route_without_surface",
                    "Audio route is active but Audio Upload/Audio Influence is not named as an official control surface.",
                    "add Audio Upload and Audio Influence to Official control surfaces",
                )
            )
        if not re.search(r"rights|source|permission|owned|授权|来源|权利|自有", fields["song_specific_transfer"] + " " + fields["protected_identity_safeguard"], re.I):
            findings.append(
                Finding(
                    "blocker",
                    "audio_route_without_source_rights",
                    "Audio route does not mention source/rights handling.",
                    "link audio-rights-ledger and source-rights evidence",
                )
            )

    identity_route = " ".join(
        [
            fields["human_anchor_lane"],
            fields["primary_tool_route"],
            fields["voice_identity_source"],
            fields["persona_source"],
            fields["custom_model_source"],
            fields["custom_model_corpus"],
            fields["my_taste_state"],
            fields["prompt_boost_state"],
        ]
    )
    if active_route(identity_route, r"voice|persona|custom model|my taste|prompt boost|声线|自定义|偏好"):
        if not re.search(r"voice|persona|custom model|my taste|prompt boost|voices|声线|自定义|偏好", fields["official_control_surfaces"], re.I):
            findings.append(
                Finding(
                    "blocker",
                    "identity_route_without_surface",
                    "Identity route is active but Voice/Persona/Custom Model/My Taste/Prompt Boost surface is not named.",
                    "add identity surfaces to Official control surfaces",
                )
            )
        if active_route(fields["human_anchor_lane"] + " " + fields["primary_tool_route"], r"voice|persona") and not (fields["voice_identity_source"] or fields["persona_source"]):
            findings.append(Finding("blocker", "identity_source_missing", "Voice/Persona route lacks source evidence.", "fill persona-voice-model-routing.md"))
        if active_route(fields["human_anchor_lane"] + " " + fields["primary_tool_route"], r"custom") and not (fields["custom_model_source"] or fields["custom_model_corpus"]):
            findings.append(Finding("blocker", "custom_model_source_missing", "Custom Model route lacks corpus/source evidence.", "fill custom model corpus"))
        if positive_value(fields["my_taste_state"]) and not fields["my_taste_summary"]:
            findings.append(Finding("blocker", "my_taste_summary_missing", "My Taste is active but preference summary is not recorded.", "fill My Taste summary"))
        if positive_value(fields["prompt_boost_state"]) and not fields["boosted_style_text"]:
            findings.append(Finding("blocker", "prompt_boost_text_missing", "Prompt Boost is active but boosted style text is not recorded.", "record boosted style text"))

    if fields["model"] and fields["model_rationale"] and fields["model"].casefold() == fields["model_rationale"].casefold():
        findings.append(Finding("warning", "model_rationale_repeats_model", "Model rationale only repeats the model name.", "explain why this model/version fits the song"))
    if fields["source_freshness"] and not has_date_like(fields["source_freshness"]):
        findings.append(Finding("warning", "source_freshness_weak", "Source freshness has no date-like or current-check wording.", "record source check date"))

    if fields["community_candidates"]:
        if unrejected_magic_claim(fields["community_candidates"]):
            findings.append(
                Finding(
                    "blocker",
                    "community_magic_claim",
                    "Community candidates contain magic/guaranteed-result language.",
                    "convert community claims into experiment hypotheses or reject them",
                )
            )
        if not re.search(r"candidate|experiment|test|hypothesis|verify|not rule|待验证|候选|实验|测试|非规则", fields["community_candidates"], re.I):
            findings.append(
                Finding(
                    "warning",
                    "community_candidate_not_flagged_experimental",
                    "Community/external candidates are not clearly marked as experiments.",
                    "mark community tips as hypotheses with validation metrics",
                )
            )

    if fields["anti_magic"] and not re.search(r"reject|rejected|avoid|not use|do not|candidate|experiment|refuse|拒绝|不用|避免|实验|候选", fields["anti_magic"], re.I):
        findings.append(
            Finding(
                "blocker",
                "anti_magic_not_actionable",
                "Anti-magic safeguard does not actually reject or sandbox weak claims.",
                "state what is rejected or only tested as a variable",
            )
        )

    variable_text = fields["variable_discipline"] + " " + fields["what_this_tests"] + " " + fields["phase"]
    if variable_text and not re.search(r"one|single|primary|constant|fixed|只改|单一|固定|保持", variable_text, re.I):
        findings.append(
            Finding(
                "blocker",
                "variable_discipline_not_testable",
                "Variable discipline does not define one primary variable or fixed controls.",
                "state one changed variable and what stays fixed",
            )
        )

    transfer_text = " ".join(
        [
            fields["song_specific_transfer"],
            fields["human_likeness_hypothesis"],
            fields["style_genre"],
            fields["style_vocal"],
            fields["style_production"],
            fields["exclude"],
        ]
    )
    if fields["song_specific_transfer"] and len(fields["song_specific_transfer"]) < 40:
        findings.append(
            Finding(
                "warning",
                "song_specific_transfer_thin",
                "Song-specific transfer is short; it may not constrain the actual prompt.",
                "connect methodology to title hook, vocal, groove, production, Exclude, or tool route",
            )
        )
    if transfer_text and unresolved_protected_identity(transfer_text):
        preview = ", ".join(unresolved_protected_identity(transfer_text)[:5])
        findings.append(
            Finding(
                "blocker",
                "protected_identity_unresolved",
                f"Methodology transfer contains protected artist/band names without rejection or neutralization: {preview}",
                "route to reference DNA and protected identity removal",
            )
        )

    if not fields["model"] or not fields["weirdness"] or not fields["style_influence"]:
        findings.append(
            Finding(
                "blocker",
                "slider_source_missing",
                "Model, Weirdness, and Style Influence must exist before methodology transfer can be attributed.",
                "fill slider-intent-map.md",
            )
        )

    return fields, findings, local_ready, optional_ready


def render_findings(findings: list[Finding]) -> str:
    if not findings:
        return "| severity | code | message | route |\n|---|---|---|---|\n| pass | none | methodology transfer approved | prompt compile |\n"
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    for item in findings:
        rows.append(f"| {item.severity} | {item.code} | {item.message} | {item.route} |")
    return "\n".join(rows) + "\n"


def render_audit(project_root: Path, source_root: Path, fields: dict[str, str], findings: list[Finding], local_ready: list[str], optional_ready: list[str]) -> str:
    blockers = [finding for finding in findings if finding.severity == "blocker"]
    decision = "pass" if not blockers else "repair before prompt compile"
    surface_tags = surfaces_from_text(fields.get("official_control_surfaces", "") + " " + fields.get("adopted_method", "") + " " + fields.get("song_specific_transfer", ""))
    return f"""# Methodology Transfer Audit

Decision: {decision}

## Methodology Transfer Evidence

Local source root: {source_root}
Local source status: {'ready' if not any(f.code.startswith('local_method_source') and f.severity == 'blocker' for f in findings) else 'repair'}
Local source files ready: {len(local_ready)}
Optional source files ready: {len(optional_ready)}
External method claims: {'pass' if external_method_claim_audit_ready(project_root) else 'missing or repair'}
Source confidence split: {fields.get('source_confidence_split', '')}
Official control surfaces: {fields.get('official_control_surfaces', '')}
Official surface tags: {', '.join(surface_tags) if surface_tags else ''}
Community candidates: {fields.get('community_candidates', '')}
Model/version rationale: {fields.get('model_rationale', '')}
Primary tool route: {fields.get('primary_tool_route', '')}
Human-likeness transfer: {fields.get('human_likeness_hypothesis', '')}
Song-specific transfer: {fields.get('song_specific_transfer', '')}
Variable discipline: {fields.get('variable_discipline', '')}
Anti-magic safeguards: {fields.get('anti_magic', '')}
Protected-identity safeguard: {fields.get('protected_identity_safeguard', '')}
Validation metric: {fields.get('validation_metric', '')}
Rollback condition: {fields.get('rollback_condition', '')}
Source freshness: {fields.get('source_freshness', '')}

## Project Prompt Links

Model: {fields.get('model', '')}
Weirdness: {fields.get('weirdness', '')}
Style Influence: {fields.get('style_influence', '')}
Audio Influence: {fields.get('audio_influence', '')}
Human anchor lane: {fields.get('human_anchor_lane', '')}
My Taste state: {fields.get('my_taste_state', '')}
Prompt Boost state: {fields.get('prompt_boost_state', '')}

## Findings

{render_findings(findings)}

Generated by: tools/audit_music_methodology_transfer.py
Project root: {project_root}
"""


def methodology_transfer_audit_ready(project_root: Path) -> bool:
    text = (project_root / DEFAULT_OUTPUT).read_text(encoding="utf-8") if (project_root / DEFAULT_OUTPUT).exists() else ""
    lowered = text.casefold()
    return (
        MARKER.casefold() in lowered
        and "decision: pass" in lowered
        and "## methodology transfer evidence" in lowered
        and "local source status: ready" in lowered
        and "external method claims: pass" in lowered
        and "source confidence split:" in lowered
        and "official control surfaces:" in lowered
        and "model/version rationale:" in lowered
        and "primary tool route:" in lowered
        and "human-likeness transfer:" in lowered
        and "variable discipline:" in lowered
        and "anti-magic safeguards:" in lowered
    )


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root created by create_music_song_project.py.")
    parser.add_argument("--source-root", default=str(DEFAULT_SOURCE_ROOT), help="Local Suno methodology source folder.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Relative output path for the audit.")
    parser.add_argument("--write", action="store_true", help="Write the audit file.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit.")
    parser.add_argument("--strict", action="store_true", help="Return exit code 1 when blockers remain.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    source_root = Path(args.source_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    docs = read_project(project_root)
    fields, findings, local_ready, optional_ready = analyze(project_root, docs, source_root)
    audit = render_audit(project_root, source_root, fields, findings, local_ready, optional_ready)
    blockers = [finding for finding in findings if finding.severity == "blocker"]

    if args.write:
        try:
            write_if_allowed(project_root / args.output, audit, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: output exists, use --allow-overwrite: {exc}", file=sys.stderr)
            return 2
    else:
        print(audit)

    if blockers:
        print(f"methodology transfer has {len(blockers)} blocker(s).", file=sys.stderr)
        for item in blockers:
            print(f"- {item.code}: {item.message} -> {item.route}", file=sys.stderr)
        return 1 if args.strict else 0

    print("methodology transfer approved.")
    print(f"audit: {project_root / args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
