#!/usr/bin/env python3
"""Audit whether a song brief fits an artist/catalog identity.

This gate runs early, before a project treats a single song as part of a
long-term artist system. One-off demos can be marked not applicable, but a
catalog song must explain its lane, identity fit, evolution, and validation
route before its prompt decisions become reusable artist memory.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


INPUT = "01_brief/catalog-fit.md"
OUTPUT = "01_brief/catalog-fit-audit.md"
MARKER = "Generated by: tools/audit_music_catalog_fit.py"

REQUIRED_FIELDS = {
    "Artist / catalog": ["Artist / catalog", "Artist", "Catalog", "Project"],
    "Catalog mode": ["Catalog mode", "Project mode"],
    "Song role": ["Song role", "Catalog role", "Role"],
    "Catalog lane": ["Catalog lane", "Lane"],
    "Identity fit": ["Identity fit", "Artist identity fit"],
    "Sonic signature fit": ["Sonic signature fit", "Sonic fit"],
    "Lyric universe fit": ["Lyric universe fit", "Lyric fit"],
    "Vocal identity fit": ["Vocal identity fit", "Vocal fit"],
    "Difference from previous songs": ["Difference from previous songs", "Evolution", "New contrast"],
    "Do not repeat": ["Do not repeat", "Banned repeat", "Avoid repeating"],
    "Protected identity boundary": ["Protected identity boundary", "Reference boundary", "Protected identity"],
    "Validation route": ["Validation route", "Catalog validation", "Blind validation"],
    "Catalog decision": ["Catalog decision", "Decision"],
}

PLACEHOLDERS = {
    "",
    "tbd",
    "todo",
    "n/a",
    "na",
    "none",
    "unknown",
    "placeholder",
    "fill in",
    "填写",
    "待定",
    "-",
}

PROTECTED_COPY_TERMS = [
    "copy artist",
    "clone artist",
    "sound exactly like",
    "same voice as",
    "impersonate",
    "模仿某某",
    "克隆",
    "同款声线",
    "一模一样",
]


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


@dataclass(frozen=True)
class CatalogFitAudit:
    project_root: Path
    values: dict[str, str]
    blockers: list[Finding]
    warnings: list[Finding]
    not_applicable: bool

    @property
    def decision(self) -> str:
        if self.blockers:
            return "hold"
        if self.not_applicable:
            return "not applicable"
        return "pass"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def normalize(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().strip('"')).strip()


def has_value(value: str) -> bool:
    normalized = normalize(value).casefold()
    return normalized not in PLACEHOLDERS and not re.fullmatch(r"[-_/ ]*", normalized)


def label_value(text: str, labels: list[str]) -> str:
    wanted = {label.casefold() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,100}):\s*(.*)$", stripped)
        if not match:
            continue
        label = normalize(match.group(1)).casefold()
        if label in wanted:
            return normalize(match.group(2))
    return ""


def is_not_applicable(text: str, values: dict[str, str]) -> bool:
    combined = "\n".join([text, *values.values()]).casefold()
    return any(
        phrase in combined
        for phrase in [
            "not a catalog project: yes",
            "catalog mode: one-off",
            "catalog mode: demo",
            "one-off: yes",
            "一次性",
            "不进入 catalog",
        ]
    )


def catalog_fit_audit_text_ready(text: str) -> bool:
    lowered = text.casefold()
    return (
        MARKER.casefold() in lowered
        and "decision: pass" in lowered
        and "artist/catalog fit: pass" in lowered
        and "catalog evolution: pass" in lowered
        and "prompt handoff: pass" in lowered
    )


def catalog_fit_audit_ready(project_root: Path) -> bool:
    return catalog_fit_audit_text_ready(read_text(project_root / OUTPUT))


def analyze(project_root: Path) -> CatalogFitAudit:
    text = read_text(project_root / INPUT)
    values = {field: label_value(text, labels) for field, labels in REQUIRED_FIELDS.items()}
    blockers: list[Finding] = []
    warnings: list[Finding] = []

    if not text:
        blockers.append(Finding("blocker", "catalog_fit_missing", f"missing {INPUT}", "write catalog-fit.md"))
        return CatalogFitAudit(project_root, values, blockers, warnings, False)

    not_applicable = is_not_applicable(text, values)
    if not_applicable:
        return CatalogFitAudit(project_root, values, blockers, warnings, True)

    for field, value in values.items():
        if not has_value(value):
            blockers.append(
                Finding("blocker", f"{field.lower().replace(' / ', '_').replace(' ', '_')}_missing", f"{field} is missing", "complete catalog-fit.md")
            )

    lowered = text.casefold()
    for term in PROTECTED_COPY_TERMS:
        if term in lowered:
            blockers.append(
                Finding("blocker", "protected_identity_copy_risk", f"catalog fit uses copy/clone language: {term}", "run reference DNA protected-identity removal")
            )

    if has_value(values.get("Protected identity boundary", "")):
        boundary = values["Protected identity boundary"].casefold()
        if not any(term in boundary for term in ["no artist", "protected", "reference", "identity", "不模仿", "不使用"]):
            blockers.append(
                Finding("blocker", "protected_identity_boundary_unclear", "protected identity boundary does not explain no-copy/reference limits", "tighten protected identity boundary")
            )

    if has_value(values.get("Difference from previous songs", "")):
        difference = values["Difference from previous songs"].casefold()
        if any(term in difference for term in ["same as previous", "no difference", "一样", "没有区别"]):
            blockers.append(
                Finding("blocker", "catalog_evolution_missing", "difference/evolution says this song repeats the previous lane", "define a concrete evolution")
            )

    if has_value(values.get("Validation route", "")):
        validation = values["Validation route"].casefold()
        if not any(term in validation for term in ["blind", "listener", "catalog", "a/b", "hook", "盲听", "听众"]):
            blockers.append(
                Finding("blocker", "catalog_validation_route_weak", "validation route must include blind/listener/catalog evidence", "add catalog fit validation route")
            )

    if has_value(values.get("Catalog decision", "")):
        decision = values["Catalog decision"].casefold()
        if not any(term in decision for term in ["proceed", "pass", "fit", "hold", "yes", "通过", "暂缓"]):
            blockers.append(
                Finding("blocker", "catalog_decision_unclear", "catalog decision must explicitly proceed/pass/fit or hold", "set catalog decision")
            )

    if "reference" not in lowered and "protected" not in lowered and "不模仿" not in lowered:
        warnings.append(
            Finding("warning", "reference_boundary_not_visible", "catalog fit does not visibly mention reference/protected identity boundaries", "link reference DNA boundary")
        )

    return CatalogFitAudit(project_root, values, blockers, warnings, False)


def render_findings(findings: list[Finding]) -> str:
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    if not findings:
        rows.append("| pass | none | no blocking findings | proceed |")
    for finding in findings:
        rows.append(f"| {finding.severity} | {finding.code} | {finding.message} | {finding.route} |")
    return "\n".join(rows)


def render(audit: CatalogFitAudit) -> str:
    values = audit.values
    status = "not applicable" if audit.not_applicable else ("pass" if not audit.blockers else "repair")
    prompt_handoff = "not applicable" if audit.not_applicable else ("pass" if not audit.blockers else "blocked")
    memory_handoff = "not applicable" if audit.not_applicable else ("pass" if not audit.blockers else "blocked")
    return f"""# Catalog Fit Audit

{MARKER}
Project root: {audit.project_root}
Decision: {audit.decision}

## Catalog Fit Evidence

Catalog mode: {values.get("Catalog mode") or "not recorded"}
Artist / catalog: {values.get("Artist / catalog") or "not recorded"}
Song role: {values.get("Song role") or "not recorded"}
Catalog lane: {values.get("Catalog lane") or "not recorded"}
Artist/catalog fit: {status}
Identity fit: {values.get("Identity fit") or "not recorded"}
Sonic signature fit: {values.get("Sonic signature fit") or "not recorded"}
Lyric universe fit: {values.get("Lyric universe fit") or "not recorded"}
Vocal identity fit: {values.get("Vocal identity fit") or "not recorded"}
Catalog evolution: {status}
Difference from previous songs: {values.get("Difference from previous songs") or "not recorded"}
Do not repeat: {values.get("Do not repeat") or "not recorded"}
Protected identity boundary: {values.get("Protected identity boundary") or "not recorded"}
Validation route: {values.get("Validation route") or "not recorded"}
Catalog decision: {values.get("Catalog decision") or "not recorded"}
Prompt handoff: {prompt_handoff}
Catalog memory handoff: {memory_handoff}

## Findings

{render_findings(audit.blockers + audit.warnings)}

## Rule

- One-off songs may be marked not applicable, but artist/catalog songs must define fit, evolution, validation, and protected-identity boundaries before their choices become reusable catalog memory.
"""


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--write", action="store_true", help="Write the catalog fit audit file.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit file.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero when blockers exist.")
    parser.add_argument("--output", default=OUTPUT, help="Relative output path.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    audit = analyze(project_root)
    output = render(audit)

    if args.write:
        path = project_root / args.output
        if path.exists() and not args.allow_overwrite:
            print(f"error: output exists, use --allow-overwrite: {path}", file=sys.stderr)
            return 2
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(output, encoding="utf-8")
    else:
        print(output)

    if audit.blockers:
        print("catalog fit audit blocked:", file=sys.stderr)
        for finding in audit.blockers:
            print(f"- {finding.code}: {finding.message} -> {finding.route}", file=sys.stderr)
        return 1 if args.strict else 0

    print(f"catalog fit audit decision: {audit.decision}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
