#!/usr/bin/env python3
"""Audit genre/lane authenticity before AI-music prompt compile.

Prompt specificity proves that fields are concrete. This gate asks the next
question: do those concrete fields cohere like a real pop/rock lane, or do they
read like a genre soup that will push Suno toward average AI music?
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from audit_music_methodology_transfer import PROTECTED_IDENTITY_NAMES
from audit_music_prompt_specificity_budget import prompt_specificity_audit_ready


STYLE_FILE = "04_prompt/style-field-map.md"
LYRICS_FILE = "04_prompt/lyrics-context-map.md"
EXCLUDE_FILE = "04_prompt/exclude-negative-aesthetic.md"
DEFAULT_OUTPUT = "04_prompt/genre-lane-authenticity-audit.md"
MARKER = "Generated by: tools/audit_music_genre_lane_authenticity.py"

EMPTY_VALUES = {
    "",
    '""',
    "''",
    "todo",
    "tbd",
    "pending",
    "unknown",
    "unclear",
    "missing",
    "n/a",
    "na",
    "none",
    "yes/no",
    "pass/fail",
    "-",
    "--",
}

BROAD_GENRES = {
    "pop",
    "rock",
    "ballad",
    "indie",
    "electronic",
    "dance",
    "folk",
    "r&b",
    "hip hop",
    "rap",
    "jazz",
    "metal",
    "edm",
}

GENRE_TERMS = {
    *BROAD_GENRES,
    "alt-pop",
    "bedroom pop",
    "city pop",
    "mandarin pop",
    "j-pop",
    "k-pop",
    "pop rock",
    "indie pop",
    "indie rock",
    "garage rock",
    "post-punk",
    "punk rock",
    "emo",
    "synth-pop",
    "electropop",
    "trap",
    "house",
    "techno",
    "trance",
    "ambient",
    "country",
    "singer-songwriter",
    "lo-fi",
    "acoustic",
}

HOOK_TERMS = ["hook", "title phrase", "chorus", "refrain", "motif", "副歌", "标题句", "钩子"]
ROCK_TERMS = [
    "guitar",
    "riff",
    "amp",
    "distortion",
    "overdrive",
    "drum",
    "snare",
    "kick",
    "bass",
    "live band",
    "吉他",
    "鼓",
    "贝斯",
    "失真",
]
POP_TERMS = ["hook", "chorus", "topline", "melody", "title phrase", "vocal", "副歌", "旋律", "标题句"]
PRODUCTION_TERMS = [
    "close",
    "dry",
    "room",
    "reverb",
    "stereo",
    "mono",
    "wide",
    "narrow",
    "tape",
    "saturation",
    "compression",
    "mix",
    "space",
    "近讲",
    "干声",
    "房间",
    "混响",
    "空间",
]
LYRIC_TERMS = ["narrator", "situation", "scene", "title phrase", "concrete", "object", "叙事", "场景", "物件", "标题句"]
DRIFT_TERMS = [
    "random genre switch",
    "genre switch",
    "generic",
    "ai",
    "karaoke",
    "overproduced",
    "polished",
    "trap",
    "edm",
    "cinematic",
    "fake crowd",
    "随机",
    "套模板",
    "AI味",
]


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


def read_project(project_root: Path) -> dict[str, str]:
    docs: dict[str, str] = {}
    for path in project_root.rglob("*.md"):
        rel = path.relative_to(project_root).as_posix()
        try:
            docs[rel] = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            docs[rel] = path.read_text(errors="replace")
    return docs


def normalize_value(raw: str) -> str:
    value = raw.strip().strip("`")
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1].strip()
    value = re.sub(r"\s+", " ", value)
    if value.casefold() in EMPTY_VALUES:
        return ""
    if value.startswith("[") and value.endswith("]") and ":" in value:
        return ""
    return value


def scan_key_values(text: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|"):
            continue
        stripped = re.sub(r"^[-*]\s+", "", stripped)
        match = re.match(r"^([^:]{1,120}):\s*(.*)$", stripped)
        if not match:
            continue
        label = re.sub(r"\s+", " ", match.group(1).strip()).casefold()
        pairs.append((label, normalize_value(match.group(2))))
    return pairs


def extract_value(docs: dict[str, str], paths: list[str], labels: list[str]) -> str:
    wanted = {re.sub(r"\s+", " ", label.strip()).casefold() for label in labels}
    for rel in paths:
        for label, value in scan_key_values(docs.get(rel, "")):
            if label in wanted and value:
                return value
    return ""


def contains_any(text: str, terms: list[str] | set[str]) -> bool:
    lowered = text.casefold()
    return any(term.casefold() in lowered for term in terms)


def term_list(value: str) -> list[str]:
    chunks = re.split(r"[,;、，/]| and | plus |\+", value, flags=re.I)
    return list(dict.fromkeys(chunk.strip() for chunk in chunks if normalize_value(chunk)))


def genre_hits(value: str) -> list[str]:
    lowered = value.casefold()
    hits = [term for term in sorted(GENRE_TERMS, key=len, reverse=True) if term in lowered]
    return list(dict.fromkeys(hits))


def only_broad_genre(value: str) -> bool:
    terms = term_list(value.casefold())
    if not terms:
        return True
    meaningful = [term for term in terms if term]
    return len(meaningful) <= 2 and all(term in BROAD_GENRES or term in {"slow", "fast", "sad"} for term in meaningful)


def protected_identity_hits(text: str) -> list[str]:
    hits: list[str] = []
    for name in PROTECTED_IDENTITY_NAMES:
        if not name:
            continue
        if re.fullmatch(r"[A-Za-z0-9 .'\-&]+", name):
            pattern = rf"(?<![A-Za-z0-9]){re.escape(name)}(?![A-Za-z0-9])"
            found = re.search(pattern, text, flags=re.I)
        else:
            found = name.casefold() in text.casefold()
        if found:
            hits.append(name)
    return hits


def collect_fields(docs: dict[str, str]) -> dict[str, str]:
    all_paths = list(docs)
    writing_paths = [path for path in all_paths if path.startswith("03_writing/")]
    brief_paths = [path for path in all_paths if path.startswith("01_brief/")]
    fields = {
        "language": extract_value(docs, [STYLE_FILE, LYRICS_FILE] + brief_paths, ["Language", "Language lane"]),
        "lane": extract_value(docs, [STYLE_FILE] + brief_paths, ["Genre lane", "Pop / rock lane", "Lane"]),
        "genre": extract_value(docs, [STYLE_FILE], ["genre", "style"]),
        "secondary_lane_purpose": extract_value(docs, [STYLE_FILE] + brief_paths, ["Secondary lane purpose", "Genre blend rationale", "Secondary genre purpose"]),
        "era_scene_anchor": extract_value(docs, [STYLE_FILE] + brief_paths, ["Era / scene anchor", "Scene anchor", "Era", "Listening context"]),
        "tempo_meter": extract_value(docs, [STYLE_FILE] + writing_paths, ["tempo / meter", "tempo", "meter"]),
        "vocal": extract_value(docs, [STYLE_FILE] + writing_paths, ["vocal", "singer brief", "vocal identity"]),
        "instrumentation": extract_value(docs, [STYLE_FILE] + writing_paths, ["instrumentation", "core instruments"]),
        "drums_groove": extract_value(docs, [STYLE_FILE] + writing_paths, ["drums / groove", "drums", "groove", "groove role"]),
        "bass_role": extract_value(docs, [STYLE_FILE] + writing_paths, ["bass role", "bass"]),
        "harmony_instruments": extract_value(docs, [STYLE_FILE] + writing_paths, ["harmony instruments", "chords", "harmony"]),
        "lead_instruments": extract_value(docs, [STYLE_FILE] + writing_paths, ["lead / hook instruments", "lead instrument", "hook instrument"]),
        "production": extract_value(docs, [STYLE_FILE] + writing_paths, ["production", "production texture", "mix", "space"]),
        "mood": extract_value(docs, [STYLE_FILE] + writing_paths, ["mood", "mood / energy arc", "energy arc", "emotion arc"]),
        "narrator": extract_value(docs, brief_paths + writing_paths, ["Narrator", "Singer persona", "Point of view"]),
        "situation": extract_value(docs, brief_paths + writing_paths, ["Situation", "Scene", "Concrete place"]),
        "title_phrase": extract_value(docs, brief_paths + writing_paths, ["Title phrase", "Hook phrase", "Chorus title phrase"]),
        "hook_mechanism": extract_value(docs, [STYLE_FILE, LYRICS_FILE] + writing_paths, ["Hook mechanism", "Hook promise", "Hook", "Title phrase function"]),
        "exclude": extract_value(docs, [EXCLUDE_FILE], ["Exclude", "Exclude term", "Must-not-have"]),
    }
    if not fields["instrumentation"]:
        fields["instrumentation"] = ", ".join(
            part
            for part in [
                fields["drums_groove"],
                fields["bass_role"],
                fields["harmony_instruments"],
                fields["lead_instruments"],
            ]
            if part
        )
    fields["lyrics_context"] = docs.get(LYRICS_FILE, "")
    fields["style_text"] = "\n".join(
        fields[key]
        for key in [
            "lane",
            "genre",
            "secondary_lane_purpose",
            "era_scene_anchor",
            "tempo_meter",
            "vocal",
            "instrumentation",
            "drums_groove",
            "bass_role",
            "production",
            "mood",
        ]
    )
    fields["lyric_text"] = "\n".join([fields["narrator"], fields["situation"], fields["title_phrase"], fields["hook_mechanism"], fields["lyrics_context"]])
    return fields


def analyze(project_root: Path) -> tuple[dict[str, str], list[Finding]]:
    docs = read_project(project_root)
    fields = collect_fields(docs)
    findings: list[Finding] = []
    lane_text = f"{fields['lane']} {fields['genre']}".strip()
    style_text = fields["style_text"]
    lyric_text = fields["lyric_text"]
    exclude_text = docs.get(EXCLUDE_FILE, "") + "\n" + fields["exclude"]
    genre_terms = genre_hits(lane_text)

    if not prompt_specificity_audit_ready(project_root):
        findings.append(Finding("blocker", "prompt_specificity_not_ready", "Prompt specificity audit must pass before genre/lane authenticity can be judged.", "run audit_music_prompt_specificity_budget.py"))
    if not fields["language"]:
        findings.append(Finding("blocker", "language_missing", "Language lane is missing.", "fill song-brief.md or style-field-map.md"))
    if not lane_text:
        findings.append(Finding("blocker", "genre_lane_missing", "Genre/lane is missing.", "fill style-field-map.md"))
    elif only_broad_genre(lane_text):
        findings.append(Finding("blocker", "genre_lane_too_broad", f"Genre/lane is too broad for a real production lane: {lane_text}", "add subgenre, scene, era, tempo, and production anchor"))
    if len(genre_terms) >= 4 and not fields["secondary_lane_purpose"]:
        findings.append(Finding("blocker", "genre_soup_without_rationale", "Multiple genre tags are present but no secondary lane purpose explains the blend.", "write Secondary lane purpose or simplify genre list"))
    if not fields["era_scene_anchor"]:
        findings.append(Finding("blocker", "scene_anchor_missing", "Era/scene/listening-context anchor is missing.", "add Era / scene anchor"))
    if not fields["tempo_meter"]:
        findings.append(Finding("blocker", "tempo_meter_missing", "Tempo/meter is missing; lane cannot be tested against performance feel.", "fill tempo / meter"))
    if not fields["vocal"]:
        findings.append(Finding("blocker", "vocal_lane_missing", "Vocal delivery is missing from lane evidence.", "fill vocal field"))
    if not fields["instrumentation"]:
        findings.append(Finding("blocker", "arrangement_lane_missing", "Instrumentation is missing from lane evidence.", "fill instrumentation or instrument-role map"))
    if not contains_any(fields["production"], PRODUCTION_TERMS):
        findings.append(Finding("blocker", "production_lane_unphysical", "Production field lacks physical recording/mix language.", "add room, mic, width, saturation, reverb, or dynamics evidence"))
    if not contains_any(lyric_text, LYRIC_TERMS):
        findings.append(Finding("blocker", "style_lyric_fit_missing", "Lyrics/narrator/title evidence is too thin to judge style-lyric fit.", "fill lyric brief, title phrase, or lyrics-context-map.md"))
    if not contains_any(lyric_text, HOOK_TERMS):
        findings.append(Finding("blocker", "hook_lane_missing", "No hook/title/chorus mechanism is visible for the lane.", "route to topline hook workflow"))

    is_pop = "pop" in lane_text.casefold() or "ballad" in lane_text.casefold()
    is_rock = "rock" in lane_text.casefold() or "punk" in lane_text.casefold() or "metal" in lane_text.casefold()
    if is_pop and not contains_any(style_text + "\n" + lyric_text, POP_TERMS):
        findings.append(Finding("blocker", "pop_hook_grammar_missing", "Pop lane needs hook/topline/title/chorus grammar.", "repair style-field-map.md and lyrics-context-map.md"))
    if is_rock and not contains_any(fields["instrumentation"] + " " + fields["drums_groove"] + " " + fields["bass_role"], ROCK_TERMS):
        findings.append(Finding("blocker", "rock_band_grammar_missing", "Rock lane needs guitar/drum/bass/performance evidence.", "repair instrument-role-map.md"))
    if "edm" in lane_text.casefold() and "acoustic" in lane_text.casefold() and not fields["secondary_lane_purpose"]:
        findings.append(Finding("blocker", "conflicting_lane_no_rationale", "EDM and acoustic tags conflict without a blend rationale.", "write Secondary lane purpose or split experiments"))
    if not contains_any(exclude_text, DRIFT_TERMS):
        findings.append(Finding("warning", "anti_drift_exclude_weak", "Exclude/anti-drift plan does not name common lane drift risks.", "add genre drift and AI-flavor exclusions"))

    identity_hits = protected_identity_hits(style_text + "\n" + exclude_text)
    if identity_hits:
        findings.append(Finding("blocker", "protected_identity_in_lane", "Genre/lane fields contain protected artist/band names: " + ", ".join(identity_hits[:5]), "route to reference DNA and remove protected names"))

    fields["primary_lane"] = fields["lane"] or fields["genre"]
    fields["genre_terms"] = ", ".join(genre_terms) if genre_terms else "none"
    fields["style_lyric_fit"] = "pass" if contains_any(lyric_text, LYRIC_TERMS) and contains_any(lyric_text, HOOK_TERMS) else "repair"
    fields["arrangement_fit"] = "pass" if fields["instrumentation"] and (not is_rock or contains_any(fields["instrumentation"] + " " + fields["drums_groove"] + " " + fields["bass_role"], ROCK_TERMS)) else "repair"
    fields["production_fit"] = "pass" if contains_any(fields["production"], PRODUCTION_TERMS) else "repair"
    fields["prompt_specificity"] = "pass" if prompt_specificity_audit_ready(project_root) else "missing or repair"
    return fields, findings


def render_findings(findings: list[Finding]) -> str:
    if not findings:
        return "| severity | code | message | route |\n|---|---|---|---|\n| pass | none | genre/lane authenticity approved | prompt compile |\n"
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    for item in findings:
        rows.append(f"| {item.severity} | {item.code} | {item.message} | {item.route} |")
    return "\n".join(rows) + "\n"


def render_audit(project_root: Path, fields: dict[str, str], findings: list[Finding]) -> str:
    blockers = [finding for finding in findings if finding.severity == "blocker"]
    decision = "pass" if not blockers else "repair before prompt compile"
    handoff = "pass" if decision == "pass" else "blocked"
    return f"""# Genre Lane Authenticity Audit

{MARKER}
Project root: {project_root}
Decision: {decision}

## Genre/Lane Evidence

Prompt specificity: {fields['prompt_specificity']}
Primary lane: {fields['primary_lane'] or 'NEEDS_REPAIR'}
Genre terms detected: {fields['genre_terms']}
Language lane: {fields['language'] or 'NEEDS_REPAIR'}
Secondary lane purpose: {fields['secondary_lane_purpose'] or 'not recorded'}
Era / scene anchor: {fields['era_scene_anchor'] or 'NEEDS_REPAIR'}
Tempo / meter: {fields['tempo_meter'] or 'NEEDS_REPAIR'}
Vocal lane: {fields['vocal'] or 'NEEDS_REPAIR'}
Arrangement lane: {fields['instrumentation'] or 'NEEDS_REPAIR'}
Production lane: {fields['production'] or 'NEEDS_REPAIR'}
Lyric stance: {fields['narrator'] or fields['situation'] or fields['title_phrase'] or 'NEEDS_REPAIR'}
Hook mechanism: {fields['hook_mechanism'] or fields['title_phrase'] or 'NEEDS_REPAIR'}
Style-lyric fit: {fields['style_lyric_fit']}
Arrangement fit: {fields['arrangement_fit']}
Production fit: {fields['production_fit']}
Anti-drift / exclude plan: {fields['exclude'] or 'review exclude-negative-aesthetic.md'}
Genre/lane authenticity: {'pass' if decision == 'pass' else 'repair'}
Prompt compile handoff: {handoff}

## Findings

{render_findings(findings)}
"""


def genre_lane_authenticity_audit_text_ready(text: str) -> bool:
    lowered = text.casefold()
    return (
        MARKER.casefold() in lowered
        and "decision: pass" in lowered
        and "genre/lane authenticity: pass" in lowered
        and "prompt compile handoff: pass" in lowered
    )


def genre_lane_authenticity_audit_ready(project_root: Path) -> bool:
    path = project_root / DEFAULT_OUTPUT
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    return genre_lane_authenticity_audit_text_ready(text)


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root created by create_music_song_project.py.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Relative output path for the audit.")
    parser.add_argument("--write", action="store_true", help="Write the audit file.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting the output file.")
    parser.add_argument("--strict", action="store_true", help="Exit non-zero when blockers exist.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists():
        print(f"Project root does not exist: {project_root}", file=sys.stderr)
        return 2
    fields, findings = analyze(project_root)
    output = render_audit(project_root, fields, findings)
    blockers = [finding for finding in findings if finding.severity == "blocker"]
    if args.write:
        try:
            write_if_allowed(project_root / args.output, output, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"Refusing to overwrite existing file without --allow-overwrite: {exc}", file=sys.stderr)
            return 2
    else:
        print(output)
    if args.strict and blockers:
        print("genre/lane authenticity audit blocked:", file=sys.stderr)
        for finding in blockers:
            print(f"- {finding.code}: {finding.message} -> {finding.route}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
