#!/usr/bin/env python3
"""Audit external listener evidence before release-candidate approval.

This tool does not decide artistic taste. It checks whether a public or release
candidate has external listener evidence showing first-20-second pull, hook
memory, low AI-flavor red flags, and a positive listener release verdict.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


OUTPUT = "06_review/release-listener-evidence-audit.md"
EXTERNAL_PANEL = "06_review/external-listener-panel.md"
FIRST_20 = "06_review/first-20-second-test.md"
HOOK_MEMORY = "06_review/hook-memory-test.md"
AI_FLAVOR = "06_review/ai-flavor-red-flag-survey.md"

RELEASE_LISTENER_AUDIT_MARKER = "Generated by: tools/audit_music_release_listener_evidence.py"
RELEASE_LISTENER_AUDIT_REQUIRED_TERMS = [
    "Decision: pass",
    "## Release Listener Evidence",
    "Panel tags:",
    "First 20 second tags:",
    "Hook memory tags:",
    "AI flavor tags:",
    "Release gate handoff:",
]

PLACEHOLDERS = {"", "-", "--", "tbd", "todo", "pending", "unknown", "missing", "n/a", "na"}


@dataclass
class Finding:
    severity: str
    code: str
    message: str
    route: str


@dataclass
class Audit:
    blockers: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)
    tags: dict[str, str] = field(default_factory=dict)

    @property
    def decision(self) -> str:
        return "pass" if not self.blockers else "hold"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def normalized(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().lower())


def has_value(value: str) -> bool:
    return normalized(value).strip("`\"'") not in PLACEHOLDERS


def label_value(text: str, labels: list[str]) -> str:
    wanted = {label.lower() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,90}):\s*(.*)$", stripped)
        if not match:
            continue
        label = match.group(1).strip().lower()
        value = match.group(2).strip().strip('"')
        if label in wanted:
            return value
    return ""


def positive_value(value: str) -> bool:
    return bool(re.search(r"\b(pass|passed|yes|clear|cleared|ok|approved|approve|strong|remembered|recalled|keep|continue|positive|ready)\b|通过|记住|可发布|正向", value, re.I))


def low_risk_value(value: str) -> bool:
    return bool(re.search(r"^(no|none|0|zero|low|pass|passed|clear|cleared|ok|n/a|not applicable)\b|无|否|低风险|通过|清楚", normalized(value), re.I))


def parse_number(value: str) -> float | None:
    match = re.search(r"(\d+(?:\.\d+)?)", value)
    return float(match.group(1)) if match else None


def add_finding(items: list[Finding], severity: str, code: str, message: str, route: str) -> None:
    items.append(Finding(severity=severity, code=code, message=message, route=route))


def require_file(project_root: Path, audit: Audit, rel: str) -> str:
    text = read_text(project_root / rel)
    if not text:
        add_finding(audit.blockers, "blocker", f"{Path(rel).stem.replace('-', '_')}_missing", f"missing {rel}", "complete external listener evidence before release")
    return text


def require_label(audit: Audit, rel: str, text: str, labels: list[str], code: str, route: str) -> str:
    value = label_value(text, labels)
    if not has_value(value):
        add_finding(audit.blockers, "blocker", code, f"{rel} missing {' / '.join(labels)}", route)
    return value


def audit_external_panel(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, EXTERNAL_PANEL)
    if not text:
        return
    panel_size = require_label(audit, EXTERNAL_PANEL, text, ["Panel size"], "panel_size_missing", "record listener panel size")
    target = require_label(audit, EXTERNAL_PANEL, text, ["Target audience"], "target_audience_missing", "record target listener fit")
    blind = require_label(audit, EXTERNAL_PANEL, text, ["Blind condition"], "blind_condition_missing", "blind panel to prompt/provider")
    ai_flags = require_label(audit, EXTERNAL_PANEL, text, ["AI flavor red flags", "AI-flavor red flags", "AI flavor concern", "Red flags"], "panel_ai_flags_missing", "record AI-flavor flags from panel")
    verdict = require_label(audit, EXTERNAL_PANEL, text, ["Release listener verdict", "Listener release verdict", "Panel decision", "Decision"], "panel_verdict_missing", "record listener release verdict")
    number = parse_number(panel_size)
    if number is not None and number < 5:
        add_finding(audit.warnings, "warning", "panel_size_small", f"{EXTERNAL_PANEL} panel size {number:g} is below the 5-listener red-flag screen", "treat as directional, not final")
    if ai_flags and not low_risk_value(ai_flags):
        add_finding(audit.blockers, "blocker", "panel_ai_flags_not_low", f"{EXTERNAL_PANEL} AI flavor red flags must be none/no/low; got {ai_flags}", "route to artifact diagnosis and retest")
    if verdict and not positive_value(verdict):
        add_finding(audit.blockers, "blocker", "panel_verdict_not_positive", f"{EXTERNAL_PANEL} release verdict is not positive: {verdict}", "repair before release candidate")
    audit.tags["panel"] = f"size={panel_size or 'missing'}, target={target or 'missing'}, blind={blind or 'missing'}, flags={ai_flags or 'missing'}, verdict={verdict or 'missing'}"


def audit_first_20(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, FIRST_20)
    if not text:
        return
    skip = require_label(audit, FIRST_20, text, ["Skip risk", "First 20 second skip risk", "Drop-off risk"], "first20_skip_risk_missing", "record skip risk after 20 seconds")
    pull = require_label(audit, FIRST_20, text, ["First 20 second decision", "First 20-second decision", "Decision", "Pull"], "first20_pull_missing", "record pull/listen decision")
    synthetic = label_value(text, ["Synthetic / fake feeling", "Synthetic feeling", "Felt synthetic", "AI flavor red flags"])
    if skip and not low_risk_value(skip):
        add_finding(audit.blockers, "blocker", "first20_skip_risk_not_low", f"{FIRST_20} skip risk must be low/no/none; got {skip}", "repair intro, vocal entrance, hook setup, or mix clarity")
    if pull and not positive_value(pull):
        add_finding(audit.blockers, "blocker", "first20_pull_not_positive", f"{FIRST_20} does not show positive pull/listen decision: {pull}", "repair opening before release")
    if synthetic and not low_risk_value(synthetic):
        add_finding(audit.blockers, "blocker", "first20_synthetic_flag", f"{FIRST_20} has synthetic/fake flag: {synthetic}", "route to AI artifact diagnosis")
    audit.tags["first20"] = f"skip={skip or 'missing'}, pull={pull or 'missing'}, synthetic={synthetic or 'not recorded'}"


def audit_hook_memory(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, HOOK_MEMORY)
    if not text:
        return
    recalled = require_label(audit, HOOK_MEMORY, text, ["Hook recalled", "Hook recall", "Title hook recalled", "Memory result"], "hook_recall_missing", "record hook recall result")
    phrase = label_value(text, ["Title phrase remembered", "Lyric fragment remembered", "Title phrase", "Remembered lyric"])
    contour = label_value(text, ["Melody contour remembered", "Contour remembered", "Hummed contour"])
    if recalled and not positive_value(recalled):
        add_finding(audit.blockers, "blocker", "hook_not_recalled", f"{HOOK_MEMORY} must prove the hook/title phrase is recalled; got {recalled}", "return to topline or lyric narrative workflow")
    if not has_value(phrase) and not has_value(contour):
        add_finding(audit.blockers, "blocker", "hook_memory_no_trace", f"{HOOK_MEMORY} needs a remembered phrase or contour", "test whether anything survives after listening")
    audit.tags["hook"] = f"recall={recalled or 'missing'}, phrase={phrase or 'not recorded'}, contour={contour or 'not recorded'}"


def audit_ai_flavor(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, AI_FLAVOR)
    if not text:
        return
    flags = require_label(audit, AI_FLAVOR, text, ["AI flavor red flags", "AI-flavor red flags", "Red flags", "AI flavor concern"], "ai_flavor_flags_missing", "record AI-flavor red flags")
    verdict = require_label(audit, AI_FLAVOR, text, ["AI flavor release verdict", "Release verdict", "Decision"], "ai_flavor_verdict_missing", "record AI-flavor release verdict")
    severity = label_value(text, ["Severity 0-3", "Severity", "Max severity"])
    if flags and not low_risk_value(flags):
        add_finding(audit.blockers, "blocker", "ai_flavor_flags_not_low", f"{AI_FLAVOR} red flags must be none/no/low; got {flags}", "route red flags to repair before release")
    if verdict and not positive_value(verdict):
        add_finding(audit.blockers, "blocker", "ai_flavor_verdict_not_positive", f"{AI_FLAVOR} release verdict is not pass/clear: {verdict}", "repair and retest")
    number = parse_number(severity)
    if number is not None and number > 1:
        add_finding(audit.blockers, "blocker", "ai_flavor_severity_too_high", f"{AI_FLAVOR} severity {number:g} exceeds release threshold 1", "repair AI flavor before release")
    audit.tags["ai_flavor"] = f"flags={flags or 'missing'}, verdict={verdict or 'missing'}, severity={severity or 'not recorded'}"


def audit_project(project_root: Path) -> Audit:
    audit = Audit()
    audit_external_panel(project_root, audit)
    audit_first_20(project_root, audit)
    audit_hook_memory(project_root, audit)
    audit_ai_flavor(project_root, audit)
    return audit


def release_listener_audit_decision(project_root: Path) -> str:
    text = read_text(project_root / OUTPUT)
    return label_value(text, ["Decision"]) or "missing"


def release_listener_audit_ready(project_root: Path) -> bool:
    text = read_text(project_root / OUTPUT)
    if RELEASE_LISTENER_AUDIT_MARKER not in text:
        return False
    return all(term in text for term in RELEASE_LISTENER_AUDIT_REQUIRED_TERMS)


def finding_rows(findings: list[Finding]) -> str:
    if not findings:
        return "| pass | none | no blocking findings | proceed |\n"
    return "\n".join(f"| {item.severity} | {item.code} | {item.message} | {item.route} |" for item in findings) + "\n"


def render_audit(project_root: Path, audit: Audit) -> str:
    return f"""# Release Listener Evidence Audit

Generated by: tools/audit_music_release_listener_evidence.py
Project root: {project_root}
Decision: {audit.decision}

This gate checks whether outside ears support release-candidate promotion. It
does not replace producer judgment, but it prevents a song from passing release
only because the maker got used to its AI flavor.

## Release Listener Evidence

Panel tags: {audit.tags.get('panel', 'missing')}
First 20 second tags: {audit.tags.get('first20', 'missing')}
Hook memory tags: {audit.tags.get('hook', 'missing')}
AI flavor tags: {audit.tags.get('ai_flavor', 'missing')}
Release gate handoff: {"ready" if not audit.blockers else "blocked"}

## Findings

| severity | code | message | route |
|---|---|---|---|
{finding_rows(audit.blockers).rstrip()}

## Warnings

| severity | code | message | route |
|---|---|---|---|
{finding_rows(audit.warnings).rstrip()}

## Repair Route

- When first 20 seconds are weak, repair intro, vocal entrance, hook setup, or mix clarity.
- When hook memory is weak, return to topline, lyric narrative, or title phrase work.
- If AI flavor flags are above low, route the timestamps to artifact diagnosis and retest.
- Do not use rights approval to override listener evidence.
"""


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--output", default=OUTPUT, help="Relative output path for the audit note.")
    parser.add_argument("--write", action="store_true", help="Write the audit note.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit note.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero when release listener evidence is blocked.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2
    audit = audit_project(project_root)
    output = render_audit(project_root, audit)
    if args.write:
        output_path = project_root / args.output
        if output_path.exists() and not args.allow_overwrite:
            print(f"error: output exists, use --allow-overwrite: {output_path}", file=sys.stderr)
            return 2
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(output, encoding="utf-8")
        print(f"wrote {output_path.relative_to(project_root).as_posix()}")
    else:
        print(output)
    if audit.blockers:
        for blocker in audit.blockers[:12]:
            print(f"release listener blocker: {blocker.code}: {blocker.message}", file=sys.stderr)
        return 1 if args.strict else 0
    print("release listener evidence: pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
