#!/usr/bin/env python3
"""Audit prompt experiment iteration discipline before generation evidence."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from review_music_takes import parse_markdown_tables


OUTPUT = "05_generations/prompt-iteration-discipline-audit.md"
PROMPT_ITERATION_DISCIPLINE_MARKER = "Generated by: tools/audit_music_prompt_iteration_discipline.py"
PROMPT_ITERATION_DISCIPLINE_REQUIRED_TERMS = [
    "Decision: pass",
    "## Prompt Iteration Discipline Evidence",
    "Experiment question:",
    "Frozen brief:",
    "Allowed variable count:",
    "Changed variables:",
    "Candidate hypotheses:",
    "Batch discipline:",
    "Attribution strength:",
    "Generation evidence handoff: pass",
]

PROMPT_PACKAGE = "04_prompt/prompt-package-v001.md"
PROMPT_PREFLIGHT = "04_prompt/prompt-preflight-review.md"
EXPERIMENT_HANDOFF = "04_prompt/experiment-handoff.md"
EXPERIMENT_INTENT = "05_generations/experiment-intent.md"
BRIEF_FREEZE = "05_generations/brief-freeze.md"
VARIABLE_INVENTORY = "05_generations/variable-inventory.md"
PROMPT_CANDIDATE_SET = "05_generations/prompt-candidate-set.md"
BATCH_PLAN = "05_generations/batch-generation-plan.md"

PROMPT_COMPILER_MARKER = "Generated by: tools/compile_music_prompt_package.py"
PLACEHOLDERS = {"", "-", "--", "todo", "tbd", "pending", "unknown", "missing", "n/a", "na"}
BLOCKING_RE = re.compile(
    r"\b(todo|tbd|pending|unknown|unresolved|unclear|missing|fail(?:ed)?|hold|blocked|red flag)\b"
    r"|待定|未知|未解决|不清楚|缺失|失败|不通过|暂停|阻塞|红灯|红旗",
    re.I,
)
CLEARING_RE = re.compile(
    r"\b(no|none|0|zero|resolved|clear|cleared|pass|passed|approved|ready|not applicable|n/a|low)\b"
    r"|无|否|已解决|通过|清楚|低风险",
    re.I,
)
VARIABLE_ALIASES = {
    "style prompt": "style",
    "style influence": "style influence",
    "audio influence": "audio influence",
    "lyrics text": "lyrics text",
    "lyrics": "lyrics text",
    "lyrics context": "lyrics context",
    "exclude": "exclude",
    "model": "model",
    "weirdness": "weirdness",
    "style": "style",
    "persona": "persona/voice",
    "voice": "persona/voice",
    "persona / voice": "persona/voice",
    "audio upload seed": "audio seed",
    "audio seed": "audio seed",
    "prompt boost": "prompt boost",
    "creative prompt boosting": "prompt boost",
    "remi": "remi",
}


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


@dataclass
class Audit:
    blockers: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)
    tags: dict[str, str] = field(default_factory=dict)
    changed_variables: list[str] = field(default_factory=list)
    allowed_variable_count: int = 0

    @property
    def decision(self) -> str:
        return "pass" if not self.blockers else "hold"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def normalized(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().strip("`\"'")).lower()


def has_value(value: str) -> bool:
    return normalized(value) not in PLACEHOLDERS


def label_value(text: str, labels: list[str]) -> str:
    wanted = {label.lower() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,100}):\s*(.*)$", stripped)
        if not match:
            continue
        label = match.group(1).strip().lower()
        value = match.group(2).strip().strip('"')
        if label in wanted:
            return value
    return ""


def add_finding(items: list[Finding], severity: str, code: str, message: str, route: str) -> None:
    items.append(Finding(severity=severity, code=code, message=message, route=route))


def require_file(project_root: Path, audit: Audit, rel: str) -> str:
    text = read_text(project_root / rel)
    if not text:
        add_finding(audit.blockers, "blocker", f"{Path(rel).stem.replace('-', '_')}_missing", f"missing {rel}", "complete prompt experiment discipline evidence")
    return text


def require_label(audit: Audit, rel: str, text: str, labels: list[str], code: str, route: str) -> str:
    value = label_value(text, labels)
    if not has_value(value):
        add_finding(audit.blockers, "blocker", code, f"{rel} missing {' / '.join(labels)}", route)
    return value


def decision_is_compile_approved(text: str) -> bool:
    return bool(re.search(r"^Decision:\s*compile approved\b", text, re.I | re.M))


def line_is_blocking(line: str) -> bool:
    text = line.strip()
    if not text or text.startswith("#") or text.startswith("|") or text.startswith("```"):
        return False
    if not BLOCKING_RE.search(text):
        return False
    return not CLEARING_RE.search(text)


def blocking_lines(text: str) -> list[str]:
    return [line.strip() for line in text.splitlines() if line_is_blocking(line)][:6]


def split_list(value: str) -> list[str]:
    raw = value.strip()
    if not has_value(raw):
        return []
    pieces = re.split(r"\s*(?:,|;|\+|/|、|，|\band\b)\s*", raw, flags=re.I)
    return [piece.strip().strip("`\"'") for piece in pieces if has_value(piece)]


def canonical_variable(value: str) -> str:
    text = normalized(value)
    text = re.sub(r"[^a-z0-9 /-]+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    for alias, canonical in VARIABLE_ALIASES.items():
        if alias in text:
            return canonical
    return text


def parse_changed_variables(*texts: str) -> list[str]:
    labels = [
        "Changed variables",
        "Primary changed variable",
        "Allowed changed variables",
        "Variable under test",
        "What changes",
    ]
    variables: list[str] = []
    for text in texts:
        for label in labels:
            value = label_value(text, [label])
            if value:
                variables.extend(canonical_variable(item) for item in split_list(value))
    deduped: list[str] = []
    for item in variables:
        if item and item not in deduped and item not in {"none", "no"}:
            deduped.append(item)
    return deduped


def phase_allowed_count(phase: str) -> int:
    lowered = normalized(phase)
    if re.search(r"explor|探索|diverge|sandbox", lowered):
        return 2
    if re.search(r"repair|local|section|局部|修作", lowered):
        return 1
    if re.search(r"converg|收敛|lock|release|catalog|final", lowered):
        return 1
    return 1


def candidate_ids_from_value(value: str) -> list[str]:
    ids: list[str] = []
    for part in split_list(value):
        for match in re.finditer(r"\b[A-Z]\d{2}\b|\bC\d{2}\b|\bP\d{2}\b", part, re.I):
            ids.append(match.group(0).upper())
    return sorted(set(ids))


def candidate_ids_from_text(text: str) -> list[str]:
    ids: set[str] = set()
    for match in re.finditer(r"(?im)^\s*(?:[-*]\s*)?Candidate ID:\s*([A-Za-z]\d{2})\b", text):
        ids.add(match.group(1).upper())
    for table in parse_markdown_tables(text):
        for row in table:
            value = row.get("candidate") or row.get("candidate_id") or row.get("candidate id") or row.get("id") or ""
            for item in candidate_ids_from_value(value):
                ids.add(item)
    return sorted(ids)


def audit_prompt_approval(project_root: Path, audit: Audit) -> None:
    package = read_text(project_root / PROMPT_PACKAGE)
    preflight = read_text(project_root / PROMPT_PREFLIGHT)
    if not package:
        add_finding(audit.blockers, "blocker", "prompt_package_missing", f"missing {PROMPT_PACKAGE}", "run compile_music_prompt_package.py")
    elif PROMPT_COMPILER_MARKER not in package or not decision_is_compile_approved(package):
        add_finding(audit.blockers, "blocker", "prompt_package_not_approved", f"{PROMPT_PACKAGE} must be compiler-generated with Decision: compile approved", "repair prompt package before experiments")
    if not preflight:
        add_finding(audit.blockers, "blocker", "prompt_preflight_missing", f"missing {PROMPT_PREFLIGHT}", "run compile_music_prompt_package.py")
    elif PROMPT_COMPILER_MARKER not in preflight or not decision_is_compile_approved(preflight):
        add_finding(audit.blockers, "blocker", "prompt_preflight_not_approved", f"{PROMPT_PREFLIGHT} must be compiler-generated with Decision: compile approved", "repair prompt preflight before experiments")


def audit_experiment_intent(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, EXPERIMENT_INTENT)
    if not text:
        return
    question = require_label(audit, EXPERIMENT_INTENT, text, ["Experiment question"], "experiment_question_missing", "write the experiment question")
    metric = require_label(audit, EXPERIMENT_INTENT, text, ["Success metric", "Success metrics"], "success_metric_missing", "write measurable success metrics")
    stop = require_label(audit, EXPERIMENT_INTENT, text, ["Stop condition", "Stop conditions"], "stop_condition_missing", "write stop/lock/abandon conditions")
    phase = require_label(audit, EXPERIMENT_INTENT, text, ["Experiment phase", "Phase"], "experiment_phase_missing", "mark exploration or convergence phase")
    audit.allowed_variable_count = phase_allowed_count(phase)
    audit.tags["question"] = question or "missing"
    audit.tags["success_metric"] = metric or "missing"
    audit.tags["stop_condition"] = stop or "missing"
    audit.tags["phase"] = phase or "missing"


def audit_brief_freeze(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, BRIEF_FREEZE)
    if not text:
        return
    required = [
        ("Use case", "brief_use_case_missing"),
        ("Language", "brief_language_missing"),
        ("Genre lane", "brief_genre_lane_missing"),
        ("Title phrase", "brief_title_phrase_missing"),
        ("Vocal identity", "brief_vocal_identity_missing"),
        ("Must keep", "brief_must_keep_missing"),
        ("Must avoid", "brief_must_avoid_missing"),
        ("Rights boundary", "brief_rights_boundary_missing"),
    ]
    missing: list[str] = []
    for label, code in required:
        value = require_label(audit, BRIEF_FREEZE, text, [label], code, "freeze brief before generation")
        if not value:
            missing.append(label)
    audit.tags["brief"] = "complete" if not missing else "missing " + ", ".join(missing)


def audit_variable_inventory(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, VARIABLE_INVENTORY)
    if not text:
        return
    required_terms = [
        "Style prompt",
        "Lyrics text",
        "Lyrics context",
        "Exclude",
        "Model",
        "Weirdness",
        "Style Influence",
        "Audio Influence",
        "Persona / Voice",
        "Audio Upload seed",
    ]
    missing = [term for term in required_terms if term.lower() not in text.lower()]
    if missing:
        add_finding(audit.blockers, "blocker", "variable_inventory_incomplete", f"{VARIABLE_INVENTORY} missing variables: {', '.join(missing[:4])}", "list all prompt/provider variables")
    changed = parse_changed_variables(text)
    if changed:
        audit.changed_variables = changed
    audit.tags["variable_inventory"] = "complete" if not missing else "missing " + ", ".join(missing[:4])


def audit_candidate_set(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, PROMPT_CANDIDATE_SET)
    if not text:
        return
    ids = candidate_ids_from_text(text)
    if not ids:
        add_finding(audit.blockers, "blocker", "candidate_ids_missing", f"{PROMPT_CANDIDATE_SET} needs Candidate ID entries", "create 2-4 prompt candidates")
    if len(ids) == 1:
        add_finding(audit.warnings, "warning", "single_candidate_weak_attribution", f"{PROMPT_CANDIDATE_SET} has one candidate; attribution may be weak", "add baseline or comparison candidate when possible")
    lowered = text.lower()
    for term, code in [
        ("hypothesis", "candidate_hypothesis_missing"),
        ("what this tests", "candidate_test_missing"),
        ("what it keeps constant", "candidate_constant_missing"),
        ("what it changes", "candidate_change_missing"),
        ("risk", "candidate_risk_missing"),
    ]:
        if term not in lowered:
            add_finding(audit.blockers, "blocker", code, f"{PROMPT_CANDIDATE_SET} missing {term}", "write candidate rationale")
    if "baseline" not in lowered:
        add_finding(audit.blockers, "blocker", "baseline_candidate_missing", f"{PROMPT_CANDIDATE_SET} needs a baseline candidate", "include a baseline for attribution")
    if re.search(r"boost|prompt boosting", lowered) and not re.search(r"original\s*/\s*boosted|original vs boosted|boosted comparison", lowered, re.I):
        add_finding(audit.blockers, "blocker", "boost_comparison_missing", "boosted prompt appears without original/boosted comparison", "test boosted prompt as its own variable")
    if not audit.changed_variables:
        audit.changed_variables = parse_changed_variables(text)
    audit.tags["candidate_ids"] = ", ".join(ids) or "missing"
    audit.tags["candidate_hypotheses"] = "present" if "hypothesis" in lowered else "missing"


def audit_batch_plan(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, BATCH_PLAN)
    candidate_text = read_text(project_root / PROMPT_CANDIDATE_SET)
    if not text:
        return
    required = [
        ("Candidate IDs", "batch_candidate_ids_missing"),
        ("Takes per candidate", "batch_takes_per_candidate_missing"),
        ("Total takes", "batch_total_takes_missing"),
        ("Generation date", "batch_generation_date_missing"),
        ("Expected listen order", "batch_expected_listen_order_missing"),
        ("Anonymization rule", "batch_anonymization_rule_missing"),
    ]
    for label, code in required:
        require_label(audit, BATCH_PLAN, text, [label], code, "fill batch-generation-plan.md")
    batch_ids = candidate_ids_from_value(label_value(text, ["Candidate IDs"]))
    candidate_ids = candidate_ids_from_text(candidate_text)
    missing_ids = [item for item in batch_ids if item not in candidate_ids]
    if batch_ids and missing_ids:
        add_finding(audit.blockers, "blocker", "batch_candidate_missing_from_set", f"batch plan references candidates not in prompt-candidate-set: {', '.join(missing_ids)}", "sync batch plan and candidate set")
    if not audit.changed_variables:
        audit.changed_variables = parse_changed_variables(text)
    if not audit.changed_variables:
        add_finding(audit.blockers, "blocker", "changed_variables_missing", f"{BATCH_PLAN} or {VARIABLE_INVENTORY} must state Changed variables", "make the experiment attributable")

    total_value = label_value(text, ["Total takes"])
    match = re.search(r"\d+", total_value)
    total = int(match.group(0)) if match else 0
    phase = audit.tags.get("phase", "")
    if total:
        if re.search(r"explor|探索", phase, re.I) and not (4 <= total <= 12):
            add_finding(audit.warnings, "warning", "exploration_batch_size_unusual", f"exploration total takes {total} is outside the 4-12 guideline", "keep listening workload bounded")
        if re.search(r"converg|收敛|lock|release|catalog|final", phase, re.I) and not (2 <= total <= 6):
            add_finding(audit.warnings, "warning", "convergence_batch_size_unusual", f"convergence total takes {total} is outside the 2-6 guideline", "keep convergence tight")
    audit.tags["batch"] = f"candidates={', '.join(batch_ids) or 'missing'}, total={total_value or 'missing'}"


def audit_variable_count(audit: Audit) -> None:
    changed = audit.changed_variables
    allowed = audit.allowed_variable_count or 1
    audit.tags["changed_variables"] = ", ".join(changed) or "missing"
    audit.tags["allowed_count"] = str(allowed)
    if len(changed) > allowed:
        add_finding(
            audit.blockers,
            "blocker",
            "too_many_changed_variables",
            f"changed variables exceed phase limit {allowed}: {', '.join(changed)}",
            "split into single-variable or bounded two-variable rounds",
        )
    if any("brief" in item or "goal" in item for item in changed):
        add_finding(audit.blockers, "blocker", "brief_changed_inside_batch", "brief/goal changed inside the generation batch", "freeze brief or start a new side direction")
    if "persona/voice" in changed and any(item in changed for item in ["style", "lyrics text", "lyrics context", "exclude", "weirdness", "style influence"]):
        add_finding(audit.blockers, "blocker", "persona_mixed_with_music_variables", "Persona/Voice changed together with music variables", "test identity variables separately")


def audit_handoff(project_root: Path, audit: Audit) -> None:
    handoff = read_text(project_root / EXPERIMENT_HANDOFF)
    if not handoff:
        add_finding(audit.warnings, "warning", "experiment_handoff_missing", f"missing {EXPERIMENT_HANDOFF}", "compiler handoff should explain first batch")
        return
    next_test = label_value(handoff, ["Next test", "What to test first", "First experiment"])
    if not has_value(next_test):
        add_finding(audit.warnings, "warning", "experiment_handoff_next_test_missing", f"{EXPERIMENT_HANDOFF} missing next test", "connect prompt compiler to generation batch")
    audit.tags["handoff"] = next_test or "missing"


def audit_unresolved_lines(project_root: Path, audit: Audit) -> None:
    for rel in [EXPERIMENT_INTENT, BRIEF_FREEZE, VARIABLE_INVENTORY, PROMPT_CANDIDATE_SET, BATCH_PLAN]:
        for line in blocking_lines(read_text(project_root / rel)):
            add_finding(audit.blockers, "blocker", "unresolved_evidence_line", f"{rel} has unresolved blocker line: {line}", "resolve hold/fail/pending/unknown lines")


def audit_project(project_root: Path) -> Audit:
    audit = Audit()
    audit_prompt_approval(project_root, audit)
    audit_experiment_intent(project_root, audit)
    audit_brief_freeze(project_root, audit)
    audit_variable_inventory(project_root, audit)
    audit_candidate_set(project_root, audit)
    audit_batch_plan(project_root, audit)
    audit_variable_count(audit)
    audit_handoff(project_root, audit)
    audit_unresolved_lines(project_root, audit)
    return audit


def prompt_iteration_discipline_audit_decision(project_root: Path) -> str:
    return label_value(read_text(project_root / OUTPUT), ["Decision"]) or "missing"


def prompt_iteration_discipline_audit_text_ready(text: str) -> bool:
    if PROMPT_ITERATION_DISCIPLINE_MARKER not in text:
        return False
    if not re.search(r"^Decision:\s*pass\b", text, re.I | re.M):
        return False
    if any(term not in text for term in PROMPT_ITERATION_DISCIPLINE_REQUIRED_TERMS):
        return False
    if re.search(r"\bNEEDS_REPAIR\b|Decision:\s*(hold|fail)", text, re.I):
        return False
    return True


def prompt_iteration_discipline_audit_ready(project_root: Path) -> bool:
    return prompt_iteration_discipline_audit_text_ready(read_text(project_root / OUTPUT))


def finding_rows(findings: list[Finding]) -> str:
    if not findings:
        return "| pass | none | no blocking findings | proceed |\n"
    return "\n".join(f"| {item.severity} | {item.code} | {item.message} | {item.route} |" for item in findings) + "\n"


def render_audit(project_root: Path, audit: Audit) -> str:
    attribution = "strong" if not audit.blockers and len(audit.changed_variables) <= (audit.allowed_variable_count or 1) else "weak"
    return f"""# Prompt Iteration Discipline Audit

{PROMPT_ITERATION_DISCIPLINE_MARKER}
Project root: {project_root}
Decision: {audit.decision}

This gate checks whether the next generation batch is attributable. It blocks
prompt experiments that change too many variables, drift from the frozen brief,
or lack candidate hypotheses before generated takes enter provenance and blind
review.

## Prompt Iteration Discipline Evidence

Experiment question: {audit.tags.get('question', 'missing')}
Frozen brief: {audit.tags.get('brief', 'missing')}
Allowed variable count: {audit.tags.get('allowed_count', 'missing')}
Changed variables: {audit.tags.get('changed_variables', 'missing')}
Candidate hypotheses: {audit.tags.get('candidate_hypotheses', 'missing')}; candidates={audit.tags.get('candidate_ids', 'missing')}
Batch discipline: {audit.tags.get('batch', 'missing')}
Attribution strength: {attribution}
Generation evidence handoff: {audit.decision}

## Findings

| severity | code | message | route |
|---|---|---|---|
{finding_rows(audit.blockers + audit.warnings)}
## Next Route

- pass: run `tools/audit_music_generation_evidence.py` after generating/exporting takes.
- hold: reduce variables, freeze the brief, or rewrite candidate hypotheses before spending generation attempts.
"""


def write_output(project_root: Path, text: str, allow_overwrite: bool) -> Path:
    path = project_root / OUTPUT
    if path.exists() and not allow_overwrite:
        raise FileExistsError(f"refusing to overwrite existing file: {path.relative_to(project_root).as_posix()}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--write", action="store_true", help="Write the prompt iteration discipline audit.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting the audit output.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero when prompt iteration evidence is blocked.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists():
        print(f"error: project root does not exist: {project_root}", file=sys.stderr)
        return 2

    audit = audit_project(project_root)
    if audit.blockers and args.strict:
        print("prompt iteration discipline audit blocked:", file=sys.stderr)
        for finding in audit.blockers:
            print(f"- {finding.code}: {finding.message}", file=sys.stderr)
        return 2

    text = render_audit(project_root, audit)
    if args.write:
        try:
            written = write_output(project_root, text, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        print(f"wrote {written.relative_to(project_root).as_posix()}")
    else:
        print("prompt iteration discipline audit preview")
        print(f"decision: {audit.decision}")
        print(f"changed variables: {audit.tags.get('changed_variables', 'missing')}")
        print(f"blockers: {len(audit.blockers)}")
        print(f"warnings: {len(audit.warnings)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
