#!/usr/bin/env python3
"""Audit lyric narrative and cliche removal before AI-music prompt compile.

This gate checks the semantic side of human-feeling lyrics before prosody and
prompt compilation: who is singing, where the scene happens, which concrete
images carry the song, how the title phrase functions, what each section adds,
and whether common AI-lyric cliches have been actively replaced.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


LYRIC_BRIEF_FILE = "03_writing/lyric-brief.md"
IMAGE_BANK_FILE = "03_writing/image-bank.md"
SECTION_MAP_FILE = "03_writing/section-information-map.md"
CLICHE_CUT_FILE = "03_writing/cliche-cut.md"
TITLE_PHRASE_FILE = "03_writing/title-phrase.md"
LYRICS_CONTEXT_FILE = "04_prompt/lyrics-context-map.md"
PROMPT_BRIEF_FILE = "04_prompt/prompt-compile-brief.md"
SONG_BRIEF_FILE = "01_brief/song-brief.md"
DEFAULT_OUTPUT = "03_writing/lyric-narrative-audit.md"
MARKER = "Generated by: tools/audit_music_lyric_narrative.py"

EMPTY_VALUES = {
    "",
    '""',
    "''",
    "todo",
    "tbd",
    "pending",
    "unknown",
    "unclear",
    "missing",
    "n/a",
    "na",
    "none",
    "yes/no",
    "pass/fail",
    "-",
    "--",
}

CLICHE_TERMS = [
    "dream",
    "dreams",
    "heart",
    "sky",
    "light",
    "shadow",
    "fire",
    "ocean",
    "stars",
    "echo",
    "echoes",
    "void",
    "broken",
    "lost",
    "forever",
    "tonight",
    "neon",
    "rain",
    "city lights",
    "shattered",
    "fragments",
    "midnight",
    "whisper",
    "soul",
    "wings",
    "fly",
    "tears",
    "星辰",
    "大海",
    "天空",
    "影子",
    "光",
    "火",
    "梦",
    "心",
    "永远",
    "破碎",
    "迷失",
    "回忆",
    "霓虹",
    "雨夜",
    "城市灯火",
    "孤独",
    "温柔",
    "远方",
    "自由",
    "命运",
]

CONCRETE_PATTERNS = [
    r"\bbus\b",
    r"\btrain\b",
    r"\bstation\b",
    r"\bplatform\b",
    r"\bwindow\b",
    r"\bticket\b",
    r"\bphone\b",
    r"\bmessage\b",
    r"\bkey\b",
    r"\bcup\b",
    r"\bcoat\b",
    r"\bsleeve\b",
    r"\bstair",
    r"\bstreet\b",
    r"\bkitchen\b",
    r"\bsink\b",
    r"\bdoor\b",
    r"\btable\b",
    r"\bseat\b",
    r"\breceipt\b",
    r"\bphoto\b",
    r"\bclock\b",
    r"\bshoe",
    r"\bmirror\b",
    r"\bhand\b",
    r"\bshoulder\b",
    r"\bbreath\b",
    r"\bwalk",
    r"\bwait",
    r"\bturn",
    r"车|站|窗|票|手机|讯息|钥匙|杯|外套|袖口|楼梯|街|厨房|水槽|门|桌|座位|收据|照片|钟|鞋|镜子|手|肩|呼吸|等|走|转身|末班",
]


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


def read_project(project_root: Path) -> dict[str, str]:
    docs: dict[str, str] = {}
    for path in project_root.rglob("*.md"):
        rel = path.relative_to(project_root).as_posix()
        try:
            docs[rel] = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            docs[rel] = path.read_text(errors="replace")
    return docs


def normalize_value(raw: str) -> str:
    value = raw.strip().strip("`")
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1].strip()
    value = re.sub(r"\s+", " ", value)
    if value.casefold() in EMPTY_VALUES:
        return ""
    if value.startswith("[") and value.endswith("]") and ":" in value:
        return ""
    return value


def scan_key_values(text: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|"):
            continue
        stripped = re.sub(r"^[-*]\s+", "", stripped)
        match = re.match(r"^([^:]{1,110}):\s*(.*)$", stripped)
        if not match:
            continue
        label = re.sub(r"\s+", " ", match.group(1).strip()).casefold()
        pairs.append((label, normalize_value(match.group(2))))
    return pairs


def labels_present(text: str) -> set[str]:
    return {label for label, _ in scan_key_values(text)}


def extract_value(docs: dict[str, str], paths: list[str], labels: list[str]) -> str:
    wanted = {re.sub(r"\s+", " ", label.strip()).casefold() for label in labels}
    for rel in paths:
        for label, value in scan_key_values(docs.get(rel, "")):
            if label in wanted and value:
                return value
    return ""


def extract_code_blocks(text: str) -> list[str]:
    return [block.strip() for block in re.findall(r"```(?:text|markdown)?\s*\n(.*?)```", text, flags=re.S)]


def extract_lyrics_block(docs: dict[str, str]) -> str:
    text = docs.get(LYRICS_CONTEXT_FILE, "")
    for block in extract_code_blocks(text):
        if "[Verse" in block or "[Chorus" in block or "[Intro" in block:
            return block.strip()

    lines: list[str] = []
    capture = False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and "]" in stripped:
            capture = True
        if capture and stripped and not stripped.startswith("#"):
            lines.append(stripped)
            if stripped == "[End]":
                break
    return "\n".join(lines).strip()


def split_terms(value: str) -> list[str]:
    chunks = re.split(r"[,;、，/]| and | plus |\|", value, flags=re.I)
    terms = [normalize_value(chunk) for chunk in chunks]
    return list(dict.fromkeys(term for term in terms if term))


def line_items(text: str) -> list[str]:
    items: list[str] = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|") or stripped.startswith("```"):
            continue
        stripped = re.sub(r"^[-*]\s+", "", stripped)
        if ":" in stripped:
            _, value = stripped.split(":", 1)
            stripped = value.strip()
        for item in split_terms(stripped):
            if item:
                items.append(item)
    return list(dict.fromkeys(items))


def concrete_image_items(text: str) -> list[str]:
    items = line_items(text)
    concrete: list[str] = []
    for item in items:
        if len(item) < 2:
            continue
        if any(re.search(pattern, item, flags=re.I) for pattern in CONCRETE_PATTERNS):
            concrete.append(item)
        elif re.search(r"[\u4e00-\u9fff]", item) and len(item) <= 18 and not cliche_hits(item):
            concrete.append(item)
    return list(dict.fromkeys(concrete))


def cliche_hits(text: str) -> list[str]:
    lowered = text.casefold()
    hits: list[str] = []
    for term in CLICHE_TERMS:
        if re.fullmatch(r"[a-z0-9 ' -]+", term, flags=re.I):
            pattern = rf"(?<![a-z0-9]){re.escape(term.casefold())}(?![a-z0-9])"
            if re.search(pattern, lowered):
                hits.append(term)
        elif term in text:
            hits.append(term)
    return list(dict.fromkeys(hits))


def section_present(text: str, patterns: list[str]) -> bool:
    lowered = text.casefold()
    return any(re.search(pattern, lowered, flags=re.I) for pattern in patterns)


def title_in_chorus(lyrics_block: str, title_phrase: str) -> bool:
    if not lyrics_block or not title_phrase:
        return False
    compact_title = re.sub(r"\s+", "", title_phrase.casefold())
    current = ""
    for raw in lyrics_block.splitlines():
        stripped = raw.strip()
        if stripped.startswith("[") and "]" in stripped:
            current = stripped.casefold()
            continue
        if "chorus" in current:
            compact_line = re.sub(r"\s+", "", stripped.casefold())
            if compact_title and compact_title in compact_line:
                return True
    return False


def positive_decision(value: str) -> bool:
    return bool(re.search(r"\b(pass|ready|approved|rewrite|complete|done)\b|通过|已完成|可写|可改写", value, re.I))


def evidence_tag(value: str, fallback: str = "NEEDS_REPAIR") -> str:
    return value if value else fallback


def analyze(docs: dict[str, str]) -> tuple[dict[str, str], list[Finding]]:
    lyric_paths = [LYRIC_BRIEF_FILE, SONG_BRIEF_FILE, PROMPT_BRIEF_FILE, LYRICS_CONTEXT_FILE]
    fields = {
        "narrator": extract_value(docs, lyric_paths, ["Narrator", "Point of view", "Singer persona", "Speaker"]),
        "situation": extract_value(docs, lyric_paths, ["Situation", "Scene", "Concrete place", "Time/place", "Dramatic situation"]),
        "title_phrase": extract_value(
            docs,
            lyric_paths + [TITLE_PHRASE_FILE],
            ["Title phrase", "Hook phrase", "Chorus title phrase", "Title"],
        ),
        "title_phrase_function": extract_value(
            docs,
            [TITLE_PHRASE_FILE, LYRIC_BRIEF_FILE, LYRICS_CONTEXT_FILE],
            ["Title phrase function", "Hook function", "Chorus function", "Function"],
        ),
        "central_metaphor": extract_value(
            docs,
            [LYRIC_BRIEF_FILE, TITLE_PHRASE_FILE, IMAGE_BANK_FILE],
            ["Central metaphor", "Controlling image", "Core image", "Main metaphor"],
        ),
        "verse2_development": extract_value(
            docs,
            [SECTION_MAP_FILE, LYRICS_CONTEXT_FILE],
            ["Verse 2 development", "Verse 2 new information", "Verse 2 adds", "Second verse development"],
        ),
        "bridge_perspective": extract_value(
            docs,
            [SECTION_MAP_FILE, LYRICS_CONTEXT_FILE],
            ["Bridge perspective", "Bridge turn", "Bridge reveal", "New perspective", "Final chorus payoff"],
        ),
        "cliche_removed": extract_value(
            docs,
            [CLICHE_CUT_FILE],
            ["Removed cliches", "Cliche removed", "Do not use", "Banned abstractions"],
        ),
        "cliche_replacements": extract_value(
            docs,
            [CLICHE_CUT_FILE],
            ["Replacement images", "Replace with", "Specific replacement", "Concrete replacements"],
        ),
        "cliche_decision": extract_value(
            docs,
            [CLICHE_CUT_FILE],
            ["Cliche cut decision", "Decision", "Rewrite handoff"],
        ),
    }
    fields["lyrics_block"] = extract_lyrics_block(docs)
    fields["image_tags"] = ", ".join(concrete_image_items(docs.get(IMAGE_BANK_FILE, ""))[:10])
    fields["section_tags"] = ", ".join(
        tag
        for tag, present in [
            ("verse 1", section_present(docs.get(SECTION_MAP_FILE, ""), [r"\bverse\s*1\b", r"主歌\s*1", r"第一段"])),
            ("chorus", section_present(docs.get(SECTION_MAP_FILE, ""), [r"\bchorus\b", r"副歌"])),
            ("verse 2", section_present(docs.get(SECTION_MAP_FILE, ""), [r"\bverse\s*2\b", r"主歌\s*2", r"第二段"])),
            ("bridge", section_present(docs.get(SECTION_MAP_FILE, ""), [r"\bbridge\b", r"桥段"])),
            ("final chorus", section_present(docs.get(SECTION_MAP_FILE, ""), [r"\bfinal chorus\b", r"最终副歌", r"最后副歌"])),
        ]
        if present
    )
    fields["cliche_hits"] = ", ".join(cliche_hits("\n".join([fields["lyrics_block"], docs.get(LYRIC_BRIEF_FILE, "")]))[:12])

    findings: list[Finding] = []
    required = [
        ("narrator_missing", fields["narrator"], "Narrator or point of view is missing.", "fill lyric-brief.md"),
        ("situation_missing", fields["situation"], "Concrete dramatic situation or scene is missing.", "fill lyric-brief.md"),
        ("title_phrase_missing", fields["title_phrase"], "Title phrase is missing.", "fill title-phrase.md"),
        ("title_phrase_function_missing", fields["title_phrase_function"], "Title phrase function is missing.", "fill title-phrase.md"),
        ("central_metaphor_missing", fields["central_metaphor"], "Central metaphor or controlling image is missing.", "fill lyric-brief.md"),
    ]
    for code, value, message, route in required:
        if not value:
            findings.append(Finding("blocker", code, message, route))

    image_count = len(concrete_image_items(docs.get(IMAGE_BANK_FILE, "")))
    if image_count < 4:
        findings.append(
            Finding(
                "blocker",
                "image_bank_sparse",
                f"Image bank needs at least four concrete objects, places, or actions; found {image_count}.",
                "fill image-bank.md",
            )
        )

    section_text = docs.get(SECTION_MAP_FILE, "")
    required_sections = [
        ("verse1_missing", [r"\bverse\s*1\b", r"主歌\s*1", r"第一段"], "Section map needs Verse 1 information."),
        ("chorus_missing", [r"\bchorus\b", r"副歌"], "Section map needs Chorus function/information."),
        ("verse2_missing", [r"\bverse\s*2\b", r"主歌\s*2", r"第二段"], "Section map needs Verse 2 information."),
    ]
    for code, patterns, message in required_sections:
        if not section_present(section_text, patterns):
            findings.append(Finding("blocker", code, message, "fill section-information-map.md"))
    if not section_present(section_text, [r"\bbridge\b", r"桥段"]) and not section_present(section_text, [r"\bfinal chorus\b", r"最终副歌", r"最后副歌"]):
        findings.append(
            Finding(
                "blocker",
                "bridge_or_payoff_missing",
                "Section map needs either a Bridge turn or Final Chorus payoff.",
                "fill section-information-map.md",
            )
        )
    if not fields["verse2_development"] or not re.search(r"new|add|develop|reveal|change|detail|twist|信息|推进|发展|变化|揭示|新", fields["verse2_development"], re.I):
        findings.append(
            Finding(
                "blocker",
                "verse2_development_missing",
                "Verse 2 must add new information instead of repeating Verse 1.",
                "fill section-information-map.md",
            )
        )
    if not fields["bridge_perspective"] or not re.search(r"turn|perspective|reveal|payoff|reframe|confess|视角|转折|揭示|承认|回收|升格|答案", fields["bridge_perspective"], re.I):
        findings.append(
            Finding(
                "blocker",
                "bridge_perspective_missing",
                "Bridge or final chorus needs a new perspective, reveal, or payoff.",
                "fill section-information-map.md",
            )
        )

    cliche_labels = labels_present(docs.get(CLICHE_CUT_FILE, ""))
    required_cliche_labels = {"removed cliches", "replacement images"}
    if not required_cliche_labels.issubset(cliche_labels):
        findings.append(
            Finding(
                "blocker",
                "cliche_cut_labels_missing",
                "Cliche cut needs Removed cliches and Replacement images labels.",
                "fill cliche-cut.md",
            )
        )
    if len(split_terms(fields["cliche_removed"])) < 2 or len(split_terms(fields["cliche_replacements"])) < 2:
        findings.append(
            Finding(
                "blocker",
                "cliche_replacements_sparse",
                "Cliche cut needs at least two removed cliches and two concrete replacements.",
                "fill cliche-cut.md",
            )
        )
    if fields["cliche_decision"] and not positive_decision(fields["cliche_decision"]):
        findings.append(
            Finding(
                "blocker",
                "cliche_cut_not_ready",
                f"Cliche cut decision is not ready: {fields['cliche_decision']}",
                "repair cliche-cut.md",
            )
        )

    lyric_context = fields["lyrics_block"]
    if not lyric_context:
        findings.append(Finding("blocker", "lyrics_block_missing", "Lyrics context has no section-tagged lyrics block.", "fill lyrics-context-map.md"))
    else:
        lowered = lyric_context.casefold()
        if "[verse" not in lowered:
            findings.append(Finding("blocker", "lyrics_verse_missing", "Lyrics block needs a Verse tag.", "repair lyrics-context-map.md"))
        if "[chorus" not in lowered and "[final chorus" not in lowered:
            findings.append(Finding("blocker", "lyrics_chorus_missing", "Lyrics block needs a Chorus tag.", "repair lyrics-context-map.md"))
        if "[verse 2" not in lowered and "[verse2" not in lowered:
            findings.append(Finding("warning", "lyrics_verse2_tag_missing", "Lyrics block should tag Verse 2 explicitly.", "repair lyrics-context-map.md"))
        if fields["title_phrase"] and not title_in_chorus(lyric_context, fields["title_phrase"]):
            findings.append(
                Finding(
                    "blocker",
                    "title_phrase_not_in_chorus",
                    "Title phrase must appear in a chorus or final chorus line.",
                    "repair chorus hook",
                )
            )

    cliche_text = docs.get(CLICHE_CUT_FILE, "").casefold()
    unhandled = [term for term in cliche_hits(lyric_context + "\n" + docs.get(LYRIC_BRIEF_FILE, "")) if term.casefold() not in cliche_text]
    if len(unhandled) >= 3:
        findings.append(
            Finding(
                "blocker",
                "cliche_terms_unhandled",
                "Lyrics/brief contain unhandled AI-cliche terms: " + ", ".join(unhandled[:8]),
                "move abstractions into cliche-cut.md replacements",
            )
        )

    return fields, findings


def render_findings(findings: list[Finding]) -> str:
    if not findings:
        return "| severity | code | message | route |\n|---|---|---|---|\n| pass | none | lyric narrative approved | prompt compile |\n"
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    for finding in findings:
        rows.append(f"| {finding.severity} | {finding.code} | {finding.message} | {finding.route} |")
    return "\n".join(rows) + "\n"


def render_audit(project_root: Path, fields: dict[str, str], findings: list[Finding]) -> str:
    blockers = [finding for finding in findings if finding.severity == "blocker"]
    decision = "pass" if not blockers else "repair before prompt compile"
    return f"""# Lyric Narrative Audit

{MARKER}
Project root: {project_root}
Decision: {decision}

## Lyric Narrative Evidence

Narrator/situation tags: {evidence_tag(fields['narrator'])}; {evidence_tag(fields['situation'])}
Concrete image tags: {fields['image_tags'] or 'NEEDS_REPAIR: concrete image tags'}
Title phrase function: {evidence_tag(fields['title_phrase_function'])}
Central metaphor: {evidence_tag(fields['central_metaphor'])}
Section information tags: {fields['section_tags'] or 'NEEDS_REPAIR: section information tags'}
Cliche removal: removed={fields['cliche_removed'] or 'NEEDS_REPAIR'}, replacements={fields['cliche_replacements'] or 'NEEDS_REPAIR'}
Verse 2 development: {evidence_tag(fields['verse2_development'])}
Bridge perspective: {evidence_tag(fields['bridge_perspective'])}
Lyrics rewrite handoff: {'pass' if decision == 'pass' else 'repair'}

## Findings

{render_findings(findings)}
## Prompt Routing

Lyrics context source: {LYRICS_CONTEXT_FILE}
Rewrite route: lyric-brief.md -> image-bank.md -> section-information-map.md -> cliche-cut.md -> lyrics-context-map.md -> lyrics-prosody-audit.md
Blind-listening red flags: anonymous narrator, abstract slogan chorus, Verse 2 repeat, no bridge/payoff turn, title not recalled, concrete images not heard
Cliche hits observed: {fields['cliche_hits'] or 'none'}
"""


def lyric_narrative_audit_ready(project_root: Path) -> bool:
    path = project_root / DEFAULT_OUTPUT
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    return lyric_narrative_audit_text_ready(text)


def lyric_narrative_audit_text_ready(text: str) -> bool:
    lowered = text.casefold()
    return (
        MARKER.casefold() in lowered
        and "decision: pass" in lowered
        and "## lyric narrative evidence" in lowered
        and "narrator/situation tags:" in lowered
        and "concrete image tags:" in lowered
        and "title phrase function:" in lowered
        and "central metaphor:" in lowered
        and "section information tags:" in lowered
        and "cliche removal:" in lowered
        and "verse 2 development:" in lowered
        and "bridge perspective:" in lowered
        and "lyrics rewrite handoff: pass" in lowered
        and "needs_repair" not in lowered
    )


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root created by create_music_song_project.py.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Relative output path.")
    parser.add_argument("--write", action="store_true", help="Write the audit markdown file.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit file.")
    parser.add_argument("--strict", action="store_true", help="Return exit code 1 when blockers remain.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    docs = read_project(project_root)
    fields, findings = analyze(docs)
    audit = render_audit(project_root, fields, findings)
    blockers = [finding for finding in findings if finding.severity == "blocker"]

    if args.write:
        try:
            write_if_allowed(project_root / args.output, audit, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: output exists, use --allow-overwrite: {exc}", file=sys.stderr)
            return 2
    else:
        print(audit)

    if blockers:
        print(f"lyric narrative audit has {len(blockers)} blocker(s).", file=sys.stderr)
        for finding in blockers:
            print(f"- {finding.code}: {finding.message} -> {finding.route}", file=sys.stderr)
        return 1 if args.strict else 0

    print("lyric narrative audit passed.")
    print(f"audit: {project_root / args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
