#!/usr/bin/env python3
"""Audit harmony and bass-direction evidence before an AI music prompt is compiled."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


HARMONY_BRIEF_FILE = "03_writing/harmony-brief.md"
PROGRESSION_FILE = "03_writing/progression-map.md"
BASSLINE_FILE = "03_writing/bassline-map.md"
HARMONIC_RHYTHM_FILE = "03_writing/harmonic-rhythm-map.md"
CADENCE_FILE = "03_writing/cadence-and-bridge-plan.md"
TOPLINE_AUDIT_FILE = "03_writing/topline-hook-audit.md"
TOPLINE_FILE = "03_writing/topline-map.md"
STYLE_FILE = "04_prompt/style-field-map.md"
PROMPT_BRIEF_FILE = "04_prompt/prompt-compile-brief.md"
SONG_BRIEF_FILE = "01_brief/song-brief.md"
DEFAULT_OUTPUT = "03_writing/harmony-bass-audit.md"

EMPTY_VALUES = {"", '""', "''", "todo", "tbd", "n/a", "na", "none", "yes/no", "-", "--"}
GENERIC_HARMONY = {"emotional chords", "beautiful chords", "sad chords", "pop chords", "rock chords", "cool chords"}


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


def read_project(project_root: Path) -> dict[str, str]:
    docs: dict[str, str] = {}
    for path in project_root.rglob("*.md"):
        rel = path.relative_to(project_root).as_posix()
        try:
            docs[rel] = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            docs[rel] = path.read_text(errors="replace")
    return docs


def normalize_value(raw: str) -> str:
    value = raw.strip().strip("`")
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1].strip()
    value = re.sub(r"\s+", " ", value)
    if value.casefold() in EMPTY_VALUES:
        return ""
    if value.startswith("[") and value.endswith("]") and ":" in value:
        return ""
    return value


def scan_key_values(text: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|"):
            continue
        stripped = re.sub(r"^[-*]\s+", "", stripped)
        match = re.match(r"^([^:]{1,90}):\s*(.*)$", stripped)
        if match:
            label = re.sub(r"\s+", " ", match.group(1).strip()).casefold()
            value = normalize_value(match.group(2))
            pairs.append((label, value))
    return pairs


def extract_value(docs: dict[str, str], paths: list[str], labels: list[str]) -> str:
    wanted = {re.sub(r"\s+", " ", label.strip()).casefold() for label in labels}
    for rel in paths:
        for label, value in scan_key_values(docs.get(rel, "")):
            if label in wanted and value:
                return value
    return ""


def section_present(text: str, names: list[str]) -> bool:
    lowered = text.casefold()
    for name in names:
        pattern = r"\[\s*" + re.escape(name).replace(r"\ ", r"\s+")
        if re.search(pattern, lowered) or name in lowered:
            return True
    return False


def topline_audit_passed(docs: dict[str, str]) -> bool:
    text = docs.get(TOPLINE_AUDIT_FILE, "")
    return "Generated by: tools/audit_music_topline_hook.py" in text and re.search(r"^Decision:\s*pass\b", text, flags=re.I | re.M) is not None


def is_positive(value: str) -> bool:
    return bool(re.search(r"\b(yes|true|required|exact|必须|需要)\b", value, re.I))


def is_generic(value: str) -> bool:
    compact = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", " ", value.casefold()).strip()
    if compact in GENERIC_HARMONY:
        return True
    return any(term in compact for term in GENERIC_HARMONY)


def analyze(docs: dict[str, str]) -> tuple[dict[str, str], list[Finding]]:
    paths = [
        HARMONY_BRIEF_FILE,
        PROGRESSION_FILE,
        BASSLINE_FILE,
        HARMONIC_RHYTHM_FILE,
        CADENCE_FILE,
        TOPLINE_FILE,
        TOPLINE_AUDIT_FILE,
        STYLE_FILE,
        PROMPT_BRIEF_FILE,
        SONG_BRIEF_FILE,
    ]
    fields = {
        "language": extract_value(docs, paths, ["Language", "Language lane"]),
        "genre": extract_value(docs, paths, ["Genre", "Genre lane", "Pop / rock lane"]),
        "tempo_meter": extract_value(docs, paths, ["Tempo / meter", "Tempo", "Meter", "Tempo feel"]),
        "song_emotion": extract_value(docs, paths, ["Song emotion", "Emotion arc", "Mood / energy arc", "Mood"]),
        "lyric_turning_point": extract_value(docs, paths, ["Lyric turning point", "Turning point"]),
        "topline_hook_status": extract_value(docs, paths, ["Topline hook status", "Topline lock", "Topline audit", "Decision"]),
        "key_mode_target": extract_value(docs, paths, ["Key / mode target", "Key / mode", "Key", "Mode", "Harmonic color"]),
        "main_chord_color": extract_value(docs, paths, ["Main chord color", "Chord color", "Home color"]),
        "tension_level": extract_value(docs, paths, ["Tension level", "Tension device"]),
        "bass_identity": extract_value(docs, paths, ["Bass identity", "Primary bass role", "Bass role", "Bass"]),
        "exact_harmony_required": extract_value(docs, paths, ["Exact harmony required?", "Exact harmony required"]),
        "exact_harmony_plan": extract_value(docs, paths, ["If exact", "If exact: self-made demo / MIDI / audio plan", "MIDI / audio plan", "Audio plan"]),
        "verse_progression": extract_value(docs, [PROGRESSION_FILE], ["Verse progression", "Progression"]),
        "verse_function": extract_value(docs, [PROGRESSION_FILE], ["Verse function", "Function", "Why it fits lyrics"]),
        "pre_tension": extract_value(docs, [PROGRESSION_FILE, CADENCE_FILE], ["Pre target", "Pre-Chorus tension", "Tension device", "Target chord"]),
        "chorus_progression": extract_value(docs, [PROGRESSION_FILE], ["Chorus progression"]),
        "chorus_arrival": extract_value(docs, [PROGRESSION_FILE, CADENCE_FILE], ["Chorus arrival", "Arrival point", "Chorus title landing"]),
        "title_phrase_chord": extract_value(docs, [PROGRESSION_FILE, CADENCE_FILE], ["Title phrase chord", "Title chord", "Long-note chord"]),
        "bridge_contrast": extract_value(docs, [PROGRESSION_FILE, CADENCE_FILE], ["Bridge contrast", "New color", "Reason"]),
        "final_chorus_lift": extract_value(docs, [PROGRESSION_FILE, CADENCE_FILE], ["Final chorus lift", "Return / lift", "Final chorus variation"]),
        "ending_cadence": extract_value(docs, [CADENCE_FILE], ["Ending cadence"]),
        "kick_relationship": extract_value(docs, [BASSLINE_FILE, STYLE_FILE], ["Kick relationship", "Bass/kick relationship"]),
        "bass_range_sound": extract_value(docs, [BASSLINE_FILE], ["Range / sound", "Bass sound"]),
        "verse_motion": extract_value(docs, [BASSLINE_FILE], ["Verse motion"]),
        "pre_motion": extract_value(docs, [BASSLINE_FILE], ["Pre motion", "Pre-Chorus motion"]),
        "chorus_motion": extract_value(docs, [BASSLINE_FILE], ["Chorus motion"]),
        "bridge_motion": extract_value(docs, [BASSLINE_FILE], ["Bridge motion"]),
        "verse_chord_rate": extract_value(docs, [HARMONIC_RHYTHM_FILE], ["Verse chord-change rate"]),
        "pre_chord_rate": extract_value(docs, [HARMONIC_RHYTHM_FILE], ["Pre chord-change rate", "Pre-Chorus chord-change rate"]),
        "chorus_chord_rate": extract_value(docs, [HARMONIC_RHYTHM_FILE], ["Chorus chord-change rate"]),
        "bridge_chord_rate": extract_value(docs, [HARMONIC_RHYTHM_FILE], ["Bridge chord-change rate"]),
        "pause_point": extract_value(docs, [HARMONIC_RHYTHM_FILE], ["Where harmony should pause"]),
        "accelerate_point": extract_value(docs, [HARMONIC_RHYTHM_FILE], ["Where harmony should accelerate"]),
        "must_avoid": extract_value(docs, paths, ["Must avoid", "Avoid", "Do not use"]),
    }
    findings: list[Finding] = []
    progression_text = docs.get(PROGRESSION_FILE, "")

    required = [
        ("language_missing", fields["language"], "Language is missing; four-language harmony defaults cannot be selected.", "repair song brief"),
        ("key_mode_missing", fields["key_mode_target"], "Key/mode target or harmonic color is missing.", "fill harmony-brief.md"),
        ("main_chord_color_missing", fields["main_chord_color"], "Main chord color is missing.", "fill harmony-brief.md"),
        ("bass_identity_missing", fields["bass_identity"], "Bass identity must be more specific than just 'bass'.", "fill bassline-map.md"),
        ("verse_function_missing", fields["verse_function"], "Verse progression function is missing.", "fill progression-map.md"),
        ("pre_tension_missing", fields["pre_tension"] or fields["pre_motion"], "Pre-chorus tension or bass lift is missing.", "fill progression-map.md"),
        ("chorus_arrival_missing", fields["chorus_arrival"], "Chorus arrival is missing; the hook may only get louder, not land.", "fill cadence-and-bridge-plan.md"),
        ("title_chord_missing", fields["title_phrase_chord"] or fields["chorus_arrival"], "Title phrase chord or long-note chord is missing.", "fill progression-map.md"),
        ("kick_relationship_missing", fields["kick_relationship"], "Bass/kick relationship is missing.", "fill bassline-map.md"),
        ("chorus_bass_motion_missing", fields["chorus_motion"], "Chorus bass motion is missing.", "fill bassline-map.md"),
        ("harmonic_rhythm_missing", fields["verse_chord_rate"] and fields["pre_chord_rate"] and fields["chorus_chord_rate"], "Verse/pre/chorus harmonic rhythm rates must be stated.", "fill harmonic-rhythm-map.md"),
        ("cadence_plan_missing", fields["ending_cadence"] or fields["final_chorus_lift"], "Ending cadence or final chorus lift is missing.", "fill cadence-and-bridge-plan.md"),
    ]
    for code, value, message, route in required:
        if not value:
            findings.append(Finding("blocker", code, message, route))

    if not section_present(progression_text, ["verse"]):
        findings.append(Finding("blocker", "verse_section_missing", "Progression map needs a Verse section.", "fill progression-map.md"))
    if not section_present(progression_text, ["pre-chorus", "pre chorus", "pre"]):
        findings.append(Finding("blocker", "pre_section_missing", "Progression map needs a Pre-Chorus section.", "fill progression-map.md"))
    if not section_present(progression_text, ["chorus"]):
        findings.append(Finding("blocker", "chorus_section_missing", "Progression map needs a Chorus section.", "fill progression-map.md"))

    if not topline_audit_passed(docs):
        findings.append(Finding("blocker", "topline_audit_missing", "Harmony/bass audit requires a passing topline hook audit first.", "run audit_music_topline_hook.py"))

    if fields["exact_harmony_required"] and is_positive(fields["exact_harmony_required"]) and not fields["exact_harmony_plan"]:
        findings.append(Finding("blocker", "exact_harmony_plan_missing", "Exact harmony is required, but no self-made MIDI/audio/DAW plan is recorded.", "add self-made demo or DAW plan"))

    if fields["main_chord_color"] and is_generic(fields["main_chord_color"]):
        findings.append(Finding("warning", "generic_chord_color", "Main chord color is too generic to be blind-testable.", "write mode, cadence, or voicing color"))
    if fields["bass_identity"] and fields["bass_identity"].casefold() == "bass":
        findings.append(Finding("warning", "generic_bass_identity", "Bass identity says only 'bass'; specify root, melodic, pedal, 808, upright, or kick-locked.", "fill bassline-map.md"))
    if not fields["bridge_contrast"] and not fields["final_chorus_lift"]:
        findings.append(Finding("warning", "bridge_or_lift_missing", "No bridge contrast or final chorus lift is recorded.", "fill cadence-and-bridge-plan.md"))
    if not fields["must_avoid"]:
        findings.append(Finding("warning", "avoid_list_missing", "No harmony/bass avoid list is recorded.", "add Exclude-ready avoid list"))
    if re.search(r"same four[- ]chord loop all song|四和弦全曲|random key change|muddy bass", fields["must_avoid"], re.I) is None:
        findings.append(Finding("warning", "ai_flavor_avoid_terms_missing", "Avoid list should include same-loop, random-key, or muddy-bass risks.", "add harmony/bass Exclude terms"))

    return fields, findings


def render_finding_table(findings: list[Finding]) -> str:
    if not findings:
        return "| severity | code | message | route |\n|---|---|---|---|\n| pass | none | harmony/bass direction approved | prompt compile |\n"
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    for finding in findings:
        rows.append(f"| {finding.severity} | {finding.code} | {finding.message} | {finding.route} |")
    return "\n".join(rows) + "\n"


def harmony_tags(fields: dict[str, str]) -> str:
    pieces = [
        fields["key_mode_target"],
        fields["main_chord_color"],
        fields["pre_tension"],
        fields["chorus_arrival"],
        fields["title_phrase_chord"],
        fields["final_chorus_lift"],
    ]
    text = ", ".join(piece for piece in pieces if piece)
    return text or "NEEDS_REPAIR: harmony tags"


def bass_tags(fields: dict[str, str]) -> str:
    pieces = [
        fields["bass_identity"],
        fields["kick_relationship"],
        fields["pre_motion"],
        fields["chorus_motion"],
        fields["bridge_motion"],
    ]
    text = ", ".join(piece for piece in pieces if piece)
    return text or "NEEDS_REPAIR: bass tags"


def render_audit(project_root: Path, fields: dict[str, str], findings: list[Finding]) -> str:
    blockers = [finding for finding in findings if finding.severity == "blocker"]
    warnings = [finding for finding in findings if finding.severity == "warning"]
    decision = "pass" if not blockers else "repair before prompt compile"
    return f"""# Harmony Bass Audit

Generated by: tools/audit_music_harmony_bass.py
Project root: {project_root}
Decision: {decision}

Language: {fields['language'] or 'NEEDS_REPAIR: language'}
Genre: {fields['genre'] or 'NEEDS_REPAIR: genre'}
Tempo / meter: {fields['tempo_meter'] or 'NEEDS_REPAIR: tempo / meter'}
Key / mode target: {fields['key_mode_target'] or 'NEEDS_REPAIR: key / mode target'}
Main chord color: {fields['main_chord_color'] or 'NEEDS_REPAIR: main chord color'}
Tension level: {fields['tension_level'] or fields['pre_tension'] or 'NEEDS_REPAIR: tension plan'}
Bass identity: {fields['bass_identity'] or 'NEEDS_REPAIR: bass identity'}
Chorus arrival: {fields['chorus_arrival'] or 'NEEDS_REPAIR: chorus arrival'}
Title phrase chord: {fields['title_phrase_chord'] or fields['chorus_arrival'] or 'NEEDS_REPAIR: title phrase chord'}
Kick relationship: {fields['kick_relationship'] or 'NEEDS_REPAIR: kick relationship'}
Harmonic rhythm: verse={fields['verse_chord_rate'] or 'NEEDS_REPAIR'}; pre={fields['pre_chord_rate'] or 'NEEDS_REPAIR'}; chorus={fields['chorus_chord_rate'] or 'NEEDS_REPAIR'}; bridge={fields['bridge_chord_rate'] or 'optional'}
Ending / lift: {fields['ending_cadence'] or fields['final_chorus_lift'] or 'NEEDS_REPAIR: ending or lift'}
Exact harmony required: {fields['exact_harmony_required'] or 'no'}
Blockers: {len(blockers)}
Warnings: {len(warnings)}

## Harmony Design

| field | value |
|---|---|
| song emotion | {fields['song_emotion'] or ''} |
| lyric turning point | {fields['lyric_turning_point'] or ''} |
| verse function | {fields['verse_function'] or ''} |
| pre tension | {fields['pre_tension'] or fields['pre_motion'] or ''} |
| bridge contrast | {fields['bridge_contrast'] or ''} |
| final chorus lift | {fields['final_chorus_lift'] or ''} |
| bass range / sound | {fields['bass_range_sound'] or ''} |
| avoid | {fields['must_avoid'] or ''} |

## Findings

{render_finding_table(findings)}
## Prompt Routing

Harmony tags: {harmony_tags(fields)}
Bass tags: {bass_tags(fields)}
Topline/harmony fit: title long note should land on {fields['title_phrase_chord'] or fields['chorus_arrival'] or 'NEEDS_REPAIR: title chord'} with {fields['bass_identity'] or 'NEEDS_REPAIR: bass role'}
Exclude additions: {fields['must_avoid'] or 'same four-chord loop all song, random key change, muddy bass, bass unrelated to kick, unresolved chorus'}
Repair route: key/mode palette, progression function, bassline map, harmonic rhythm, cadence/bridge plan, or self-made MIDI/audio seed
"""


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root created by create_music_song_project.py.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Relative output path.")
    parser.add_argument("--write", action="store_true", help="Write the audit markdown file.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit file.")
    parser.add_argument("--strict", action="store_true", help="Return exit code 1 when blockers remain.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    docs = read_project(project_root)
    fields, findings = analyze(docs)
    audit = render_audit(project_root, fields, findings)
    blockers = [finding for finding in findings if finding.severity == "blocker"]

    if args.write:
        try:
            write_if_allowed(project_root / args.output, audit, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: output exists, use --allow-overwrite: {exc}", file=sys.stderr)
            return 2
    else:
        print(audit)

    if blockers:
        print(f"harmony/bass audit has {len(blockers)} blocker(s).", file=sys.stderr)
        for finding in blockers:
            print(f"- {finding.code}: {finding.message} -> {finding.route}", file=sys.stderr)
        return 1 if args.strict else 0

    print("harmony/bass audit passed.")
    print(f"audit: {project_root / args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
