#!/usr/bin/env python3
"""Audit external AI-music methodology claims before methodology transfer."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from review_music_takes import parse_markdown_tables


LEDGER = "04_prompt/external-method-claim-ledger.md"
OUTPUT = "04_prompt/external-method-claim-audit.md"
MARKER = "Generated by: tools/audit_music_external_method_claims.py"
REQUIRED_TERMS = [
    "Decision: pass",
    "## External Method Claim Evidence",
    "External method claims:",
    "Official/local foundations:",
    "Community candidates:",
    "Candidate-only handoff: pass",
    "Validation route:",
    "Rejected claims:",
    "Methodology transfer handoff: pass",
]

COMMUNITY_RE = re.compile(r"bilibili|douyin|抖音|youtube|github|reddit|forum|community|blog|教程|视频|社区|外部", re.I)
OFFICIAL_LOCAL_RE = re.compile(r"official|suno help|suno docs|local|本地|官方|/path/to/suno-prompt-methodology", re.I)
MAGIC_RE = re.compile(r"guarantee|guaranteed|secret|magic|viral|100%|必爆|神\s*prompt|万能|绝对|爆款", re.I)
ADOPTED_RE = re.compile(r"\b(adopt|adopted|rule|standard|always|must)\b|规则|标准|直接采用|必须", re.I)
CANDIDATE_RE = re.compile(r"candidate|experiment|test|hypothesis|validate|a/b|blind|候选|实验|测试|验证|盲听", re.I)


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


@dataclass
class Claim:
    source: str
    url_or_path: str
    claim: str
    source_type: str
    confidence: str
    control_surface: str
    testable_variable: str
    status: str
    validation_route: str
    risk: str

    @property
    def joined(self) -> str:
        return " ".join(
            [
                self.source,
                self.url_or_path,
                self.claim,
                self.source_type,
                self.confidence,
                self.control_surface,
                self.testable_variable,
                self.status,
                self.validation_route,
                self.risk,
            ]
        )

    @property
    def is_community(self) -> bool:
        return bool(COMMUNITY_RE.search(self.joined))

    @property
    def is_official_or_local(self) -> bool:
        return bool(OFFICIAL_LOCAL_RE.search(self.joined))


@dataclass
class Audit:
    claims: list[Claim] = field(default_factory=list)
    blockers: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)

    @property
    def decision(self) -> str:
        return "pass" if not self.blockers else "hold"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def has_value(value: str) -> bool:
    normalized = value.strip().strip("`\"'").lower()
    return normalized not in {
        "",
        "-",
        "--",
        "todo",
        "tbd",
        "pending",
        "unknown",
        "n/a",
        "na",
        "missing",
        "url or local path",
        "claim to test",
    }


def pick(row: dict[str, str], names: list[str]) -> str:
    for name in names:
        key = name.lower().replace(" ", "_").replace("/", "_")
        if row.get(key):
            return row[key].strip()
        if row.get(name):
            return row[name].strip()
    return ""


def claims_from_tables(text: str) -> list[Claim]:
    claims: list[Claim] = []
    for table in parse_markdown_tables(text):
        for row in table:
            claim = Claim(
                source=pick(row, ["source", "platform", "source/platform", "source platform", "form"]),
                url_or_path=pick(row, ["url", "path", "url/path", "source url", "source path"]),
                claim=pick(row, ["claim", "method claim", "tip"]),
                source_type=pick(row, ["source type", "type"]),
                confidence=pick(row, ["confidence", "source confidence"]),
                control_surface=pick(row, ["control surface", "target control surface", "target"]),
                testable_variable=pick(row, ["testable variable", "variable", "what this tests"]),
                status=pick(row, ["status", "adoption status", "claim status"]),
                validation_route=pick(row, ["validation route", "validation", "test route"]),
                risk=pick(row, ["risk", "rights risk", "failure risk"]),
            )
            if any(has_value(value) for value in claim.__dict__.values()):
                claims.append(claim)
    return claims


def add(items: list[Finding], severity: str, code: str, message: str, route: str) -> None:
    items.append(Finding(severity, code, message, route))


def audit_project(project_root: Path) -> Audit:
    audit = Audit()
    text = read_text(project_root / LEDGER)
    if not text:
        add(audit.blockers, "blocker", "external_method_claim_ledger_missing", f"missing {LEDGER}", "create source-ranked claim ledger")
        return audit

    audit.claims = claims_from_tables(text)
    if not audit.claims:
        add(audit.blockers, "blocker", "external_method_claim_rows_missing", f"{LEDGER} has no structured claim rows", "fill the markdown table")
        return audit

    for index, claim in enumerate(audit.claims, start=1):
        prefix = f"row {index}"
        required = [
            ("source", claim.source),
            ("url/path", claim.url_or_path),
            ("claim", claim.claim),
            ("source type", claim.source_type),
            ("confidence", claim.confidence),
            ("control surface", claim.control_surface),
            ("testable variable", claim.testable_variable),
            ("status", claim.status),
            ("validation route", claim.validation_route),
            ("risk", claim.risk),
        ]
        for label, value in required:
            if not has_value(value):
                add(audit.blockers, "blocker", "claim_field_missing", f"{prefix} missing {label}", "complete claim ledger")
        if MAGIC_RE.search(claim.joined):
            add(audit.blockers, "blocker", "magic_claim_not_allowed", f"{prefix} contains magic/guaranteed-result language", "reject or rewrite as a testable hypothesis")
        if claim.is_community and ADOPTED_RE.search(claim.status) and not CANDIDATE_RE.search(claim.status + " " + claim.validation_route):
            add(audit.blockers, "blocker", "community_claim_adopted_as_rule", f"{prefix} community claim is adopted as a rule", "mark as candidate and route to blind A/B validation")
        if claim.is_community and not CANDIDATE_RE.search(claim.status + " " + claim.testable_variable + " " + claim.validation_route):
            add(audit.blockers, "blocker", "community_claim_not_testable", f"{prefix} community claim is not testable", "state variable and validation route")
        if not (claim.is_community or claim.is_official_or_local):
            add(audit.warnings, "warning", "claim_source_class_unclear", f"{prefix} source class is unclear", "mark source as official, local, or community")

    if not any(claim.is_official_or_local for claim in audit.claims):
        add(audit.blockers, "blocker", "official_or_local_foundation_missing", "no official/local foundation claim is present", "include official Suno or local local Suno prompt methodology source")
    if not any(claim.is_community for claim in audit.claims):
        add(audit.warnings, "warning", "community_claims_absent", "no community/external claims are listed", "add web/community candidates when the song uses them")

    return audit


def finding_rows(findings: list[Finding]) -> str:
    if not findings:
        return "| pass | none | no blocking findings | proceed |\n"
    return "\n".join(f"| {item.severity} | {item.code} | {item.message} | {item.route} |" for item in findings) + "\n"


def render(project_root: Path, audit: Audit) -> str:
    community = [claim for claim in audit.claims if claim.is_community]
    foundations = [claim for claim in audit.claims if claim.is_official_or_local]
    rejected = [finding.message for finding in audit.blockers if finding.code == "magic_claim_not_allowed"]
    validation_routes = sorted({claim.validation_route for claim in audit.claims if has_value(claim.validation_route)})
    return f"""# External Method Claim Audit

{MARKER}
Project root: {project_root}
Decision: {audit.decision}

This gate source-ranks external AI-music method claims before they enter the
methodology transfer plan. It allows official/local facts to become foundations,
but keeps Bilibili/Douyin/YouTube/GitHub/community tips as testable candidates
until blind listening proves they help this song.

## External Method Claim Evidence

External method claims: {len(audit.claims)}
Official/local foundations: {len(foundations)}
Community candidates: {len(community)}
Candidate-only handoff: {'pass' if not audit.blockers else 'hold'}
Validation route: {', '.join(validation_routes) if validation_routes else 'missing'}
Rejected claims: {', '.join(rejected) if rejected else 'none'}
Methodology transfer handoff: {'pass' if not audit.blockers else 'hold'}

## Findings

| severity | code | message | route |
|---|---|---|---|
{finding_rows(audit.blockers + audit.warnings)}
## Next Route

- pass: use `04_prompt/methodology-transfer-plan.md` to translate only source-ranked claims into this song.
- hold: add source URL/path, mark community claims as candidates, or remove magic/guaranteed-result language.
"""


def external_method_claim_audit_text_ready(text: str) -> bool:
    if MARKER not in text:
        return False
    if not re.search(r"^Decision:\s*pass\b", text, re.I | re.M):
        return False
    if any(term not in text for term in REQUIRED_TERMS):
        return False
    if re.search(r"\bDecision:\s*(hold|fail)\b|magic_claim_not_allowed|community_claim_adopted_as_rule", text, re.I):
        return False
    return True


def external_method_claim_audit_ready(project_root: Path) -> bool:
    return external_method_claim_audit_text_ready(read_text(project_root / OUTPUT))


def write_output(project_root: Path, text: str, allow_overwrite: bool) -> Path:
    path = project_root / OUTPUT
    if path.exists() and not allow_overwrite:
        raise FileExistsError(f"refusing to overwrite existing file: {path.relative_to(project_root).as_posix()}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--write", action="store_true", help="Write the external method claim audit.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting audit output.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero when external method claims are blocked.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists():
        print(f"error: project root does not exist: {project_root}", file=sys.stderr)
        return 2
    audit = audit_project(project_root)
    if audit.blockers and args.strict:
        print("external method claim audit blocked:", file=sys.stderr)
        for finding in audit.blockers:
            print(f"- {finding.code}: {finding.message}", file=sys.stderr)
        return 2
    text = render(project_root, audit)
    if args.write:
        try:
            written = write_output(project_root, text, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        print(f"wrote {written.relative_to(project_root).as_posix()}")
    else:
        print("external method claim audit preview")
        print(f"decision: {audit.decision}")
        print(f"claims: {len(audit.claims)}")
        print(f"blockers: {len(audit.blockers)}")
        print(f"warnings: {len(audit.warnings)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
