#!/usr/bin/env python3
"""Audit an AI music song project and update the production control board.

The audit reads project evidence and decides which stage gate should run next.
It does not listen to audio, judge rights, or replace the specialist tools. It
keeps the unattended workflow oriented by writing the current stage, blocker,
next action, and next command into 00_admin files.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from audit_music_audio_seed_retention import (
    OUTPUT as AUDIO_SEED_AUDIT,
    audio_seed_audit_ready,
    audio_seed_required,
)
from audit_music_chord_skeleton_transfer import (
    OUTPUT as CHORD_SKELETON_TRANSFER_AUDIT,
    chord_skeleton_transfer_audit_ready,
    chord_skeleton_transfer_required,
)
from audit_music_methodology_transfer import (
    DEFAULT_OUTPUT as METHODOLOGY_TRANSFER_AUDIT,
    methodology_transfer_audit_ready,
)
from audit_music_lyric_narrative import (
    DEFAULT_OUTPUT as LYRIC_NARRATIVE_AUDIT,
    lyric_narrative_audit_ready,
)
from audit_music_prompt_specificity_budget import (
    DEFAULT_OUTPUT as PROMPT_SPECIFICITY_AUDIT,
    prompt_specificity_audit_ready,
)
from audit_music_genre_lane_authenticity import (
    DEFAULT_OUTPUT as GENRE_LANE_AUTHENTICITY_AUDIT,
    genre_lane_authenticity_audit_ready,
)
from audit_music_prompt_iteration_discipline import (
    OUTPUT as PROMPT_ITERATION_DISCIPLINE_AUDIT,
    prompt_iteration_discipline_audit_ready,
)
from audit_music_post_production_mix_lock import (
    OUTPUT as POST_PRODUCTION_MIX_LOCK_AUDIT,
    post_production_mix_lock_audit_ready,
)
from audit_music_release_listener_evidence import (
    OUTPUT as RELEASE_LISTENER_AUDIT,
    release_listener_audit_ready,
)
from review_music_takes import parse_markdown_tables


OUTPUTS = {
    "board": "00_admin/song-production-control-board.md",
    "audit": "00_admin/project-status-audit.md",
    "next_action": "00_admin/next-action.md",
}

PROMPT_COMPILER_MARKER = "Generated by: tools/compile_music_prompt_package.py"
PROMPT_PACKAGE_REQUIRED_TERMS = [
    "## metadata",
    "## style of music",
    "## lyrics",
    "## prompt rationale",
    "## preflight summary",
    "model:",
    "weirdness:",
    "style influence:",
    "methodology transfer:",
    "prompt specificity:",
    "genre/lane authenticity:",
    "lyric narrative:",
    "reference audit:",
    "prosody audit:",
    "topline audit:",
    "harmony/bass audit:",
    "groove audit:",
    "structure audit:",
    "vocal audit:",
    "human anchor lane:",
    "voice identity source:",
    "persona source:",
    "custom model source:",
    "custom model corpus:",
    "my taste state:",
    "prompt boost state:",
    "exclude:",
    "genre:",
    "vocal:",
    "instrumentation:",
    "production:",
    "mood:",
]
PROMPT_PREFLIGHT_REQUIRED_TERMS = [
    "field completeness:",
    "lyrics context:",
    "methodology transfer:",
    "prompt specificity:",
    "genre/lane authenticity:",
    "lyric narrative:",
    "reference audit:",
    "prosody audit:",
    "topline audit:",
    "harmony/bass audit:",
    "groove audit:",
    "structure audit:",
    "vocal audit:",
    "exclude rationale:",
    "slider intent:",
    "model/version:",
    "human anchor lane:",
    "identity routing:",
    "my taste / boost:",
    "identity / rights:",
    "conflict check:",
    "blockers:",
    "## issues",
]
AUDIO_INSPECTION_MARKER = "Generated by: tools/inspect_music_release_audio.py"
RELEASE_GATE_MARKER = "Generated by: tools/prepare_music_release_candidate.py"
RELEASE_AUDIO_QC_MARKER = "Generated by: tools/prepare_music_release_audio_qc.py"
GENERATION_AUDIT_MARKER = "Generated by: tools/audit_music_generation_evidence.py"
GENERATION_AUDIT_REQUIRED_TERMS = [
    "Decision: pass",
    "## Generation Evidence",
    "Take provenance tags:",
    "Batch tags:",
    "Provider metadata tags:",
    "Blind review handoff:",
]
AUDIO_INSPECTION_METRICS = [
    "duration",
    "sample rate",
    "bit depth",
    "channels",
    "peak",
    "rms",
    "dc offset",
    "clipped ratio",
]
RELEASE_AUDIO_QC_REQUIRED_TERMS = [
    "## required evidence",
    "## measurements",
    "integrated lufs:",
    "lra:",
    "true peak:",
    "clipped samples:",
    "sample rate:",
    "bit depth:",
    "## listening",
    "loudness-matched reference a/b:",
    "codec preview:",
    "translation matrix:",
    "mono/phase:",
    "low end:",
    "intro/outro:",
    "## ai artifact check",
    "vocal tail:",
    "cymbals:",
    "backing vocal smear:",
    "stem bleed:",
    "over-limiting:",
    "## blocking items",
]
RELEASE_PACK_RELS = [
    "11_release/release-candidate-evidence-audit.md",
    "11_release/release-candidate-package.md",
    "11_release/release_candidate/metadata/release-candidate-manifest.md",
]


@dataclass(frozen=True)
class StageState:
    current_stage: str
    status: str
    current_blocker: str
    next_action: str
    next_command: str
    why: str
    do_not_do: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def field_value(text: str, labels: list[str]) -> str:
    wanted = {label.lower() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,80}):\s*(.*)$", stripped)
        if not match:
            continue
        label = match.group(1).strip().lower()
        value = match.group(2).strip().strip('"')
        if label in wanted and value:
            return value
    return ""


def value_from_files(project_root: Path, rels: list[str], labels: list[str]) -> str:
    for rel in rels:
        value = field_value(read_text(project_root / rel), labels)
        if value:
            return value
    return ""


def command(script: str, project_root: Path) -> str:
    return f"python3 tools/{script} --project-root {project_root} --write --allow-overwrite --strict"


def decision_is(text: str, pattern: str) -> bool:
    decision = field_value(text, ["Decision"])
    return bool(decision and re.search(pattern, decision, re.I))


def prompt_package_ready(project_root: Path) -> bool:
    text = read_text(project_root / "04_prompt/prompt-package-v001.md")
    if re.search(r"Decision:\s*repair before generation|NEEDS_REPAIR", text, re.I):
        return False
    lowered = text.lower()
    return (
        PROMPT_COMPILER_MARKER in text
        and decision_is(text, r"compile approved")
        and all(term in lowered for term in PROMPT_PACKAGE_REQUIRED_TERMS)
    )


def prompt_preflight_ready(project_root: Path) -> bool:
    text = read_text(project_root / "04_prompt/prompt-preflight-review.md")
    if not text:
        return False
    if PROMPT_COMPILER_MARKER not in text:
        return False
    lowered = text.lower()
    if any(term not in lowered for term in PROMPT_PREFLIGHT_REQUIRED_TERMS):
        return False
    if re.search(
        r"repair before generation|Field completeness:\s*fail|Prompt specificity:\s*(fail|review)|Genre/lane authenticity:\s*(fail|review)|Lyric narrative:\s*(fail|review)|Reference audit:\s*(fail|review)|Chord skeleton transfer:\s*fail|Prosody audit:\s*(fail|review)|Topline audit:\s*(fail|review)|Harmony/Bass audit:\s*(fail|review)|Groove audit:\s*(fail|review)|Structure audit:\s*(fail|review)|Vocal audit:\s*(fail|review)|Human anchor lane:\s*fail|Identity routing:\s*fail|My Taste / boost:\s*fail|Identity / rights:\s*fail|Conflict check:\s*fail|Slider intent:\s*(fail|review)|Model/version:\s*fail",
        text,
        re.I,
    ):
        return False
    return decision_is(text, r"compile approved|approved|pass")


def take_decision_ready(project_root: Path) -> bool:
    text = read_text(project_root / "06_review/take-selection-decision.md")
    best = field_value(text, ["Best take"])
    action = field_value(text, ["Action"])
    if not best or not action:
        return False
    if re.search(r"repair review evidence|insufficient evidence", action, re.I):
        return False
    return True


def generation_evidence_ready(project_root: Path) -> bool:
    text = read_text(project_root / "05_generations/generation-evidence-audit.md")
    return GENERATION_AUDIT_MARKER in text and all(term in text for term in GENERATION_AUDIT_REQUIRED_TERMS)


def take_action(project_root: Path) -> str:
    return field_value(read_text(project_root / "06_review/take-selection-decision.md"), ["Action"]).lower()


def repair_route_ready(project_root: Path) -> bool:
    text = read_text(project_root / "07_repair/repair-route-map.md")
    for table in parse_markdown_tables(text):
        headers = set(table[0].keys()) if table else set()
        if "problem" not in headers or "layer" not in headers:
            continue
        for row in table:
            problem = row.get("problem", "").strip().lower()
            if problem and problem != "problem":
                return True
    return False


def repair_route_text(project_root: Path) -> str:
    return read_text(project_root / "07_repair/repair-route-map.md")


def route_suggests_daw(project_root: Path) -> bool:
    text = repair_route_text(project_root)
    return bool(re.search(r"daw|stem|vocal|groove|drum|bass|mix|post|artifact|human|re[- ]?record|overdub|分轨|人声|鼓|贝斯|混音|后期", text, re.I))


def yes_no_pass(value: str, *, allow_na: bool = True) -> bool:
    normalized = value.strip().lower()
    if allow_na and normalized in {"n/a", "na", "not applicable"}:
        return True
    return bool(re.search(r"^(yes|y|pass|passed|preserved|no new|none|no)$", normalized, re.I))


def repair_regression_ready(project_root: Path) -> bool:
    text = read_text(project_root / "07_repair/regression-listen.md")
    if not text:
        return False
    decision = field_value(text, ["Decision"])
    if not re.search(r"keep|pass|passed|resolved|approve", decision, re.I):
        return False
    improvement = field_value(text, ["Did issue improve? 0-3", "Did issue improve"])
    match = re.search(r"(\d+(?:\.\d+)?)", improvement)
    if not match or float(match.group(1)) < 2.0:
        return False
    new_artifacts = field_value(text, ["New artifacts introduced"])
    if not new_artifacts or not re.search(r"^(no|none|n/a|na)$", new_artifacts.strip(), re.I):
        return False
    for label in ["Hook preserved", "Vocal identity preserved", "Groove preserved"]:
        value = field_value(text, [label])
        if not value or not yes_no_pass(value):
            return False
    return True


def daw_handoff_ready(project_root: Path) -> bool:
    text = read_text(project_root / "08_stems-daw/session-pack.md")
    return "Generated by: tools/prepare_music_daw_handoff.py" in text and bool(re.search(r"Locked take:\s*\S+", text))


def release_gate_ready(project_root: Path) -> bool:
    text = read_text(project_root / "11_release/release-candidate-rights-gate.md")
    return release_rights_gate_ready(project_root) and release_pack_ready(project_root)


def release_rights_gate_ready(project_root: Path) -> bool:
    text = read_text(project_root / "11_release/release-candidate-rights-gate.md")
    return RELEASE_GATE_MARKER in text and decision_is(text, r"approve release-candidate")


def release_pack_file_ready(project_root: Path, rel: str) -> bool:
    text = read_text(project_root / rel)
    return RELEASE_GATE_MARKER in text and decision_is(text, r"approve release-candidate")


def release_pack_ready(project_root: Path) -> bool:
    return all(release_pack_file_ready(project_root, rel) for rel in RELEASE_PACK_RELS)


def release_gate_blocker(project_root: Path) -> str:
    text = read_text(project_root / "11_release/release-candidate-rights-gate.md")
    if not text:
        return "release-candidate rights gate is missing"
    if RELEASE_GATE_MARKER not in text:
        return "release-candidate rights gate is not generated by tools/prepare_music_release_candidate.py"
    if not decision_is(text, r"approve release-candidate"):
        return "release-candidate rights gate is not approved"
    if not release_pack_ready(project_root):
        return "release gate is approved but release-candidate audit/package/manifest are missing, hold, or not tool-generated"
    return ""


def catalog_memory_ready(project_root: Path) -> bool:
    manifest = read_text(project_root / "12_catalog-memory/catalog-writeback-manifest.md")
    catalog = read_text(project_root / "12_catalog-memory/catalog-memory-update.md")
    generated = "Generated by: tools/prepare_music_catalog_memory.py" in manifest
    has_promotion = bool(re.search(r"^Catalog promotion:\s*(yes|no)", manifest + "\n" + catalog, re.I | re.M))
    return generated and has_promotion


def audio_qc_ready(project_root: Path) -> bool:
    text = read_text(project_root / "10_mix-master/release-audio-qc-report.md")
    return release_audio_qc_report_ready(text)


def release_audio_qc_report_ready(text: str) -> bool:
    if RELEASE_AUDIO_QC_MARKER not in text:
        return False
    if not decision_is(text, r"pass|approved|approve"):
        return False
    lowered = text.lower()
    if any(term not in lowered for term in RELEASE_AUDIO_QC_REQUIRED_TERMS):
        return False
    if re.search(r"Decision:\s*(hold|fail|return|do not release)|\b(return to master|return to mix|return to daw|do not release)\b", text, re.I):
        return False
    return True


def audio_technical_report_ready(text: str) -> bool:
    if AUDIO_INSPECTION_MARKER not in text:
        return False
    if not decision_is(text, r"pass|approved|approve"):
        return False
    lowered = text.lower()
    if "## results" not in lowered:
        return False
    if any(metric not in lowered for metric in AUDIO_INSPECTION_METRICS):
        return False
    table_rows = [line.strip() for line in text.splitlines() if line.strip().startswith("|")]
    data_rows = [
        row
        for row in table_rows
        if row.count("|") >= 10 and not re.search(r"^\|\s*-", row) and "sample rate" not in row.lower()
    ]
    return any(re.search(r"\|\s*pass\s*\|\s*$", row, re.I) for row in data_rows)


def audio_technical_ready(project_root: Path) -> bool:
    text = read_text(project_root / "10_mix-master/release-audio-technical-inspection.md")
    return audio_technical_report_ready(text)


def decide_stage(project_root: Path) -> StageState:
    if not methodology_transfer_audit_ready(project_root):
        return StageState(
            current_stage="methodology-transfer-gate",
            status="design",
            current_blocker="methodology transfer audit is missing or not passed",
            next_action="source-rank external method claims, then map local local Suno prompt methodology, official control surfaces, community candidates, model/tool route, variable discipline, and anti-magic safeguards to this song",
            next_command=command("audit_music_methodology_transfer.py", project_root),
            why="generation should not start until prompt methods and web/community claims are tied to this song's human-likeness target and treated as evidence rather than magic tags",
            do_not_do="do not compile from community tips, artist names, or model-version habits that are not source-ranked and song-specific",
        )
    if not prompt_specificity_audit_ready(project_root):
        return StageState(
            current_stage="prompt-specificity-gate",
            status="design",
            current_blocker="prompt specificity budget audit is missing or not passed",
            next_action="translate vague style words into recording, performance, section, and field-budget evidence",
            next_command=command("audit_music_prompt_specificity_budget.py", project_root),
            why="generation should not start until the prompt is specific enough to be blind-testable and free of vague style tags",
            do_not_do="do not compile from generic labels such as realistic, emotional, professional, catchy, or high quality",
        )
    if not genre_lane_authenticity_audit_ready(project_root):
        return StageState(
            current_stage="genre-lane-authenticity-gate",
            status="design",
            current_blocker="genre/lane authenticity audit is missing or not passed",
            next_action="prove the style fields cohere as a real language/genre lane with scene, tempo, vocal, arrangement, production, lyric stance, hook, and anti-drift evidence",
            next_command=command("audit_music_genre_lane_authenticity.py", project_root),
            why="generation should not start until concrete prompt fields form a believable production lane instead of genre soup or style-lyric mismatch",
            do_not_do="do not compile from stacked genre tags whose blend, lyric stance, arrangement, or production grammar is not explained",
        )
    if not lyric_narrative_audit_ready(project_root):
        return StageState(
            current_stage="lyric-narrative-gate",
            status="design",
            current_blocker="lyric narrative/cliche-cut audit is missing or not passed",
            next_action="prove narrator, concrete scene, image bank, title phrase function, section information, Verse 2 development, bridge/payoff turn, and cliche replacements",
            next_command=command("audit_music_lyric_narrative.py", project_root),
            why="generation should not start until lyrics have semantic evidence of a human narrator, concrete images, section development, and removed AI-cliche language",
            do_not_do="do not treat prosody-only lyrics as semantically human or generate from abstract slogan choruses",
        )
    if chord_skeleton_transfer_required(project_root) and not chord_skeleton_transfer_audit_ready(project_root):
        return StageState(
            current_stage="chord-skeleton-transfer-gate",
            status="design",
            current_blocker="reference upload / chord skeleton route is active but chord skeleton transfer audit is missing or not passed",
            next_action="prove reference status, allowed action, BPM/Key/progression, MIDI simplification, upload permission, retention target, prompt pairing, and reverse-analysis plan",
            next_command=command("audit_music_chord_skeleton_transfer.py", project_root),
            why="reference upload generation must prove it is using a self-owned or authorized chord skeleton, not an unauthorized reference clone",
            do_not_do="do not upload reference audio, exported MIDI, or a chord skeleton into Suno before this gate passes",
        )
    if not prompt_package_ready(project_root) or not prompt_preflight_ready(project_root):
        return StageState(
            current_stage="prompt-compile-gate",
            status="design",
            current_blocker="compiler-generated prompt package or prompt preflight is missing, unresolved, or not approved",
            next_action="fill brief/writing/prompt inputs, then run the prompt package compiler",
            next_command=command("compile_music_prompt_package.py", project_root),
            why="generation should not start until Style, Lyrics, Exclude, sliders, and rights constraints are explicit and compiler-audited",
            do_not_do="do not batch-generate from an empty scaffold or vague genre labels",
        )
    if not prompt_iteration_discipline_audit_ready(project_root):
        return StageState(
            current_stage="prompt-iteration-discipline-gate",
            status="prompt compiled",
            current_blocker="prompt iteration discipline audit is missing or not passed",
            next_action="freeze the brief, state the experiment question, list allowed variables, write prompt candidates, and prove the batch changes only the allowed variable(s)",
            next_command=command("audit_music_prompt_iteration_discipline.py", project_root),
            why="generated takes must be attributable before they can teach prompt memory or enter blind review",
            do_not_do="do not spend generation attempts or audit take provenance from a batch that changed style, lyrics, sliders, persona, and excludes at once",
        )
    if not generation_evidence_ready(project_root):
        return StageState(
            current_stage="prompt-experiment-gate",
            status="prompt compiled",
            current_blocker="generation evidence audit is missing or not passed",
            next_action="fill batch-generation-plan, take-ledger, provider-result-ledger, metadata, and audio paths or links, then audit generation evidence",
            next_command=command("audit_music_generation_evidence.py", project_root),
            why="generated takes must prove prompt package, provider/model, settings, audio source, and metadata provenance before blind review",
            do_not_do="do not blind-review, lock, repair, DAW-handoff, release, or catalog orphan takes",
        )
    if audio_seed_required(project_root) and not audio_seed_audit_ready(project_root):
        return StageState(
            current_stage="audio-seed-retention-gate",
            status="prompt experiment",
            current_blocker="human audio seed is used but audio seed retention audit is missing or not passed",
            next_action="fill audio-rights-ledger, retention-target, prompt-pairing, generation evidence, and anchor-retention-review, then audit seed retention",
            next_command=command("audit_music_audio_seed_retention.py", project_root),
            why="a generated take that used Audio Upload, Cover, Add Vocals, or nonzero Audio Influence must prove the intended human seed survived before ordinary blind review",
            do_not_do="do not treat a seeded generation as best take, release candidate, or catalog seed until retention and rights evidence pass",
        )
    if not take_decision_ready(project_root):
        return StageState(
            current_stage="take-selection-gate",
            status="prompt experiment",
            current_blocker="no scored best-take decision found",
            next_action="fill take-ledger and blind-review scores, then select the next production action",
            next_command=command("review_music_takes.py", project_root),
            why="the workflow needs a blind-review decision before repair, DAW, or release routing",
            do_not_do="do not pick the loudest or newest take without structured listening evidence",
        )
    if not repair_route_ready(project_root):
        return StageState(
            current_stage="repair-routing-gate",
            status="best take",
            current_blocker="best take exists but no concrete repair route rows are present",
            next_action="turn the take decision into repair routes and regression checks",
            next_command=command("route_music_repairs.py", project_root),
            why="AI flavor must be assigned to lyric, prosody, topline, groove, vocal, mix, rights, or catalog layers",
            do_not_do="do not keep regenerating the whole song before identifying the blocker layer",
        )
    action = take_action(project_root)
    if action in {"controlled regeneration", "discard and repair brief"}:
        return StageState(
            current_stage="prompt-experiment-gate",
            status="repair required",
            current_blocker=f"take action is {action}; this is not a post-production or release candidate",
            next_action="repair the brief or run a single-variable generation batch before selecting a new take",
            next_command=command("compile_music_prompt_package.py", project_root),
            why="controlled regeneration and discard decisions mean the current take should not enter DAW, release, or catalog gates",
            do_not_do="do not use repair-route-map.md as permission to publish a take that was not locked",
        )
    if action == "repair candidate" and not route_suggests_daw(project_root):
        if not repair_regression_ready(project_root):
            return StageState(
                current_stage="repair-regression-gate",
                status="repair candidate",
                current_blocker="local repair route exists but 07_repair/regression-listen.md has not passed",
                next_action="perform the routed lyric/topline/structure/prompt repair, then fill regression-listen and update blind-review",
                next_command="",
                why="non-DAW repairs must prove the issue improved and no new AI artifacts were introduced before the project can move on",
                do_not_do="do not advance to release, catalog, or mastering from an unresolved local repair route",
            )
        return StageState(
            current_stage="take-selection-gate",
            status="repair verified",
            current_blocker="repair regression passed; best-take decision must be refreshed",
            next_action="rerun blind review and regenerate take-selection-decision from the repaired version",
            next_command=command("review_music_takes.py", project_root),
            why="a repaired take needs a fresh blind-review decision before it can become lock for post-production",
            do_not_do="do not treat regression-listen keep as release approval",
        )
    if route_suggests_daw(project_root) and not daw_handoff_ready(project_root) and not release_gate_ready(project_root):
        return StageState(
            current_stage="daw-humanization-gate",
            status="repair candidate",
            current_blocker="repair route points to stems/DAW/vocal/groove/mix work but no session pack is ready",
            next_action="prepare DAW/stems handoff and humanization session files",
            next_command=command("prepare_music_daw_handoff.py", project_root),
            why="a strong AI take should become editable material before it is treated as final audio",
            do_not_do="do not master or publish over unresolved stem, vocal, groove, or mix artifacts",
        )
    if not post_production_mix_lock_audit_ready(project_root) and not release_gate_ready(project_root):
        return StageState(
            current_stage="post-production-mix-lock-gate",
            status="release-candidate",
            current_blocker="post-production mix-lock audit is missing or not passed",
            next_action="fill post-review, arrangement-density-triage, mix-plan, mix-lock-preflight, and final-humanized-master-review, then audit post-production mix lock",
            next_command=command("audit_music_post_production_mix_lock.py", project_root),
            why="a locked take should not enter release listener or rights gates until arrangement density, vocal center, low-end pocket, space/dynamics, transitions/outro, and AI artifacts are locked",
            do_not_do="do not let loudness, rights approval, or repeated listening hide unresolved post-production AI flavor",
        )
    if not release_listener_audit_ready(project_root) and not release_gate_ready(project_root):
        return StageState(
            current_stage="release-listener-gate",
            status="release-candidate",
            current_blocker="external listener release evidence audit is missing or not passed",
            next_action="fill external-listener-panel, first-20-second-test, hook-memory-test, and ai-flavor-red-flag-survey, then audit listener evidence",
            next_command=command("audit_music_release_listener_evidence.py", project_root),
            why="public releases need outside-ear proof that the first 20 seconds hold, the hook is remembered, and AI-flavor red flags are low",
            do_not_do="do not let rights approval override weak listener pull, failed hook memory, or obvious AI flavor",
        )
    release_blocker = release_gate_blocker(project_root)
    if release_blocker or not audio_technical_ready(project_root) or not audio_qc_ready(project_root):
        blocker = release_blocker or "release gate is approved but required release audio evidence is incomplete"
        if not release_blocker and not audio_technical_ready(project_root):
            blocker = "release gate is missing and release-audio-technical-inspection.md has not passed"
            if release_gate_ready(project_root):
                blocker = "release gate is approved but release-audio-technical-inspection.md is not tool-generated with metrics"
        if not release_blocker and not audio_qc_ready(project_root):
            blocker = "release gate is missing and release-audio-qc-report.md has not passed"
            if release_gate_ready(project_root):
                blocker = "release gate is approved but release-audio-qc-report.md is not tool-generated with QC evidence"
        return StageState(
            current_stage="release-rights-gate",
            status="release-candidate",
            current_blocker=blocker,
            next_action="complete audio QC/listener/rights evidence, then prepare the release-candidate gate",
            next_command=command("prepare_music_release_candidate.py", project_root),
            why="audio quality, external feedback, rights, AI disclosure, and platform policy must be checked before publish-ready",
            do_not_do="do not mark publish-ready from musical preference alone",
        )
    if not catalog_memory_ready(project_root):
        return StageState(
            current_stage="catalog-memory-gate",
            status="publish-ready",
            current_blocker="release gate exists but catalog memory has not been written back",
            next_action="write catalog memory, prompt memory, artifact memory, and next-song seed",
            next_command=command("prepare_music_catalog_memory.py", project_root),
            why="a finished song should improve the next song instead of becoming an isolated one-off",
            do_not_do="do not use this song as a Persona, Voice, Custom Model, or catalog seed before promotion status is explicit",
        )
    return StageState(
        current_stage="catalog-memory-gate",
        status="catalog-updated",
        current_blocker="none",
        next_action="human review, archive evidence, then decide whether to release, revise, or start the next song",
        next_command="",
        why="all core automated gates have evidence and catalog writeback exists",
        do_not_do="do not keep editing without a new concrete review question",
    )


def evidence_table(project_root: Path) -> str:
    audio_seed_status = "not required"
    if audio_seed_required(project_root):
        audio_seed_status = "pass" if audio_seed_audit_ready(project_root) else "missing/incomplete"
    chord_skeleton_status = "not required"
    if chord_skeleton_transfer_required(project_root):
        chord_skeleton_status = "pass" if chord_skeleton_transfer_audit_ready(project_root) else "missing/incomplete"
    checks = [
        ("methodology transfer", METHODOLOGY_TRANSFER_AUDIT, methodology_transfer_audit_ready(project_root)),
        ("prompt specificity", PROMPT_SPECIFICITY_AUDIT, prompt_specificity_audit_ready(project_root)),
        ("genre/lane authenticity", GENRE_LANE_AUTHENTICITY_AUDIT, genre_lane_authenticity_audit_ready(project_root)),
        ("lyric narrative", LYRIC_NARRATIVE_AUDIT, lyric_narrative_audit_ready(project_root)),
        ("chord skeleton transfer", CHORD_SKELETON_TRANSFER_AUDIT, chord_skeleton_status),
        ("prompt package", "04_prompt/prompt-package-v001.md", prompt_package_ready(project_root)),
        ("prompt preflight", "04_prompt/prompt-preflight-review.md", prompt_preflight_ready(project_root)),
        ("prompt iteration discipline", PROMPT_ITERATION_DISCIPLINE_AUDIT, prompt_iteration_discipline_audit_ready(project_root)),
        ("generation evidence", "05_generations/generation-evidence-audit.md", generation_evidence_ready(project_root)),
        ("audio seed retention", AUDIO_SEED_AUDIT, audio_seed_status),
        ("take decision", "06_review/take-selection-decision.md", take_decision_ready(project_root)),
        ("repair route", "07_repair/repair-route-map.md", repair_route_ready(project_root)),
        ("repair regression", "07_repair/regression-listen.md", repair_regression_ready(project_root)),
        ("DAW handoff", "08_stems-daw/session-pack.md", daw_handoff_ready(project_root)),
        ("post-production mix lock", POST_PRODUCTION_MIX_LOCK_AUDIT, post_production_mix_lock_audit_ready(project_root)),
        ("audio technical inspection", "10_mix-master/release-audio-technical-inspection.md", audio_technical_ready(project_root)),
        ("audio QC", "10_mix-master/release-audio-qc-report.md", audio_qc_ready(project_root)),
        ("release listener evidence", RELEASE_LISTENER_AUDIT, release_listener_audit_ready(project_root)),
        ("release gate", "11_release/release-candidate-rights-gate.md", release_gate_ready(project_root)),
        ("release candidate pack", "11_release/release-candidate-evidence-audit.md + package + manifest", release_pack_ready(project_root)),
        ("catalog memory", "12_catalog-memory/catalog-writeback-manifest.md", catalog_memory_ready(project_root)),
    ]
    rows = ["| gate | evidence | status |", "|---|---|---|"]
    for gate, rel, ok in checks:
        status = ok if isinstance(ok, str) else ("pass" if ok else "missing/incomplete")
        rows.append(f"| {gate} | {rel} | {status} |")
    return "\n".join(rows)


def project_context(project_root: Path) -> dict[str, str]:
    return {
        "project": value_from_files(project_root, ["README.md", "01_brief/project-intake.md"], ["project / artist", "project", "artist / catalog"]),
        "song": value_from_files(project_root, ["README.md", "01_brief/song-brief.md"], ["song", "song title", "title"]) or project_root.name,
        "language": value_from_files(project_root, ["README.md", "01_brief/song-brief.md"], ["language"]),
        "lane": value_from_files(project_root, ["README.md", "01_brief/song-brief.md"], ["lane", "genre lane"]),
        "best_take": field_value(read_text(project_root / "06_review/take-selection-decision.md"), ["Best take"]),
        "release_decision": field_value(read_text(project_root / "11_release/release-candidate-rights-gate.md"), ["Decision"]),
    }


def render_board(project_root: Path, state: StageState) -> str:
    ctx = project_context(project_root)
    return f"""# Song Production Control Board

Generated by: tools/audit_music_song_project_status.py
Project root: {project_root}

Project: {ctx['project']}
Song title: {ctx['song']}
Language: {ctx['language']}
Lane: {ctx['lane']}
Best take: {ctx['best_take']}
Release decision: {ctx['release_decision']}

Current stage: {state.current_stage}
Status: {state.status}
Current blocker: {state.current_blocker}
Next action: {state.next_action}
Why this action: {state.why}
Do not do: {state.do_not_do}
Next command:
```bash
{state.next_command or '# no automated next command; human review required'}
```

## Gate Evidence

{evidence_table(project_root)}
"""


def render_audit(project_root: Path, state: StageState) -> str:
    return f"""# Project Status Audit

Generated by: tools/audit_music_song_project_status.py
Project root: {project_root}

Current stage: {state.current_stage}
Status: {state.status}
Current blocker: {state.current_blocker}
Next action: {state.next_action}
Next command: {state.next_command or 'human review'}

## Gate Evidence

{evidence_table(project_root)}

## Interpretation

{state.why}

## Guardrail

{state.do_not_do}
"""


def render_next_action(project_root: Path, state: StageState) -> str:
    return f"""# Next Action

Generated by: tools/audit_music_song_project_status.py
Project root: {project_root}

Stage: {state.current_stage}
Status: {state.status}
Action: {state.next_action}
Blocker: {state.current_blocker}

```bash
{state.next_command or '# human review required'}
```
"""


def output_contents(project_root: Path, state: StageState) -> dict[str, str]:
    return {
        OUTPUTS["board"]: render_board(project_root, state),
        OUTPUTS["audit"]: render_audit(project_root, state),
        OUTPUTS["next_action"]: render_next_action(project_root, state),
    }


def write_outputs(project_root: Path, contents: dict[str, str], allow_overwrite: bool) -> list[Path]:
    targets = [project_root / rel for rel in contents]
    existing = [path for path in targets if path.exists()]
    if existing and not allow_overwrite:
        raise FileExistsError("refusing to overwrite existing files: " + ", ".join(path.relative_to(project_root).as_posix() for path in existing))
    written: list[Path] = []
    for rel, text in contents.items():
        path = project_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--write", action="store_true", help="Write status audit files.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting status audit files.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists():
        print(f"error: project root does not exist: {project_root}", file=sys.stderr)
        return 2
    state = decide_stage(project_root)
    contents = output_contents(project_root, state)
    if args.write:
        try:
            written = write_outputs(project_root, contents, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        for path in written:
            print(f"wrote {path.relative_to(project_root).as_posix()}")
    else:
        print("song project status audit")
        print(f"stage: {state.current_stage}")
        print(f"status: {state.status}")
        print(f"next action: {state.next_action}")
        if state.next_command:
            print(f"next command: {state.next_command}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
