#!/usr/bin/env python3
"""Audit prompt specificity and field budget before AI-music prompt compile.

This gate turns the local Suno methodology into an executable pre-compile
check. It rejects vague prompt language unless the project has translated it
into concrete, audible recording, performance, section, and field-budget
evidence.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from audit_music_methodology_transfer import (
    PROTECTED_IDENTITY_NAMES,
    methodology_transfer_audit_ready,
)


STYLE_FILE = "04_prompt/style-field-map.md"
LYRICS_FILE = "04_prompt/lyrics-context-map.md"
EXCLUDE_FILE = "04_prompt/exclude-negative-aesthetic.md"
BUDGET_FILE = "04_prompt/field-length-and-specificity-budget.md"
DEFAULT_OUTPUT = "04_prompt/prompt-specificity-budget-audit.md"
MARKER = "Generated by: tools/audit_music_prompt_specificity_budget.py"

EMPTY_VALUES = {
    "",
    '""',
    "''",
    "todo",
    "tbd",
    "pending",
    "unknown",
    "unclear",
    "missing",
    "n/a",
    "na",
    "none",
    "yes/no",
    "pass/fail",
    "-",
    "--",
}

VAGUE_TERMS = [
    "beautiful",
    "catchy",
    "cinematic",
    "cool",
    "emotional",
    "epic",
    "good",
    "great",
    "high quality",
    "hit song",
    "natural",
    "nice",
    "professional",
    "powerful",
    "realistic",
    "trending",
    "viral",
]

RECORDING_PATTERNS = [
    r"\bclose[- ]?mic\b",
    r"\bdry\b",
    r"\broom\b",
    r"\bplate\b",
    r"\breverb\b",
    r"\btape\b",
    r"\bsaturation\b",
    r"\banalog\b",
    r"\bpreamp\b",
    r"\bmic(?:rophone)?\b",
    r"\bnoise floor\b",
    r"\bmono\b",
    r"\bstereo\b",
    r"\bnarrow\b",
    r"\bwide(?:r)?\b",
    r"\bcenter(?:ed)?\b",
    r"\bcompression\b",
    r"\bdistortion\b",
    r"\btransient\b",
    r"\blow[- ]end\b",
    r"\bspace\b",
    r"\bbleed\b",
    r"\bhiss\b",
    r"干声|近讲|近距|房间|混响|板式|磁带|饱和|单声道|立体声|窄|宽|空间",
]

PERFORMANCE_PATTERNS = [
    r"\bdiction\b",
    r"\bregister\b",
    r"\bvibrato\b",
    r"\bbreath\b",
    r"\brestrained\b",
    r"\bbelt\b",
    r"\bfalsetto\b",
    r"\bmixed voice\b",
    r"\blead vocal\b",
    r"\bdouble[sd]?\b",
    r"\bharmon(?:y|ies)\b",
    r"\bbrushed\b",
    r"\bfingerpicked\b",
    r"\bmuted\b",
    r"\bghost notes?\b",
    r"\bbackbeat\b",
    r"\bkick\b",
    r"\bsnare\b",
    r"\bhat[s]?\b",
    r"\bbass\b",
    r"\bgroove\b",
    r"\bpocket\b",
    r"\bpickup\b",
    r"\bstrum(?:med|ming)?\b",
    r"\barticulation\b",
    r"\bvelocity\b",
    r"\bmicrotiming\b",
    r"\bbehind\b",
    r"\bahead\b",
    r"\blegato\b",
    r"\bstaccato\b",
    r"\bsustain(?:ed)?\b",
    r"\briff\b",
    r"\bmotif\b",
    r"咬字|气口|颤音|克制|弱唱|强拍|鼓|贝斯|律动|口袋|切分|拨弦|闷音|过门|动机",
]

SECTION_PATTERNS = [
    r"\bintro\b",
    r"\bverse\b",
    r"\bpre[- ]?chorus\b",
    r"\bchorus\b",
    r"\bbridge\b",
    r"\bfinal chorus\b",
    r"\boutro\b",
    r"\btitle phrase\b",
    r"\bhook\b",
    r"\bsection\b",
    r"\btransition\b",
    r"\bpayoff\b",
    r"\benergy\b",
    r"主歌|副歌|预副歌|桥段|尾声|标题句|钩子|段落|转场|能量|收束",
]


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


def read_project(project_root: Path) -> dict[str, str]:
    docs: dict[str, str] = {}
    for path in project_root.rglob("*.md"):
        rel = path.relative_to(project_root).as_posix()
        try:
            docs[rel] = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            docs[rel] = path.read_text(errors="replace")
    return docs


def normalize_value(raw: str) -> str:
    value = raw.strip().strip("`")
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1].strip()
    value = re.sub(r"\s+", " ", value)
    if value.casefold() in EMPTY_VALUES:
        return ""
    if value.startswith("[") and value.endswith("]") and ":" in value:
        return ""
    return value


def scan_key_values(text: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|"):
            continue
        stripped = re.sub(r"^[-*]\s+", "", stripped)
        match = re.match(r"^([^:]{1,110}):\s*(.*)$", stripped)
        if not match:
            continue
        label = re.sub(r"\s+", " ", match.group(1).strip()).casefold()
        pairs.append((label, normalize_value(match.group(2))))
    return pairs


def labels_present(text: str) -> set[str]:
    return {label for label, _ in scan_key_values(text)}


def extract_value(docs: dict[str, str], paths: list[str], labels: list[str]) -> str:
    wanted = {re.sub(r"\s+", " ", label.strip()).casefold() for label in labels}
    for rel in paths:
        for label, value in scan_key_values(docs.get(rel, "")):
            if label in wanted and value:
                return value
    return ""


def extract_code_blocks(text: str) -> list[str]:
    return [block.strip() for block in re.findall(r"```(?:text|markdown)?\s*\n(.*?)```", text, flags=re.S)]


def word_count(value: str) -> int:
    return len(re.findall(r"[A-Za-z0-9]+|[\u4e00-\u9fff]", value))


def contains_pattern(value: str, patterns: list[str]) -> bool:
    return any(re.search(pattern, value, flags=re.I) for pattern in patterns)


def matching_terms(value: str, patterns: list[str]) -> list[str]:
    hits: list[str] = []
    for pattern in patterns:
        match = re.search(pattern, value, flags=re.I)
        if match:
            hits.append(match.group(0))
    return list(dict.fromkeys(hits))


def vague_hits(value: str) -> list[str]:
    compact = re.sub(r"[^a-z0-9]+", " ", value.casefold())
    hits: list[str] = []
    for term in VAGUE_TERMS:
        pattern = rf"(?<![a-z0-9]){re.escape(term)}(?![a-z0-9])"
        if re.search(pattern, compact):
            hits.append(term)
    return hits


def protected_identity_hits(text: str) -> list[str]:
    hits: list[str] = []
    for name in PROTECTED_IDENTITY_NAMES:
        if not name:
            continue
        if re.fullmatch(r"[A-Za-z0-9 .'\-&]+", name):
            pattern = rf"(?<![A-Za-z0-9]){re.escape(name)}(?![A-Za-z0-9])"
            found = re.search(pattern, text, flags=re.I)
        else:
            found = name.casefold() in text.casefold()
        if found:
            hits.append(name)
    return hits


def term_list(value: str) -> list[str]:
    chunks = re.split(r"[,;、，/]| and | plus ", value, flags=re.I)
    terms = [chunk.strip() for chunk in chunks if normalize_value(chunk)]
    return list(dict.fromkeys(terms))


def analyze(docs: dict[str, str], project_root: Path) -> tuple[dict[str, str], list[Finding]]:
    style_paths = [STYLE_FILE]
    fields = {
        "genre": extract_value(docs, style_paths, ["genre", "genre lane", "style"]),
        "tempo_meter": extract_value(docs, style_paths, ["tempo / meter", "tempo", "meter"]),
        "key_mode": extract_value(docs, style_paths, ["key / mode", "key", "mode", "harmonic color"]),
        "vocal": extract_value(docs, style_paths, ["vocal", "vocal identity"]),
        "drums_groove": extract_value(docs, style_paths, ["drums / groove", "drums", "groove"]),
        "bass_role": extract_value(docs, style_paths, ["bass role", "bass"]),
        "harmony_instruments": extract_value(docs, style_paths, ["harmony instruments", "chords", "harmony"]),
        "lead_instruments": extract_value(docs, style_paths, ["lead / hook instruments", "lead instrument", "hook instrument"]),
        "instrumentation": extract_value(docs, style_paths, ["instrumentation", "core instruments"]),
        "production": extract_value(docs, style_paths, ["production", "production texture", "mix", "space"]),
        "mood": extract_value(docs, style_paths, ["mood", "mood / energy arc", "energy arc"]),
        "must_hear_terms": extract_value(docs, [BUDGET_FILE], ["Must-hear terms"]),
        "nice_terms": extract_value(docs, [BUDGET_FILE], ["Nice-to-have terms"]),
        "remove_vague_terms": extract_value(docs, [BUDGET_FILE], ["Remove vague terms"]),
        "remove_duplicated_terms": extract_value(docs, [BUDGET_FILE], ["Remove duplicated terms"]),
        "move_to_lyrics": extract_value(docs, [BUDGET_FILE], ["Move to Lyrics context"]),
        "move_to_exclude": extract_value(docs, [BUDGET_FILE], ["Move to Exclude"]),
        "move_to_experiment": extract_value(docs, [BUDGET_FILE], ["Move to experiment note"]),
        "field_budget_decision": extract_value(docs, [BUDGET_FILE], ["Field budget decision", "Budget decision"]),
        "source_rationale": extract_value(docs, [BUDGET_FILE], ["Source / rationale", "Source rationale"]),
    }
    if not fields["instrumentation"]:
        fields["instrumentation"] = ", ".join(
            part
            for part in [
                fields["drums_groove"],
                fields["bass_role"],
                fields["harmony_instruments"],
                fields["lead_instruments"],
            ]
            if part
        )

    lyrics_context = docs.get(LYRICS_FILE, "")
    for block in extract_code_blocks(lyrics_context):
        if "[" in block and "]" in block:
            lyrics_context = block
            break
    exclude_text = docs.get(EXCLUDE_FILE, "")
    generation_text = "\n".join(
        [
            fields["genre"],
            fields["tempo_meter"],
            fields["key_mode"],
            fields["vocal"],
            fields["drums_groove"],
            fields["bass_role"],
            fields["harmony_instruments"],
            fields["lead_instruments"],
            fields["instrumentation"],
            fields["production"],
            fields["mood"],
        ]
    )
    fields["style_generation_text"] = generation_text
    fields["recording_tags"] = ", ".join(matching_terms(generation_text, RECORDING_PATTERNS))
    fields["performance_tags"] = ", ".join(matching_terms(generation_text, PERFORMANCE_PATTERNS))
    fields["section_tags"] = ", ".join(matching_terms(generation_text + "\n" + lyrics_context, SECTION_PATTERNS))
    fields["vague_hits"] = ", ".join(vague_hits(generation_text))

    findings: list[Finding] = []
    required_style = [
        ("genre_missing", fields["genre"], "Genre/lane is missing.", "fill style-field-map.md"),
        ("vocal_missing", fields["vocal"], "Vocal field is missing.", "fill style-field-map.md"),
        ("instrumentation_missing", fields["instrumentation"], "Instrumentation or instrument-role fields are missing.", "fill style-field-map.md"),
        ("production_missing", fields["production"], "Production/recording field is missing.", "fill style-field-map.md"),
        ("mood_missing", fields["mood"], "Mood or energy arc is missing.", "fill style-field-map.md"),
    ]
    for code, value, message, route in required_style:
        if not value:
            findings.append(Finding("blocker", code, message, route))

    budget_labels = labels_present(docs.get(BUDGET_FILE, ""))
    required_budget_labels = {
        "must-hear terms",
        "nice-to-have terms",
        "remove vague terms",
        "remove duplicated terms",
        "move to lyrics context",
        "move to exclude",
        "move to experiment note",
        "field budget decision",
        "source / rationale",
    }
    missing_labels = sorted(required_budget_labels - budget_labels)
    if missing_labels:
        findings.append(
            Finding(
                "blocker",
                "budget_labels_missing",
                "Field-length budget is missing labels: " + ", ".join(missing_labels[:5]),
                "fill field-length-and-specificity-budget.md",
            )
        )
    if len(term_list(fields["must_hear_terms"])) < 3:
        findings.append(Finding("blocker", "must_hear_terms_sparse", "Must-hear terms needs at least three concrete audible terms.", "fill field-length-and-specificity-budget.md"))
    if fields["field_budget_decision"] and not re.search(r"\b(pass|ready|approved|compile)\b", fields["field_budget_decision"], re.I):
        findings.append(Finding("blocker", "budget_decision_not_ready", f"Field budget decision is not ready: {fields['field_budget_decision']}", "repair field-length-and-specificity-budget.md"))
    if not fields["source_rationale"] or not re.search(r"suno prompt|realism|local|method|source|方法论|真实|录音", fields["source_rationale"], re.I):
        findings.append(Finding("warning", "budget_source_weak", "Source/rationale should link the budget to local Suno methodology or realism descriptors.", "add source rationale"))

    if not methodology_transfer_audit_ready(project_root):
        findings.append(Finding("blocker", "methodology_transfer_not_ready", "Methodology transfer audit must pass before prompt specificity can be attributed.", "run audit_music_methodology_transfer.py"))
    if not contains_pattern(fields["production"], RECORDING_PATTERNS):
        findings.append(Finding("blocker", "recording_descriptor_missing", "Production needs recording-engineer language such as mic distance, room, reverb, width, tape, or dynamics.", "repair style-field-map.md"))
    if not contains_pattern(fields["vocal"] + " " + fields["instrumentation"], PERFORMANCE_PATTERNS):
        findings.append(Finding("blocker", "performance_descriptor_missing", "Vocal/instrumentation needs performance language such as diction, breath, pocket, kick/snare, articulation, or motif.", "repair style-field-map.md"))
    if not contains_pattern(lyrics_context + " " + fields["mood"] + " " + fields["lead_instruments"], SECTION_PATTERNS):
        findings.append(Finding("blocker", "section_descriptor_missing", "Lyrics context or style fields need section/hook language such as verse, chorus, bridge, title phrase, or payoff.", "fill lyrics-context-map.md"))

    style_word_limits = {
        "genre": 28,
        "vocal": 34,
        "instrumentation": 55,
        "production": 42,
        "mood": 34,
    }
    for field, limit in style_word_limits.items():
        count = word_count(fields[field])
        if count > limit:
            findings.append(Finding("warning", f"{field}_field_over_budget", f"{field} field has {count} words; tighten to the strongest audible terms.", "repair field-length-and-specificity-budget.md"))

    vague = vague_hits(generation_text)
    if vague:
        removal_text = fields["remove_vague_terms"].casefold()
        unhandled = [term for term in vague if term not in removal_text]
        if unhandled:
            findings.append(
                Finding(
                    "blocker",
                    "vague_terms_unremoved",
                    "Generation-facing style fields contain unhandled vague terms: " + ", ".join(unhandled[:6]),
                    "move vague words to removals or replace with physical descriptors",
                )
            )

    identity_hits = protected_identity_hits(generation_text + "\n" + exclude_text)
    if identity_hits:
        findings.append(
            Finding(
                "blocker",
                "protected_identity_in_specificity_fields",
                "Prompt specificity fields contain protected artist/band names: " + ", ".join(identity_hits[:5]),
                "route to reference DNA and protected identity removal",
            )
        )

    return fields, findings


def render_findings(findings: list[Finding]) -> str:
    if not findings:
        return "| severity | code | message | route |\n|---|---|---|---|\n| pass | none | specificity budget approved | prompt compile |\n"
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    for item in findings:
        rows.append(f"| {item.severity} | {item.code} | {item.message} | {item.route} |")
    return "\n".join(rows) + "\n"


def render_audit(project_root: Path, fields: dict[str, str], findings: list[Finding]) -> str:
    blockers = [finding for finding in findings if finding.severity == "blocker"]
    decision = "pass" if not blockers else "repair before prompt compile"
    style_tags = ", ".join(
        part
        for part in [
            fields["genre"],
            fields["vocal"],
            fields["instrumentation"],
            fields["production"],
            fields["mood"],
        ]
        if part
    )
    return f"""# Prompt Specificity Budget Audit

Generated by: tools/audit_music_prompt_specificity_budget.py
Project root: {project_root}
Decision: {decision}

## Specificity Budget Evidence

Style source: {STYLE_FILE}
Budget source: {BUDGET_FILE}
Methodology transfer: {'pass' if methodology_transfer_audit_ready(project_root) else 'missing or repair'}
Style specificity tags: {style_tags or 'NEEDS_REPAIR: style tags'}
Recording realism tags: {fields['recording_tags'] or 'NEEDS_REPAIR: recording realism tags'}
Performance realism tags: {fields['performance_tags'] or 'NEEDS_REPAIR: performance realism tags'}
Section/director tags: {fields['section_tags'] or 'NEEDS_REPAIR: section/director tags'}
Field budget tags: must-hear={fields['must_hear_terms'] or 'NEEDS_REPAIR'}, nice={fields['nice_terms'] or ''}, decision={fields['field_budget_decision'] or 'NEEDS_REPAIR'}
Vague term removals: {fields['remove_vague_terms'] or 'none recorded'}
Protected identity check: {'pass' if not protected_identity_hits(fields['style_generation_text']) else 'fail'}
Prompt compile handoff: {'pass' if decision == 'pass' else 'repair'}

## Findings

{render_findings(findings)}
"""


def prompt_specificity_audit_ready(project_root: Path) -> bool:
    path = project_root / DEFAULT_OUTPUT
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    lowered = text.casefold()
    return (
        MARKER.casefold() in lowered
        and "decision: pass" in lowered
        and "## specificity budget evidence" in lowered
        and "methodology transfer: pass" in lowered
        and "style specificity tags:" in lowered
        and "recording realism tags:" in lowered
        and "performance realism tags:" in lowered
        and "section/director tags:" in lowered
        and "field budget tags:" in lowered
        and "prompt compile handoff: pass" in lowered
        and "needs_repair" not in lowered
    )


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root created by create_music_song_project.py.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Relative output path for the audit.")
    parser.add_argument("--write", action="store_true", help="Write the audit file.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting the output file.")
    parser.add_argument("--strict", action="store_true", help="Exit non-zero when blockers exist.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists():
        print(f"Project root does not exist: {project_root}", file=sys.stderr)
        return 2
    docs = read_project(project_root)
    fields, findings = analyze(docs, project_root)
    output = render_audit(project_root, fields, findings)
    blockers = [finding for finding in findings if finding.severity == "blocker"]
    if args.write:
        try:
            write_if_allowed(project_root / args.output, output, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"Refusing to overwrite existing file without --allow-overwrite: {exc}", file=sys.stderr)
            return 2
    else:
        print(output)
    if args.strict and blockers:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
