#!/usr/bin/env python3
"""Audit generated-take provenance before blind review.

This tool does not listen to audio. It checks whether a song project's generated
takes can be traced back to an approved prompt package, batch plan, provider
result, settings, audio export or link, and metadata before any take-selection
decision is allowed.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from audit_music_prompt_iteration_discipline import (
    OUTPUT as PROMPT_ITERATION_DISCIPLINE_AUDIT,
    prompt_iteration_discipline_audit_ready,
)
from review_music_takes import parse_markdown_tables


OUTPUT = "05_generations/generation-evidence-audit.md"
PROMPT_PACKAGE = "04_prompt/prompt-package-v001.md"
PROMPT_PREFLIGHT = "04_prompt/prompt-preflight-review.md"
BATCH_PLAN = "05_generations/batch-generation-plan.md"
TAKE_LEDGER = "05_generations/take-ledger.md"
PROVIDER_LEDGER = "05_generations/provider-result-ledger.md"
METADATA_DIR = "05_generations/metadata"
AUDIO_DIR = "05_generations/audio"

PROMPT_COMPILER_MARKER = "Generated by: tools/compile_music_prompt_package.py"
REQUIRED_BATCH_FIELDS = [
    ("Candidate IDs", "batch_plan_missing_candidate_ids"),
    ("Takes per candidate", "batch_plan_missing_takes_per_candidate"),
    ("Total takes", "batch_plan_missing_total_takes"),
    ("Generation date", "batch_plan_missing_generation_date"),
    ("Expected listen order", "batch_plan_missing_expected_listen_order"),
    ("Anonymization rule", "batch_plan_missing_anonymization_rule"),
]

PLACEHOLDERS = {
    "",
    "-",
    "--",
    "tbd",
    "todo",
    "pending",
    "unknown",
    "missing",
    "n/a",
    "na",
}


@dataclass
class Finding:
    severity: str
    code: str
    message: str
    route: str


@dataclass
class Audit:
    blockers: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)
    take_rows: list[dict[str, str]] = field(default_factory=list)
    provider_rows: dict[str, dict[str, str]] = field(default_factory=dict)
    metadata_files: list[Path] = field(default_factory=list)
    audio_files: list[Path] = field(default_factory=list)
    batch_expected_total: int | None = None

    @property
    def passed(self) -> bool:
        return not self.blockers


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def add_finding(items: list[Finding], severity: str, code: str, message: str, route: str) -> None:
    items.append(Finding(severity=severity, code=code, message=message, route=route))


def normalized(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().lower())


def has_value(value: str, *, allow_none: bool = False) -> bool:
    text = normalized(value)
    if allow_none and text in {"none", "no issue", "no known issue", "无", "无明显问题"}:
        return True
    return text not in PLACEHOLDERS and text != "none"


def label_value(text: str, labels: list[str]) -> str:
    wanted = {label.lower() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,90}):\s*(.*)$", stripped)
        if not match:
            continue
        label = match.group(1).strip().lower()
        value = match.group(2).strip().strip('"')
        if label in wanted:
            return value
    return ""


def decision_is_compile_approved(text: str) -> bool:
    return bool(re.search(r"^Decision:\s*compile approved\b", text, re.I | re.M))


def local_or_url_exists(project_root: Path, value: str) -> tuple[bool, str]:
    text = value.strip().strip("`")
    if re.search(r"^https?://", text, re.I):
        return True, "url"
    candidates = [
        item.strip().strip("`")
        for item in re.split(r"[,;]\s*|\s+\|\s+", text)
        if item.strip()
    ]
    if not candidates:
        return False, text
    for item in candidates:
        if re.search(r"^https?://", item, re.I):
            return True, "url"
        path = Path(item).expanduser()
        if not path.is_absolute():
            path = project_root / path
        if path.exists():
            return True, path.as_posix()
    return False, candidates[0]


def placeholder_take_row(row: dict[str, str], take_id: str) -> bool:
    source = row.get("source_audio") or row.get("generated_url") or row.get("downloaded_file") or row.get("audio") or ""
    return (
        take_id.lower().startswith("take-")
        and not has_value(row.get("provider_model", ""))
        and not has_value(row.get("settings", ""))
        and not has_value(source)
    )


def flatten_rows(text: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for table in parse_markdown_tables(text):
        for row in table:
            take_id = (row.get("take") or row.get("take_id") or row.get("blind_id") or "").strip()
            if take_id and take_id.lower() not in {"take", "take id", "blind id"}:
                if placeholder_take_row(row, take_id):
                    continue
                row["take"] = take_id
                rows.append(row)
    return rows


def metadata_mentions(metadata_files: list[Path], take_id: str) -> bool:
    needle = take_id.lower()
    for path in metadata_files:
        if needle in path.name.lower():
            return True
        try:
            if needle in path.read_text(encoding="utf-8", errors="ignore").lower():
                return True
        except UnicodeDecodeError:
            continue
    return False


def provider_row_complete(row: dict[str, str]) -> bool:
    source = row.get("generated_url") or row.get("downloaded_file") or row.get("source_audio") or row.get("audio") or ""
    return has_value(row.get("provider_model", "")) and has_value(row.get("settings", "")) and has_value(source)


def audit_prompt_files(project_root: Path, audit: Audit) -> None:
    if not prompt_iteration_discipline_audit_ready(project_root):
        add_finding(
            audit.blockers,
            "blocker",
            "prompt_iteration_discipline_not_passed",
            f"{PROMPT_ITERATION_DISCIPLINE_AUDIT} must be generated by tools/audit_music_prompt_iteration_discipline.py with Decision: pass",
            "run audit_music_prompt_iteration_discipline.py before generation evidence",
        )
    package_text = read_text(project_root / PROMPT_PACKAGE)
    preflight_text = read_text(project_root / PROMPT_PREFLIGHT)
    if not package_text:
        add_finding(audit.blockers, "blocker", "prompt_package_missing", f"missing {PROMPT_PACKAGE}", "run compile_music_prompt_package.py")
    elif PROMPT_COMPILER_MARKER not in package_text or not decision_is_compile_approved(package_text):
        add_finding(
            audit.blockers,
            "blocker",
            "prompt_package_not_approved",
            f"{PROMPT_PACKAGE} must be compiler-generated with Decision: compile approved",
            "repair prompt package and rerun compile_music_prompt_package.py",
        )
    if not preflight_text:
        add_finding(audit.blockers, "blocker", "prompt_preflight_missing", f"missing {PROMPT_PREFLIGHT}", "run compile_music_prompt_package.py")
    elif PROMPT_COMPILER_MARKER not in preflight_text or not decision_is_compile_approved(preflight_text):
        add_finding(
            audit.blockers,
            "blocker",
            "prompt_preflight_not_approved",
            f"{PROMPT_PREFLIGHT} must be compiler-generated with Decision: compile approved",
            "repair prompt preflight and rerun compile_music_prompt_package.py",
        )


def audit_batch_plan(project_root: Path, audit: Audit) -> None:
    text = read_text(project_root / BATCH_PLAN)
    if not text:
        add_finding(audit.blockers, "blocker", "batch_plan_missing", f"missing {BATCH_PLAN}", "fill batch-generation-plan.md")
        return
    for label, code in REQUIRED_BATCH_FIELDS:
        value = label_value(text, [label])
        if not has_value(value):
            add_finding(audit.blockers, "blocker", code, f"{BATCH_PLAN} missing {label}", "fill batch-generation-plan.md")
    total_value = label_value(text, ["Total takes"])
    match = re.search(r"\d+", total_value)
    if match:
        audit.batch_expected_total = int(match.group(0))


def audit_take_ledger(project_root: Path, audit: Audit) -> None:
    text = read_text(project_root / TAKE_LEDGER)
    if not text:
        add_finding(audit.blockers, "blocker", "take_ledger_missing", f"missing {TAKE_LEDGER}", "fill take-ledger.md")
        return

    audit.take_rows = flatten_rows(text)
    if not audit.take_rows:
        add_finding(audit.blockers, "blocker", "no_take_rows", f"{TAKE_LEDGER} has no generated take rows", "fill take-ledger.md")
        return

    seen: set[str] = set()
    for row in audit.take_rows:
        take_id = row["take"]
        if take_id in seen:
            add_finding(audit.blockers, "blocker", "duplicate_take_id", f"duplicate take id: {take_id}", "deduplicate take-ledger.md")
        seen.add(take_id)

        prompt_package = row.get("prompt_package", "")
        if not has_value(prompt_package):
            add_finding(audit.blockers, "blocker", "take_prompt_package_missing", f"{take_id} missing prompt package", "fill take-ledger.md")
        else:
            prompt_path = Path(prompt_package.strip().strip("`"))
            if not prompt_path.is_absolute():
                prompt_path = project_root / prompt_path
            if not prompt_path.exists():
                add_finding(audit.blockers, "blocker", "take_prompt_package_path_missing", f"{take_id} prompt package path does not exist: {prompt_package}", "fix take-ledger.md")

        if not has_value(row.get("provider_model", "")):
            add_finding(audit.blockers, "blocker", "take_provider_model_missing", f"{take_id} missing provider/model", "fill take-ledger.md")
        if not has_value(row.get("settings", "")):
            add_finding(audit.blockers, "blocker", "take_settings_missing", f"{take_id} missing generation settings/sliders", "fill take-ledger.md")

        source_audio = row.get("source_audio", "") or row.get("audio", "")
        if not has_value(source_audio):
            add_finding(audit.blockers, "blocker", "take_source_missing", f"{take_id} missing source audio file or URL", "export audio or paste provider URL")
        else:
            exists, resolved = local_or_url_exists(project_root, source_audio)
            if not exists:
                add_finding(audit.blockers, "blocker", "take_audio_file_missing", f"{take_id} source audio not found: {resolved}", "fix source audio path or URL")

        if not has_value(row.get("first_impression", "")):
            add_finding(audit.blockers, "blocker", "take_first_impression_missing", f"{take_id} missing first impression", "fill take-ledger.md")
        if not has_value(row.get("known_issue", ""), allow_none=True):
            add_finding(audit.blockers, "blocker", "take_known_issue_missing", f"{take_id} missing known issue or explicit none", "fill take-ledger.md")
        status = row.get("review_status", "")
        if not has_value(status) or not re.search(r"ready|review|blind|pass", status, re.I):
            add_finding(audit.blockers, "blocker", "take_review_status_not_ready", f"{take_id} review status must be ready for blind review or reviewed", "update take-ledger.md")


def audit_provider_results(project_root: Path, audit: Audit) -> None:
    text = read_text(project_root / PROVIDER_LEDGER)
    if not text:
        add_finding(audit.blockers, "blocker", "provider_ledger_missing", f"missing {PROVIDER_LEDGER}", "fill provider-result-ledger.md")
        return

    provider_rows = flatten_rows(text)
    audit.provider_rows = {row["take"]: row for row in provider_rows}
    if not audit.provider_rows:
        add_finding(audit.blockers, "blocker", "provider_rows_missing", f"{PROVIDER_LEDGER} has no take rows", "fill provider-result-ledger.md")
        return

    for row in audit.take_rows:
        take_id = row["take"]
        provider = audit.provider_rows.get(take_id)
        if not provider:
            add_finding(audit.blockers, "blocker", "provider_row_missing", f"{take_id} missing provider-result row", "fill provider-result-ledger.md")
            continue
        if not has_value(provider.get("provider_model", "")):
            add_finding(audit.blockers, "blocker", "provider_model_missing", f"{take_id} provider-result row missing provider/model", "fill provider-result-ledger.md")
        if not has_value(provider.get("settings", "")):
            add_finding(audit.blockers, "blocker", "provider_settings_missing", f"{take_id} provider-result row missing settings", "fill provider-result-ledger.md")
        source = provider.get("generated_url") or provider.get("downloaded_file") or provider.get("source_audio") or provider.get("audio") or ""
        if not has_value(source):
            add_finding(audit.blockers, "blocker", "provider_source_missing", f"{take_id} provider-result row missing generated URL or downloaded file", "fill provider-result-ledger.md")
        elif provider.get("downloaded_file") and not re.search(r"^https?://", provider.get("downloaded_file", ""), re.I):
            exists, resolved = local_or_url_exists(project_root, provider["downloaded_file"])
            if not exists:
                add_finding(audit.blockers, "blocker", "provider_download_missing", f"{take_id} downloaded file not found: {resolved}", "fix provider-result-ledger.md")


def audit_metadata_and_counts(project_root: Path, audit: Audit) -> None:
    metadata_dir = project_root / METADATA_DIR
    audio_dir = project_root / AUDIO_DIR
    audit.metadata_files = sorted(path for path in metadata_dir.rglob("*") if path.is_file() and path.suffix.lower() in {".md", ".txt", ".json"})
    audit.audio_files = sorted(path for path in audio_dir.rglob("*") if path.is_file()) if audio_dir.exists() else []

    for row in audit.take_rows:
        take_id = row["take"]
        provider = audit.provider_rows.get(take_id, {})
        if not metadata_mentions(audit.metadata_files, take_id) and not provider_row_complete(provider):
            add_finding(
                audit.blockers,
                "blocker",
                "take_metadata_missing",
                f"{take_id} needs a metadata file or complete provider-result row",
                "add metadata file or complete provider-result-ledger.md",
            )

    if audit.batch_expected_total is not None:
        actual = len(audit.take_rows)
        if actual < audit.batch_expected_total:
            add_finding(
                audit.blockers,
                "blocker",
                "batch_total_mismatch",
                f"batch plan expects {audit.batch_expected_total} takes but take ledger has {actual}",
                "finish generation batch or update batch-generation-plan.md",
            )
        elif actual > audit.batch_expected_total:
            add_finding(
                audit.warnings,
                "warning",
                "batch_extra_takes",
                f"take ledger has {actual} takes but batch plan expected {audit.batch_expected_total}",
                "either prune or update batch-generation-plan.md",
            )


def audit_project(project_root: Path) -> Audit:
    audit = Audit()
    audit_prompt_files(project_root, audit)
    audit_batch_plan(project_root, audit)
    audit_take_ledger(project_root, audit)
    audit_provider_results(project_root, audit)
    audit_metadata_and_counts(project_root, audit)
    return audit


def finding_rows(findings: list[Finding]) -> str:
    if not findings:
        return "| pass | none | no blocking findings | proceed |\n"
    rows = []
    for item in findings:
        rows.append(f"| {item.severity} | {item.code} | {item.message} | {item.route} |")
    return "\n".join(rows) + "\n"


def render_audit(project_root: Path, audit: Audit) -> str:
    decision = "pass" if audit.passed else "hold"
    take_ids = ", ".join(row["take"] for row in audit.take_rows) or "none"
    provider_ids = ", ".join(sorted(audit.provider_rows)) or "none"
    metadata_names = ", ".join(path.name for path in audit.metadata_files[:12]) or "none"
    audio_names = ", ".join(path.name for path in audit.audio_files[:12]) or "none"
    return f"""# Generation Evidence Audit

Generated by: tools/audit_music_generation_evidence.py
Project root: {project_root}
Decision: {decision}

This gate checks generated-take provenance before blind review. It prevents
orphan takes, lucky-draw selection, missing provider/model settings, missing
audio exports, missing platform links, and stale prompt packages from entering
take selection.

## Generation Evidence

Prompt package: {PROMPT_PACKAGE}
Prompt preflight: {PROMPT_PREFLIGHT}
Batch plan: {BATCH_PLAN}
Take ledger: {TAKE_LEDGER}
Provider result ledger: {PROVIDER_LEDGER}
Expected takes: {audit.batch_expected_total if audit.batch_expected_total is not None else 'unknown'}
Actual take rows: {len(audit.take_rows)}
Take provenance tags: {take_ids}
Batch tags: candidate ids, takes per candidate, total takes, generation date, expected listen order, anonymization rule
Provider metadata tags: {provider_ids}
Audio exports / links: {audio_names}
Metadata files: {metadata_names}
Blind review handoff: {"ready" if audit.passed else "blocked"}

## Findings

| severity | code | message | route |
|---|---|---|---|
{finding_rows(audit.blockers).rstrip()}

## Warnings

| severity | code | message | route |
|---|---|---|---|
{finding_rows(audit.warnings).rstrip()}

## Repair Route

- batch-generation-plan: fill candidate IDs, takes per candidate, total takes, generation date, listen order, and anonymization rule.
- take-ledger: one row per generated take with prompt package, provider/model, settings, source audio, first impression, known issue, and review status.
- provider-result-ledger: one matching row per take with provider/model, settings, generated URL or downloaded file, prompt package, metadata, and status.
- metadata: store platform settings, seed/version/export notes, or a captured provider result per take.
- audio exports: keep local files under `05_generations/audio/` or paste durable provider URLs in the ledger.
- prompt package: regenerate with `tools/compile_music_prompt_package.py` if prompt/preflight is stale, handwritten, or not approved.
"""


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--output", default=OUTPUT, help="Relative output path for the audit note.")
    parser.add_argument("--write", action="store_true", help="Write the audit note.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit note.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero if provenance evidence is blocked.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    audit = audit_project(project_root)
    output = render_audit(project_root, audit)
    if args.write:
        output_path = project_root / args.output
        if output_path.exists() and not args.allow_overwrite:
            print(f"error: output exists, use --allow-overwrite: {output_path}", file=sys.stderr)
            return 2
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(output, encoding="utf-8")
        print(f"wrote {output_path.relative_to(project_root).as_posix()}")
    else:
        print(output)

    if audit.blockers:
        for blocker in audit.blockers[:12]:
            print(f"generation evidence blocker: {blocker.code}: {blocker.message}", file=sys.stderr)
        return 1 if args.strict else 0

    print(f"generation evidence: pass ({len(audit.take_rows)} takes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
