#!/usr/bin/env python3
"""Audit topline hook evidence before an AI music prompt is compiled."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


TITLE_FILE = "03_writing/title-phrase.md"
TOPLINE_FILE = "03_writing/topline-map.md"
MELODY_FILE = "03_writing/melody-contour.md"
PROSODY_AUDIT_FILE = "03_writing/lyrics-prosody-audit.md"
LYRICS_FILE = "04_prompt/lyrics-context-map.md"
PROMPT_BRIEF_FILE = "04_prompt/prompt-compile-brief.md"
SONG_BRIEF_FILE = "01_brief/song-brief.md"
DEFAULT_OUTPUT = "03_writing/topline-hook-audit.md"

EMPTY_VALUES = {"", '""', "''", "todo", "tbd", "n/a", "na", "none", "yes/no", "-", "--"}
WEAK_TITLE_WORDS = {"love", "dream", "light", "night", "heart", "forever", "memories", "echoes", "stars"}
MANDARIN_WEAK_ENDINGS = ("的", "了", "着", "在", "和", "与", "而", "吗")


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


def read_project(project_root: Path) -> dict[str, str]:
    docs: dict[str, str] = {}
    for path in project_root.rglob("*.md"):
        rel = path.relative_to(project_root).as_posix()
        try:
            docs[rel] = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            docs[rel] = path.read_text(errors="replace")
    return docs


def normalize_value(raw: str) -> str:
    value = raw.strip().strip("`")
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1].strip()
    value = re.sub(r"\s+", " ", value)
    if value.casefold() in EMPTY_VALUES:
        return ""
    if value.startswith("[") and value.endswith("]") and ":" in value:
        return ""
    return value


def scan_key_values(text: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|"):
            continue
        stripped = re.sub(r"^[-*]\s+", "", stripped)
        match = re.match(r"^([^:]{1,80}):\s*(.*)$", stripped)
        if match:
            label = re.sub(r"\s+", " ", match.group(1).strip()).casefold()
            value = normalize_value(match.group(2))
            pairs.append((label, value))
    return pairs


def extract_value(docs: dict[str, str], paths: list[str], labels: list[str]) -> str:
    wanted = {re.sub(r"\s+", " ", label.strip()).casefold() for label in labels}
    for rel in paths:
        for label, value in scan_key_values(docs.get(rel, "")):
            if label in wanted and value:
                return value
    return ""


def extract_code_blocks(text: str) -> list[str]:
    return [block.strip() for block in re.findall(r"```(?:text|markdown)?\s*\n(.*?)```", text, flags=re.S)]


def extract_lyrics_block(docs: dict[str, str]) -> str:
    text = docs.get(LYRICS_FILE, "")
    for block in extract_code_blocks(text):
        if "[Verse" in block or "[Chorus" in block or "[Intro" in block:
            return block.strip()
    return ""


def title_in_chorus(lyrics_block: str, title_phrase: str) -> bool:
    if not lyrics_block or not title_phrase:
        return False
    compact_title = re.sub(r"\s+", "", title_phrase.casefold())
    in_chorus = False
    for line in lyrics_block.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and "]" in stripped:
            tag = stripped.casefold()
            in_chorus = "[chorus" in tag or "[final chorus" in tag
            continue
        if in_chorus and compact_title and compact_title in re.sub(r"\s+", "", stripped.casefold()):
            return True
    return False


def language_kind(language: str) -> str:
    text = language.casefold()
    if any(term in text for term in ["zh", "中文", "华语", "mandarin", "chinese"]):
        return "zh"
    if any(term in text for term in ["ja", "jp", "日本", "日语", "japanese"]):
        return "ja"
    if any(term in text for term in ["ko", "kr", "韩", "korean"]):
        return "ko"
    if any(term in text for term in ["en", "英语", "english"]):
        return "en"
    return "mixed"


def title_units(title_phrase: str, language: str) -> int:
    cjk = re.findall(r"[\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af]", title_phrase)
    words = re.findall(r"[A-Za-z]+(?:'[A-Za-z]+)?", title_phrase)
    if language_kind(language) == "en":
        return len([word for word in words if word.casefold() not in {"a", "an", "the", "of", "to", "and"}])
    return len(cjk) + len(words)


def prosody_audit_passed(docs: dict[str, str]) -> bool:
    text = docs.get(PROSODY_AUDIT_FILE, "")
    return "Generated by: tools/audit_music_lyrics_prosody.py" in text and re.search(r"^Decision:\s*pass\b", text, flags=re.I | re.M) is not None


def analyze(docs: dict[str, str]) -> tuple[dict[str, str], list[Finding]]:
    paths = [TITLE_FILE, TOPLINE_FILE, MELODY_FILE, PROMPT_BRIEF_FILE, SONG_BRIEF_FILE, LYRICS_FILE]
    fields = {
        "language": extract_value(docs, paths, ["Language", "Language lane"]),
        "title_phrase": extract_value(docs, paths, ["Title phrase", "Hook phrase", "Chorus title phrase", "Text"]),
        "meaning": extract_value(docs, paths, ["Meaning", "Hook promise", "Hook idea"]),
        "spoken_stress": extract_value(docs, paths, ["Natural spoken stress", "Spoken rhythm", "Natural stress"]),
        "long_note_word": extract_value(docs, paths, ["Long-note word", "Best long-note word", "Long note word"]),
        "must_not_distort": extract_value(docs, paths, ["Must-not-distort words", "Must not distort", "Must-not-distort"]),
        "rhythm_cell": extract_value(docs, paths, ["Rhythm cell", "Motif rhythm", "Verse rhythm", "Chorus rhythm"]),
        "motif_contour": extract_value(docs, paths, ["Contour", "Motif contour", "Target contour"]),
        "target_interval": extract_value(docs, paths, ["Target interval", "Signature interval"]),
        "start_position": extract_value(docs, paths, ["Start position", "Title start", "Hook start", "Chorus entry"]),
        "repeat_plan": extract_value(docs, paths, ["Repeat plan", "Repetition plan", "Hook repeat"]),
        "contrast_plan": extract_value(docs, paths, ["Contrast plan", "Verse/chorus contrast", "Contrast"]),
        "chorus_contour": extract_value(docs, paths, ["Chorus contour", "Chorus title contour"]),
        "chorus_title_landing": extract_value(docs, paths, ["Chorus title landing", "Title landing", "Hook landing"]),
        "bridge_contrast": extract_value(docs, paths, ["Bridge contrast"]),
        "final_chorus_variation": extract_value(docs, paths, ["Final chorus variation"]),
        "demo_file": extract_value(docs, paths, ["Demo file", "Melody demo", "Demo"]),
        "demo_source": extract_value(docs, paths, ["Source", "Demo source"]),
        "demo_keep": extract_value(docs, paths, ["Keep", "Retention target"]),
        "demo_rights": extract_value(docs, paths, ["Rights", "Demo rights"]),
    }
    lyrics_block = extract_lyrics_block(docs)
    findings: list[Finding] = []

    if not fields["language"]:
        findings.append(Finding("blocker", "language_missing", "Language is missing; title length and hook rules cannot be selected.", "repair song brief"))
    if not fields["title_phrase"]:
        findings.append(Finding("blocker", "title_phrase_missing", "Topline needs a title phrase before prompt compile.", "fill title-phrase.md"))
    if not fields["spoken_stress"]:
        findings.append(Finding("blocker", "spoken_stress_missing", "Natural spoken stress or rhythm is missing.", "fill title-phrase.md"))
    if not fields["long_note_word"] and not fields["chorus_title_landing"]:
        findings.append(Finding("blocker", "hook_landing_missing", "Long-note word or chorus title landing is missing.", "fill topline-map.md"))
    if not fields["rhythm_cell"]:
        findings.append(Finding("blocker", "rhythm_cell_missing", "Hook motif rhythm cell is missing.", "fill topline-map.md"))
    if not (fields["motif_contour"] or fields["chorus_contour"]):
        findings.append(Finding("blocker", "contour_missing", "Motif or chorus contour is missing.", "fill melody-contour.md"))
    if not fields["start_position"]:
        findings.append(Finding("blocker", "start_position_missing", "Hook start position is missing.", "fill topline-map.md"))
    if not fields["repeat_plan"]:
        findings.append(Finding("blocker", "repeat_plan_missing", "Hook repeat or variation plan is missing.", "fill topline-map.md"))
    if not fields["contrast_plan"]:
        findings.append(Finding("blocker", "contrast_plan_missing", "Verse/chorus contrast plan is missing.", "fill melody-contour.md"))
    if fields["title_phrase"] and lyrics_block and not title_in_chorus(lyrics_block, fields["title_phrase"]):
        findings.append(Finding("blocker", "title_phrase_not_in_chorus", "Title phrase must appear in a chorus line.", "repair lyrics-context-map.md"))
    if not prosody_audit_passed(docs):
        findings.append(Finding("blocker", "prosody_audit_missing", "Topline audit requires a passing lyrics prosody audit first.", "run audit_music_lyrics_prosody.py"))

    if fields["title_phrase"]:
        units = title_units(fields["title_phrase"], fields["language"])
        kind = language_kind(fields["language"])
        if kind == "zh" and (units < 4 or units > 10):
            findings.append(Finding("warning", "title_length_risk", f"Mandarin title phrase has {units} units; check hook singability.", "revise title phrase"))
        elif kind == "en" and (units < 2 or units > 8):
            findings.append(Finding("warning", "title_length_risk", f"English title phrase has {units} stressed-ish units; check memorability.", "revise title phrase"))
        if kind == "zh" and fields["title_phrase"].endswith(MANDARIN_WEAK_ENDINGS):
            findings.append(Finding("warning", "weak_title_ending", "Mandarin title may land on a weak function/aspect word.", "move landing to content word"))
        if kind == "en":
            weak_hits = [word for word in re.findall(r"[A-Za-z]+", fields["title_phrase"].casefold()) if word in WEAK_TITLE_WORDS]
            if len(weak_hits) >= 2:
                findings.append(Finding("warning", "generic_title_words", "Title phrase uses several generic hook words: " + ", ".join(weak_hits), "make title more concrete"))

    demo_present = bool(fields["demo_file"] or fields["demo_source"])
    if not demo_present:
        findings.append(Finding("warning", "no_human_melody_demo", "No human melody demo is recorded; text-only topline is allowed but less anchored.", "optionally record melody demo"))
    elif not fields["demo_rights"] or re.search(r"\b(unknown|unclear|third[- ]party|unlicensed)\b|未知|不清楚|未授权", fields["demo_rights"], re.I):
        findings.append(Finding("blocker", "demo_rights_unclear", "Melody demo exists but rights are missing or unclear.", "repair demo rights"))

    return fields, findings


def title_unit_summary(fields: dict[str, str]) -> str:
    if not fields["title_phrase"]:
        return "0"
    return str(title_units(fields["title_phrase"], fields["language"]))


def topline_tags(fields: dict[str, str]) -> str:
    pieces = [
        fields["start_position"],
        fields["rhythm_cell"],
        fields["motif_contour"] or fields["chorus_contour"],
        fields["chorus_title_landing"] or fields["long_note_word"],
        fields["repeat_plan"],
    ]
    text = ", ".join(piece for piece in pieces if piece)
    return text or "NEEDS_REPAIR: topline tags"


def render_finding_table(findings: list[Finding]) -> str:
    if not findings:
        return "| severity | code | message | route |\n|---|---|---|---|\n| pass | none | topline hook approved | prompt compile |\n"
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    for finding in findings:
        rows.append(f"| {finding.severity} | {finding.code} | {finding.message} | {finding.route} |")
    return "\n".join(rows) + "\n"


def render_audit(project_root: Path, fields: dict[str, str], findings: list[Finding]) -> str:
    blockers = [finding for finding in findings if finding.severity == "blocker"]
    warnings = [finding for finding in findings if finding.severity == "warning"]
    decision = "pass" if not blockers else "repair before prompt compile"
    return f"""# Topline Hook Audit

Generated by: tools/audit_music_topline_hook.py
Project root: {project_root}
Decision: {decision}

Language: {fields['language'] or 'NEEDS_REPAIR: language'}
Title phrase: {fields['title_phrase'] or 'NEEDS_REPAIR: title phrase'}
Title units: {title_unit_summary(fields)}
Natural spoken stress: {fields['spoken_stress'] or 'NEEDS_REPAIR: spoken stress'}
Long-note word: {fields['long_note_word'] or 'NEEDS_REPAIR: long-note word'}
Rhythm cell: {fields['rhythm_cell'] or 'NEEDS_REPAIR: rhythm cell'}
Motif contour: {fields['motif_contour'] or fields['chorus_contour'] or 'NEEDS_REPAIR: motif contour'}
Start position: {fields['start_position'] or 'NEEDS_REPAIR: start position'}
Repeat plan: {fields['repeat_plan'] or 'NEEDS_REPAIR: repeat plan'}
Contrast plan: {fields['contrast_plan'] or 'NEEDS_REPAIR: contrast plan'}
Chorus title landing: {fields['chorus_title_landing'] or fields['long_note_word'] or 'NEEDS_REPAIR: chorus title landing'}
Demo source: {fields['demo_source'] or fields['demo_file'] or 'none'}
Demo rights: {fields['demo_rights'] or 'none'}
Blockers: {len(blockers)}
Warnings: {len(warnings)}

## Hook Design

| field | value |
|---|---|
| meaning | {fields['meaning'] or ''} |
| target interval | {fields['target_interval'] or ''} |
| bridge contrast | {fields['bridge_contrast'] or ''} |
| final chorus variation | {fields['final_chorus_variation'] or ''} |
| demo keep | {fields['demo_keep'] or ''} |

## Findings

{render_finding_table(findings)}
## Prompt Routing

Topline tags: {topline_tags(fields)}
Audio seed routing: {'human melody demo available' if fields['demo_file'] or fields['demo_source'] else 'text-only topline; optional melody demo recommended'}
Blind hook test: first 20-30 seconds, title phrase recall, hummed contour, strongest moment, weak syllable
Repair route: title phrase, rhythm cell, contour map, prosody fit, or human melody demo
"""


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root created by create_music_song_project.py.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Relative output path.")
    parser.add_argument("--write", action="store_true", help="Write the audit markdown file.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit file.")
    parser.add_argument("--strict", action="store_true", help="Return exit code 1 when blockers remain.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    docs = read_project(project_root)
    fields, findings = analyze(docs)
    audit = render_audit(project_root, fields, findings)
    blockers = [finding for finding in findings if finding.severity == "blocker"]

    if args.write:
        try:
            write_if_allowed(project_root / args.output, audit, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: output exists, use --allow-overwrite: {exc}", file=sys.stderr)
            return 2
    else:
        print(audit)

    if blockers:
        print(f"topline hook audit has {len(blockers)} blocker(s).", file=sys.stderr)
        for finding in blockers:
            print(f"- {finding.code}: {finding.message} -> {finding.route}", file=sys.stderr)
        return 1 if args.strict else 0

    print("topline hook audit passed.")
    print(f"audit: {project_root / args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
