#!/usr/bin/env python3
"""Audit human audio-seed retention before ordinary blind review.

This tool does not listen to audio. It checks whether a project that uses a
human audio seed has rights, seed classification, retention target, prompt
pairing, generation provenance, and anchor-retention review evidence before
the generated takes enter ordinary blind review, release, or catalog memory.
If no human audio seed is detected, the gate is explicitly not applicable.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


OUTPUT = "06_review/audio-seed-retention-audit.md"

HUMAN_SEED_INTENT = "02_references/human-seed-intent.md"
AUDIO_RIGHTS = "02_references/audio-rights-ledger.md"
SEED_CLASSIFICATION = "02_references/seed-type-classification.md"
CAPTURE_CLEANUP = "02_references/capture-and-cleanup.md"
RETENTION_TARGET = "04_prompt/retention-target.md"
PROMPT_PAIRING = "04_prompt/prompt-pairing.md"
GENERATION_AUDIT = "05_generations/generation-evidence-audit.md"
ANCHOR_REVIEW = "06_review/anchor-retention-review.md"

AUDIO_SEED_AUDIT_MARKER = "Generated by: tools/audit_music_audio_seed_retention.py"
AUDIO_SEED_AUDIT_REQUIRED_TERMS = [
    "Decision: pass",
    "## Audio Seed Evidence",
    "Seed rights tags:",
    "Retention target tags:",
    "Prompt pairing tags:",
    "Anchor retention tags:",
    "Blind review handoff:",
]
GENERATION_AUDIT_MARKER = "Generated by: tools/audit_music_generation_evidence.py"
GENERATION_AUDIT_REQUIRED_TERMS = [
    "Decision: pass",
    "## Generation Evidence",
    "Take provenance tags:",
    "Batch tags:",
    "Provider metadata tags:",
    "Blind review handoff:",
]

SEED_DETECTION_FILES = [
    "04_prompt/persona-voice-model-routing.md",
    "04_prompt/prompt-package-v001.md",
    "04_prompt/prompt-preflight-review.md",
    "04_prompt/slider-intent-map.md",
    PROMPT_PAIRING,
    RETENTION_TARGET,
    "05_generations/batch-generation-plan.md",
    "05_generations/take-ledger.md",
    "05_generations/provider-result-ledger.md",
]

PLACEHOLDERS = {
    "",
    "-",
    "--",
    "tbd",
    "todo",
    "pending",
    "unknown",
    "missing",
    "n/a",
    "na",
    "none",
}


@dataclass
class Finding:
    severity: str
    code: str
    message: str
    route: str


@dataclass
class Audit:
    seed_required: bool
    detection_signals: list[str] = field(default_factory=list)
    blockers: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)
    evidence_tags: dict[str, str] = field(default_factory=dict)

    @property
    def decision(self) -> str:
        if not self.seed_required:
            return "not applicable"
        return "pass" if not self.blockers else "hold"

    @property
    def passed(self) -> bool:
        return self.decision in {"not applicable", "pass"}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def normalized(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().lower())


def has_value(value: str, *, allow_none: bool = False) -> bool:
    text = normalized(value).strip("`\"'")
    if allow_none and text in {"none", "no", "no issue", "not applicable", "n/a", "na", "无"}:
        return True
    return text not in PLACEHOLDERS


def label_value(text: str, labels: list[str]) -> str:
    wanted = {label.lower() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,90}):\s*(.*)$", stripped)
        if not match:
            continue
        label = match.group(1).strip().lower()
        value = match.group(2).strip().strip('"')
        if label in wanted:
            return value
    return ""


def positive_value(value: str) -> bool:
    text = normalized(value)
    return bool(
        re.search(
            r"^(yes|y|pass|passed|clear|cleared|approved|approve|allowed|ok|ready|documented|keep)\b|通过|清楚|已授权|允许|可用|保留",
            text,
            re.I,
        )
    )


def blocking_value(value: str) -> bool:
    text = normalized(value)
    return bool(re.search(r"\b(no|fail|failed|hold|blocked|unclear|unknown|pending|unresolved|not approved)\b|不通过|未知|未解决|不清楚", text, re.I))


def parse_score(value: str) -> float | None:
    text = normalized(value)
    if not text:
        return None
    words = {
        "low": 1.0,
        "medium": 2.5,
        "mid": 2.5,
        "high": 4.0,
        "pass": 4.0,
        "yes": 4.0,
        "clear": 4.0,
        "fail": 1.0,
        "no": 1.0,
        "低": 1.0,
        "中": 2.5,
        "高": 4.0,
    }
    if text in words:
        return words[text]
    match = re.search(r"(\d+(?:\.\d+)?)", text)
    if not match:
        return None
    score = float(match.group(1))
    if score > 5.0 and score <= 100.0:
        score = score / 20.0
    return max(0.0, min(5.0, score))


def add_finding(items: list[Finding], severity: str, code: str, message: str, route: str) -> None:
    items.append(Finding(severity=severity, code=code, message=message, route=route))


def value_says_seed(value: str) -> bool:
    text = normalized(value)
    if not has_value(text):
        return False
    if re.search(r"\b(text[- ]only|none|no seed|no audio|not applicable|n/a|off|0)\b", text, re.I):
        return False
    if re.search(r"\b(human audio seed|audio seed|audio upload|uploaded audio|own audio|voice memo|guide vocal|demo|cover|add vocals|inspire|init audio)\b", text, re.I):
        return True
    return False


def numeric_audio_influence(value: str) -> bool:
    text = normalized(value)
    if not has_value(text):
        return False
    if re.search(r"\b(none|off|n/a|not applicable)\b", text, re.I):
        return False
    match = re.search(r"(\d+(?:\.\d+)?)", text)
    if not match:
        return value_says_seed(text)
    return float(match.group(1)) > 0


def field_signals(project_root: Path) -> list[str]:
    signals: list[str] = []
    label_groups = {
        "Human anchor lane": ["Human anchor lane", "Human Anchor Lane", "Anchor lane"],
        "Feature type": ["Feature type", "Tool", "Target workflow", "Suno plan at upload"],
        "Audio seed": ["Audio seed", "Audio Upload seed", "Own audio seed", "Seed file", "Audio file"],
        "Audio upload": ["Audio Upload", "Uploaded audio", "Input audio", "Source seed", "Seed source"],
        "Audio influence": ["Audio Influence", "Audio Strength", "Seed strength"],
    }
    for rel in SEED_DETECTION_FILES:
        text = read_text(project_root / rel)
        if not text:
            continue
        for label_name, labels in label_groups.items():
            value = label_value(text, labels)
            if not value:
                continue
            if label_name == "Audio influence":
                if numeric_audio_influence(value):
                    signals.append(f"{rel}: {label_name}={value}")
            elif value_says_seed(value):
                signals.append(f"{rel}: {label_name}={value}")
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or stripped.lower().startswith("lane options"):
                continue
            if re.match(r"^[-*]\s+(text-only|human audio seed|voice/persona|custom model|my taste)", stripped, re.I):
                continue
            if re.search(r"\b(audio[- ]?upload seed|source seed|uploaded audio|input audio)\b\s*[:|]", stripped, re.I):
                value = re.split(r"[:|]", stripped, maxsplit=1)[-1].strip()
                if value_says_seed(value):
                    signals.append(f"{rel}: {stripped[:80]}")
    return signals


def audio_seed_required(project_root: Path) -> bool:
    return bool(field_signals(project_root))


def audio_seed_audit_decision(project_root: Path) -> str:
    text = read_text(project_root / OUTPUT)
    return label_value(text, ["Decision"]) or "missing"


def audio_seed_audit_ready(project_root: Path) -> bool:
    text = read_text(project_root / OUTPUT)
    if AUDIO_SEED_AUDIT_MARKER not in text:
        return False
    return all(term in text for term in AUDIO_SEED_AUDIT_REQUIRED_TERMS)


def generation_audit_ready(project_root: Path) -> bool:
    text = read_text(project_root / GENERATION_AUDIT)
    return GENERATION_AUDIT_MARKER in text and all(term in text for term in GENERATION_AUDIT_REQUIRED_TERMS)


def require_fields(project_root: Path, audit: Audit, rel: str, fields: list[str], code_prefix: str, route: str) -> dict[str, str]:
    text = read_text(project_root / rel)
    values: dict[str, str] = {}
    if not text:
        add_finding(audit.blockers, "blocker", f"{code_prefix}_missing", f"missing {rel}", route)
        return values
    for field_name in fields:
        value = label_value(text, [field_name])
        values[field_name] = value
        if not has_value(value):
            add_finding(audit.blockers, "blocker", f"{code_prefix}_{field_name.lower().replace(' ', '_').replace('/', '_')}_missing", f"{rel} missing {field_name}", route)
    return values


def audit_audio_rights(project_root: Path, audit: Audit) -> None:
    values = require_fields(
        project_root,
        audit,
        AUDIO_RIGHTS,
        [
            "File",
            "Recorded by",
            "Owner",
            "Consent",
            "Commercial use",
            "Can upload to AI tool",
            "Can use in release",
        ],
        "audio_rights",
        "fill audio-rights-ledger.md before using the seed",
    )
    if not values:
        return
    for label in ["Consent", "Commercial use", "Can upload to AI tool", "Can use in release"]:
        value = values.get(label, "")
        if not positive_value(value):
            add_finding(
                audit.blockers,
                "blocker",
                f"audio_rights_{label.lower().replace(' ', '_')}_not_clear",
                f"{AUDIO_RIGHTS} needs {label}: yes/clear/pass; got {value or 'blank'}",
                "stop upload/release path until seed rights are clear",
            )
    third_party = label_value(read_text(project_root / AUDIO_RIGHTS), ["Third-party material", "Public figure voice", "Sample", "Loop"])
    if third_party and blocking_value(third_party) and not positive_value(third_party):
        add_finding(audit.blockers, "blocker", "audio_rights_third_party_unresolved", f"{AUDIO_RIGHTS} has unresolved third-party material", "do not upload this seed; convert to style DNA only")
    audit.evidence_tags["rights"] = ", ".join(f"{key}={value}" for key, value in values.items() if value) or "missing"


def audit_seed_classification(project_root: Path, audit: Audit) -> None:
    values = require_fields(
        project_root,
        audit,
        SEED_CLASSIFICATION,
        [
            "Primary seed type",
            "Strongest audible feature",
            "Keep",
            "May transform",
            "Should ignore",
        ],
        "seed_classification",
        "fill seed-type-classification.md",
    )
    audit.evidence_tags["classification"] = ", ".join(f"{key}={value}" for key, value in values.items() if value) or "missing"
    if not read_text(project_root / HUMAN_SEED_INTENT):
        add_finding(audit.warnings, "warning", "human_seed_intent_missing", f"missing {HUMAN_SEED_INTENT}", "write why text-only prompting is insufficient")
    if not read_text(project_root / CAPTURE_CLEANUP):
        add_finding(audit.warnings, "warning", "capture_cleanup_missing", f"missing {CAPTURE_CLEANUP}", "record capture cleanup if seed quality affects retention")


def audit_retention_target(project_root: Path, audit: Audit) -> None:
    values = require_fields(
        project_root,
        audit,
        RETENTION_TARGET,
        [
            "Seed file",
            "Tool",
            "Primary retention",
            "Retention level",
            "Strict keep",
            "Allowed transformations",
            "Must change",
            "Risk if over-retained",
            "Risk if under-retained",
            "Listening proof",
        ],
        "retention_target",
        "fill retention-target.md",
    )
    audit.evidence_tags["retention"] = ", ".join(f"{key}={value}" for key, value in values.items() if value) or "missing"


def audit_prompt_pairing(project_root: Path, audit: Audit) -> None:
    values = require_fields(
        project_root,
        audit,
        PROMPT_PAIRING,
        [
            "Audio seed",
            "Seed type",
            "Retention target",
            "Style prompt",
            "Lyrics prompt",
            "Exclude",
        ],
        "prompt_pairing",
        "fill prompt-pairing.md",
    )
    text = read_text(project_root / PROMPT_PAIRING)
    influence = label_value(text, ["Audio Influence", "Audio Strength", "Seed strength"])
    values["Audio Influence"] = influence
    if not numeric_audio_influence(influence):
        add_finding(audit.blockers, "blocker", "prompt_pairing_audio_influence_missing", f"{PROMPT_PAIRING} needs nonzero Audio Influence / Audio Strength for this seed", "align slider value with retention-target.md")
    audit.evidence_tags["prompt_pairing"] = ", ".join(f"{key}={value}" for key, value in values.items() if value) or "missing"


def audit_anchor_review(project_root: Path, audit: Audit) -> None:
    values = require_fields(
        project_root,
        audit,
        ANCHOR_REVIEW,
        [
            "Seed",
            "Hidden take IDs",
            "Seed identity",
            "Musical transformation",
            "Prosody fit",
            "Rights clarity",
            "Decision",
        ],
        "anchor_retention_review",
        "fill anchor-retention-review.md after listening against the seed",
    )
    if not values:
        return
    thresholds = [
        ("Seed identity", 3.0, "seed_identity_below_floor"),
        ("Musical transformation", 3.0, "musical_transformation_below_floor"),
        ("Prosody fit", 4.0, "prosody_fit_below_floor"),
    ]
    for label, floor, code in thresholds:
        score = parse_score(values.get(label, ""))
        if score is None:
            add_finding(audit.blockers, "blocker", f"anchor_retention_{label.lower().replace(' ', '_')}_unscored", f"{ANCHOR_REVIEW} missing numeric {label}", "score anchor-retention review on a 0-5 scale")
        elif score < floor:
            add_finding(audit.blockers, "blocker", code, f"{ANCHOR_REVIEW} {label}={score:.2f} below {floor:.1f}", "repair, reseed, or regenerate before ordinary blind review")
    rights = values.get("Rights clarity", "")
    if not positive_value(rights):
        add_finding(audit.blockers, "blocker", "anchor_retention_rights_not_clear", f"{ANCHOR_REVIEW} needs Rights clarity: clear/pass/yes; got {rights or 'blank'}", "stop release chain until seed rights are clear")
    decision = values.get("Decision", "")
    if not positive_value(decision) or re.search(r"\b(reseed|discard|hold|fail|blocked|repair only|unknown)\b", decision, re.I):
        add_finding(audit.blockers, "blocker", "anchor_retention_decision_not_keep", f"{ANCHOR_REVIEW} decision is not a keep/pass decision: {decision or 'blank'}", "repair or reseed before take selection")
    audit.evidence_tags["anchor"] = ", ".join(f"{key}={value}" for key, value in values.items() if value) or "missing"


def audit_project(project_root: Path) -> Audit:
    signals = field_signals(project_root)
    audit = Audit(seed_required=bool(signals), detection_signals=signals)
    if not audit.seed_required:
        return audit
    audit_audio_rights(project_root, audit)
    audit_seed_classification(project_root, audit)
    audit_retention_target(project_root, audit)
    audit_prompt_pairing(project_root, audit)
    if not generation_audit_ready(project_root):
        add_finding(
            audit.blockers,
            "blocker",
            "generation_evidence_not_ready",
            f"{GENERATION_AUDIT} must pass before anchor-retention review is trusted",
            "run tools/audit_music_generation_evidence.py",
        )
    audit_anchor_review(project_root, audit)
    return audit


def finding_rows(findings: list[Finding]) -> str:
    if not findings:
        return "| pass | none | no blocking findings | proceed |\n"
    return "\n".join(f"| {item.severity} | {item.code} | {item.message} | {item.route} |" for item in findings) + "\n"


def render_audit(project_root: Path, audit: Audit) -> str:
    detection = "\n".join(f"- {signal}" for signal in audit.detection_signals) if audit.detection_signals else "- none"
    rights = audit.evidence_tags.get("rights", "not applicable")
    retention = audit.evidence_tags.get("retention", "not applicable")
    pairing = audit.evidence_tags.get("prompt_pairing", "not applicable")
    anchor = audit.evidence_tags.get("anchor", "not applicable")
    classification = audit.evidence_tags.get("classification", "not applicable")
    handoff = "not applicable"
    if audit.seed_required:
        handoff = "ready" if not audit.blockers else "blocked"
    return f"""# Audio Seed Retention Audit

Generated by: tools/audit_music_audio_seed_retention.py
Project root: {project_root}
Decision: {audit.decision}

This conditional gate checks human audio-seed use before ordinary blind review.
It prevents Audio Upload, Cover, Add Vocals, Inspire, Voice/Persona-like seed
paths, or nonzero Audio Influence from advancing without rights, retention
target, prompt pairing, generation provenance, and anchor-retention evidence.

## Audio Seed Detection

{detection}

## Audio Seed Evidence

Human audio seed required: {"yes" if audit.seed_required else "no"}
Seed rights tags: {rights}
Seed classification tags: {classification}
Retention target tags: {retention}
Prompt pairing tags: {pairing}
Generation evidence: {"pass" if generation_audit_ready(project_root) else "missing/incomplete"}
Anchor retention tags: {anchor}
Blind review handoff: {handoff}

## Findings

| severity | code | message | route |
|---|---|---|---|
{finding_rows(audit.blockers).rstrip()}

## Warnings

| severity | code | message | route |
|---|---|---|---|
{finding_rows(audit.warnings).rstrip()}

## Repair Route

- If this gate is not applicable, keep ordinary generation evidence and blind-review gates.
- If seed rights are unclear, do not upload or release; convert the source into prompt-safe style DNA instead.
- If retention target is vague, decide whether the seed protects melody, rhythm, harmony, vocal phrase, texture, arrangement, or catalog identity.
- If anchor-retention scores fail, repair or reseed before selecting the best take.
"""


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--output", default=OUTPUT, help="Relative output path for the audit note.")
    parser.add_argument("--write", action="store_true", help="Write the audit note.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit note.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero when required seed evidence is blocked.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    audit = audit_project(project_root)
    output = render_audit(project_root, audit)
    if args.write:
        output_path = project_root / args.output
        if output_path.exists() and not args.allow_overwrite:
            print(f"error: output exists, use --allow-overwrite: {output_path}", file=sys.stderr)
            return 2
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(output, encoding="utf-8")
        print(f"wrote {output_path.relative_to(project_root).as_posix()}")
    else:
        print(output)

    if audit.blockers:
        for blocker in audit.blockers[:12]:
            print(f"audio seed retention blocker: {blocker.code}: {blocker.message}", file=sys.stderr)
        return 1 if args.strict else 0
    if audit.seed_required:
        print("audio seed retention: pass")
    else:
        print("audio seed retention: not applicable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
