#!/usr/bin/env python3
"""Audit Suno personalization state before prompt compilation.

Voice, Persona, Custom Model, My Taste, and Prompt Boost can improve continuity,
but they also make a song less reproducible if the account/profile state is not
recorded. This gate requires source, scope, attribution, isolation, and rollback
evidence whenever a personalization feature is active.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROUTING_FILE = "04_prompt/persona-voice-model-routing.md"
STATE_FILE = "04_prompt/personalization-state.md"
OUTPUT = "04_prompt/personalization-hygiene-audit.md"
MARKER = "Generated by: tools/audit_music_personalization_hygiene.py"

ACTIVE_TERMS = {
    "voice": ["voice"],
    "persona": ["persona"],
    "custom_model": ["custom model", "custom-model"],
    "my_taste": ["my taste", "taste"],
    "prompt_boost": ["prompt boost", "boost"],
}

REQUIRED_WHEN_ACTIVE = {
    "Account / profile scope": ["Account / profile scope", "Account scope", "Profile scope"],
    "Active personalization features": ["Active personalization features", "Feature state", "Features active"],
    "Source / rights evidence": ["Source / rights evidence", "Rights evidence", "Source evidence"],
    "Catalog fit link": ["Catalog fit link", "Catalog fit audit", "Catalog link"],
    "Isolation boundary": ["Isolation boundary", "Project isolation", "Contamination check"],
    "Attribution plan": ["Attribution plan", "A/B attribution", "Validation route"],
    "Rollback condition": ["Rollback condition", "Rollback"],
    "Personalization decision": ["Personalization decision", "Decision"],
}

VOICE_FIELDS = {
    "Voice source": ["Voice source", "Voice identity source"],
    "Voice verification": ["Voice verification", "Verification status"],
}
PERSONA_FIELDS = {
    "Persona source": ["Persona source", "Source song"],
    "Persona role": ["Persona role", "Catalog role"],
}
CUSTOM_MODEL_FIELDS = {
    "Custom Model source": ["Custom Model source", "Custom model source"],
    "Custom Model corpus": ["Custom Model corpus", "Custom model corpus"],
    "Custom Model rights": ["Custom Model rights", "Corpus rights"],
}
MY_TASTE_FIELDS = {
    "My Taste state": ["My Taste state", "My Taste enabled"],
    "My Taste summary": ["My Taste summary", "Taste summary"],
}
PROMPT_BOOST_FIELDS = {
    "Prompt Boost state": ["Prompt Boost state", "Prompt boost state"],
    "Original style text": ["Original style text", "Original prompt"],
    "Boosted style text": ["Boosted style text", "Boosted prompt"],
    "Boost delta": ["Boost delta", "Changed by boost", "Boost changes"],
}

PLACEHOLDERS = {"", "tbd", "todo", "n/a", "na", "none", "unknown", "placeholder", "-", "填写", "待定"}
CONTAMINATION_TERMS = ["mixed client", "other client", "random likes", "shared taste", "unknown account", "混用", "其他客户", "随机偏好"]
MAGIC_TERMS = ["magic", "secret", "guarantee", "viral", "100%", "神 prompt", "必爆", "万能"]


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


@dataclass(frozen=True)
class PersonalizationAudit:
    project_root: Path
    active_features: set[str]
    values: dict[str, str]
    blockers: list[Finding]
    warnings: list[Finding]

    @property
    def not_applicable(self) -> bool:
        return not self.active_features

    @property
    def decision(self) -> str:
        if self.blockers:
            return "hold"
        if self.not_applicable:
            return "not applicable"
        return "pass"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def normalize(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().strip('"')).strip()


def has_value(value: str) -> bool:
    normalized = normalize(value).casefold()
    return normalized not in PLACEHOLDERS and not re.fullmatch(r"[-_/ ]*", normalized)


def positive_value(value: str) -> bool:
    lowered = normalize(value).casefold()
    if lowered in PLACEHOLDERS:
        return False
    return any(term in lowered for term in ["yes", "on", "enabled", "active", "use", "using", "true", "pass", "有", "启用", "使用"])


def label_value(text: str, labels: list[str]) -> str:
    wanted = {label.casefold() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,100}):\s*(.*)$", stripped)
        if not match:
            continue
        label = normalize(match.group(1)).casefold()
        if label in wanted:
            return normalize(match.group(2))
    return ""


def extract_values(text: str, field_map: dict[str, list[str]]) -> dict[str, str]:
    return {field: label_value(text, labels) for field, labels in field_map.items()}


def active_features_from_text(text: str, values: dict[str, str]) -> set[str]:
    active: set[str] = set()
    lowered = text.casefold()
    anchor = label_value(text, ["Human anchor lane", "Human Anchor Lane"]).casefold()
    feature_state = " ".join(
        [
            label_value(text, ["Active personalization features", "Feature state", "Features active"]),
            anchor,
        ]
    ).casefold()
    combined = f"{lowered}\n{feature_state}"

    for feature, terms in ACTIVE_TERMS.items():
        if any(term in feature_state for term in terms):
            active.add(feature)

    for feature, fields in [
        ("voice", VOICE_FIELDS),
        ("persona", PERSONA_FIELDS),
        ("custom_model", CUSTOM_MODEL_FIELDS),
        ("my_taste", MY_TASTE_FIELDS),
        ("prompt_boost", PROMPT_BOOST_FIELDS),
    ]:
        feature_values = extract_values(text, fields)
        if any(positive_value(value) for value in feature_values.values()):
            active.add(feature)

    if "text-only" in combined or "text only" in combined:
        active.discard("voice")
        active.discard("persona")
        active.discard("custom_model")
        if "my taste" not in feature_state and not positive_value(values.get("My Taste state", "")):
            active.discard("my_taste")
        if "prompt boost" not in feature_state and not positive_value(values.get("Prompt Boost state", "")):
            active.discard("prompt_boost")
    return active


def personalization_hygiene_audit_text_ready(text: str) -> bool:
    lowered = text.casefold()
    return (
        MARKER.casefold() in lowered
        and "decision: pass" in lowered
        and "personalization hygiene: pass" in lowered
        and "prompt compile handoff: pass" in lowered
    )


def personalization_hygiene_audit_ready(project_root: Path) -> bool:
    return personalization_hygiene_audit_text_ready(read_text(project_root / OUTPUT))


def personalization_hygiene_required_from_docs(docs: dict[str, str]) -> bool:
    text = "\n".join(docs.get(path, "") for path in [ROUTING_FILE, STATE_FILE, "09_vocal/voice-rights.md"])
    values = extract_values(text, {**MY_TASTE_FIELDS, **PROMPT_BOOST_FIELDS})
    return bool(active_features_from_text(text, values))


def analyze(project_root: Path) -> PersonalizationAudit:
    text = "\n".join(
        [
            read_text(project_root / ROUTING_FILE),
            read_text(project_root / STATE_FILE),
            read_text(project_root / "09_vocal/voice-rights.md"),
            read_text(project_root / "01_brief/catalog-fit-audit.md"),
        ]
    )
    values = extract_values(
        text,
        {
            **REQUIRED_WHEN_ACTIVE,
            **VOICE_FIELDS,
            **PERSONA_FIELDS,
            **CUSTOM_MODEL_FIELDS,
            **MY_TASTE_FIELDS,
            **PROMPT_BOOST_FIELDS,
        },
    )
    active = active_features_from_text(text, values)
    blockers: list[Finding] = []
    warnings: list[Finding] = []

    if not active:
        return PersonalizationAudit(project_root, active, values, blockers, warnings)

    if not read_text(project_root / STATE_FILE):
        blockers.append(Finding("blocker", "personalization_state_missing", f"missing {STATE_FILE}", "write personalization-state.md"))

    for field, labels in REQUIRED_WHEN_ACTIVE.items():
        if not has_value(values.get(field, "")):
            blockers.append(Finding("blocker", f"{field.lower().replace(' / ', '_').replace(' ', '_')}_missing", f"{field} is missing", "complete personalization-state.md"))

    feature_field_map = {
        "voice": VOICE_FIELDS,
        "persona": PERSONA_FIELDS,
        "custom_model": CUSTOM_MODEL_FIELDS,
        "my_taste": MY_TASTE_FIELDS,
        "prompt_boost": PROMPT_BOOST_FIELDS,
    }
    for feature in sorted(active):
        for field in feature_field_map[feature]:
            if not has_value(values.get(field, "")):
                blockers.append(Finding("blocker", f"{feature}_{field.lower().replace(' ', '_')}_missing", f"{feature} requires {field}", "complete personalization-state.md"))

    combined = text.casefold()
    for term in CONTAMINATION_TERMS:
        if term in combined:
            blockers.append(Finding("blocker", "personalization_contamination_risk", f"personalization state suggests cross-project contamination: {term}", "isolate account/profile/taste state"))
    for term in MAGIC_TERMS:
        if term in combined:
            blockers.append(Finding("blocker", "personalization_magic_claim", f"personalization state uses magic/guaranteed language: {term}", "rewrite as testable attribution"))

    attribution = values.get("Attribution plan", "").casefold()
    if has_value(attribution) and not any(term in attribution for term in ["a/b", "blind", "one variable", "single variable", "original", "boosted", "盲听", "单变量"]):
        blockers.append(Finding("blocker", "attribution_plan_not_testable", "Attribution plan must preserve A/B, blind, original/boosted, or one-variable evidence.", "rewrite attribution plan"))

    isolation = values.get("Isolation boundary", "").casefold()
    if has_value(isolation) and not any(term in isolation for term in ["project", "catalog", "profile", "account", "isolat", "separate", "独立", "隔离"]):
        blockers.append(Finding("blocker", "isolation_boundary_weak", "Isolation boundary must name project/catalog/profile/account separation.", "tighten isolation boundary"))

    if "prompt_boost" in active:
        original = values.get("Original style text", "")
        boosted = values.get("Boosted style text", "")
        if has_value(original) and has_value(boosted) and normalize(original).casefold() == normalize(boosted).casefold():
            warnings.append(Finding("warning", "boost_delta_empty", "Prompt Boost original and boosted text are identical.", "record actual boost delta or disable boost"))

    return PersonalizationAudit(project_root, active, values, blockers, warnings)


def render_findings(findings: list[Finding]) -> str:
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    if not findings:
        rows.append("| pass | none | no blocking findings | proceed |")
    for finding in findings:
        rows.append(f"| {finding.severity} | {finding.code} | {finding.message} | {finding.route} |")
    return "\n".join(rows)


def render(audit: PersonalizationAudit) -> str:
    active = ", ".join(sorted(audit.active_features)) if audit.active_features else "none"
    status = "not applicable" if audit.not_applicable else ("pass" if not audit.blockers else "repair")
    handoff = "not applicable" if audit.not_applicable else ("pass" if not audit.blockers else "blocked")
    v = audit.values
    return f"""# Personalization Hygiene Audit

{MARKER}
Project root: {audit.project_root}
Decision: {audit.decision}

## Personalization Hygiene Evidence

Active personalization features: {active}
Personalization hygiene: {status}
Account / profile scope: {v.get("Account / profile scope") or "not recorded"}
Source / rights evidence: {v.get("Source / rights evidence") or "not recorded"}
Catalog fit link: {v.get("Catalog fit link") or "not recorded"}
Isolation boundary: {v.get("Isolation boundary") or "not recorded"}
Attribution plan: {v.get("Attribution plan") or "not recorded"}
Rollback condition: {v.get("Rollback condition") or "not recorded"}
Voice source: {v.get("Voice source") or "not recorded"}
Voice verification: {v.get("Voice verification") or "not recorded"}
Persona source: {v.get("Persona source") or "not recorded"}
Persona role: {v.get("Persona role") or "not recorded"}
Custom Model source: {v.get("Custom Model source") or "not recorded"}
Custom Model corpus: {v.get("Custom Model corpus") or "not recorded"}
Custom Model rights: {v.get("Custom Model rights") or "not recorded"}
My Taste state: {v.get("My Taste state") or "not recorded"}
My Taste summary: {v.get("My Taste summary") or "not recorded"}
Prompt Boost state: {v.get("Prompt Boost state") or "not recorded"}
Original style text: {v.get("Original style text") or "not recorded"}
Boosted style text: {v.get("Boosted style text") or "not recorded"}
Boost delta: {v.get("Boost delta") or "not recorded"}
Personalization decision: {v.get("Personalization decision") or "not recorded"}
Prompt compile handoff: {handoff}

## Findings

{render_findings(audit.blockers + audit.warnings)}

## Rule

- If personalization is active, keep it isolated, attributable, rights-backed, and reversible. If no personalization feature is active, this gate is not applicable.
"""


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--write", action="store_true", help="Write the personalization hygiene audit file.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit file.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero when blockers exist.")
    parser.add_argument("--output", default=OUTPUT, help="Relative output path.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    audit = analyze(project_root)
    output = render(audit)
    if args.write:
        path = project_root / args.output
        if path.exists() and not args.allow_overwrite:
            print(f"error: output exists, use --allow-overwrite: {path}", file=sys.stderr)
            return 2
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(output, encoding="utf-8")
    else:
        print(output)

    if audit.blockers:
        print("personalization hygiene audit blocked:", file=sys.stderr)
        for finding in audit.blockers:
            print(f"- {finding.code}: {finding.message} -> {finding.route}", file=sys.stderr)
        return 1 if args.strict else 0

    print(f"personalization hygiene audit decision: {audit.decision}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
