#!/usr/bin/env python3
"""Audit post-production and mix-lock evidence before release listener tests."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


OUTPUT = "10_mix-master/post-production-mix-lock-audit.md"
POST_PRODUCTION_MIX_LOCK_MARKER = "Generated by: tools/audit_music_post_production_mix_lock.py"
POST_PRODUCTION_MIX_LOCK_REQUIRED_TERMS = [
    "Decision: pass",
    "## Post Production Mix Lock Evidence",
    "Locked take:",
    "Arrangement density tags:",
    "Vocal center:",
    "Low-end/kick-bass:",
    "Space/dynamics automation:",
    "Transition/outro:",
    "AI artifact repair:",
    "Stem/DAW handoff:",
    "Reference A/B:",
    "Mix lock handoff: pass",
]

TAKE_DECISION = "06_review/take-selection-decision.md"
REPAIR_ROUTE = "07_repair/repair-route-map.md"
BEST_TAKE_LOCK = "08_stems-daw/best-take-lock.md"
SESSION_PACK = "08_stems-daw/session-pack.md"
FINAL_HUMANIZED_REVIEW = "08_stems-daw/final-humanized-master-review.md"
POST_REVIEW = "10_mix-master/post-review.md"
DENSITY_TRIAGE = "10_mix-master/arrangement-density-triage.md"
MIX_PLAN = "10_mix-master/mix-plan.md"
MIX_PREFLIGHT = "10_mix-master/mix-lock-preflight.md"

PLACEHOLDER_VALUES = {"", "-", "--", "todo", "tbd", "pending", "unknown", "missing", "n/a", "na"}
BLOCKING_RE = re.compile(
    r"\b(todo|tbd|pending|unknown|unresolved|unclear|missing|fail(?:ed)?|hold|blocked|red flag)\b"
    r"|待定|未知|未解决|不清楚|缺失|失败|不通过|暂停|阻塞|红灯|红旗",
    re.I,
)
CLEARING_RE = re.compile(
    r"\b(no|none|0|zero|resolved|clear|cleared|pass|passed|approved|ready|not applicable|n/a|low)\b"
    r"|无|否|已解决|通过|清楚|低风险",
    re.I,
)


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


@dataclass
class Audit:
    blockers: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)
    tags: dict[str, str] = field(default_factory=dict)

    @property
    def decision(self) -> str:
        return "pass" if not self.blockers else "hold"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def normalized(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().strip("`\"'")).lower()


def has_value(value: str) -> bool:
    return normalized(value) not in PLACEHOLDER_VALUES


def label_value(text: str, labels: list[str]) -> str:
    wanted = {label.lower() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,100}):\s*(.*)$", stripped)
        if not match:
            continue
        label = match.group(1).strip().lower()
        value = match.group(2).strip().strip('"')
        if label in wanted:
            return value
    return ""


def add_finding(items: list[Finding], severity: str, code: str, message: str, route: str) -> None:
    items.append(Finding(severity=severity, code=code, message=message, route=route))


def require_file(project_root: Path, audit: Audit, rel: str) -> str:
    text = read_text(project_root / rel)
    if not text:
        add_finding(audit.blockers, "blocker", f"{Path(rel).stem.replace('-', '_')}_missing", f"missing {rel}", "complete post-production mix-lock evidence")
    return text


def require_label(audit: Audit, rel: str, text: str, labels: list[str], code: str, route: str) -> str:
    value = label_value(text, labels)
    if not has_value(value):
        add_finding(audit.blockers, "blocker", code, f"{rel} missing {' / '.join(labels)}", route)
    return value


def positive_value(value: str) -> bool:
    return bool(re.search(r"\b(pass|passed|yes|clear|cleared|ok|approved|approve|ready|locked|complete|completed|resolved)\b|通过|清楚|已解决|完成|锁定", value, re.I))


def low_risk_value(value: str) -> bool:
    return bool(re.search(r"^(no|none|0|zero|low|pass|passed|clear|cleared|ok|resolved|n/a|not applicable)\b|无|否|低风险|通过|清楚", normalized(value), re.I))


def line_is_blocking(line: str) -> bool:
    text = line.strip()
    if not text or text.startswith("#") or text.startswith("|") or text.startswith("```"):
        return False
    if not BLOCKING_RE.search(text):
        return False
    return not CLEARING_RE.search(text)


def blocking_lines(text: str) -> list[str]:
    return [line.strip() for line in text.splitlines() if line_is_blocking(line)][:6]


def extract_locked_take(project_root: Path) -> str:
    for rel in [TAKE_DECISION, BEST_TAKE_LOCK, SESSION_PACK, POST_REVIEW]:
        text = read_text(project_root / rel)
        value = label_value(text, ["Best take", "Locked take", "Take"])
        if has_value(value):
            return value
    return ""


def route_suggests_daw(project_root: Path) -> bool:
    text = "\n".join(read_text(project_root / rel) for rel in [REPAIR_ROUTE, TAKE_DECISION])
    return bool(re.search(r"daw|stem|vocal|groove|drum|bass|mix|post|artifact|human|re[- ]?record|overdub|分轨|人声|鼓|贝斯|混音|后期", text, re.I))


def section_present(text: str, names: list[str]) -> bool:
    lowered = text.lower()
    for name in names:
        escaped = re.escape(name.lower()).replace(r"\ ", r"\s+")
        if re.search(rf"(?m)^\s*(?:\[|#+\s*)?{escaped}\b", lowered):
            return True
        if re.search(rf"(?m)^\s*\|\s*{escaped}\s*\|", lowered):
            return True
    return False


def density_has_action(text: str) -> bool:
    return bool(
        re.search(
            r"\b(remove|removed|mute|muted|duck|ducked|thin|thinned|drop|dropped|cut|carve|carved|space|left space|automation|notch)\b"
            r"|移除|删除|删掉|静音|让位|削薄|减少|留白|挖频|自动化",
            text,
            re.I,
        )
    )


def audit_take_and_post_review(project_root: Path, audit: Audit) -> None:
    locked_take = extract_locked_take(project_root)
    if not has_value(locked_take):
        add_finding(audit.blockers, "blocker", "locked_take_missing", "locked take is missing from take decision, best-take lock, session pack, or post review", "lock best take before post-production")
    audit.tags["locked_take"] = locked_take or "missing"

    post = require_file(project_root, audit, POST_REVIEW)
    if post:
        post_locked = require_label(audit, POST_REVIEW, post, ["Locked take", "Best take"], "post_review_locked_take_missing", "tie post review to the locked take")
        keep = require_label(audit, POST_REVIEW, post, ["Keep", "Preserve", "Must keep"], "post_review_keep_missing", "name what must not be damaged in post")
        repair = require_label(audit, POST_REVIEW, post, ["Must repair", "Repair", "Fix"], "post_review_repair_missing", "name post-production targets")
        decision = require_label(audit, POST_REVIEW, post, ["Decision", "Review result"], "post_review_decision_missing", "approve post-review before mix lock")
        if post_locked and locked_take and post_locked.strip() != locked_take.strip():
            add_finding(audit.blockers, "blocker", "locked_take_mismatch", f"{POST_REVIEW} locked take {post_locked} does not match {locked_take}", "refresh post review for the locked take")
        if decision and not positive_value(decision):
            add_finding(audit.blockers, "blocker", "post_review_not_ready", f"{POST_REVIEW} decision is not ready/pass: {decision}", "finish post review before mix lock")
        audit.tags["post_review"] = f"keep={keep or 'missing'}, repair={repair or 'missing'}, decision={decision or 'missing'}"


def audit_density(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, DENSITY_TRIAGE)
    if not text:
        return
    required_sections = {
        "verse": ["verse 1", "verse", "a段", "主歌"],
        "chorus": ["chorus", "副歌"],
        "bridge_or_final": ["bridge", "final chorus", "outro", "桥段", "末段", "最后副歌"],
    }
    missing = [name for name, terms in required_sections.items() if not section_present(text, terms)]
    if missing:
        add_finding(audit.blockers, "blocker", "density_sections_missing", f"{DENSITY_TRIAGE} missing section density evidence: {', '.join(missing)}", "triage arrangement density by song section")
    if not density_has_action(text):
        add_finding(audit.blockers, "blocker", "density_action_missing", f"{DENSITY_TRIAGE} needs at least one remove/mute/duck/thin/space action", "remove clutter before mix lock")
    audit.tags["density"] = "sections=" + ("complete" if not missing else ",".join(missing)) + "; action=" + ("yes" if density_has_action(text) else "missing")


def audit_mix_plan(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, MIX_PLAN)
    if not text:
        return
    vocal = require_label(audit, MIX_PLAN, text, ["Vocal center", "Lead vocal center", "Lead vocal clarity", "人声中心"], "vocal_center_missing", "define lead vocal center and clarity")
    low = require_label(audit, MIX_PLAN, text, ["Low-end / kick-bass", "Low-end", "Kick/bass", "Kick-bass", "鼓贝斯", "低频"], "low_end_missing", "define kick/bass pocket")
    space = require_label(audit, MIX_PLAN, text, ["Space / reverb / width", "Space", "Reverb", "Width", "空间"], "space_width_missing", "define reverb, width, and depth")
    dynamics = require_label(audit, MIX_PLAN, text, ["Dynamics / automation", "Dynamics", "Automation", "动态"], "dynamics_automation_missing", "define automation and dynamic movement")
    transition = require_label(audit, MIX_PLAN, text, ["Transition/outro", "Transitions", "Outro", "转场", "尾声"], "transition_outro_missing", "define section transitions and ending")
    artifact = require_label(audit, MIX_PLAN, text, ["AI artifact repair", "Artifact repair", "Artifact control", "AI artifacts"], "artifact_repair_missing", "define AI artifact repair targets")
    reference = require_label(audit, MIX_PLAN, text, ["Reference A/B", "Loudness-matched reference A/B", "A/B"], "reference_ab_missing", "define reference A/B boundary")
    audit.tags["mix_plan"] = (
        f"vocal={vocal or 'missing'}, low_end={low or 'missing'}, space={space or 'missing'}, "
        f"dynamics={dynamics or 'missing'}, transition={transition or 'missing'}, artifact={artifact or 'missing'}, reference={reference or 'missing'}"
    )


def audit_preflight(project_root: Path, audit: Audit) -> None:
    text = require_file(project_root, audit, MIX_PREFLIGHT)
    if not text:
        return
    required = [
        ("lead_vocal_clear", ["Lead vocal clear", "Vocal clear", "Lead vocal"], "lead vocal must read as the song center"),
        ("hook_title_clear", ["Hook/title clear", "Title hook clear", "Hook clear"], "hook and title must be intelligible"),
        ("low_end_controlled", ["Low end controlled", "Low-end controlled", "Kick/bass controlled"], "kick and bass must be controlled"),
        ("space_dynamics_clear", ["Space/dynamics", "Space and dynamics", "Width/dynamics"], "space and dynamics must move without clutter"),
        ("transition_outro_clear", ["Transition/outro", "Transitions/outro", "Intro/outro"], "transitions and ending must feel intentional"),
        ("ai_artifacts_clear", ["AI artifacts", "AI artifact repair", "Artifact status"], "AI artifacts must be resolved or low-risk"),
    ]
    tags: list[str] = []
    for code, labels, route in required:
        value = require_label(audit, MIX_PREFLIGHT, text, labels, f"{code}_missing", route)
        tags.append(f"{code}={value or 'missing'}")
        if value and not (positive_value(value) or low_risk_value(value)):
            add_finding(audit.blockers, "blocker", f"{code}_not_pass", f"{MIX_PREFLIGHT} {labels[0]} is not pass/clear/low-risk: {value}", route)
    mono = label_value(text, ["Mono/phase", "Mono phase", "Phase"])
    if not has_value(mono):
        add_finding(audit.warnings, "warning", "mono_phase_not_recorded", f"{MIX_PREFLIGHT} has no Mono/phase note", "record before final audio QC")
    elif not (positive_value(mono) or low_risk_value(mono)):
        add_finding(audit.blockers, "blocker", "mono_phase_not_pass", f"{MIX_PREFLIGHT} Mono/phase is not pass/clear/low-risk: {mono}", "fix phase before mix lock")
    decision = require_label(audit, MIX_PREFLIGHT, text, ["Decision", "Mix lock decision"], "mix_lock_decision_missing", "approve or hold mix lock explicitly")
    if decision and not positive_value(decision):
        add_finding(audit.blockers, "blocker", "mix_lock_decision_not_pass", f"{MIX_PREFLIGHT} decision is not pass/ready: {decision}", "hold release until mix lock passes")
    tags.append(f"decision={decision or 'missing'}")
    audit.tags["preflight"] = ", ".join(tags)


def audit_handoff(project_root: Path, audit: Audit) -> None:
    session = read_text(project_root / SESSION_PACK)
    best_lock = read_text(project_root / BEST_TAKE_LOCK)
    final_review = require_file(project_root, audit, FINAL_HUMANIZED_REVIEW)
    handoff_ready = ("Generated by: tools/prepare_music_daw_handoff.py" in session and bool(label_value(session, ["Locked take"]))) or has_value(label_value(best_lock, ["Locked take", "Best take"]))
    if route_suggests_daw(project_root) and not handoff_ready:
        add_finding(audit.blockers, "blocker", "stem_daw_handoff_missing", "repair route suggests stems/DAW/post work but session pack or best-take lock is missing", "prepare DAW/stems handoff before mix lock")
    if final_review:
        decision = label_value(final_review, ["Decision", "Review result"]) or ""
        if not has_value(decision):
            add_finding(audit.blockers, "blocker", "final_humanized_review_decision_missing", f"{FINAL_HUMANIZED_REVIEW} missing Decision", "blind-review final humanized master before release")
        elif not positive_value(decision):
            add_finding(audit.blockers, "blocker", "final_humanized_review_not_pass", f"{FINAL_HUMANIZED_REVIEW} decision is not pass/ready: {decision}", "finish DAW/humanization review before mix lock")
        audit.tags["final_review"] = decision or "missing"
    audit.tags["handoff"] = "ready" if handoff_ready else "missing"


def audit_unresolved_lines(project_root: Path, audit: Audit) -> None:
    for rel in [POST_REVIEW, DENSITY_TRIAGE, MIX_PLAN, MIX_PREFLIGHT, FINAL_HUMANIZED_REVIEW]:
        text = read_text(project_root / rel)
        for line in blocking_lines(text):
            add_finding(audit.blockers, "blocker", "unresolved_evidence_line", f"{rel} has unresolved blocker line: {line}", "resolve hold/fail/pending/unknown lines")


def audit_project(project_root: Path) -> Audit:
    audit = Audit()
    audit_take_and_post_review(project_root, audit)
    audit_density(project_root, audit)
    audit_mix_plan(project_root, audit)
    audit_preflight(project_root, audit)
    audit_handoff(project_root, audit)
    audit_unresolved_lines(project_root, audit)
    return audit


def post_production_mix_lock_audit_decision(project_root: Path) -> str:
    return label_value(read_text(project_root / OUTPUT), ["Decision"]) or "missing"


def post_production_mix_lock_audit_text_ready(text: str) -> bool:
    if POST_PRODUCTION_MIX_LOCK_MARKER not in text:
        return False
    if not re.search(r"^Decision:\s*pass\b", text, re.I | re.M):
        return False
    if any(term not in text for term in POST_PRODUCTION_MIX_LOCK_REQUIRED_TERMS):
        return False
    if re.search(r"\bNEEDS_REPAIR\b|Decision:\s*(hold|fail)", text, re.I):
        return False
    return True


def post_production_mix_lock_audit_ready(project_root: Path) -> bool:
    return post_production_mix_lock_audit_text_ready(read_text(project_root / OUTPUT))


def finding_rows(findings: list[Finding]) -> str:
    if not findings:
        return "| pass | none | no blocking findings | proceed |\n"
    return "\n".join(f"| {item.severity} | {item.code} | {item.message} | {item.route} |" for item in findings) + "\n"


def render_audit(project_root: Path, audit: Audit) -> str:
    return f"""# Post Production Mix Lock Audit

{POST_PRODUCTION_MIX_LOCK_MARKER}
Project root: {project_root}
Decision: {audit.decision}

This gate checks whether the locked take has been post-produced enough to enter
release-listener and rights gates without hiding unresolved AI flavor under
loudness, polish, or platform paperwork.

## Post Production Mix Lock Evidence

Locked take: {audit.tags.get('locked_take', 'missing')}
Arrangement density tags: {audit.tags.get('density', 'missing')}
Vocal center: {label_value(read_text(project_root / MIX_PLAN), ['Vocal center', 'Lead vocal center', 'Lead vocal clarity', '人声中心']) or 'missing'}
Low-end/kick-bass: {label_value(read_text(project_root / MIX_PLAN), ['Low-end / kick-bass', 'Low-end', 'Kick/bass', 'Kick-bass', '鼓贝斯', '低频']) or 'missing'}
Space/dynamics automation: {label_value(read_text(project_root / MIX_PLAN), ['Space / reverb / width', 'Space', 'Reverb', 'Width', '空间']) or 'missing'}; {label_value(read_text(project_root / MIX_PLAN), ['Dynamics / automation', 'Dynamics', 'Automation', '动态']) or 'missing'}
Transition/outro: {label_value(read_text(project_root / MIX_PLAN), ['Transition/outro', 'Transitions', 'Outro', '转场', '尾声']) or 'missing'}
AI artifact repair: {label_value(read_text(project_root / MIX_PLAN), ['AI artifact repair', 'Artifact repair', 'Artifact control', 'AI artifacts']) or 'missing'}
Stem/DAW handoff: {audit.tags.get('handoff', 'missing')}
Reference A/B: {label_value(read_text(project_root / MIX_PLAN), ['Reference A/B', 'Loudness-matched reference A/B', 'A/B']) or 'missing'}
Mix lock handoff: {audit.decision}

## Findings

| severity | code | message | route |
|---|---|---|---|
{finding_rows(audit.blockers + audit.warnings)}
## Release Routing

- pass: run release-listener evidence and release-candidate gates.
- hold: repair the named post-production layer before audio QC, listener release tests, or rights packaging.
"""


def write_output(project_root: Path, text: str, allow_overwrite: bool) -> Path:
    path = project_root / OUTPUT
    if path.exists() and not allow_overwrite:
        raise FileExistsError(f"refusing to overwrite existing file: {path.relative_to(project_root).as_posix()}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--write", action="store_true", help="Write the post-production mix-lock audit.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting the audit output.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero when post-production evidence is blocked.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists():
        print(f"error: project root does not exist: {project_root}", file=sys.stderr)
        return 2

    audit = audit_project(project_root)
    if audit.blockers and args.strict:
        print("post-production mix-lock audit blocked:", file=sys.stderr)
        for finding in audit.blockers:
            print(f"- {finding.code}: {finding.message}", file=sys.stderr)
        return 2

    text = render_audit(project_root, audit)
    if args.write:
        try:
            written = write_output(project_root, text, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        print(f"wrote {written.relative_to(project_root).as_posix()}")
    else:
        print("post-production mix-lock audit preview")
        print(f"decision: {audit.decision}")
        print(f"blockers: {len(audit.blockers)}")
        print(f"warnings: {len(audit.warnings)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
