#!/usr/bin/env python3
"""Audit reference-chord-skeleton transfer before Suno upload generation.

This gate is conditional. Ordinary text-only Suno generation should not be
blocked by it. It activates when the project uses a reference upload, chord
progression extraction, Audio Upload/Cover, or a chord-skeleton transfer plan.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


OUTPUT = "02_references/chord-skeleton-transfer-audit.md"

TRANSFER_FILE = "02_references/chord-skeleton-transfer.md"
REFERENCE_RIGHTS = "02_references/reference-rights.md"
SOURCE_RIGHTS = "02_references/source-rights-ledger.md"
AUDIO_RIGHTS = "02_references/audio-rights-ledger.md"
SEED_CLASSIFICATION = "02_references/seed-type-classification.md"
RETENTION_TARGET = "04_prompt/retention-target.md"
PROMPT_PAIRING = "04_prompt/prompt-pairing.md"
STYLE_FILE = "04_prompt/style-field-map.md"
SLIDER_FILE = "04_prompt/slider-intent-map.md"
BATCH_PLAN = "05_generations/batch-generation-plan.md"

MARKER = "Generated by: tools/audit_music_chord_skeleton_transfer.py"
REQUIRED_TERMS = [
    "Decision: pass",
    "## Chord Skeleton Transfer",
    "Rights route:",
    "Skeleton tags:",
    "MIDI simplification:",
    "Suno upload route:",
    "Reverse analysis plan:",
    "Prompt compile handoff:",
]

PLACEHOLDERS = {
    "",
    "-",
    "--",
    "todo",
    "tbd",
    "pending",
    "unknown",
    "missing",
    "n/a",
    "na",
    "none",
    "yes/no",
}


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


@dataclass
class Audit:
    required: bool
    signals: list[str] = field(default_factory=list)
    fields: dict[str, str] = field(default_factory=dict)
    blockers: list[Finding] = field(default_factory=list)
    warnings: list[Finding] = field(default_factory=list)

    @property
    def decision(self) -> str:
        if not self.required:
            return "not applicable"
        return "pass" if not self.blockers else "hold"

    @property
    def passed(self) -> bool:
        return self.decision in {"not applicable", "pass"}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def normalized(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().strip("`\"'")).strip()


def has_value(value: str, *, allow_none: bool = False) -> bool:
    text = normalized(value).casefold()
    if allow_none and text in {"none", "no", "not applicable", "n/a", "na", "无", "不适用"}:
        return True
    return text not in PLACEHOLDERS


def label_value(text: str, labels: list[str]) -> str:
    wanted = {label.casefold() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,110}):\s*(.*)$", stripped)
        if not match:
            continue
        label = match.group(1).strip().casefold()
        value = normalized(match.group(2))
        if label in wanted:
            return value
    return ""


def content_without_scaffold_metadata(text: str) -> str:
    metadata_labels = {
        "project root",
        "song title",
        "artist / catalog",
        "language",
        "lane",
        "use case",
        "file",
        "created",
        "generated by",
    }
    lines: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            continue
        match = re.match(r"^([^:]{1,80}):", stripped)
        if match and match.group(1).strip().casefold() in metadata_labels:
            continue
        lines.append(line)
    return "\n".join(lines)


def project_docs(project_root: Path) -> dict[str, str]:
    docs: dict[str, str] = {}
    for path in project_root.rglob("*.md"):
        rel = path.relative_to(project_root).as_posix()
        try:
            docs[rel] = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            docs[rel] = path.read_text(errors="replace")
    return docs


def positive(value: str) -> bool:
    return bool(
        re.search(
            r"\b(yes|true|allowed|cleared|approved|licensed|self-owned|own|original|pass)\b|允许|已授权|自有|原创|通过|可上传|可用",
            value,
            re.I,
        )
    )


def negative_or_unknown(value: str) -> bool:
    return bool(
        re.search(
            r"\b(no|false|unknown|unclear|unlicensed|not allowed|forbidden|pending|third-party|listen-only)\b|否|未知|不清楚|未授权|禁止|待定|第三方|仅听辨",
            value,
            re.I,
        )
    )


def upload_route(value: str) -> bool:
    if re.search(r"\b(no|not|without|do not|don't|text-only)\b[^.\n;]{0,60}\b(audio upload|upload|cover|seed|midi)\b|不上传|仅文字", value, re.I):
        return False
    return bool(re.search(r"audio upload|upload audio|cover|uploaded audio|audio seed|midi|reference upload|上传|和弦骨架|参考曲上传", value, re.I))


def signals_from_docs(docs: dict[str, str]) -> list[str]:
    signals: list[str] = []
    signal_patterns = [
        r"\bchord skeleton\b|chord-skeleton|\bchord progression\b|\breference upload\b|\bsong master pro\b|\baudio upload\b|\bcover\b|\buploaded audio\b",
        r"和弦骨架|和弦进行|参考曲上传|上传参考曲|上传音频|导出\s*MIDI|长音骨架|Suno\s*伴奏",
    ]
    transfer_text = docs.get(TRANSFER_FILE, "")
    if transfer_text:
        transfer_route = label_value(transfer_text, ["Suno route", "Suno tool choice", "Audio Upload / Cover / Custom Mode", "Target workflow"])
        allowed_action = label_value(transfer_text, ["Allowed action", "Allowed use", "Allowed use in this project"])
        progression = label_value(transfer_text, ["Progression", "Chord Progression", "Chord progression"])
        bpm = label_value(transfer_text, ["BPM", "Tempo", "Tempo / meter"])
        key = label_value(transfer_text, ["Key", "Key / mode", "Mode"])
        tool_used = label_value(transfer_text, ["Tool used", "Analysis tool"])
        seed_file = label_value(transfer_text, ["File", "Seed file", "Audio file", "Upload file"])
        if (
            upload_route(" ".join([transfer_route, allowed_action, seed_file]))
            or (has_value(progression) and (has_value(bpm) or has_value(key) or has_value(tool_used)))
        ):
            signals.append(f"{TRANSFER_FILE}: filled chord skeleton transfer plan")

    signal_files = [STYLE_FILE, SLIDER_FILE, PROMPT_PAIRING, RETENTION_TARGET, BATCH_PLAN]
    for rel in signal_files:
        text = content_without_scaffold_metadata(docs.get(rel, ""))
        if not text:
            continue
        for pattern in signal_patterns:
            if re.search(pattern, text, re.I):
                signals.append(f"{rel}: {pattern}")
                break
    audio_influence = label_value(docs.get(SLIDER_FILE, ""), ["Audio Influence", "Audio influence"])
    if audio_influence and re.search(r"\d", audio_influence):
        match = re.search(r"(\d+(?:\.\d+)?)", audio_influence)
        if match and float(match.group(1)) > 0:
            signals.append(f"{SLIDER_FILE}: Audio Influence={audio_influence}")
    return signals


def chord_skeleton_transfer_required(project_root: Path) -> bool:
    return bool(signals_from_docs(project_docs(project_root)))


def chord_skeleton_transfer_required_from_docs(docs: dict[str, str]) -> bool:
    return bool(signals_from_docs(docs))


def chord_skeleton_transfer_audit_ready(project_root: Path) -> bool:
    text = read_text(project_root / OUTPUT)
    return MARKER in text and all(term in text for term in REQUIRED_TERMS)


def chord_skeleton_transfer_audit_ready_from_docs(docs: dict[str, str]) -> bool:
    text = docs.get(OUTPUT, "")
    return MARKER in text and all(term in text for term in REQUIRED_TERMS)


def collect_fields(docs: dict[str, str]) -> dict[str, str]:
    paths = [TRANSFER_FILE, REFERENCE_RIGHTS, SOURCE_RIGHTS, AUDIO_RIGHTS, SEED_CLASSIFICATION, RETENTION_TARGET, PROMPT_PAIRING, STYLE_FILE, SLIDER_FILE]
    def get(labels: list[str], source_paths: list[str] | None = None) -> str:
        for rel in source_paths or paths:
            value = label_value(docs.get(rel, ""), labels)
            if has_value(value):
                return value
        return ""

    return {
        "reference_status": get(["Reference status", "Reference route", "Material type"]),
        "allowed_action": get(["Allowed action", "Allowed use", "Allowed use in this project"]),
        "forbidden_use": get(["Forbidden use", "Forbidden action", "Do not use", "Do-not-copy"]),
        "can_upload_audio": get(["Can upload audio", "Can upload audio?", "Can upload to AI tool"]),
        "commercial_use": get(["Commercial use", "Can use for commercial release?", "Can use in release"]),
        "source_section": get(["Source section", "Source bars", "Reference section"]),
        "bpm": get(["BPM", "Tempo", "Tempo / meter"]),
        "key": get(["Key", "Key / mode", "Mode"]),
        "progression": get(["Progression", "Chord Progression", "Chord progression"]),
        "bars": get(["Bars", "Bar count"]),
        "harmonic_rhythm": get(["Harmonic rhythm", "Chord-change rate"]),
        "emotional_color": get(["Emotional color", "Main emotional color", "Mood"]),
        "bass_root_direction": get(["Bass/root direction", "Root direction", "Bass direction"]),
        "tool_used": get(["Tool used", "Analysis tool"]),
        "tool_confidence": get(["Tool confidence", "Chord labels confidence"]),
        "manual_corrections": get(["Manual corrections", "Manual correction"]),
        "removed": get(["Removed", "MIDI removed", "Simplification removed"]),
        "extended": get(["Extended", "MIDI extended", "Simplification extended"]),
        "retained": get(["Retained", "MIDI retained", "Simplification retained"]),
        "do_not_copy": get(["Do-not-copy", "Do not copy", "Do-not-copy list"]),
        "seed_file": get(["File", "Seed file", "Audio file", "Upload file"], [AUDIO_RIGHTS, TRANSFER_FILE, PROMPT_PAIRING]),
        "suno_route": get(["Suno route", "Suno tool choice", "Audio Upload / Cover / Custom Mode", "Target workflow"]),
        "style_field": get(["Style field", "Style Of Music", "Style of Music"], [TRANSFER_FILE, STYLE_FILE, PROMPT_PAIRING]),
        "exclude": get(["Exclude", "Exclude field"], [TRANSFER_FILE, STYLE_FILE, "04_prompt/exclude-negative-aesthetic.md"]),
        "retention_target": get(["Retention target", "Target retention", "Keep"], [RETENTION_TARGET, TRANSFER_FILE]),
        "prompt_pairing": get(["Prompt pairing", "Prompt pairing plan"], [PROMPT_PAIRING, TRANSFER_FILE]),
        "reverse_analysis_plan": get(["Reverse analysis plan", "Reverse analysis", "Validation route", "Check route"], [TRANSFER_FILE, BATCH_PLAN]),
        "similarity_risk": get(["Similarity risk", "Similarity risk score"], [TRANSFER_FILE, REFERENCE_RIGHTS]),
    }


def analyze(docs: dict[str, str]) -> Audit:
    audit = Audit(required=chord_skeleton_transfer_required_from_docs(docs), signals=signals_from_docs(docs))
    audit.fields = collect_fields(docs)
    if not audit.required:
        return audit

    required_fields = [
        ("reference_status", "reference_status_missing", "Reference status is missing.", "fill chord-skeleton-transfer.md"),
        ("allowed_action", "allowed_action_missing", "Allowed action is missing.", "fill reference-rights.md"),
        ("forbidden_use", "forbidden_use_missing", "Forbidden use is missing.", "fill reference-rights.md"),
        ("bpm", "bpm_missing", "BPM/tempo is missing.", "fill chord-skeleton-transfer.md"),
        ("key", "key_missing", "Key/mode is missing.", "fill chord-skeleton-transfer.md"),
        ("progression", "progression_missing", "Chord progression is missing.", "fill chord-skeleton-transfer.md"),
        ("harmonic_rhythm", "harmonic_rhythm_missing", "Harmonic rhythm is missing.", "fill chord-skeleton-transfer.md"),
        ("bass_root_direction", "bass_root_direction_missing", "Bass/root direction is missing.", "fill chord-skeleton-transfer.md"),
        ("tool_used", "tool_used_missing", "Analysis/rebuild tool is missing.", "fill chord-skeleton-transfer.md"),
        ("tool_confidence", "tool_confidence_missing", "Tool confidence or manual verification is missing.", "fill chord-skeleton-transfer.md"),
        ("manual_corrections", "manual_corrections_missing", "Manual corrections are missing.", "fill chord-skeleton-transfer.md"),
        ("removed", "midi_removed_missing", "MIDI simplification removed layer is missing.", "fill chord-skeleton-transfer.md"),
        ("extended", "midi_extended_missing", "MIDI simplification extended layer is missing.", "fill chord-skeleton-transfer.md"),
        ("retained", "midi_retained_missing", "MIDI simplification retained layer is missing.", "fill chord-skeleton-transfer.md"),
        ("do_not_copy", "do_not_copy_missing", "Do-not-copy list is missing.", "fill chord-skeleton-transfer.md"),
        ("suno_route", "suno_route_missing", "Suno route is missing.", "fill chord-skeleton-transfer.md"),
        ("style_field", "style_field_missing", "Style field is missing.", "fill style-field-map.md"),
        ("exclude", "exclude_missing", "Exclude field is missing.", "fill exclude-negative-aesthetic.md"),
        ("reverse_analysis_plan", "reverse_analysis_plan_missing", "Reverse analysis plan is missing.", "fill chord-skeleton-transfer.md"),
    ]
    for field, code, message, route in required_fields:
        if not has_value(audit.fields.get(field, "")):
            audit.blockers.append(Finding("blocker", code, message, route))

    route_text = " ".join(
        audit.fields.get(name, "")
        for name in ["reference_status", "allowed_action", "can_upload_audio", "suno_route", "seed_file", "prompt_pairing"]
    )
    if upload_route(route_text):
        if negative_or_unknown(audit.fields.get("reference_status", "")) and not positive(audit.fields.get("can_upload_audio", "")):
            audit.blockers.append(
                Finding(
                    "blocker",
                    "third_party_upload_not_allowed",
                    "Reference route appears third-party/listen-only, but the Suno route uses upload/Cover/MIDI.",
                    "use text-only neutral harmony or provide authorization",
                )
            )
        if not positive(audit.fields.get("can_upload_audio", "")):
            audit.blockers.append(
                Finding(
                    "blocker",
                    "upload_rights_missing",
                    "Upload/Cover route is active but audio upload permission is not clearly approved.",
                    "fill audio-rights-ledger.md and reference-rights.md",
                )
            )
        if not has_value(audit.fields.get("seed_file", "")):
            audit.blockers.append(
                Finding(
                    "blocker",
                    "seed_file_missing",
                    "Upload/Cover route is active but seed audio/MIDI file is not recorded.",
                    "fill audio-rights-ledger.md",
                )
            )
        if not has_value(audit.fields.get("retention_target", "")):
            audit.blockers.append(
                Finding(
                    "blocker",
                    "retention_target_missing",
                    "Upload/Cover route is active but retention target is missing.",
                    "fill retention-target.md",
                )
            )
        if not has_value(audit.fields.get("prompt_pairing", "")):
            audit.blockers.append(
                Finding(
                    "blocker",
                    "prompt_pairing_missing",
                    "Upload/Cover route is active but prompt pairing is missing.",
                    "fill prompt-pairing.md",
                )
            )

    if re.search(r"artist|song title|歌名|艺人|歌手|原曲|爱笑的眼睛", audit.fields.get("style_field", ""), re.I):
        audit.blockers.append(
            Finding(
                "blocker",
                "protected_identity_in_style_field",
                "Style field appears to include protected identity or reference-song language.",
                "neutralize style-field-map.md",
            )
        )
    if not re.search(r"melody|lyrics|riff|voice|sample|旋律|歌词|riff|声线|采样|原曲", audit.fields.get("do_not_copy", ""), re.I):
        audit.warnings.append(
            Finding(
                "warning",
                "do_not_copy_too_thin",
                "Do-not-copy list should explicitly ban melody, lyrics, riff, voice, sample, or original arrangement copying.",
                "expand chord-skeleton-transfer.md",
            )
        )
    if not re.search(r"song master pro|manual|daw|midi|ableton|logic|fl|人工|宿主|复核", audit.fields.get("tool_used", "") + " " + audit.fields.get("manual_corrections", ""), re.I):
        audit.warnings.append(
            Finding(
                "warning",
                "manual_verification_unclear",
                "Tool analysis is recorded, but manual or DAW verification is unclear.",
                "add manual correction notes",
            )
        )

    return audit


def table(findings: list[Finding]) -> str:
    if not findings:
        return "| severity | code | message | route |\n|---|---|---|---|\n| pass | none | no issues | prompt compile |\n"
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    for item in findings:
        rows.append(f"| {item.severity} | {item.code} | {item.message} | {item.route} |")
    return "\n".join(rows) + "\n"


def render(audit: Audit, project_root: Path) -> str:
    fields = audit.fields
    return f"""# Chord Skeleton Transfer Audit

{MARKER}
Project root: {project_root}
Decision: {audit.decision}

Required: {'yes' if audit.required else 'no'}
Signals:
{chr(10).join(f'- {signal}' for signal in audit.signals) if audit.signals else '- none'}

## Chord Skeleton Transfer

Rights route: {fields.get('reference_status', '')}; allowed={fields.get('allowed_action', '')}; upload={fields.get('can_upload_audio', '')}
Skeleton tags: BPM={fields.get('bpm', '')}; Key={fields.get('key', '')}; Progression={fields.get('progression', '')}; Harmonic rhythm={fields.get('harmonic_rhythm', '')}; Bass/root={fields.get('bass_root_direction', '')}
MIDI simplification: removed={fields.get('removed', '')}; extended={fields.get('extended', '')}; retained={fields.get('retained', '')}; do-not-copy={fields.get('do_not_copy', '')}
Suno upload route: route={fields.get('suno_route', '')}; seed={fields.get('seed_file', '')}; retention={fields.get('retention_target', '')}; prompt pairing={fields.get('prompt_pairing', '')}
Reverse analysis plan: {fields.get('reverse_analysis_plan', '')}
Prompt compile handoff: {'pass' if audit.decision in {'pass', 'not applicable'} else 'hold'}

## Field Snapshot

- Source section: {fields.get('source_section', '')}
- Bars: {fields.get('bars', '')}
- Emotional color: {fields.get('emotional_color', '')}
- Tool used: {fields.get('tool_used', '')}
- Tool confidence: {fields.get('tool_confidence', '')}
- Manual corrections: {fields.get('manual_corrections', '')}
- Style field: {fields.get('style_field', '')}
- Exclude: {fields.get('exclude', '')}
- Similarity risk: {fields.get('similarity_risk', '')}

## Findings

{table(audit.blockers + audit.warnings)}
"""


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(f"output exists: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--output", default=OUTPUT)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--allow-overwrite", action="store_true")
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()

    project_root = Path(args.project_root).expanduser().resolve()
    docs = project_docs(project_root)
    audit = analyze(docs)
    text = render(audit, project_root)

    if args.write:
        try:
            write_if_allowed(project_root / args.output, text, args.allow_overwrite)
        except FileExistsError as exc:
            print(str(exc), file=sys.stderr)
            return 1
    else:
        print(text)

    if audit.blockers:
        print("chord skeleton transfer audit has blocker(s):", file=sys.stderr)
        for finding in audit.blockers:
            print(f"- {finding.code}: {finding.message}", file=sys.stderr)
        return 1 if args.strict else 0

    print(f"chord skeleton transfer audit: {audit.decision}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
