#!/usr/bin/env python3
"""Audit groove and instrument-performance evidence before an AI music prompt is compiled."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


PERFORMANCE_FILE = "03_writing/performance-brief.md"
GROOVE_FILE = "03_writing/groove-audit.md"
DRUM_FILE = "03_writing/drum-realism-map.md"
ROLE_FILE = "03_writing/instrument-role-map.md"
SECTION_FILE = "03_writing/section-performance-map.md"
HARMONY_AUDIT_FILE = "03_writing/harmony-bass-audit.md"
BASSLINE_FILE = "03_writing/bassline-map.md"
STYLE_FILE = "04_prompt/style-field-map.md"
PROMPT_BRIEF_FILE = "04_prompt/prompt-compile-brief.md"
SONG_BRIEF_FILE = "01_brief/song-brief.md"
DEFAULT_OUTPUT = "03_writing/groove-humanization-audit.md"

EMPTY_VALUES = {"", '""', "''", "todo", "tbd", "n/a", "na", "none", "yes/no", "-", "--"}
GENERIC_GROOVE = {"humanized", "groovy", "realistic band", "natural drums", "live feel", "good groove"}
AI_GROOVE_RED_FLAGS = (
    "plastic quantized drums",
    "quantized plastic drums",
    "random drum fills",
    "constant eighth-note bass",
    "fake live band",
    "wall of guitars",
    "constant pad",
    "over-busy fills",
)


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    route: str


def read_project(project_root: Path) -> dict[str, str]:
    docs: dict[str, str] = {}
    for path in project_root.rglob("*.md"):
        rel = path.relative_to(project_root).as_posix()
        try:
            docs[rel] = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            docs[rel] = path.read_text(errors="replace")
    return docs


def normalize_value(raw: str) -> str:
    value = raw.strip().strip("`")
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1].strip()
    value = re.sub(r"\s+", " ", value)
    if value.casefold() in EMPTY_VALUES:
        return ""
    if value.startswith("[") and value.endswith("]") and ":" in value:
        return ""
    return value


def scan_key_values(text: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|"):
            continue
        stripped = re.sub(r"^[-*]\s+", "", stripped)
        match = re.match(r"^([^:]{1,95}):\s*(.*)$", stripped)
        if match:
            label = re.sub(r"\s+", " ", match.group(1).strip()).casefold()
            value = normalize_value(match.group(2))
            pairs.append((label, value))
    return pairs


def extract_value(docs: dict[str, str], paths: list[str], labels: list[str]) -> str:
    wanted = {re.sub(r"\s+", " ", label.strip()).casefold() for label in labels}
    for rel in paths:
        for label, value in scan_key_values(docs.get(rel, "")):
            if label in wanted and value:
                return value
    return ""


def harmony_audit_passed(docs: dict[str, str]) -> bool:
    text = docs.get(HARMONY_AUDIT_FILE, "")
    return "Generated by: tools/audit_music_harmony_bass.py" in text and re.search(r"^Decision:\s*pass\b", text, flags=re.I | re.M) is not None


def is_generic(value: str) -> bool:
    compact = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", " ", value.casefold()).strip()
    return compact in GENERIC_GROOVE or any(term in compact for term in GENERIC_GROOVE)


def has_ai_groove_avoid_terms(value: str) -> bool:
    lowered = value.casefold()
    return any(term in lowered for term in AI_GROOVE_RED_FLAGS) or bool(re.search(r"量化|塑料鼓|随机过门|假现场|铺满", value))


def analyze(docs: dict[str, str]) -> tuple[dict[str, str], list[Finding]]:
    paths = [PERFORMANCE_FILE, GROOVE_FILE, DRUM_FILE, ROLE_FILE, SECTION_FILE, BASSLINE_FILE, STYLE_FILE, PROMPT_BRIEF_FILE, SONG_BRIEF_FILE]
    fields = {
        "language": extract_value(docs, paths, ["Language", "Language lane"]),
        "style": extract_value(docs, paths, ["Style", "Genre", "Genre lane"]),
        "tempo_meter": extract_value(docs, paths, ["Tempo / meter", "Tempo", "Meter", "Tempo feel"]),
        "master_pocket": extract_value(docs, paths, ["Master pocket", "Pocket"]),
        "drum_role": extract_value(docs, paths, ["Drum role", "Drums / groove", "Drums", "Groove role"]),
        "bass_role": extract_value(docs, paths, ["Bass role", "Primary bass role", "Bass"]),
        "guitar_role": extract_value(docs, paths, ["Guitar role", "Guitar"]),
        "keys_role": extract_value(docs, paths, ["Keys / synth role", "Keys role", "Synth role", "Keys", "Keyboard role"]),
        "vocal_rhythm_relationship": extract_value(docs, paths, ["Vocal-rhythm relationship", "Vocal rhythm relationship", "Vocal/groove relationship"]),
        "verse_feel": extract_value(docs, paths, ["Verse feel", "Verse 1", "Verse performance"]),
        "pre_feel": extract_value(docs, paths, ["Pre-chorus feel", "Pre feel", "Pre-Chorus"]),
        "chorus_feel": extract_value(docs, paths, ["Chorus feel", "Chorus performance"]),
        "bridge_feel": extract_value(docs, paths, ["Bridge feel", "Bridge performance"]),
        "kick": extract_value(docs, [DRUM_FILE, PERFORMANCE_FILE, GROOVE_FILE], ["Kick"]),
        "snare": extract_value(docs, [DRUM_FILE, PERFORMANCE_FILE, GROOVE_FILE], ["Snare"]),
        "hats_ride": extract_value(docs, [DRUM_FILE, PERFORMANCE_FILE, GROOVE_FILE], ["Hats / ride", "Hi-hat", "Hi-hat / ride", "Hats"]),
        "ghost_notes": extract_value(docs, [DRUM_FILE, PERFORMANCE_FILE, GROOVE_FILE], ["Ghost notes"]),
        "fills": extract_value(docs, [DRUM_FILE, PERFORMANCE_FILE, GROOVE_FILE], ["Fills", "Drum fills"]),
        "cymbals": extract_value(docs, [DRUM_FILE, PERFORMANCE_FILE, GROOVE_FILE], ["Cymbals"]),
        "velocity_shape": extract_value(docs, [DRUM_FILE, GROOVE_FILE, PERFORMANCE_FILE], ["Velocity shape", "Velocity", "Dynamics"]),
        "timing_shape": extract_value(docs, [DRUM_FILE, GROOVE_FILE, PERFORMANCE_FILE], ["Timing shape", "Timing", "Microtiming"]),
        "section_changes": extract_value(docs, [DRUM_FILE, SECTION_FILE, GROOVE_FILE], ["Section changes", "Section interaction"]),
        "bass_kick_relationship": extract_value(docs, [BASSLINE_FILE, PERFORMANCE_FILE, GROOVE_FILE], ["Kick relationship", "Bass/kick relationship"]),
        "bass_articulation": extract_value(docs, [BASSLINE_FILE, GROOVE_FILE, PERFORMANCE_FILE], ["Articulation", "Bass articulation", "Articulation humanization"]),
        "bass_section_variation": extract_value(docs, [BASSLINE_FILE, SECTION_FILE, GROOVE_FILE], ["Section variation", "Bass section variation", "Chorus motion", "Verse motion"]),
        "playability": extract_value(docs, [ROLE_FILE, GROOVE_FILE, PERFORMANCE_FILE], ["Playable", "Playability", "Guitar / keys playability"]),
        "texture_control": extract_value(docs, [ROLE_FILE, GROOVE_FILE, PERFORMANCE_FILE], ["Texture control", "Vocal space", "Vocal-space"]),
        "timing_humanization": extract_value(docs, paths, ["Timing humanization", "Timing shape", "Microtiming"]),
        "velocity_humanization": extract_value(docs, paths, ["Velocity humanization", "Velocity shape", "Velocity"]),
        "articulation_humanization": extract_value(docs, paths, ["Articulation humanization", "Articulation"]),
        "must_not_sound_like": extract_value(docs, paths, ["Must not sound like", "Do not", "Avoid"]),
        "repair_priority": extract_value(docs, paths, ["Repair priority", "Repair"]),
    }
    findings: list[Finding] = []

    required = [
        ("language_missing", fields["language"], "Language is missing; groove rules depend on language and lane.", "repair song brief"),
        ("tempo_meter_missing", fields["tempo_meter"], "Tempo/meter is missing; pocket cannot be judged without it.", "fill performance-brief.md"),
        ("master_pocket_missing", fields["master_pocket"], "Master pocket is missing; state who is ahead/behind/stable.", "fill performance-brief.md"),
        ("drum_role_missing", fields["drum_role"], "Drum role is missing.", "fill performance-brief.md"),
        ("bass_role_missing", fields["bass_role"], "Bass role is missing.", "fill performance-brief.md"),
        ("vocal_rhythm_relationship_missing", fields["vocal_rhythm_relationship"], "Vocal/rhythm relationship is missing.", "fill performance-brief.md"),
        ("verse_feel_missing", fields["verse_feel"], "Verse performance feel is missing.", "fill section-performance-map.md"),
        ("pre_feel_missing", fields["pre_feel"], "Pre-chorus performance feel is missing.", "fill section-performance-map.md"),
        ("chorus_feel_missing", fields["chorus_feel"], "Chorus performance feel is missing.", "fill section-performance-map.md"),
        ("kick_missing", fields["kick"], "Kick role is missing.", "fill drum-realism-map.md"),
        ("snare_missing", fields["snare"], "Snare role is missing.", "fill drum-realism-map.md"),
        ("hats_missing", fields["hats_ride"], "Hi-hat/ride role is missing.", "fill drum-realism-map.md"),
        ("fills_missing", fields["fills"], "Fill strategy is missing; random fills are a common AI-flavor source.", "fill drum-realism-map.md"),
        ("velocity_missing", fields["velocity_shape"], "Velocity shape is missing.", "fill drum-realism-map.md"),
        ("timing_missing", fields["timing_shape"], "Timing/microtiming shape is missing.", "fill drum-realism-map.md"),
        ("bass_kick_missing", fields["bass_kick_relationship"], "Bass/kick relationship is missing.", "fill bassline-map.md"),
        ("bass_articulation_missing", fields["bass_articulation"], "Bass articulation is missing.", "fill bassline-map.md"),
        ("playability_missing", fields["playability"] or fields["guitar_role"] or fields["keys_role"], "Guitar/keys/instrument playability or role is missing.", "fill instrument-role-map.md"),
        ("humanization_missing", fields["timing_humanization"] and fields["velocity_humanization"] and fields["articulation_humanization"], "Controlled humanization needs timing, velocity, and articulation plans.", "fill performance-brief.md"),
        ("avoid_list_missing", fields["must_not_sound_like"], "AI groove red-flag avoid list is missing.", "fill performance-brief.md"),
    ]
    for code, value, message, route in required:
        if not value:
            findings.append(Finding("blocker", code, message, route))

    if not harmony_audit_passed(docs):
        findings.append(Finding("blocker", "harmony_audit_missing", "Groove audit requires a passing harmony/bass audit first.", "run audit_music_harmony_bass.py"))
    if fields["master_pocket"] and is_generic(fields["master_pocket"]):
        findings.append(Finding("warning", "generic_master_pocket", "Master pocket is too generic to be blind-testable.", "write ahead/behind/stable relationships"))
    if fields["drum_role"] and is_generic(fields["drum_role"]):
        findings.append(Finding("warning", "generic_drum_role", "Drum role uses generic realism language instead of kick/snare/hat behavior.", "fill drum-realism-map.md"))
    if fields["must_not_sound_like"] and not has_ai_groove_avoid_terms(fields["must_not_sound_like"]):
        findings.append(Finding("warning", "ai_groove_avoid_terms_missing", "Avoid list should name quantized drums, random fills, fake live band, or constant pad/bass risks.", "add groove Exclude terms"))
    if not fields["section_changes"]:
        findings.append(Finding("warning", "section_changes_missing", "No explicit section interaction/change plan is recorded.", "fill section-performance-map.md"))
    if not fields["bridge_feel"]:
        findings.append(Finding("warning", "bridge_feel_missing", "Bridge performance feel is missing; acceptable only for no-bridge forms.", "fill section-performance-map.md"))

    return fields, findings


def render_finding_table(findings: list[Finding]) -> str:
    if not findings:
        return "| severity | code | message | route |\n|---|---|---|---|\n| pass | none | groove and instrument performance approved | prompt compile |\n"
    rows = ["| severity | code | message | route |", "|---|---|---|---|"]
    for finding in findings:
        rows.append(f"| {finding.severity} | {finding.code} | {finding.message} | {finding.route} |")
    return "\n".join(rows) + "\n"


def groove_tags(fields: dict[str, str]) -> str:
    pieces = [fields["master_pocket"], fields["drum_role"], fields["bass_role"], fields["vocal_rhythm_relationship"], fields["chorus_feel"]]
    text = ", ".join(piece for piece in pieces if piece)
    return text or "NEEDS_REPAIR: groove tags"


def performance_tags(fields: dict[str, str]) -> str:
    pieces = [fields["timing_shape"], fields["velocity_shape"], fields["bass_articulation"], fields["guitar_role"], fields["keys_role"], fields["playability"]]
    text = ", ".join(piece for piece in pieces if piece)
    return text or "NEEDS_REPAIR: instrument performance tags"


def render_audit(project_root: Path, fields: dict[str, str], findings: list[Finding]) -> str:
    blockers = [finding for finding in findings if finding.severity == "blocker"]
    warnings = [finding for finding in findings if finding.severity == "warning"]
    decision = "pass" if not blockers else "repair before prompt compile"
    return f"""# Groove Humanization Audit

Generated by: tools/audit_music_groove_humanization.py
Project root: {project_root}
Decision: {decision}

Language: {fields['language'] or 'NEEDS_REPAIR: language'}
Style: {fields['style'] or 'NEEDS_REPAIR: style'}
Tempo / meter: {fields['tempo_meter'] or 'NEEDS_REPAIR: tempo / meter'}
Master pocket: {fields['master_pocket'] or 'NEEDS_REPAIR: master pocket'}
Drum role: {fields['drum_role'] or 'NEEDS_REPAIR: drum role'}
Bass role: {fields['bass_role'] or 'NEEDS_REPAIR: bass role'}
Guitar role: {fields['guitar_role'] or ''}
Keys / synth role: {fields['keys_role'] or ''}
Vocal-rhythm relationship: {fields['vocal_rhythm_relationship'] or 'NEEDS_REPAIR: vocal-rhythm relationship'}
Timing humanization: {fields['timing_humanization'] or 'NEEDS_REPAIR: timing humanization'}
Velocity humanization: {fields['velocity_humanization'] or 'NEEDS_REPAIR: velocity humanization'}
Articulation humanization: {fields['articulation_humanization'] or 'NEEDS_REPAIR: articulation humanization'}
Must not sound like: {fields['must_not_sound_like'] or 'NEEDS_REPAIR: avoid list'}
Blockers: {len(blockers)}
Warnings: {len(warnings)}

## Groove Design

| field | value |
|---|---|
| verse feel | {fields['verse_feel'] or ''} |
| pre feel | {fields['pre_feel'] or ''} |
| chorus feel | {fields['chorus_feel'] or ''} |
| bridge feel | {fields['bridge_feel'] or ''} |
| kick | {fields['kick'] or ''} |
| snare | {fields['snare'] or ''} |
| hats / ride | {fields['hats_ride'] or ''} |
| ghost notes | {fields['ghost_notes'] or ''} |
| fills | {fields['fills'] or ''} |
| cymbals | {fields['cymbals'] or ''} |
| bass/kick | {fields['bass_kick_relationship'] or ''} |
| bass articulation | {fields['bass_articulation'] or ''} |
| playability | {fields['playability'] or ''} |

## Findings

{render_finding_table(findings)}
## Prompt Routing

Groove tags: {groove_tags(fields)}
Instrument performance tags: {performance_tags(fields)}
Rhythm-section blind test: instrument-only or rhythm-section-only listen for master pocket, drum realism, bass lock, playability, section interaction, and random-fill artifacts
Exclude additions: {fields['must_not_sound_like'] or 'plastic quantized drums, random drum fills, fake live band, constant eighth-note bass, constant pad'}
Repair route: performance brief, drum-realism map, bass articulation, instrument-role map, section-performance map, Studio/stems, or DAW humanization
"""


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root created by create_music_song_project.py.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Relative output path.")
    parser.add_argument("--write", action="store_true", help="Write the audit markdown file.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing audit file.")
    parser.add_argument("--strict", action="store_true", help="Return exit code 1 when blockers remain.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    docs = read_project(project_root)
    fields, findings = analyze(docs)
    audit = render_audit(project_root, fields, findings)
    blockers = [finding for finding in findings if finding.severity == "blocker"]

    if args.write:
        try:
            write_if_allowed(project_root / args.output, audit, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: output exists, use --allow-overwrite: {exc}", file=sys.stderr)
            return 2
    else:
        print(audit)

    if blockers:
        print(f"groove humanization audit has {len(blockers)} blocker(s).", file=sys.stderr)
        for finding in blockers:
            print(f"- {finding.code}: {finding.message} -> {finding.route}", file=sys.stderr)
        return 1 if args.strict else 0

    print("groove humanization audit passed.")
    print(f"audit: {project_root / args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
