#!/usr/bin/env python3
"""Build a safe MIDI chord-skeleton seed for approved Suno reference upload.

The builder deliberately creates only long block chords from a recorded
progression. It never uploads the file, never opens Suno, and never copies
melody, lyrics, riffs, voice, samples, timing performance, or artist identity.
"""

from __future__ import annotations

import argparse
import re
import struct
import sys
from dataclasses import dataclass, field
from pathlib import Path

from audit_music_chord_skeleton_transfer import analyze, project_docs


OUTPUT_MIDI = "02_references/audio/chord-skeleton.mid"
OUTPUT_REPORT = "02_references/chord-skeleton-build-report.md"
MARKER = "Generated by: tools/build_music_chord_skeleton_seed.py"
TICKS_PER_QUARTER = 480
BEATS_PER_BAR = 4

NOTE_TO_SEMITONE = {
    "C": 0,
    "C#": 1,
    "Db": 1,
    "D": 2,
    "D#": 3,
    "Eb": 3,
    "E": 4,
    "F": 5,
    "F#": 6,
    "Gb": 6,
    "G": 7,
    "G#": 8,
    "Ab": 8,
    "A": 9,
    "A#": 10,
    "Bb": 10,
    "B": 11,
}

SEMITONE_TO_NOTE = {
    0: "C",
    1: "Db",
    2: "D",
    3: "Eb",
    4: "E",
    5: "F",
    6: "Gb",
    7: "G",
    8: "Ab",
    9: "A",
    10: "Bb",
    11: "B",
}

ROMAN_MAJOR = {
    "I": 0,
    "II": 2,
    "III": 4,
    "IV": 5,
    "V": 7,
    "VI": 9,
    "VII": 11,
}


@dataclass(frozen=True)
class ChordEvent:
    symbol: str
    notes: list[int]
    duration_ticks: int


@dataclass
class BuildResult:
    decision: str
    project_root: Path
    midi_path: Path
    report_path: Path
    fields: dict[str, str]
    chords: list[ChordEvent] = field(default_factory=list)
    blockers: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return self.decision == "pass"


def normalize_note(note: str) -> str:
    stripped = note.strip().replace("♯", "#").replace("♭", "b")
    if not stripped:
        return stripped
    return stripped[0].upper() + stripped[1:]


def parse_bpm(value: str) -> int | None:
    match = re.search(r"(\d+(?:\.\d+)?)", value or "")
    if not match:
        return None
    bpm = round(float(match.group(1)))
    return bpm if 35 <= bpm <= 240 else None


def parse_key_root(value: str) -> str | None:
    match = re.search(r"\b([A-Ga-g](?:#|b|♯|♭)?)\b", value or "")
    if not match:
        return None
    note = normalize_note(match.group(1))
    return note if note in NOTE_TO_SEMITONE else None


def split_progression(value: str) -> list[str]:
    cleaned = (value or "").replace("–", "-").replace("—", "-").replace("，", ",")
    cleaned = re.sub(r"\([^)]*\)", "", cleaned)
    parts = re.split(r"\s*(?:,|\||\s+/\s+|\s+-\s+|→|->|、)\s*", cleaned)
    return [part.strip() for part in parts if part.strip()]


def roman_to_symbol(symbol: str, key_root: str | None) -> str | None:
    if not key_root:
        return None
    match = re.match(r"^([b#]?)(i{1,3}|iv|v|vi{0,2}|vii)(.*)$", symbol.strip(), re.I)
    if not match:
        return None
    accidental, numeral, suffix = match.groups()
    numeral_upper = numeral.upper()
    if numeral_upper not in ROMAN_MAJOR:
        return None
    semitone = (NOTE_TO_SEMITONE[key_root] + ROMAN_MAJOR[numeral_upper]) % 12
    if accidental == "b":
        semitone = (semitone - 1) % 12
    elif accidental == "#":
        semitone = (semitone + 1) % 12
    note = SEMITONE_TO_NOTE[semitone]
    quality = "m" if numeral.islower() and not suffix.lower().startswith(("maj", "m")) else ""
    return f"{note}{quality}{suffix}"


def chord_intervals(quality: str) -> list[int]:
    suffix = quality.strip()
    lowered = suffix.lower()
    if "dim" in lowered or "°" in suffix:
        intervals = [0, 3, 6]
    elif "aug" in lowered or "+" in suffix:
        intervals = [0, 4, 8]
    elif "sus2" in lowered:
        intervals = [0, 2, 7]
    elif "sus4" in lowered or lowered.startswith("sus"):
        intervals = [0, 5, 7]
    elif re.match(r"^(m|min|-)(?!aj)", lowered):
        intervals = [0, 3, 7]
    else:
        intervals = [0, 4, 7]

    if re.search(r"(maj7|ma7|m7\+|Δ7|Δ)", suffix, re.I):
        intervals.append(11)
    elif "7" in suffix:
        intervals.append(10)
    elif "6" in suffix:
        intervals.append(9)
    if re.search(r"add\s*9|add9", suffix, re.I):
        intervals.append(14)
    return sorted(set(intervals))


def symbol_to_notes(symbol: str, key_root: str | None) -> ChordEvent | None:
    candidate = symbol.strip()
    converted = roman_to_symbol(candidate, key_root)
    if converted:
        candidate = converted
    match = re.match(r"^([A-Ga-g](?:#|b|♯|♭)?)([^/\s]*)", candidate)
    if not match:
        return None
    root_name = normalize_note(match.group(1))
    if root_name not in NOTE_TO_SEMITONE:
        return None
    suffix = match.group(2) or ""
    root_midi = 48 + NOTE_TO_SEMITONE[root_name]
    notes = [root_midi + interval for interval in chord_intervals(suffix)]
    duration = TICKS_PER_QUARTER * BEATS_PER_BAR
    return ChordEvent(symbol=symbol, notes=notes, duration_ticks=duration)


def encode_varlen(value: int) -> bytes:
    buffer = value & 0x7F
    value >>= 7
    while value:
        buffer <<= 8
        buffer |= (value & 0x7F) | 0x80
        value >>= 7
    data = bytearray()
    while True:
        data.append(buffer & 0xFF)
        if buffer & 0x80:
            buffer >>= 8
        else:
            break
    return bytes(data)


def midi_track(chords: list[ChordEvent], bpm: int) -> bytes:
    events = bytearray()
    tempo = int(60_000_000 / bpm)
    events += b"\x00\xff\x51\x03" + tempo.to_bytes(3, "big")
    events += b"\x00\xff\x58\x04\x04\x02\x18\x08"
    events += b"\x00\xc0\x04"
    for chord in chords:
        for note in chord.notes:
            events += b"\x00" + bytes([0x90, note, 64])
        for index, note in enumerate(chord.notes):
            delta = chord.duration_ticks if index == 0 else 0
            events += encode_varlen(delta) + bytes([0x80, note, 0])
    events += b"\x00\xff\x2f\x00"
    return b"MTrk" + struct.pack(">I", len(events)) + bytes(events)


def write_midi(path: Path, chords: list[ChordEvent], bpm: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = b"MThd" + struct.pack(">IHHH", 6, 0, 1, TICKS_PER_QUARTER)
    path.write_bytes(header + midi_track(chords, bpm))


def safety_boundary_present(text: str) -> bool:
    return all(re.search(term, text, re.I) for term in ["melody|旋律", "lyrics|歌词", "riff", "voice|声线|人声", "sample|采样"])


def build(project_root: Path, midi_output: str = OUTPUT_MIDI, report_output: str = OUTPUT_REPORT) -> BuildResult:
    docs = project_docs(project_root)
    audit = analyze(docs)
    fields = audit.fields
    midi_path = project_root / midi_output
    report_path = project_root / report_output
    result = BuildResult(
        decision="hold",
        project_root=project_root,
        midi_path=midi_path,
        report_path=report_path,
        fields=fields,
    )

    if not audit.required:
        result.decision = "not applicable"
        result.warnings.append("Chord skeleton route is not active; no MIDI seed was built.")
        return result

    for finding in audit.blockers:
        result.blockers.append(f"{finding.code}: {finding.message}")
    for finding in audit.warnings:
        result.warnings.append(f"{finding.code}: {finding.message}")

    bpm = parse_bpm(fields.get("bpm", ""))
    key_root = parse_key_root(fields.get("key", ""))
    if bpm is None:
        result.blockers.append("bpm_invalid: BPM must be a clear number between 35 and 240.")
    if key_root is None:
        result.blockers.append("key_invalid: Key must include a parseable note name.")
    if not safety_boundary_present(fields.get("do_not_copy", "")):
        result.blockers.append("copy_boundary_incomplete: Do-not-copy must ban melody, lyrics, riff, voice, and sample copying.")

    chord_symbols = split_progression(fields.get("progression", ""))
    if not chord_symbols:
        result.blockers.append("progression_invalid: Chord progression is empty.")
    else:
        for symbol in chord_symbols:
            chord = symbol_to_notes(symbol, key_root)
            if chord is None:
                result.blockers.append(f"chord_unparseable: {symbol}")
            else:
                result.chords.append(chord)

    if result.blockers:
        result.decision = "hold"
        return result

    result.decision = "pass"
    return result


def findings_table(items: list[str], severity: str) -> str:
    if not items:
        return f"| {severity} | none | no issues |\n"
    rows = []
    for item in items:
        code, _, message = item.partition(":")
        rows.append(f"| {severity} | {code.strip()} | {message.strip() or item} |")
    return "\n".join(rows) + "\n"


def render(result: BuildResult) -> str:
    fields = result.fields
    chord_rows = ["| index | symbol | MIDI notes | duration |", "|---:|---|---|---|"]
    for index, chord in enumerate(result.chords, start=1):
        chord_rows.append(f"| {index} | {chord.symbol} | {' '.join(str(note) for note in chord.notes)} | 1 bar block chord |")
    if not result.chords:
        chord_rows.append("| - | none | none | none |")

    return f"""# Chord Skeleton MIDI Seed Build Report

{MARKER}
Project root: {result.project_root}
Decision: {result.decision}

MIDI file: {result.midi_path if result.passed else 'not written'}
Suno action: not opened; not uploaded; awaiting explicit upload confirmation

## Rights And Boundary

Rights route: {fields.get('reference_status', '')}
Allowed action: {fields.get('allowed_action', '')}
Can upload audio: {fields.get('can_upload_audio', '')}
Commercial use: {fields.get('commercial_use', '')}
Do-not-copy: {fields.get('do_not_copy', '')}

## Skeleton Spec

- BPM: {fields.get('bpm', '')}
- Key: {fields.get('key', '')}
- Progression: {fields.get('progression', '')}
- Harmonic rhythm: {fields.get('harmonic_rhythm', '')}
- Bass/root direction: {fields.get('bass_root_direction', '')}
- Source section: {fields.get('source_section', '')}
- Tool used: {fields.get('tool_used', '')}
- Manual corrections: {fields.get('manual_corrections', '')}

## Builder Boundary

- Generates long block chords only.
- Does not generate melody, topline, lyric rhythm, riff contour, voice, sample, drum groove, or arrangement timing.
- Does not include artist name, song title, protected identity, or reference singer imitation.
- Keeps upload as a separate human-confirmed sensitive action.

## Chord Events

{chr(10).join(chord_rows)}

## Findings

| severity | code | message |
|---|---|---|
{findings_table(result.blockers, 'blocker')}{findings_table(result.warnings, 'warning')}"""


def write_report(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(f"output exists: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--output-midi", default=OUTPUT_MIDI)
    parser.add_argument("--output-report", default=OUTPUT_REPORT)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--allow-overwrite", action="store_true")
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()

    project_root = Path(args.project_root).expanduser().resolve()
    result = build(project_root, args.output_midi, args.output_report)
    report = render(result)

    if args.write:
        try:
            write_report(result.report_path, report, args.allow_overwrite)
            if result.passed:
                if result.midi_path.exists() and not args.allow_overwrite:
                    raise FileExistsError(f"output exists: {result.midi_path}")
                bpm = parse_bpm(result.fields.get("bpm", "")) or 90
                write_midi(result.midi_path, result.chords, bpm)
        except FileExistsError as exc:
            print(str(exc), file=sys.stderr)
            return 1
    else:
        print(report)

    if result.blockers:
        print("chord skeleton MIDI seed build has blocker(s):", file=sys.stderr)
        for blocker in result.blockers:
            print(f"- {blocker}", file=sys.stderr)
        return 1 if args.strict else 0
    if result.decision == "not applicable":
        print("chord skeleton MIDI seed build: not applicable")
        return 1 if args.strict else 0

    print(f"chord skeleton MIDI seed build: {result.decision}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
