#!/usr/bin/env python3
"""Plan the simplest effective Suno generation route.

This is the product-facing entry point for the local AI music system. It hides
low-level gates behind one route decision: ordinary text generation, approved
reference upload generation, or a safe listen-only fallback.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from audit_music_chord_skeleton_transfer import (
    OUTPUT as CHORD_SKELETON_AUDIT,
    chord_skeleton_transfer_audit_ready_from_docs,
    chord_skeleton_transfer_required_from_docs,
    collect_fields,
    negative_or_unknown,
    positive,
    project_docs,
    signals_from_docs,
    upload_route,
)


OUTPUT = "00_admin/generation-route-plan.md"
MARKER = "Generated by: tools/plan_music_generation_route.py"


REFERENCE_PATTERNS = [
    r"reference|参考|对标|像.*感觉|保留.*感觉|按.*生成|曲风",
    r"audio upload|cover|uploaded audio|audio influence|上传|上传参考曲|上传音频|音频种子",
    r"chord skeleton|chord progression|midi|和弦骨架|和弦进行|导出\s*MIDI|BPM|Key",
]

RIGHTS_SAFE_PATTERN = r"self-owned|authorized|licensed|original|own|自有|原创|已授权|明确授权|授权可用|可上传|允许上传"
RIGHTS_UNSAFE_PATTERN = r"third-party|listen-only|unlicensed|not allowed|released song|商业发行曲|第三方|仅听辨|未授权|没有授权|无授权|不能上传"


@dataclass
class RoutePlan:
    decision: str
    operating_mode: str
    confidence: str
    primary_route: str
    fallback_route: str
    effect_lever: str
    user_effort: str
    risk_level: str
    next_action: str
    approval_phrase: str = "none"
    signals: list[str] = field(default_factory=list)
    missing: list[str] = field(default_factory=list)
    questions: list[str] = field(default_factory=list)
    commands: list[str] = field(default_factory=list)
    fields: dict[str, str] = field(default_factory=dict)


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def brief_signals(brief: str) -> list[str]:
    signals: list[str] = []
    for pattern in REFERENCE_PATTERNS:
        if re.search(pattern, brief, re.I):
            signals.append(f"brief: {pattern}")
    return signals


def value(fields: dict[str, str], name: str) -> str:
    return normalize(fields.get(name, ""))


def rights_is_safe(fields: dict[str, str], brief: str) -> bool:
    status_text = " ".join(
        [
            value(fields, "reference_status"),
            value(fields, "can_upload_audio"),
            value(fields, "commercial_use"),
            brief,
        ]
    )
    upload_permission = value(fields, "can_upload_audio")
    if re.search(RIGHTS_UNSAFE_PATTERN, status_text, re.I) and not re.search(RIGHTS_SAFE_PATTERN, status_text, re.I):
        return False
    return positive(upload_permission) or bool(re.search(RIGHTS_SAFE_PATTERN, status_text, re.I))


def rights_is_unsafe(fields: dict[str, str], brief: str) -> bool:
    text = " ".join(
        [
            value(fields, "reference_status"),
            value(fields, "allowed_action"),
            value(fields, "forbidden_use"),
            value(fields, "can_upload_audio"),
            brief,
        ]
    )
    return negative_or_unknown(text) or bool(re.search(RIGHTS_UNSAFE_PATTERN, text, re.I))


def wants_reference_upload(fields: dict[str, str], brief: str) -> bool:
    text = " ".join(
        [
            value(fields, "allowed_action"),
            value(fields, "suno_route"),
            value(fields, "seed_file"),
            value(fields, "prompt_pairing"),
            brief,
        ]
    )
    return upload_route(text)


def missing_reference_fields(fields: dict[str, str], needs_upload: bool) -> list[str]:
    base = [
        ("reference_status", "Reference status"),
        ("allowed_action", "Allowed action"),
        ("forbidden_use", "Forbidden use / do-not-copy"),
        ("bpm", "BPM"),
        ("key", "Key"),
        ("progression", "Chord progression"),
        ("harmonic_rhythm", "Harmonic rhythm"),
        ("bass_root_direction", "Bass/root direction"),
        ("removed", "MIDI removed layer"),
        ("extended", "MIDI extended layer"),
        ("retained", "MIDI retained layer"),
        ("do_not_copy", "Do-not-copy list"),
        ("suno_route", "Suno route"),
        ("style_field", "Style field"),
        ("exclude", "Exclude field"),
        ("retention_target", "Retention target"),
        ("prompt_pairing", "Prompt pairing"),
        ("reverse_analysis_plan", "Reverse analysis plan"),
    ]
    if needs_upload:
        base.extend(
            [
                ("can_upload_audio", "Can upload audio"),
                ("seed_file", "Upload seed file"),
            ]
        )
    return [label for key, label in base if not value(fields, key)]


def limit_questions(questions: list[str]) -> list[str]:
    result: list[str] = []
    for question in questions:
        if question not in result:
            result.append(question)
        if len(result) == 3:
            break
    return result


def plan(project_root: Path | None, brief: str) -> RoutePlan:
    docs = project_docs(project_root) if project_root else {}
    fields = collect_fields(docs) if docs else {}
    doc_signals = signals_from_docs(docs) if docs else []
    signals = doc_signals + brief_signals(brief)
    chord_required = chord_skeleton_transfer_required_from_docs(docs) if docs else bool(signals)
    chord_ready = chord_skeleton_transfer_audit_ready_from_docs(docs) if docs else False
    upload_requested = wants_reference_upload(fields, brief)
    safe_rights = rights_is_safe(fields, brief)
    unsafe_rights = rights_is_unsafe(fields, brief)
    has_reference_intent = bool(signals or upload_requested or chord_required)

    commands: list[str] = []
    if project_root:
        commands.append(f"python3 tools/plan_music_generation_route.py --project-root \"{project_root}\" --write --allow-overwrite")

    if not has_reference_intent:
        return RoutePlan(
            decision="ordinary_generation",
            operating_mode="quick_idea_or_professional_project",
            confidence="high" if brief or docs else "medium",
            primary_route="text-only Suno Custom Mode prompt package",
            fallback_route="escalate to project mode only if this becomes release/client/catalog work",
            effect_lever="lyrics, genre lane, hook, arrangement density, exclude field, and batch iteration",
            user_effort="low: answer up to three creative questions, then approve a generation card",
            risk_level="low",
            next_action="draft ordinary Generation Confirmation Card and compile a prompt package if project mode is needed",
            signals=signals,
            fields=fields,
            commands=commands,
        )

    if upload_requested and unsafe_rights and not safe_rights:
        return RoutePlan(
            decision="blocked_reference_upload_use_listen_only_dna",
            operating_mode="reference_upload_request_redirected_to_safe_text_generation",
            confidence="high",
            primary_route="do not upload; translate the reference into neutral style/harmony DNA and generate text-only candidates",
            fallback_route="use Audio Upload/Cover only after the user supplies self-owned or explicitly authorized seed evidence",
            effect_lever="preserve abstract BPM/key/harmonic mood and production direction without copying the source recording",
            user_effort="low: confirm the target feeling and approve a text-only generation card",
            risk_level="high if uploaded; low after listen-only fallback",
            next_action="produce a safe reference-DNA prompt and ask whether to proceed with ordinary generation",
            approval_phrase="确认生成",
            signals=signals,
            missing=missing_reference_fields(fields, True),
            questions=limit_questions(
                [
                    "这个参考音频或 MIDI 是否是你自有/原创/已授权可上传到 Suno？",
                    "目标是保留和弦情绪，还是只保留整体曲风/制作感觉？",
                    "如果没有授权，是否改走普通 text-only 生成并只使用中性 DNA？",
                ]
            ),
            commands=commands,
            fields=fields,
        )

    if upload_requested or chord_required:
        missing = missing_reference_fields(fields, upload_requested)
        if project_root:
            commands.append(
                f"python3 tools/audit_music_chord_skeleton_transfer.py --project-root \"{project_root}\" --write --allow-overwrite --strict"
            )
            commands.append(
                f"python3 tools/compile_music_prompt_package.py --project-root \"{project_root}\" --write --allow-overwrite --strict"
            )
        if missing or (project_root and not chord_ready):
            return RoutePlan(
                decision="reference_upload_generation_needs_evidence",
                operating_mode="reference_upload",
                confidence="medium",
                primary_route="fill the minimum reference-upload evidence, then use Audio Upload/Cover only if the audit passes",
                fallback_route="generate an ordinary text-only baseline immediately while the reference evidence is being prepared",
                effect_lever="BPM/key/progression retention can improve emotional grounding, but only after skeleton and rights are clear",
                user_effort="medium: fill missing reference fields once, then reuse the route card",
                risk_level="medium until rights and skeleton audit pass",
                next_action="fill chord-skeleton-transfer.md and run the chord skeleton audit before any upload",
                approval_phrase="确认上传并生成 after the audit passes",
                signals=signals,
                missing=missing,
                questions=limit_questions(
                    [
                        "上传 seed 是自有/原创/已授权的吗？",
                        "你希望保留 BPM/Key/Chord Progression，还是只保留情绪底色？",
                        "这次要先生成普通 baseline，还是先补齐参考上传证据？",
                    ]
                ),
                commands=commands,
                fields=fields,
            )
        return RoutePlan(
            decision="reference_upload_generation_ready",
            operating_mode="reference_upload",
            confidence="high",
            primary_route="approved Audio Upload/Cover seed plus structured Style field and post-generation reverse analysis",
            fallback_route="run one ordinary text-only baseline in parallel if speed or comparison matters",
            effect_lever="highest leverage is controlled harmonic/emotional grounding through a safe chord skeleton seed",
            user_effort="low after setup: review the upload confirmation card and explicitly approve",
            risk_level="controlled",
            next_action="show Reference Upload Confirmation Card; proceed only after explicit approval",
            approval_phrase="确认上传并生成",
            signals=signals,
            commands=commands,
            fields=fields,
        )

    return RoutePlan(
        decision="ordinary_generation_with_reference_dna",
        operating_mode="guided_creation",
        confidence="medium",
        primary_route="text-only prompt using neutral reference DNA",
        fallback_route="escalate to reference_upload only if the user owns or authorizes a seed",
        effect_lever="use reference-derived tempo, groove, harmony color, instrumentation, and mood as prompt constraints",
        user_effort="low",
        risk_level="low",
        next_action="draft a generation card with neutralized reference DNA and no upload action",
        approval_phrase="确认生成",
        signals=signals,
        fields=fields,
        commands=commands,
    )


def render_reference_snapshot(fields: dict[str, str]) -> str:
    keys = [
        ("Reference status", "reference_status"),
        ("Upload permission", "can_upload_audio"),
        ("Suno route", "suno_route"),
        ("Seed file", "seed_file"),
        ("BPM", "bpm"),
        ("Key", "key"),
        ("Progression", "progression"),
        ("Do-not-copy", "do_not_copy"),
        ("Retention target", "retention_target"),
    ]
    rows = []
    for label, key in keys:
        rows.append(f"- {label}: {value(fields, key) or 'missing'}")
    return "\n".join(rows)


def render(plan_result: RoutePlan, project_root: Path | None, brief: str) -> str:
    missing = "\n".join(f"- {item}" for item in plan_result.missing) if plan_result.missing else "- none"
    questions = "\n".join(f"- {item}" for item in plan_result.questions) if plan_result.questions else "- none"
    signals = "\n".join(f"- {item}" for item in plan_result.signals) if plan_result.signals else "- none"
    commands = "\n".join(f"```bash\n{command}\n```" for command in plan_result.commands) if plan_result.commands else "_No command required yet._"
    upload_action = "none"
    if plan_result.decision == "reference_upload_generation_ready":
        upload_action = "upload self-owned/authorized seed after approval"
    elif plan_result.decision == "reference_upload_generation_needs_evidence":
        upload_action = "hold until evidence passes"
    elif plan_result.decision == "blocked_reference_upload_use_listen_only_dna":
        upload_action = "blocked; use text-only fallback"

    return f"""# Suno Generation Route Plan

{MARKER}
Project root: {project_root or 'none'}
Decision: {plan_result.decision}
Operating mode: {plan_result.operating_mode}
Confidence: {plan_result.confidence}

## First-Principles Decision

- User outcome: make a better song with less expression cost, fewer blind generations, and lower rights/account risk.
- Primary route: {plan_result.primary_route}
- Fallback route: {plan_result.fallback_route}
- Effect lever: {plan_result.effect_lever}
- User effort: {plan_result.user_effort}
- Risk level: {plan_result.risk_level}
- Next action: {plan_result.next_action}

## Signals

{signals}

## Reference Snapshot

{render_reference_snapshot(plan_result.fields)}

## Missing Inputs

{missing}

## AI Should Ask At Most These Questions

{questions}

## User-Facing Confirmation Card

- Mode: {plan_result.operating_mode}
- Decision: {plan_result.decision}
- Upload action expected: {upload_action}
- Approval phrase required: {plan_result.approval_phrase}
- Credits/account action expected: no generate/create click before approval
- Effect-first check: compare against brief alignment, hook memory, vocal realism, groove, and similarity risk

## Recommended Commands

{commands}

## Brief

{brief or '_No free-text brief supplied._'}

## Chord Skeleton Audit

- Audit file: {CHORD_SKELETON_AUDIT}
- Required before upload: {'yes' if plan_result.decision.startswith('reference_upload') else 'no'}
"""


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(f"output exists: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", help="Optional song project root.")
    parser.add_argument("--brief", default="", help="Free-text user brief or request.")
    parser.add_argument("--brief-file", help="Path to a text/markdown brief file.")
    parser.add_argument("--output", default=OUTPUT, help="Output path relative to project root when --write is used.")
    parser.add_argument("--write", action="store_true", help="Write the route plan into the project.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting the output file.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve() if args.project_root else None
    if project_root and not project_root.exists():
        print(f"error: project root does not exist: {project_root}", file=sys.stderr)
        return 2
    brief = args.brief
    if args.brief_file:
        brief_path = Path(args.brief_file).expanduser().resolve()
        if not brief_path.exists():
            print(f"error: brief file does not exist: {brief_path}", file=sys.stderr)
            return 2
        brief = "\n".join(part for part in [brief, read_text(brief_path)] if part)

    if not project_root and not brief:
        print("error: provide --project-root and/or --brief", file=sys.stderr)
        return 2

    route_plan = plan(project_root, brief)
    text = render(route_plan, project_root, brief)
    if args.write:
        if not project_root:
            print("error: --write requires --project-root", file=sys.stderr)
            return 2
        try:
            write_if_allowed(project_root / args.output, text, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        print(f"wrote {(project_root / args.output).relative_to(project_root).as_posix()}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
