#!/usr/bin/env python3
"""Prepare an effect-first Suno run without touching Suno or Chrome.

This tool is the local orchestration layer described in the effect-first plan.
It turns a user brief and optional project evidence into:

- a route decision
- a Suno-ready prompt draft
- a prompt-linter report
- neutral reference DNA
- a generation confirmation card
- a take-review / next-variable recommendation
- lightweight user-preference notes

It is deliberately offline. It never opens Chrome, uploads audio, clicks
Generate, spends credits, publishes, downloads, or calls unofficial Suno APIs.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from plan_music_generation_route import RoutePlan, plan as plan_generation_route


OUTPUT = "00_admin/effect-first-suno-run.md"
PROMPT_OUTPUT = "04_prompt/effect-first-prompt-package.md"
LINTER_OUTPUT = "04_prompt/prompt-linter-report.md"
REFERENCE_DNA_OUTPUT = "02_references/reference-dna-card.md"
TAKE_REVIEW_OUTPUT = "06_review/effect-first-take-review.md"
PREFERENCE_OUTPUT = "12_catalog-memory/user-preference-profile.md"
MARKER = "Generated by: tools/prepare_music_effect_first_suno_run.py"

DATA_MODELS = ["SongRun", "RoutePlan", "PromptVersion", "Batch", "Take", "UserPreference"]
MAIN_STATE_MACHINE = [
    "new_request",
    "route_planned",
    "intake_ready",
    "prompt_ready",
    "awaiting_user_confirmation",
    "approved",
    "generating",
    "generated",
    "reviewed",
    "iterate_or_finish",
]
REFERENCE_UPLOAD_STATE_MACHINE = [
    "reference_requested",
    "rights_unknown",
    "upload_blocked_or_allowed",
    "skeleton_prepared",
    "audit_passed",
    "awaiting_upload_confirmation",
    "uploaded",
    "generated",
    "reverse_analyzed",
    "reviewed",
]
BLOCKER_STATES = [
    "blocked_login",
    "blocked_captcha",
    "blocked_credit",
    "blocked_payment",
    "blocked_rights",
    "blocked_upload_permission",
    "blocked_ui_unknown",
    "blocked_prompt_lint",
    "blocked_user_confirmation",
]
GENERATION_EXECUTOR_STATES = [
    "generated",
    "blocked_login",
    "blocked_captcha",
    "blocked_credit",
    "blocked_payment",
    "blocked_terms",
    "blocked_ui_unknown",
    "failed_timeout",
    "failed_network",
    "user_cancelled",
]
TAKE_REVIEW_FIELDS = [
    "first_20s",
    "hook_memory",
    "vocal_identity",
    "lyrics_intelligibility",
    "groove",
    "chorus_lift",
    "arrangement",
    "ai_artifacts",
    "fit_to_brief",
    "similarity_risk",
    "user_preference",
    "next_action",
]
USER_PREFERENCE_FIELDS = [
    "default_language",
    "default_use_case",
    "default_batch_size",
    "preferred_genres",
    "preferred_vocals",
    "avoid_styles",
    "default_exclude",
    "rights_default",
    "project_mode_default",
    "successful_patterns",
    "rejected_patterns",
]
PROMPT_LINTER_CODES = [
    "style_too_generic",
    "genre_soup",
    "artist_name_risk",
    "voice_imitation_risk",
    "exclude_conflict",
    "lyrics_too_short",
    "lyrics_too_dense",
    "missing_hook",
    "missing_vocal_identity",
    "missing_production_detail",
    "section_tag_overload",
    "reference_identity_leak",
    "slider_conflict",
]
SENSITIVE_ACTIONS = [
    "open Chrome",
    "navigate to Suno",
    "log in",
    "upload audio",
    "click Generate/Create/Cover",
    "spend credits",
    "publish",
    "download",
    "share",
    "use unofficial Suno APIs/cookies/tokens/CAPTCHA bypass",
]


@dataclass(frozen=True)
class PromptPackage:
    title: str
    creative_brief: str
    lyrics: str
    style: str
    exclude: str
    model_settings: str
    batch_plan: str
    review_rubric: str
    changed_variable: str


@dataclass(frozen=True)
class ReferenceDNA:
    tempo: str
    key_or_mode: str
    harmonic_color: str
    groove: str
    instrumentation: str
    production_texture: str
    vocal_register: str
    energy_curve: str
    do_not_copy: str
    similarity_risk: str


@dataclass(frozen=True)
class LintIssue:
    code: str
    severity: str
    message: str
    suggested_fix: str


@dataclass(frozen=True)
class TakeReview:
    fields: dict[str, str]
    next_changed_variable: str


@dataclass(frozen=True)
class UserPreferenceProfile:
    fields: dict[str, str]


@dataclass(frozen=True)
class EffectFirstRun:
    route: RoutePlan
    prompt: PromptPackage
    reference_dna: ReferenceDNA
    lint_issues: list[LintIssue]
    take_review: TakeReview
    preference: UserPreferenceProfile
    brief: str
    feedback: str

    @property
    def lint_decision(self) -> str:
        if any(issue.severity == "blocker" for issue in self.lint_issues):
            return "blocker"
        if any(issue.severity == "warning" for issue in self.lint_issues):
            return "warning"
        return "pass"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def has_cjk(text: str) -> bool:
    return bool(re.search(r"[\u4e00-\u9fff]", text))


def detect_language(brief: str) -> str:
    if re.search(r"English|英文|英语", brief, re.I):
        return "en"
    if re.search(r"Japanese|日文|日语", brief, re.I):
        return "ja"
    if re.search(r"Korean|韩文|韩语", brief, re.I):
        return "ko"
    return "zh" if has_cjk(brief) else "en"


def infer_title_phrase(brief: str) -> str:
    quoted = re.search(r"[「\"']([^「」\"']{2,24})[」\"']", brief)
    if quoted:
        return quoted.group(1).strip()
    title_match = re.search(r"(?:标题|title|歌名)[:：]\s*([^\n,，。；;]{2,24})", brief, re.I)
    if title_match:
        return title_match.group(1).strip()
    if "夜" in brief or "晚" in brief:
        return "把夜晚放轻"
    if "雨" in brief:
        return "雨停以前"
    if "开车" in brief or "drive" in brief.lower():
        return "夜路慢慢亮"
    if "demo" in brief.lower() or "灵感" in brief:
        return "先让它发光"
    return "还没说完的话" if has_cjk(brief) else "Signal In The Dark"


def infer_use_case(brief: str) -> str:
    lowered = brief.lower()
    if any(term in brief for term in ["发行", "正式", "单曲", "平台"]):
        return "release candidate"
    if any(term in brief for term in ["客户", "广告", "商业", "品牌"]):
        return "client / commercial draft"
    if any(term in brief for term in ["视频", "短剧", "vlog", "BGM"]):
        return "video / content soundtrack"
    if "demo" in lowered or "草稿" in brief:
        return "demo"
    return "demo"


def infer_genre(brief: str) -> str:
    lowered = brief.lower()
    if "city pop" in lowered or "城市" in brief:
        return "Mandarin late-night city pop"
    if "r&b" in lowered or "rnb" in lowered:
        return "Mandarin R&B ballad"
    if "rock" in lowered or "摇滚" in brief:
        return "Mandarin pop rock"
    if "edm" in lowered or "电子" in brief:
        return "melodic electronic pop"
    if "民谣" in brief or "folk" in lowered:
        return "intimate cyber-folk"
    if "lo-fi" in lowered or "lofi" in lowered:
        return "lo-fi indie pop"
    return "Mandarin emotional pop"


def infer_vocal(brief: str) -> str:
    if "女" in brief or "female" in brief.lower():
        return "intimate clear female vocal, controlled breath, natural diction"
    if "男" in brief or "male" in brief.lower():
        return "restrained warm male vocal, close-mic presence, natural diction"
    if "合唱" in brief or "duet" in brief.lower():
        return "lead vocal with subtle harmony doubles, natural human phrasing"
    return "clear intimate lead vocal, natural human phrasing, no impersonation"


def infer_instrumentation(brief: str) -> str:
    items: list[str] = []
    mapping = [
        ("钢琴", "electric piano"),
        ("piano", "electric piano"),
        ("吉他", "clean electric guitar"),
        ("guitar", "clean electric guitar"),
        ("贝斯", "warm melodic bass"),
        ("bass", "warm melodic bass"),
        ("鼓", "restrained live-feel drums"),
        ("drum", "restrained live-feel drums"),
        ("合成器", "soft analog synth pad"),
        ("synth", "soft analog synth pad"),
        ("弦乐", "subtle string pad"),
        ("strings", "subtle string pad"),
    ]
    for needle, instrument in mapping:
        if needle in brief.lower() and instrument not in items:
            items.append(instrument)
    if not items:
        items = ["electric piano", "clean guitar", "warm bass", "restrained drums"]
    return ", ".join(items)


def infer_production(brief: str) -> str:
    if any(term in brief for term in ["夜", "晚", "雨", "孤独"]):
        return "warm analog texture, close dry verse, wider chorus, short plate reverb"
    if any(term in brief for term in ["科技", "赛博", "cyber", "future"]):
        return "clean modern mix, granular ambient detail, tight low end, controlled stereo width"
    return "warm balanced mix, clear vocal foreground, tasteful dynamics, no muddy low end"


def infer_mood(brief: str) -> str:
    if any(term in brief for term in ["伤感", "遗憾", "失恋", "melanch"]):
        return "melancholic but hopeful, emotionally restrained, not melodramatic"
    if any(term in brief for term in ["开心", "轻松", "明亮", "happy"]):
        return "bright, relaxed, lightly uplifting"
    if any(term in brief for term in ["孤独", "夜", "雨"]):
        return "lonely, late-night, warm afterglow"
    return "emotionally specific, memorable, human, not generic"


def build_reference_dna(brief: str, route: RoutePlan) -> ReferenceDNA:
    bpm = re.search(r"\b(\d{2,3})\s*(?:bpm|BPM)?\b", brief)
    tempo = f"{bpm.group(1)} BPM target" if bpm else ("72-96 BPM slow-mid emotional range" if any(term in brief for term in ["伤感", "夜", "雨"]) else "92-118 BPM flexible pop range")
    key_match = re.search(r"\b(Key|key|调性)[:：]?\s*([A-G][b#]?m?|[A-G][b#]?\s*(?:minor|major)|[\u4e00-\u9fff]{1,3}调)\b", brief)
    key_or_mode = key_match.group(2) if key_match else "minor-leaning or modal color, keep adaptable unless user specifies key"
    harmonic = "safe neutral harmonic color; preserve emotional function, not source melody"
    if route.decision.startswith("reference_upload"):
        harmonic = "BPM/key/progression/root-motion retention only after self-owned or authorized seed evidence"
    if route.decision == "blocked_reference_upload_use_listen_only_dna":
        harmonic = "listen-only harmony impression; no upload, no extracted MIDI, no reconstructed third-party skeleton"
    return ReferenceDNA(
        tempo=tempo,
        key_or_mode=key_or_mode,
        harmonic_color=harmonic,
        groove="human pocket, clear downbeat, no mechanical loop feel",
        instrumentation=infer_instrumentation(brief),
        production_texture=infer_production(brief),
        vocal_register=infer_vocal(brief),
        energy_curve="first 20 seconds must establish identity; chorus should lift without overstuffing arrangement",
        do_not_copy="no artist name, song title, melody, lyrics, riff, vocal identity, sample, stem, or signature arrangement",
        similarity_risk="high if uploaded without rights; controlled when reduced to neutral DNA and reviewed against brief",
    )


def build_lyrics(title: str, brief: str, language: str) -> str:
    if language == "en":
        return f"""[Verse 1]
I leave the window half awake
Streetlights move like quiet waves
Your name is only in the air
I do not chase it anywhere

[Pre-Chorus]
If the night asks what I keep
I keep the part that learned to breathe

[Chorus]
{title}
I let the dark turn into sound
{title}
I am still here, still coming around

[Bridge]
Nothing breaks the way it used to
Nothing shines without a scar

[Final Chorus]
{title}
I let the last light lead me home
{title}
I am not lonely when I sing it alone
"""
    return f"""[Verse 1]
路灯把影子拉得很长
我把没说的话放进车窗
城市在后视镜里慢慢退让
心事不再急着找人原谅

[Pre-Chorus]
如果夜色问我还留下些什么
我只留下能继续呼吸的部分

[Chorus]
{title}
让风替我轻轻唱
{title}
难过也可以不声张
{title}
等天边一点点发亮
我就把遗憾放回路旁

[Bridge]
不是所有离开都要回头
不是所有沉默都是认输

[Final Chorus]
{title}
让风替我轻轻唱
{title}
我还在慢慢变得晴朗
"""


def build_prompt_package(brief: str, route: RoutePlan, reference_dna: ReferenceDNA) -> PromptPackage:
    language = detect_language(brief)
    title = infer_title_phrase(brief)
    lyrics = build_lyrics(title, brief, language)
    style = (
        f"genre: {infer_genre(brief)}; "
        f"vocal: {infer_vocal(brief)}; "
        f"instrumentation: {infer_instrumentation(brief)}; "
        f"production: {infer_production(brief)}; "
        f"mood: {infer_mood(brief)}"
    )
    if route.decision in {"ordinary_generation_with_reference_dna", "blocked_reference_upload_use_listen_only_dna"}:
        style += f"; reference DNA: {reference_dna.tempo}, {reference_dna.harmonic_color}, {reference_dna.energy_curve}"
    if route.decision.startswith("reference_upload"):
        style += "; uploaded seed target: retain authorized harmonic grounding while creating new topline and arrangement"
    exclude = (
        "robotic vocal, muddy mix, harsh sibilance, abrupt ending, random rap verse, "
        "artist imitation, copied melody, copied lyrics, recognizable riff, reference singer voice, overcompressed chorus"
    )
    changed_variable = "initial_prompt"
    if route.decision.startswith("reference_upload"):
        changed_variable = "audio_seed_or_chord_skeleton"
    elif "人声" in brief or "vocal" in brief.lower():
        changed_variable = "vocal_identity"
    elif "副歌" in brief or "chorus" in brief.lower():
        changed_variable = "structure_energy"
    return PromptPackage(
        title=title,
        creative_brief=f"{infer_use_case(brief)} / {route.decision}: {normalize(brief)}",
        lyrics=lyrics,
        style=style,
        exclude=exclude,
        model_settings="Model: current best visible Suno model; Custom Mode: on; Batch: 2; Weirdness: 30-45; Style Influence: 60-80; Audio Influence: 0 unless approved self-owned/authorized seed is active",
        batch_plan="Generate 2 candidates with one primary variable held accountable; do not broaden rewrite after approval.",
        review_rubric="first_20s, hook_memory, vocal_identity, lyrics_intelligibility, groove, chorus_lift, arrangement, ai_artifacts, fit_to_brief, similarity_risk, user_preference, next_action",
        changed_variable=changed_variable,
    )


def style_segments(style: str) -> dict[str, str]:
    segments: dict[str, str] = {}
    for part in style.split(";"):
        if ":" not in part:
            continue
        key, value = part.split(":", 1)
        segments[key.strip().casefold()] = value.strip()
    return segments


def lint_prompt(prompt: PromptPackage, route: RoutePlan) -> list[LintIssue]:
    issues: list[LintIssue] = []
    style_lower = prompt.style.casefold()
    lyrics_lower = prompt.lyrics.casefold()
    exclude_lower = prompt.exclude.casefold()
    segments = style_segments(prompt.style)
    required_segments = ["genre", "vocal", "instrumentation", "production", "mood"]
    missing_segments = [segment for segment in required_segments if segment not in segments or len(segments[segment]) < 8]
    if missing_segments:
        issues.append(LintIssue("style_too_generic", "blocker", f"Style is missing specific five-part segment(s): {', '.join(missing_segments)}.", "Use genre + vocal + instrumentation + production + mood."))
    generic_terms = re.findall(r"\b(good|nice|beautiful|emotional|vibe|catchy|pop)\b", style_lower)
    if len(generic_terms) >= 4:
        issues.append(LintIssue("style_too_generic", "warning", "Style relies on generic descriptors without enough audible detail.", "Replace vague adjectives with audible instruments, production texture, groove, and vocal behavior."))
    genre_terms = re.findall(r"\b(pop|rock|r&b|edm|folk|trap|hip hop|city pop|lo-fi|jazz|metal|punk|country|reggae)\b", style_lower)
    if len(set(genre_terms)) > 4:
        issues.append(LintIssue("genre_soup", "warning", "Too many genre labels may cause drift.", "Pick one primary lane and one secondary color."))
    if re.search(r"in the style of|像.*(周杰伦|林俊杰|Taylor|Adele|Billie|Eason|陈奕迅|王菲)|周杰伦|林俊杰|Taylor Swift|Adele|Billie Eilish|陈奕迅|王菲", prompt.style, re.I):
        issues.append(LintIssue("artist_name_risk", "blocker", "Style appears to include artist or protected identity language.", "Convert the reference into neutral style DNA."))
    if re.search(r"(模仿|克隆|copy|imitate).*(声线|声音|voice|vocal)|reference singer voice", prompt.style, re.I):
        issues.append(LintIssue("voice_imitation_risk", "blocker", "Prompt appears to ask for voice imitation.", "Describe vocal register and performance, not a specific person's voice."))
    for term in ["piano", "guitar", "bass", "drums", "synth", "rap", "钢琴", "吉他", "贝斯", "鼓", "合成器"]:
        if term in style_lower and term in exclude_lower:
            issues.append(LintIssue("exclude_conflict", "blocker", f"Exclude conflicts with required style term: {term}.", "Remove the conflict or rewrite the style requirement."))
            break
    lyric_lines = [line for line in prompt.lyrics.splitlines() if line.strip() and not line.strip().startswith("[")]
    if len(lyric_lines) < 8:
        issues.append(LintIssue("lyrics_too_short", "blocker", "Lyrics are too short for a full vocal generation.", "Add verse, chorus, and a final payoff."))
    dense_lines = [line for line in lyric_lines if len(line) > 48]
    if len(dense_lines) >= 3:
        issues.append(LintIssue("lyrics_too_dense", "warning", "Several lyric lines are too dense for natural singing.", "Shorten long lines or split phrases."))
    if prompt.title.casefold() not in lyrics_lower and prompt.title not in prompt.lyrics:
        issues.append(LintIssue("missing_hook", "warning", "Title phrase does not appear in the lyrics.", "Place the title phrase in the chorus hook."))
    if "vocal:" not in style_lower:
        issues.append(LintIssue("missing_vocal_identity", "blocker", "Style lacks an explicit vocal identity segment.", "Add vocal register, diction, breath, and performance behavior."))
    if "production:" not in style_lower:
        issues.append(LintIssue("missing_production_detail", "blocker", "Style lacks production detail.", "Add mix texture, space, width, dynamics, or specific sonic handling."))
    if len(re.findall(r"^\[[^\]]+\]", prompt.lyrics, re.M)) > 9:
        issues.append(LintIssue("section_tag_overload", "warning", "Too many section tags can overconstrain Suno.", "Keep essential sections and let arrangement breathe."))
    if route.decision == "blocked_reference_upload_use_listen_only_dna" and re.search(r"song title|artist|reference singer|原曲|歌手|歌名", prompt.style, re.I):
        issues.append(LintIssue("reference_identity_leak", "blocker", "Unsafe reference identity leaked into style prompt.", "Use only neutral DNA fields."))
    if route.decision.startswith("ordinary") and re.search(r"Audio Influence:\s*[1-9]", prompt.model_settings, re.I):
        issues.append(LintIssue("slider_conflict", "warning", "Ordinary generation should not use nonzero Audio Influence.", "Keep Audio Influence at 0 unless a seed route is approved."))
    return issues


def feedback_to_variable(feedback: str) -> str:
    text = feedback.casefold()
    routes = [
        (r"人声|声线|vocal|voice|唱", "vocal_identity"),
        (r"副歌|chorus|hook|钩子|记不住", "topline_or_chorus_lift"),
        (r"歌词|lyric|词|空泛|cliche", "lyrics_context"),
        (r"律动|groove|节奏|鼓|贝斯|bass|drum", "groove"),
        (r"结构|转场|bridge|verse|pre-chorus|intro|outro", "structure"),
        (r"混音|糊|刺耳|sibilance|mix|muddy", "production_or_exclude"),
        (r"像|太像|reference|参考|相似", "reference_distance"),
    ]
    for pattern, variable in routes:
        if re.search(pattern, text, re.I):
            return variable
    return "style_specificity"


def build_take_review(feedback: str, route: RoutePlan) -> TakeReview:
    next_variable = feedback_to_variable(feedback or route.next_action)
    fields = {
        "first_20s": "must establish title, singer identity, and arrangement world quickly",
        "hook_memory": "review whether the chorus title phrase is remembered after one listen",
        "vocal_identity": "specific human-feeling register and diction, no anonymous AI voice",
        "lyrics_intelligibility": "lines should be singable and emotionally concrete",
        "groove": "pocket should feel played, not mechanically looped",
        "chorus_lift": "chorus should open energy without overstuffing",
        "arrangement": "instrument roles should leave vocal space",
        "ai_artifacts": "watch robotic vibrato, mushy consonants, abrupt endings, muddy low end",
        "fit_to_brief": "score against the brief, not against cloning a reference",
        "similarity_risk": "low for ordinary text-only; actively check if reference DNA or upload route is used",
        "user_preference": "record what the user actually likes, not just what aligns technically",
        "next_action": f"change one primary variable next: {next_variable}",
    }
    return TakeReview(fields=fields, next_changed_variable=next_variable)


def build_preference_profile(brief: str, feedback: str) -> UserPreferenceProfile:
    language = detect_language(brief)
    fields = {
        "default_language": f"{language} (provisional unless user confirms stable default)",
        "default_use_case": infer_use_case(brief),
        "default_batch_size": "2",
        "preferred_genres": infer_genre(brief),
        "preferred_vocals": infer_vocal(brief),
        "avoid_styles": "random rap verse, robotic vocal, muddy mix, harsh sibilance, abrupt ending",
        "default_exclude": "robotic vocal, muddy mix, harsh sibilance, abrupt ending, random rap verse",
        "rights_default": "noncommercial demo unless the user states release/client use",
        "project_mode_default": "quick_idea unless release/client/catalog/rights-sensitive intent appears",
        "successful_patterns": "record only after user selects a take or repeats preference across sessions",
        "rejected_patterns": normalize(feedback) if feedback else "record only after user explicitly rejects a take or pattern",
    }
    return UserPreferenceProfile(fields=fields)


def build_effect_first_run(project_root: Path | None, brief: str, feedback: str) -> EffectFirstRun:
    route = plan_generation_route(project_root, brief)
    reference_dna = build_reference_dna(brief, route)
    prompt = build_prompt_package(brief, route, reference_dna)
    lint_issues = lint_prompt(prompt, route)
    take_review = build_take_review(feedback, route)
    preference = build_preference_profile(brief, feedback)
    return EffectFirstRun(route=route, prompt=prompt, reference_dna=reference_dna, lint_issues=lint_issues, take_review=take_review, preference=preference, brief=brief, feedback=feedback)


def finding_table(issues: list[LintIssue]) -> str:
    rows = ["| code | severity | message | suggested fix |", "|---|---|---|---|"]
    if not issues:
        rows.append("| none | pass | no linter issues | proceed to confirmation card |")
        return "\n".join(rows)
    for issue in issues:
        rows.append(f"| {issue.code} | {issue.severity} | {issue.message} | {issue.suggested_fix} |")
    return "\n".join(rows)


def dict_lines(items: dict[str, str]) -> str:
    return "\n".join(f"- {key}: {value}" for key, value in items.items())


def render_reference_dna(dna: ReferenceDNA) -> str:
    return f"""# Reference DNA Card

{MARKER}

- tempo: {dna.tempo}
- key_or_mode: {dna.key_or_mode}
- harmonic_color: {dna.harmonic_color}
- groove: {dna.groove}
- instrumentation: {dna.instrumentation}
- production_texture: {dna.production_texture}
- vocal_register: {dna.vocal_register}
- energy_curve: {dna.energy_curve}
- do_not_copy: {dna.do_not_copy}
- similarity_risk: {dna.similarity_risk}
"""


def render_prompt_package(run: EffectFirstRun) -> str:
    prompt = run.prompt
    return f"""# Effect-First Suno Prompt Package

{MARKER}
Decision: {'hold' if run.lint_decision == 'blocker' else 'ready for confirmation'}

## PromptVersion

- Title: {prompt.title}
- Creative brief: {prompt.creative_brief}
- Changed variable: {prompt.changed_variable}

## Lyrics

{prompt.lyrics}

## Style of Music

{prompt.style}

## Exclude Styles

{prompt.exclude}

## Model / Slider Intent

{prompt.model_settings}

## Batch Plan

{prompt.batch_plan}

## Review Rubric

{prompt.review_rubric}
"""


def render_linter(run: EffectFirstRun) -> str:
    return f"""# Prompt Linter Report

{MARKER}
Decision: {run.lint_decision}

Required checks: {', '.join(PROMPT_LINTER_CODES)}

## Findings

{finding_table(run.lint_issues)}
"""


def render_take_review(run: EffectFirstRun) -> str:
    return f"""# Effect-First Take Review

{MARKER}
Next changed variable: {run.take_review.next_changed_variable}

## Take Review Fields

{dict_lines(run.take_review.fields)}
"""


def render_preference(profile: UserPreferenceProfile) -> str:
    return f"""# User Preference Profile

{MARKER}

## Fields

{dict_lines(profile.fields)}

## Rule

Do not promote one-off feedback into permanent memory. Stable preferences require explicit user confirmation or repeated evidence across sessions.
"""


def render_main(run: EffectFirstRun, project_root: Path | None) -> str:
    route = run.route
    upload_action = "none"
    if route.decision == "reference_upload_generation_ready":
        upload_action = "upload self-owned/authorized seed only after explicit confirmation"
    elif route.decision == "reference_upload_generation_needs_evidence":
        upload_action = "hold before upload until rights/skeleton evidence passes"
    elif route.decision == "blocked_reference_upload_use_listen_only_dna":
        upload_action = "blocked; use listen-only DNA text route"
    approval_phrase = route.approval_phrase if route.approval_phrase != "none" else "确认生成"
    return f"""# Effect-First Suno Run

{MARKER}
Project root: {project_root or 'none'}

## SongRun

- Route decision: {route.decision}
- Operating mode: {route.operating_mode}
- Confidence: {route.confidence}
- Primary route: {route.primary_route}
- Fallback route: {route.fallback_route}
- Effect lever: {route.effect_lever}
- User effort: {route.user_effort}
- Risk level: {route.risk_level}
- Next action: {route.next_action}

## Route Card

- Decision: {route.decision}
- Why: {route.effect_lever}
- Upload action: {upload_action}
- User questions: {', '.join(route.questions) if route.questions else 'none'}
- Missing inputs: {', '.join(route.missing) if route.missing else 'none'}

## Generation Confirmation Card

- Title: {run.prompt.title}
- Use case: {infer_use_case(run.brief)}
- Language: {detect_language(run.brief)}
- Mode: {route.operating_mode}
- Model/settings: {run.prompt.model_settings}
- Batch count: 2
- Changed variable: {run.prompt.changed_variable}
- Style of Music: {run.prompt.style}
- Exclude: {run.prompt.exclude}
- Lyric summary: title hook `{run.prompt.title}` with verse/pre/chorus/bridge/final chorus payoff
- Expected Chrome/Suno action: none until user approval; fill fields and generate only after confirmation
- Credits/account action expected: no spend before approval
- Upload action expected: {upload_action}
- Approval phrase required: {approval_phrase}

## Prompt Linter

- Decision: {run.lint_decision}
- Checks: {', '.join(PROMPT_LINTER_CODES)}

## Reference DNA

- tempo: {run.reference_dna.tempo}
- key_or_mode: {run.reference_dna.key_or_mode}
- harmonic_color: {run.reference_dna.harmonic_color}
- groove: {run.reference_dna.groove}
- instrumentation: {run.reference_dna.instrumentation}
- production_texture: {run.reference_dna.production_texture}
- vocal_register: {run.reference_dna.vocal_register}
- energy_curve: {run.reference_dna.energy_curve}
- do_not_copy: {run.reference_dna.do_not_copy}
- similarity_risk: {run.reference_dna.similarity_risk}

## Generation Executor Contract

- Page object: SunoCreatePage.open, ensure_logged_in, enter_custom_mode, set_title, set_lyrics, set_style, set_exclude, set_model, set_sliders, upload_audio_seed, click_generate, wait_for_results, collect_take_metadata
- States: {', '.join(GENERATION_EXECUTOR_STATES)}
- Forbidden offline actions: {', '.join(SENSITIVE_ACTIONS)}

## Data Models

{', '.join(DATA_MODELS)}

## Main State Machine

{' -> '.join(MAIN_STATE_MACHINE)}

## Reference Upload State Machine

{' -> '.join(REFERENCE_UPLOAD_STATE_MACHINE)}

## Blocker States

{', '.join(BLOCKER_STATES)}

## Take Review

{dict_lines(run.take_review.fields)}

## User Preference Profile

{dict_lines(run.preference.fields)}
"""


def write_if_allowed(path: Path, text: str, allow_overwrite: bool) -> None:
    if path.exists() and not allow_overwrite:
        raise FileExistsError(f"output exists: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def outputs(run: EffectFirstRun, project_root: Path | None) -> dict[str, str]:
    return {
        OUTPUT: render_main(run, project_root),
        PROMPT_OUTPUT: render_prompt_package(run),
        LINTER_OUTPUT: render_linter(run),
        REFERENCE_DNA_OUTPUT: render_reference_dna(run.reference_dna),
        TAKE_REVIEW_OUTPUT: render_take_review(run),
        PREFERENCE_OUTPUT: render_preference(run.preference),
    }


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", help="Optional song project root.")
    parser.add_argument("--brief", default="", help="User brief.")
    parser.add_argument("--brief-file", help="Read additional brief text from a file.")
    parser.add_argument("--feedback", default="", help="Optional take feedback to map to the next variable.")
    parser.add_argument("--write", action="store_true", help="Write effect-first files into the project.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting output files.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve() if args.project_root else None
    if project_root and not project_root.exists():
        print(f"error: project root does not exist: {project_root}", file=sys.stderr)
        return 2
    brief = args.brief
    if args.brief_file:
        brief_path = Path(args.brief_file).expanduser().resolve()
        if not brief_path.exists():
            print(f"error: brief file does not exist: {brief_path}", file=sys.stderr)
            return 2
        brief = "\n".join(part for part in [brief, read_text(brief_path)] if part)
    if project_root and not brief:
        brief = "\n".join(
            read_text(project_root / rel)
            for rel in ["01_brief/song-brief.md", "01_brief/project-intake.md", "00_admin/generation-route-plan.md"]
            if (project_root / rel).exists()
        )
    if not brief:
        print("error: provide --brief, --brief-file, or a project with brief files", file=sys.stderr)
        return 2
    run = build_effect_first_run(project_root, brief, args.feedback)
    rendered = outputs(run, project_root)
    if args.write:
        if not project_root:
            print("error: --write requires --project-root", file=sys.stderr)
            return 2
        try:
            for rel, text in rendered.items():
                write_if_allowed(project_root / rel, text, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        for rel in rendered:
            print(f"wrote {rel}")
    else:
        print(rendered[OUTPUT])
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
