#!/usr/bin/env python3
"""Prepare a release audio QC report from mastering evidence.

This tool does not replace a mastering engineer or critical listening. It
checks that the release candidate has a technical inspection plus documented
loudness, codec, translation, mono/phase/low-end, and limiter/transient review
before writing the final release-audio-qc-report.md gate.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


OUTPUT = "10_mix-master/release-audio-qc-report.md"
AUDIO_INSPECTION_MARKER = "Generated by: tools/inspect_music_release_audio.py"
AUDIO_INSPECTION_METRICS = [
    "duration",
    "sample rate",
    "bit depth",
    "channels",
    "peak",
    "rms",
    "dc offset",
    "clipped ratio",
]

APPROVAL_RE = re.compile(r"\b(pass|passed|approved|approve|clear|cleared|ok|ready|complete|completed)\b|通过|批准|清楚|完成", re.I)
BLOCKING_RE = re.compile(
    r"\b(todo|tbd|pending|unknown|unresolved|unclear|missing|fail(?:ed)?|hold|blocked|red flag|clipping worsened|worse|distorted)\b"
    r"|待定|未知|未解决|不清楚|缺失|失败|不通过|暂停|阻塞|红灯|红旗",
    re.I,
)
CLEARING_RE = re.compile(r"\b(no|none|0|zero|resolved|clear|cleared|pass|passed|approved|ok|low|n/a|not applicable)\b|无|否|已解决|通过|清楚|低风险", re.I)
EMPTY_FIELD_RE = re.compile(r"^\s*(?:[-*]\s*)?[^:#|`][^:]{1,78}:\s*$")


@dataclass(frozen=True)
class QCEvidenceSpec:
    label: str
    path: str
    required_terms: tuple[str, ...]


@dataclass
class QCEvidenceResult:
    spec: QCEvidenceSpec
    exists: bool = False
    decision: str = "missing"
    blocking_lines: list[str] = field(default_factory=list)
    empty_fields: list[str] = field(default_factory=list)
    missing_terms: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.exists and self.approved and not self.blocking_lines and not self.empty_fields and not self.missing_terms

    @property
    def approved(self) -> bool:
        return bool(APPROVAL_RE.search(self.decision))

    @property
    def status(self) -> str:
        if not self.exists:
            return "missing"
        return "pass" if self.ok else "hold"


QC_SPECS = [
    QCEvidenceSpec("loudness true peak report", "10_mix-master/loudness-true-peak-report.md", ("integrated lufs", "lra", "true peak")),
    QCEvidenceSpec("codec preview", "10_mix-master/codec-preview.md", ("codec", "preview")),
    QCEvidenceSpec("translation listen matrix", "10_mix-master/translation-listen-matrix.md", ("translation", "matrix")),
    QCEvidenceSpec("mono phase low-end check", "10_mix-master/mono-phase-low-end-check.md", ("mono", "phase", "low end")),
    QCEvidenceSpec("transient and limiter audit", "10_mix-master/transient-and-limiter-audit.md", ("transient", "limiter", "over-limiting")),
]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def field_value(text: str, labels: list[str]) -> str:
    wanted = {label.lower() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,80}):\s*(.*)$", stripped)
        if not match:
            continue
        label = match.group(1).strip().lower()
        value = match.group(2).strip().strip('"')
        if label in wanted and value:
            return value
    return ""


def line_is_blocking(line: str) -> bool:
    text = line.strip()
    if not text or text.startswith("#"):
        return False
    if not BLOCKING_RE.search(text):
        return False
    return not CLEARING_RE.search(text)


def empty_evidence_fields(text: str) -> list[str]:
    fields: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|") or stripped.startswith("```"):
            continue
        if EMPTY_FIELD_RE.match(stripped):
            fields.append(stripped)
    return fields[:8]


def audio_technical_ready(text: str) -> tuple[bool, list[str]]:
    blockers: list[str] = []
    decision = field_value(text, ["Decision"])
    if AUDIO_INSPECTION_MARKER not in text:
        blockers.append("release audio technical inspection must be generated by tools/inspect_music_release_audio.py")
    if not decision or not re.search(r"^(pass|approved|approve)\b", decision.strip(), re.I):
        blockers.append("release audio technical inspection needs Decision: pass")
    lowered = text.lower()
    if "## results" not in lowered:
        blockers.append("release audio technical inspection must include Results")
    missing_metrics = [metric for metric in AUDIO_INSPECTION_METRICS if metric not in lowered]
    if missing_metrics:
        blockers.append("release audio technical inspection missing metrics: " + ", ".join(missing_metrics[:4]))
    table_rows = [line.strip() for line in text.splitlines() if line.strip().startswith("|")]
    data_rows = [
        row
        for row in table_rows
        if row.count("|") >= 10 and not re.search(r"^\|\s*-", row) and "sample rate" not in row.lower()
    ]
    if not any(re.search(r"\|\s*pass\s*\|\s*$", row, re.I) for row in data_rows):
        blockers.append("release audio technical inspection needs one passing inspected audio row")
    return not blockers, blockers[:8]


def evaluate_qc_evidence(project_root: Path, spec: QCEvidenceSpec) -> QCEvidenceResult:
    path = project_root / spec.path
    text = read_text(path)
    result = QCEvidenceResult(spec=spec, exists=bool(text), decision=field_value(text, ["Decision", "Status"]) or "missing")
    if not text:
        return result
    lowered = text.lower()
    result.missing_terms = [term for term in spec.required_terms if term not in lowered]
    result.empty_fields = empty_evidence_fields(text)
    result.blocking_lines = [line.strip() for line in text.splitlines() if line_is_blocking(line)][:8]
    return result


def evaluate_project(project_root: Path) -> tuple[bool, list[str], list[QCEvidenceResult]]:
    errors: list[str] = []
    technical_text = read_text(project_root / "10_mix-master/release-audio-technical-inspection.md")
    if not technical_text:
        errors.append("missing 10_mix-master/release-audio-technical-inspection.md")
    else:
        technical_ok, technical_blockers = audio_technical_ready(technical_text)
        if not technical_ok:
            errors.extend(technical_blockers)

    results = [evaluate_qc_evidence(project_root, spec) for spec in QC_SPECS]
    for item in results:
        if not item.exists:
            errors.append(f"missing {item.spec.path}")
            continue
        if not item.approved:
            errors.append(f"{item.spec.path} needs Decision: pass")
        if item.empty_fields:
            errors.append(f"{item.spec.path} has unresolved empty fields: {', '.join(item.empty_fields[:3])}")
        if item.missing_terms:
            errors.append(f"{item.spec.path} missing terms: {', '.join(item.missing_terms[:3])}")
        if item.blocking_lines:
            errors.append(f"{item.spec.path} has blocking evidence: {item.blocking_lines[0]}")
    return not errors, errors[:12], results


def source_value(project_root: Path, rel: str, labels: list[str], fallback: str = "source evidence reviewed") -> str:
    value = field_value(read_text(project_root / rel), labels)
    return value or fallback


def evidence_rows(results: list[QCEvidenceResult]) -> str:
    rows = ["| evidence | file | status | decision | missing terms | blockers |", "|---|---|---|---|---|---|"]
    for item in results:
        rows.append(
            f"| {item.spec.label} | {item.spec.path} | {item.status} | {item.decision} | "
            f"{', '.join(item.missing_terms[:3])} | {'; '.join(item.blocking_lines[:2])} |"
        )
    return "\n".join(rows)


def render_report(project_root: Path, passed: bool, errors: list[str], results: list[QCEvidenceResult]) -> str:
    decision = "pass" if passed else "hold"
    loudness = "10_mix-master/loudness-true-peak-report.md"
    codec = "10_mix-master/codec-preview.md"
    translation = "10_mix-master/translation-listen-matrix.md"
    mono = "10_mix-master/mono-phase-low-end-check.md"
    limiter = "10_mix-master/transient-and-limiter-audit.md"
    return f"""# Release Audio QC Report

Generated by: tools/prepare_music_release_audio_qc.py
Project root: {project_root}
Decision: {decision}

This report is a release audio QC evidence gate. It summarizes technical
inspection, loudness / True Peak, codec preview, translation listening,
mono/phase/low-end, and transient/limiter evidence. It is not legal advice and
does not replace final human listening.

## Required Evidence

{evidence_rows(results)}

## Measurements

- integrated LUFS: {source_value(project_root, loudness, ["Integrated LUFS", "LUFS"])}
- LRA: {source_value(project_root, loudness, ["LRA", "Loudness Range"])}
- True Peak: {source_value(project_root, loudness, ["True Peak", "TP"])}
- clipped samples: {source_value(project_root, loudness, ["Clipped samples", "Clipping"])}
- sample rate: {source_value(project_root, "10_mix-master/release-audio-technical-inspection.md", ["sample rate"])}
- bit depth: {source_value(project_root, "10_mix-master/release-audio-technical-inspection.md", ["bit depth"])}

## Listening

- loudness-matched reference A/B: {source_value(project_root, loudness, ["Loudness-matched reference A/B", "Reference A/B"])}
- codec preview: {source_value(project_root, codec, ["Codec preview", "Decision"])}
- translation matrix: {source_value(project_root, translation, ["Translation matrix", "Decision"])}
- mono/phase: {source_value(project_root, mono, ["Mono/phase", "Mono phase", "Phase"])}
- low end: {source_value(project_root, mono, ["Low end", "Low-end"])}
- intro/outro: {source_value(project_root, translation, ["Intro/outro", "Head/tail"])}

## AI Artifact Check

- vocal tail: {source_value(project_root, limiter, ["Vocal tail"])}
- cymbals: {source_value(project_root, limiter, ["Cymbals"])}
- backing vocal smear: {source_value(project_root, limiter, ["Backing vocal smear"])}
- stem bleed: {source_value(project_root, limiter, ["Stem bleed"])}
- over-limiting: {source_value(project_root, limiter, ["Over-limiting", "Limiter"])}

## Deliverable

- approved file: {source_value(project_root, "10_mix-master/release-audio-technical-inspection.md", ["file"], "see release candidate audio")}
- rejected files: {source_value(project_root, translation, ["Rejected files"], "none")}
- platform notes: {source_value(project_root, codec, ["Platform notes"], "codec and platform previews passed")}

## Blocking Items

{chr(10).join(f"- {error}" for error in errors) if errors else "- none"}

## Next Action

{"Proceed to release-candidate gate." if passed else "Repair mix/master/QC evidence, then rerun this tool with --strict."}
"""


def write_report(project_root: Path, text: str, allow_overwrite: bool) -> Path:
    path = project_root / OUTPUT
    if path.exists() and not allow_overwrite:
        raise FileExistsError(f"refusing to overwrite existing file: {OUTPUT}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--write", action="store_true", help="Write release-audio-qc-report.md.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting release-audio-qc-report.md.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero when QC evidence is incomplete.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists():
        print(f"error: project root does not exist: {project_root}", file=sys.stderr)
        return 2
    passed, errors, results = evaluate_project(project_root)
    report = render_report(project_root, passed, errors, results)
    if args.write:
        try:
            written = write_report(project_root, report, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        print(f"wrote {written.relative_to(project_root).as_posix()}")
    else:
        print("release audio QC report")
        print(f"decision: {'pass' if passed else 'hold'}")
        for error in errors:
            print(f"- {error}")
    if errors and args.strict:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
