#!/usr/bin/env python3
"""Prepare catalog memory writeback files for an AI music song project.

This tool closes the loop after a song has gone through take selection, repair
routing, and release-candidate review. It does not judge audio directly. It
turns existing project evidence into reusable catalog, prompt, artifact,
sonic-signature, lyric-universe, reference-boundary, and next-song notes.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from audit_music_audio_seed_retention import (
    OUTPUT as AUDIO_SEED_AUDIT,
    audio_seed_audit_ready,
    audio_seed_required,
)
from audit_music_release_listener_evidence import (
    OUTPUT as RELEASE_LISTENER_AUDIT,
    release_listener_audit_ready,
)
from audit_music_prompt_iteration_discipline import (
    OUTPUT as PROMPT_ITERATION_DISCIPLINE_AUDIT,
    prompt_iteration_discipline_audit_ready,
)
from audit_music_post_production_mix_lock import (
    OUTPUT as POST_PRODUCTION_MIX_LOCK_AUDIT,
    post_production_mix_lock_audit_ready,
)
from review_music_takes import parse_markdown_tables


CORE_EVIDENCE = [
    "04_prompt/prompt-package-v001.md",
    "04_prompt/prompt-preflight-review.md",
    PROMPT_ITERATION_DISCIPLINE_AUDIT,
    "05_generations/take-ledger.md",
    "05_generations/generation-evidence-audit.md",
    "06_review/take-selection-decision.md",
    "07_repair/repair-route-map.md",
    POST_PRODUCTION_MIX_LOCK_AUDIT,
    "10_mix-master/release-audio-technical-inspection.md",
    "10_mix-master/release-audio-qc-report.md",
    RELEASE_LISTENER_AUDIT,
    "11_release/release-candidate-evidence-audit.md",
    "11_release/release-candidate-rights-gate.md",
    "11_release/release-candidate-package.md",
    "11_release/release_candidate/metadata/release-candidate-manifest.md",
]

SUPPORTING_EVIDENCE = [
    "06_review/blind-review.md",
    "06_review/external-listener-panel.md",
    "06_review/ai-flavor-red-flag-survey.md",
    "08_stems-daw/session-pack.md",
    "08_stems-daw/final-humanized-master-review.md",
]

OUTPUTS = {
    "catalog": "12_catalog-memory/catalog-memory-update.md",
    "prompt": "12_catalog-memory/prompt-memory-update.md",
    "artifact": "12_catalog-memory/artifact-memory-update.md",
    "sonic": "12_catalog-memory/sonic-signature-update.md",
    "lyric": "12_catalog-memory/lyric-universe-update.md",
    "reference": "12_catalog-memory/reference-boundary-update.md",
    "postmortem": "12_catalog-memory/postmortem-and-prompt-memory.md",
    "next_song": "12_catalog-memory/next-song-brief-seed.md",
    "manifest": "12_catalog-memory/catalog-writeback-manifest.md",
}

PROMPT_COMPILER_MARKER = "Generated by: tools/compile_music_prompt_package.py"
PROMPT_PACKAGE_REQUIRED_TERMS = [
    "## metadata",
    "## style of music",
    "## lyrics",
    "## prompt rationale",
    "## preflight summary",
    "model:",
    "weirdness:",
    "style influence:",
    "methodology transfer:",
    "prompt specificity:",
    "lyric narrative:",
    "reference audit:",
    "prosody audit:",
    "topline audit:",
    "harmony/bass audit:",
    "groove audit:",
    "structure audit:",
    "vocal audit:",
    "human anchor lane:",
    "voice identity source:",
    "persona source:",
    "custom model source:",
    "custom model corpus:",
    "my taste state:",
    "prompt boost state:",
    "exclude:",
    "genre:",
    "vocal:",
    "instrumentation:",
    "production:",
    "mood:",
]
PROMPT_PREFLIGHT_REQUIRED_TERMS = [
    "field completeness:",
    "lyrics context:",
    "methodology transfer:",
    "prompt specificity:",
    "lyric narrative:",
    "reference audit:",
    "prosody audit:",
    "topline audit:",
    "harmony/bass audit:",
    "groove audit:",
    "structure audit:",
    "vocal audit:",
    "exclude rationale:",
    "slider intent:",
    "model/version:",
    "human anchor lane:",
    "identity routing:",
    "my taste / boost:",
    "identity / rights:",
    "conflict check:",
    "blockers:",
    "## issues",
]
AUDIO_INSPECTION_MARKER = "Generated by: tools/inspect_music_release_audio.py"
RELEASE_AUDIO_QC_MARKER = "Generated by: tools/prepare_music_release_audio_qc.py"
AUDIO_INSPECTION_METRICS = [
    "duration",
    "sample rate",
    "bit depth",
    "channels",
    "peak",
    "rms",
    "dc offset",
    "clipped ratio",
]
RELEASE_AUDIO_QC_REQUIRED_TERMS = [
    "## required evidence",
    "## measurements",
    "integrated lufs:",
    "lra:",
    "true peak:",
    "clipped samples:",
    "sample rate:",
    "bit depth:",
    "## listening",
    "loudness-matched reference a/b:",
    "codec preview:",
    "translation matrix:",
    "mono/phase:",
    "low end:",
    "intro/outro:",
    "## ai artifact check",
    "vocal tail:",
    "cymbals:",
    "backing vocal smear:",
    "stem bleed:",
    "over-limiting:",
    "## blocking items",
]
GENERATION_AUDIT_MARKER = "Generated by: tools/audit_music_generation_evidence.py"
GENERATION_AUDIT_REQUIRED_TERMS = [
    "Decision: pass",
    "## Generation Evidence",
    "Take provenance tags:",
    "Batch tags:",
    "Provider metadata tags:",
    "Blind review handoff:",
]


@dataclass(frozen=True)
class ProjectEvidence:
    project_root: Path
    song: str
    project: str
    language: str
    lane: str
    best_take: str
    take_action: str
    composite_score: str
    primary_route: str
    release_decision: str
    release_audit_decision: str
    release_package_decision: str
    release_manifest_decision: str
    release_gate_generated: bool
    release_pack_generated: bool
    prompt_package_ready: bool
    prompt_preflight_decision: str
    prompt_preflight_report_ready: bool
    prompt_preflight_passed: bool
    prompt_iteration_discipline_decision: str
    prompt_iteration_discipline_ready: bool
    generation_evidence_decision: str
    generation_evidence_ready: bool
    audio_seed_required: bool
    audio_seed_retention_decision: str
    audio_seed_retention_ready: bool
    release_listener_decision: str
    release_listener_ready: bool
    post_production_mix_lock_decision: str
    post_production_mix_lock_ready: bool
    audio_technical_decision: str
    audio_technical_report_ready: bool
    audio_qc_decision: str
    audio_qc_report_ready: bool
    prompt_summary: str
    route_rows: list[dict[str, str]]
    missing: list[str]

    @property
    def release_approved(self) -> bool:
        return self.release_gate_generated and "approve release-candidate" in self.release_decision.lower()

    @property
    def prompt_preflight_approved(self) -> bool:
        return self.prompt_package_ready and self.prompt_preflight_report_ready and self.prompt_preflight_passed

    @property
    def audio_technical_passed(self) -> bool:
        return self.audio_technical_report_ready and bool(re.search(r"\b(pass|approved|approve)\b", self.audio_technical_decision, re.I))

    @property
    def audio_qc_passed(self) -> bool:
        return self.audio_qc_report_ready and bool(re.search(r"\b(pass|approved|approve)\b", self.audio_qc_decision, re.I))

    @property
    def release_pack_ready(self) -> bool:
        return self.release_pack_generated and all(
            "approve release-candidate" in decision.lower()
            for decision in [self.release_audit_decision, self.release_package_decision, self.release_manifest_decision]
        )

    @property
    def promotion_ready(self) -> bool:
        return (
            self.release_approved
            and self.release_pack_ready
            and self.prompt_preflight_approved
            and self.prompt_iteration_discipline_ready
            and self.generation_evidence_ready
            and ((not self.audio_seed_required) or self.audio_seed_retention_ready)
            and self.release_listener_ready
            and self.post_production_mix_lock_ready
            and self.audio_technical_passed
            and self.audio_qc_passed
        )

    @property
    def catalog_promotion(self) -> str:
        return "yes" if self.promotion_ready else "no"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def label_value(text: str, labels: list[str]) -> str:
    wanted = {label.lower() for label in labels}
    for line in text.splitlines():
        stripped = re.sub(r"^[-*]\s+", "", line.strip())
        match = re.match(r"^([^:]{1,80}):\s*(.*)$", stripped)
        if not match:
            continue
        label = match.group(1).strip().lower()
        value = match.group(2).strip().strip('"')
        if label in wanted and value:
            return value
    return ""


def value_from_files(project_root: Path, rels: list[str], labels: list[str]) -> str:
    for rel in rels:
        value = label_value(read_text(project_root / rel), labels)
        if value:
            return value
    return ""


def generated_by_release_gate(text: str) -> bool:
    return "Generated by: tools/prepare_music_release_candidate.py" in text


def prompt_package_ready(text: str) -> bool:
    if PROMPT_COMPILER_MARKER not in text:
        return False
    decision = label_value(text, ["Decision"])
    if not re.search(r"^compile approved\b", decision.strip(), re.I):
        return False
    lowered = text.lower()
    return all(term in lowered for term in PROMPT_PACKAGE_REQUIRED_TERMS)


def prompt_preflight_report_ready(text: str) -> bool:
    if PROMPT_COMPILER_MARKER not in text:
        return False
    lowered = text.lower()
    return all(term in lowered for term in PROMPT_PREFLIGHT_REQUIRED_TERMS)


def prompt_preflight_passed(text: str) -> bool:
    if not prompt_preflight_report_ready(text):
        return False
    decision = label_value(text, ["Decision"])
    if not re.search(r"^compile approved\b", decision.strip(), re.I):
        return False
    for label in [
        "Field completeness",
        "Lyrics context",
        "Methodology transfer",
        "Prompt specificity",
        "Lyric narrative",
        "Reference audit",
        "Prosody audit",
        "Topline audit",
        "Harmony/Bass audit",
        "Groove audit",
        "Structure audit",
        "Vocal audit",
        "Exclude rationale",
        "Slider intent",
        "Model/version",
        "Human anchor lane",
        "Identity routing",
        "My Taste / boost",
        "Identity / rights",
        "Conflict check",
    ]:
        value = label_value(text, [label])
        if not value or not re.search(r"^pass\b", value.strip(), re.I):
            return False
    blockers = label_value(text, ["Blockers"])
    return bool(blockers and re.search(r"^0\b", blockers.strip()))


def audio_technical_report_ready(text: str) -> bool:
    if AUDIO_INSPECTION_MARKER not in text:
        return False
    decision = label_value(text, ["Decision"])
    if not re.search(r"^(pass|approved|approve)\b", decision.strip(), re.I):
        return False
    lowered = text.lower()
    if "## results" not in lowered:
        return False
    if any(metric not in lowered for metric in AUDIO_INSPECTION_METRICS):
        return False
    table_rows = [line.strip() for line in text.splitlines() if line.strip().startswith("|")]
    data_rows = [
        row
        for row in table_rows
        if row.count("|") >= 10 and not re.search(r"^\|\s*-", row) and "sample rate" not in row.lower()
    ]
    return any(re.search(r"\|\s*pass\s*\|\s*$", row, re.I) for row in data_rows)


def release_audio_qc_report_ready(text: str) -> bool:
    if RELEASE_AUDIO_QC_MARKER not in text:
        return False
    decision = label_value(text, ["Decision"])
    if not re.search(r"^(pass|approved|approve)\b", decision.strip(), re.I):
        return False
    lowered = text.lower()
    if any(term not in lowered for term in RELEASE_AUDIO_QC_REQUIRED_TERMS):
        return False
    if re.search(r"Decision:\s*(hold|fail|return|do not release)|\b(return to master|return to mix|return to daw|do not release)\b", text, re.I):
        return False
    return True


def generation_evidence_ready(text: str) -> bool:
    return GENERATION_AUDIT_MARKER in text and all(term in text for term in GENERATION_AUDIT_REQUIRED_TERMS)


def one_line_prompt_summary(text: str) -> str:
    snippets: list[str] = []
    for header in ["genre", "vocal", "instrumentation", "production", "mood"]:
        match = re.search(rf"^\s*{re.escape(header)}:\s*(.+)$", text, flags=re.I | re.M)
        if match:
            snippets.append(f"{header}: {match.group(1).strip()}")
    return "; ".join(snippets[:5]) or "see 04_prompt/prompt-package-v001.md"


def repair_rows(project_root: Path) -> list[dict[str, str]]:
    path = project_root / "07_repair/repair-route-map.md"
    rows: list[dict[str, str]] = []
    for table in parse_markdown_tables(read_text(path)):
        headers = set(table[0].keys()) if table else set()
        if "problem" in headers and "layer" in headers:
            rows.extend(row for row in table if row.get("problem", "").strip())
    return rows


def load_evidence(project_root: Path) -> ProjectEvidence:
    missing = [rel for rel in CORE_EVIDENCE if not (project_root / rel).exists()]
    decision = read_text(project_root / "06_review/take-selection-decision.md")
    release_gate = read_text(project_root / "11_release/release-candidate-rights-gate.md")
    release_audit = read_text(project_root / "11_release/release-candidate-evidence-audit.md")
    release_package = read_text(project_root / "11_release/release-candidate-package.md")
    release_manifest = read_text(project_root / "11_release/release_candidate/metadata/release-candidate-manifest.md")
    prompt = read_text(project_root / "04_prompt/prompt-package-v001.md")
    prompt_preflight = read_text(project_root / "04_prompt/prompt-preflight-review.md")
    prompt_iteration = read_text(project_root / PROMPT_ITERATION_DISCIPLINE_AUDIT)
    generation_evidence = read_text(project_root / "05_generations/generation-evidence-audit.md")
    audio_seed_audit = read_text(project_root / AUDIO_SEED_AUDIT)
    release_listener = read_text(project_root / RELEASE_LISTENER_AUDIT)
    post_production_mix_lock = read_text(project_root / POST_PRODUCTION_MIX_LOCK_AUDIT)
    audio_technical = read_text(project_root / "10_mix-master/release-audio-technical-inspection.md")
    audio_qc = read_text(project_root / "10_mix-master/release-audio-qc-report.md")
    routes = repair_rows(project_root)
    best_take = label_value(decision, ["Best take"]) or ""
    take_action = label_value(decision, ["Action"]) or ""
    composite_score = label_value(decision, ["Composite score"]) or ""
    release_decision = label_value(release_gate, ["Decision"]) or "missing"
    release_audit_decision = label_value(release_audit, ["Decision"]) or "missing"
    release_package_decision = label_value(release_package, ["Decision"]) or "missing"
    release_manifest_decision = label_value(release_manifest, ["Decision"]) or "missing"
    release_gate_generated = generated_by_release_gate(release_gate)
    release_pack_generated = all(generated_by_release_gate(text) for text in [release_audit, release_package, release_manifest])
    prompt_package_is_ready = prompt_package_ready(prompt)
    prompt_preflight_decision = label_value(prompt_preflight, ["Decision"]) or "missing"
    prompt_preflight_is_ready = prompt_preflight_report_ready(prompt_preflight)
    prompt_preflight_is_passed = prompt_preflight_passed(prompt_preflight)
    prompt_iteration_decision = label_value(prompt_iteration, ["Decision"]) or "missing"
    prompt_iteration_is_ready = prompt_iteration_discipline_audit_ready(project_root)
    generation_evidence_decision = label_value(generation_evidence, ["Decision"]) or "missing"
    generation_evidence_is_ready = generation_evidence_ready(generation_evidence)
    audio_seed_is_required = audio_seed_required(project_root)
    audio_seed_retention_decision = label_value(audio_seed_audit, ["Decision"]) or ("not required" if not audio_seed_is_required else "missing")
    audio_seed_retention_is_ready = audio_seed_audit_ready(project_root) if audio_seed_is_required else True
    release_listener_decision = label_value(release_listener, ["Decision"]) or "missing"
    release_listener_is_ready = release_listener_audit_ready(project_root)
    post_production_mix_lock_decision = label_value(post_production_mix_lock, ["Decision"]) or "missing"
    post_production_mix_lock_is_ready = post_production_mix_lock_audit_ready(project_root)
    audio_technical_decision = label_value(audio_technical, ["Decision"]) or "missing"
    audio_technical_ready = audio_technical_report_ready(audio_technical)
    audio_qc_decision = label_value(audio_qc, ["Decision"]) or "missing"
    audio_qc_ready = release_audio_qc_report_ready(audio_qc)
    prompt_summary = one_line_prompt_summary(prompt)
    primary_route = ""
    if routes:
        first = routes[0]
        primary_route = " -> ".join(
            part
            for part in [
                first.get("problem", "").strip(),
                (first.get("repair_route") or first.get("route") or "").strip(),
            ]
            if part
        )
    if not best_take:
        missing.append("06_review/take-selection-decision.md missing Best take")
    if not take_action:
        missing.append("06_review/take-selection-decision.md missing Action")
    if not routes:
        missing.append("07_repair/repair-route-map.md has no repair route rows")
    if prompt and not prompt_package_is_ready:
        missing.append(
            "04_prompt/prompt-package-v001.md must be generated by tools/compile_music_prompt_package.py with compiler sections, Human Anchor Lane identity routing, and Decision: compile approved"
        )
    if prompt_preflight and not prompt_preflight_is_ready:
        missing.append(
            "04_prompt/prompt-preflight-review.md must be generated by tools/compile_music_prompt_package.py with all preflight fields including Human anchor lane, Identity routing, and My Taste / boost"
        )
    if prompt_iteration and not prompt_iteration_is_ready:
        missing.append(
            "05_generations/prompt-iteration-discipline-audit.md must be generated by tools/audit_music_prompt_iteration_discipline.py with Decision: pass before catalog promotion"
        )
    if generation_evidence and not generation_evidence_is_ready:
        missing.append(
            "05_generations/generation-evidence-audit.md must be generated by tools/audit_music_generation_evidence.py with Decision: pass and take/provider metadata provenance"
        )
    if audio_seed_is_required and not audio_seed_retention_is_ready:
        missing.append(
            "06_review/audio-seed-retention-audit.md must be generated by tools/audit_music_audio_seed_retention.py with Decision: pass before catalog promotion"
        )
    if release_listener and not release_listener_is_ready:
        missing.append(
            "06_review/release-listener-evidence-audit.md must be generated by tools/audit_music_release_listener_evidence.py with Decision: pass before catalog promotion"
        )
    if post_production_mix_lock and not post_production_mix_lock_is_ready:
        missing.append(
            "10_mix-master/post-production-mix-lock-audit.md must be generated by tools/audit_music_post_production_mix_lock.py with Decision: pass before catalog promotion"
        )
    if prompt_summary == "see 04_prompt/prompt-package-v001.md":
        missing.append("04_prompt/prompt-package-v001.md has no concrete prompt summary")
    if audio_technical and not audio_technical_ready:
        missing.append("10_mix-master/release-audio-technical-inspection.md must be generated by tools/inspect_music_release_audio.py with Results metrics")
    if audio_qc and not audio_qc_ready:
        missing.append("10_mix-master/release-audio-qc-report.md must be generated by tools/prepare_music_release_audio_qc.py with mastering QC evidence")
    if release_decision == "missing":
        missing.append("11_release/release-candidate-rights-gate.md missing Decision")
    if release_gate and "approve release-candidate" in release_decision.lower() and not release_gate_generated:
        missing.append("11_release/release-candidate-rights-gate.md was not generated by tools/prepare_music_release_candidate.py")
    for rel, release_text, release_decision_value in [
        ("11_release/release-candidate-evidence-audit.md", release_audit, release_audit_decision),
        ("11_release/release-candidate-package.md", release_package, release_package_decision),
        ("11_release/release_candidate/metadata/release-candidate-manifest.md", release_manifest, release_manifest_decision),
    ]:
        if release_text and not generated_by_release_gate(release_text):
            missing.append(f"{rel} was not generated by tools/prepare_music_release_candidate.py")
        if release_text and release_decision_value == "missing":
            missing.append(f"{rel} missing Decision")

    return ProjectEvidence(
        project_root=project_root,
        song=value_from_files(project_root, ["README.md", "01_brief/song-brief.md"], ["song", "song title", "title"]) or project_root.name,
        project=value_from_files(project_root, ["README.md", "01_brief/project-intake.md"], ["project / artist", "project", "artist / catalog"]),
        language=value_from_files(project_root, ["README.md", "01_brief/song-brief.md"], ["language"]),
        lane=value_from_files(project_root, ["README.md", "01_brief/song-brief.md"], ["lane", "genre lane"]),
        best_take=best_take,
        take_action=take_action,
        composite_score=composite_score,
        primary_route=label_value(decision, ["Primary route"]) or primary_route,
        release_decision=release_decision,
        release_audit_decision=release_audit_decision,
        release_package_decision=release_package_decision,
        release_manifest_decision=release_manifest_decision,
        release_gate_generated=release_gate_generated,
        release_pack_generated=release_pack_generated,
        prompt_package_ready=prompt_package_is_ready,
        prompt_preflight_decision=prompt_preflight_decision,
        prompt_preflight_report_ready=prompt_preflight_is_ready,
        prompt_preflight_passed=prompt_preflight_is_passed,
        prompt_iteration_discipline_decision=prompt_iteration_decision,
        prompt_iteration_discipline_ready=prompt_iteration_is_ready,
        generation_evidence_decision=generation_evidence_decision,
        generation_evidence_ready=generation_evidence_is_ready,
        audio_seed_required=audio_seed_is_required,
        audio_seed_retention_decision=audio_seed_retention_decision,
        audio_seed_retention_ready=audio_seed_retention_is_ready,
        release_listener_decision=release_listener_decision,
        release_listener_ready=release_listener_is_ready,
        post_production_mix_lock_decision=post_production_mix_lock_decision,
        post_production_mix_lock_ready=post_production_mix_lock_is_ready,
        audio_technical_decision=audio_technical_decision,
        audio_technical_report_ready=audio_technical_ready,
        audio_qc_decision=audio_qc_decision,
        audio_qc_report_ready=audio_qc_ready,
        prompt_summary=prompt_summary,
        route_rows=routes,
        missing=missing,
    )


def route_lines(evidence: ProjectEvidence) -> str:
    if not evidence.route_rows:
        return "- no repair route rows found"
    lines: list[str] = []
    for row in evidence.route_rows[:8]:
        problem = row.get("problem", "").strip()
        layer = row.get("layer", "").strip()
        route = (row.get("repair_route") or row.get("route") or "").strip()
        severity = row.get("severity", "").strip()
        lines.append(f"- {problem} | layer: {layer} | severity: {severity} | route: {route}")
    return "\n".join(lines)


def promotion_note(evidence: ProjectEvidence) -> str:
    if evidence.promotion_ready:
        return "Promote only the rules that are supported by review, repair, and release-candidate evidence."
    return "Do not promote this song as a catalog standard yet; capture failure lessons and banned defaults."


def render_catalog(evidence: ProjectEvidence) -> str:
    return f"""# Catalog Memory Update

Generated by: tools/prepare_music_catalog_memory.py
Project root: {evidence.project_root}

Song: {evidence.song}
Artist / catalog: {evidence.project}
Language: {evidence.language}
Lane: {evidence.lane}
Locked take: {evidence.best_take}
Take action: {evidence.take_action}
Composite score: {evidence.composite_score}
Release decision: {evidence.release_decision}
Catalog promotion: {evidence.catalog_promotion}

## What Worked

- Prompt direction: {evidence.prompt_summary}
- Best take: {evidence.best_take or 'unknown'}
- Release-candidate status: {evidence.release_decision}
- Release-candidate evidence audit: {evidence.release_audit_decision}
- Release-candidate package: {evidence.release_package_decision}
- Release-candidate manifest: {evidence.release_manifest_decision}
- Prompt preflight: {evidence.prompt_preflight_decision}
- Prompt iteration discipline: {evidence.prompt_iteration_discipline_decision}
- Generation evidence: {evidence.generation_evidence_decision}
- Audio seed retention: {evidence.audio_seed_retention_decision}
- Release listener evidence: {evidence.release_listener_decision}
- Post-production mix lock: {evidence.post_production_mix_lock_decision}
- Release audio technical inspection: {evidence.audio_technical_decision}
- Release audio QC: {evidence.audio_qc_decision}

## What Failed Or Needed Control

{route_lines(evidence)}

## Updated Artist Rules

- Keep only choices that remain true after blind review, repair routing, and release gate.
- {promotion_note(evidence)}
- Do not write reference-artist names as catalog identity.

## Next Song Implication

- Preserve the proven hook / vocal / groove / production role only if it fits the artist identity.
- Change at least one musical dimension so the next song is evolution, not duplicate generation.
"""


def render_prompt(evidence: ProjectEvidence) -> str:
    return f"""# Prompt Memory Update

Generated by: tools/prepare_music_catalog_memory.py

Song: {evidence.song}
Prompt source: 04_prompt/prompt-package-v001.md
Release decision: {evidence.release_decision}
Release-candidate evidence audit: {evidence.release_audit_decision}
Release-candidate package: {evidence.release_package_decision}
Release-candidate manifest: {evidence.release_manifest_decision}
Prompt preflight: {evidence.prompt_preflight_decision}
Prompt iteration discipline: {evidence.prompt_iteration_discipline_decision}
Generation evidence: {evidence.generation_evidence_decision}
Audio seed retention: {evidence.audio_seed_retention_decision}
Release listener evidence: {evidence.release_listener_decision}
Post-production mix lock: {evidence.post_production_mix_lock_decision}
Release audio technical inspection: {evidence.audio_technical_decision}
Release audio QC: {evidence.audio_qc_decision}
Catalog promotion: {evidence.catalog_promotion}

## Approved Prompt Fragments

- {evidence.prompt_summary}

## Banned Or Risky Defaults

- Do not reuse prompt fragments that caused these repair routes:
{route_lines(evidence)}

## Prompt Rule For Next Batch

- Change one variable at a time.
- Keep Exclude rules that reduced AI flavor.
- Preserve language/prosody constraints before adding style adjectives.
"""


def render_artifact(evidence: ProjectEvidence) -> str:
    return f"""# Artifact Memory Update

Generated by: tools/prepare_music_catalog_memory.py

Song: {evidence.song}
Locked take: {evidence.best_take}
Release decision: {evidence.release_decision}

## Artifact Lessons

{route_lines(evidence)}

## Default Prevention

- Run blind review before declaring a take good.
- Route AI flavor into lyric, prosody, topline, groove, vocal, stem, mix, master, rights, or catalog layer.
- Do not master over unresolved stem/vocal artifacts.

## Regression Test For Similar Future Songs

- Re-listen first 20 seconds, chorus, bridge, and outro.
- Check vocal-only and stem-solo artifacts if the route mentions voice, stems, groove, or mix.
"""


def render_sonic(evidence: ProjectEvidence) -> str:
    return f"""# Sonic Signature Update

Generated by: tools/prepare_music_catalog_memory.py

Song: {evidence.song}
Lane: {evidence.lane}
Prompt summary: {evidence.prompt_summary}
Catalog promotion: {evidence.catalog_promotion}

## Candidate Sonic Signature

- tempo / meter:
- groove:
- drum identity:
- bass identity:
- harmony color:
- lead instrument:
- vocal space:
- chorus width:

## Keep / Change

- Keep only if release-candidate and listener feedback support it.
- Change at least one non-core dimension in the next song.
"""


def render_lyric(evidence: ProjectEvidence) -> str:
    return f"""# Lyric Universe Update

Generated by: tools/prepare_music_catalog_memory.py

Song: {evidence.song}
Language: {evidence.language}
Catalog promotion: {evidence.catalog_promotion}

## Reusable Lyric Signals

- title phrase:
- narrator stance:
- concrete object:
- location / time:
- Verse 2 development:
- bridge turn:

## Do Not Repeat

- generic emotional abstractions.
- cliches that appeared in repair routes.
- reference-artist biography or private identity.

## Next Lyric Constraint

- Start from a new object, scene, or action while preserving the same lyric ethics.
"""


def render_reference(evidence: ProjectEvidence) -> str:
    return f"""# Reference Boundary Update

Generated by: tools/prepare_music_catalog_memory.py

Song: {evidence.song}
Release decision: {evidence.release_decision}

## Reference Boundary Lesson

- Allowed transferable DNA:
- Disallowed identity/riff/vocal similarities:
- Similarity review result:
- Voice / Persona / Custom Model risk:

## Catalog Rule

- Do not use artist names as public identity or reusable prompt defaults.
- Keep style DNA abstract: groove, form, production space, emotional timeline.
- Re-run similarity-and-impersonation review before release.
"""


def render_postmortem(evidence: ProjectEvidence) -> str:
    return f"""# Postmortem And Prompt Memory

Generated by: tools/prepare_music_catalog_memory.py

Song: {evidence.song}
Locked take: {evidence.best_take}
Take action: {evidence.take_action}
Release decision: {evidence.release_decision}
Catalog promotion: {evidence.catalog_promotion}

## Evidence Links

- 04_prompt/prompt-package-v001.md
- 04_prompt/prompt-preflight-review.md
- 05_generations/prompt-iteration-discipline-audit.md
- 05_generations/take-ledger.md
- 05_generations/generation-evidence-audit.md
- 06_review/audio-seed-retention-audit.md
- 06_review/release-listener-evidence-audit.md
- 06_review/take-selection-decision.md
- 07_repair/repair-route-map.md
- 08_stems-daw/session-pack.md
- 10_mix-master/post-production-mix-lock-audit.md
- 10_mix-master/release-audio-technical-inspection.md
- 10_mix-master/release-audio-qc-report.md
- 11_release/release-candidate-evidence-audit.md
- 11_release/release-candidate-rights-gate.md
- 11_release/release-candidate-package.md
- 11_release/release_candidate/metadata/release-candidate-manifest.md
- 12_catalog-memory/catalog-memory-update.md

## Producer Postmortem

- Best decision:
- Worst default:
- Biggest AI-flavor risk:
- Most useful human intervention:
- One rule to reuse:
- One rule to ban:

## Next Action

- If promoted: update Artist / Catalog Bible.
- If held: repair the blocker before using this song as a Persona, Voice, Custom Model, or catalog seed.
"""


def render_next_song(evidence: ProjectEvidence) -> str:
    return f"""# Next Song Brief Seed

Generated by: tools/prepare_music_catalog_memory.py

Based on song: {evidence.song}
Catalog promotion: {evidence.catalog_promotion}

## Next Song Should Preserve

- artist promise:
- vocal identity:
- strongest hook mechanism:
- production space:

## Next Song Should Change

- title image:
- tempo or groove:
- verse situation:
- arrangement role:

## Do Not Repeat

- weak prompt defaults:
- unresolved repair route:
- reference similarity:
- release gate blocker:

## Seed Brief

Write a new song in the same catalog identity, but with a different title image,
different scene, and one clearly changed musical dimension.
"""


def render_manifest(evidence: ProjectEvidence) -> str:
    files = CORE_EVIDENCE + SUPPORTING_EVIDENCE + list(OUTPUTS.values())
    if evidence.audio_seed_required and AUDIO_SEED_AUDIT not in files:
        files.insert(files.index("06_review/take-selection-decision.md") if "06_review/take-selection-decision.md" in files else len(CORE_EVIDENCE), AUDIO_SEED_AUDIT)
    return f"""# Catalog Writeback Manifest

Generated by: tools/prepare_music_catalog_memory.py
Project root: {evidence.project_root}

Song: {evidence.song}
Catalog promotion: {evidence.catalog_promotion}
Release decision: {evidence.release_decision}
Release-candidate evidence audit: {evidence.release_audit_decision}
Release-candidate package: {evidence.release_package_decision}
Release-candidate manifest: {evidence.release_manifest_decision}
Prompt preflight: {evidence.prompt_preflight_decision}
Prompt iteration discipline: {evidence.prompt_iteration_discipline_decision}
Generation evidence: {evidence.generation_evidence_decision}
Audio seed retention: {evidence.audio_seed_retention_decision}
Release listener evidence: {evidence.release_listener_decision}
Post-production mix lock: {evidence.post_production_mix_lock_decision}
Release audio technical inspection: {evidence.audio_technical_decision}
Release audio QC: {evidence.audio_qc_decision}

## Files

{chr(10).join(f"- {path}" for path in files)}

## Rule

Catalog memory is evidence-backed only when it links to prompt, prompt
preflight, prompt iteration discipline, take review, repair route, release
audio inspection, release audio QC, generation evidence audit, conditional
audio seed retention audit, post-production mix-lock audit, release listener evidence audit,
release-candidate evidence audit, release gate, release package, manifest, and
postmortem evidence. Catalog promotion is allowed only when these gates pass;
otherwise treat it as a temporary
experiment note.
"""


def output_contents(evidence: ProjectEvidence) -> dict[str, str]:
    return {
        OUTPUTS["catalog"]: render_catalog(evidence),
        OUTPUTS["prompt"]: render_prompt(evidence),
        OUTPUTS["artifact"]: render_artifact(evidence),
        OUTPUTS["sonic"]: render_sonic(evidence),
        OUTPUTS["lyric"]: render_lyric(evidence),
        OUTPUTS["reference"]: render_reference(evidence),
        OUTPUTS["postmortem"]: render_postmortem(evidence),
        OUTPUTS["next_song"]: render_next_song(evidence),
        OUTPUTS["manifest"]: render_manifest(evidence),
    }


def write_outputs(project_root: Path, contents: dict[str, str], allow_overwrite: bool) -> list[Path]:
    targets = [project_root / rel for rel in contents]
    existing = [path for path in targets if path.exists()]
    if existing and not allow_overwrite:
        raise FileExistsError("refusing to overwrite existing files: " + ", ".join(path.relative_to(project_root).as_posix() for path in existing))
    written: list[Path] = []
    for rel, text in contents.items():
        path = project_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--write", action="store_true", help="Write catalog memory files.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting catalog memory files.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero when core evidence is missing.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists():
        print(f"error: project root does not exist: {project_root}", file=sys.stderr)
        return 2
    evidence = load_evidence(project_root)
    if evidence.missing:
        print("catalog memory writeback blocked:", file=sys.stderr)
        for rel in evidence.missing:
            print(f"- missing {rel}", file=sys.stderr)
        if args.strict:
            return 2

    contents = output_contents(evidence)
    if args.write:
        try:
            written = write_outputs(project_root, contents, args.allow_overwrite)
        except FileExistsError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        for path in written:
            print(f"wrote {path.relative_to(project_root).as_posix()}")
    else:
        print("catalog memory writeback preview")
        print(f"song: {evidence.song}")
        print(f"release decision: {evidence.release_decision}")
        print(f"catalog promotion: {evidence.catalog_promotion}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
