#!/usr/bin/env python3
"""Turn blind-review scores in a song project into a take decision.

This tool does not listen to audio. It enforces the project discipline after
listening: take-ledger and blind-review must contain structured evidence before
a take can be locked, repaired, regenerated, or discarded.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from audit_music_audio_seed_retention import (
    OUTPUT as AUDIO_SEED_AUDIT,
    audio_seed_audit_ready,
    audio_seed_required,
)


TAKE_LEDGER = "05_generations/take-ledger.md"
GENERATION_AUDIT = "05_generations/generation-evidence-audit.md"
BLIND_REVIEW = "06_review/blind-review.md"
DECISION_OUTPUT = "06_review/take-selection-decision.md"
GENERATION_AUDIT_MARKER = "Generated by: tools/audit_music_generation_evidence.py"
GENERATION_AUDIT_REQUIRED_TERMS = [
    "Decision: pass",
    "## Generation Evidence",
    "Take provenance tags:",
    "Batch tags:",
    "Provider metadata tags:",
    "Blind review handoff:",
]


POSITIVE_FIELDS = [
    "alignment",
    "preference",
    "hook",
    "vocal_identity",
    "groove",
    "form",
]
REQUIRED_SCORE_FIELDS = POSITIVE_FIELDS + ["artifact_risk"]

FIELD_WEIGHTS = {
    "alignment": 0.18,
    "preference": 0.18,
    "hook": 0.18,
    "vocal_identity": 0.16,
    "groove": 0.12,
    "form": 0.10,
    "artifact_safety": 0.08,
}


@dataclass
class TakeScore:
    take_id: str
    values: dict[str, float] = field(default_factory=dict)
    raw: dict[str, str] = field(default_factory=dict)
    ledger: dict[str, str] = field(default_factory=dict)

    @property
    def artifact_risk(self) -> float | None:
        return self.values.get("artifact_risk")

    @property
    def artifact_safety(self) -> float:
        if self.artifact_risk is None:
            return 3.0
        return max(0.0, min(5.0, 5.0 - self.artifact_risk))

    @property
    def composite(self) -> float:
        total = 0.0
        weight_sum = 0.0
        for field_name, weight in FIELD_WEIGHTS.items():
            if field_name == "artifact_safety":
                value = self.artifact_safety
            else:
                value = self.values.get(field_name)
                if value is None:
                    continue
            total += value * weight
            weight_sum += weight
        return total / weight_sum if weight_sum else 0.0

    @property
    def core_min(self) -> float:
        scores = [self.values[field] for field in POSITIVE_FIELDS if field in self.values]
        return min(scores) if scores else 0.0

    @property
    def missing_score_fields(self) -> list[str]:
        return [field for field in REQUIRED_SCORE_FIELDS if field not in self.values]

    @property
    def evidence_complete(self) -> bool:
        return not self.missing_score_fields


def normalize_header(value: str) -> str:
    value = value.strip().lower()
    value = value.replace("<br>", " ")
    value = re.sub(r"[*_`]", "", value)
    value = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", " ", value)
    value = re.sub(r"\s+", " ", value).strip()
    mapping = {
        "take": "take",
        "take id": "take",
        "blind id": "take",
        "version": "take",
        "alignment": "alignment",
        "brief alignment": "alignment",
        "preference": "preference",
        "overall preference": "preference",
        "hook": "hook",
        "hook memory": "hook",
        "vocal": "vocal_identity",
        "vocal identity": "vocal_identity",
        "vocal realism": "vocal_identity",
        "groove": "groove",
        "groove bass": "groove",
        "form": "form",
        "structure": "form",
        "artifact risk": "artifact_risk",
        "ai flavor": "artifact_risk",
        "ai flavor score": "artifact_risk",
        "ai flavor risk": "artifact_risk",
        "decision": "decision",
        "known issue": "known_issue",
        "review status": "review_status",
        "first impression": "first_impression",
        "prompt package": "prompt_package",
        "provider model": "provider_model",
        "settings": "settings",
        "changed variable": "changed_variable",
        "candidate": "candidate",
    }
    if value in mapping:
        return mapping[value]
    if "take" in value:
        return "take"
    if "alignment" in value or "符合" in value:
        return "alignment"
    if "preference" in value or "喜好" in value:
        return "preference"
    if "hook" in value or "钩子" in value or "记忆" in value:
        return "hook"
    if "vocal" in value or "声线" in value or "人声" in value:
        return "vocal_identity"
    if "groove" in value or "律动" in value:
        return "groove"
    if "form" in value or "structure" in value or "曲式" in value:
        return "form"
    if "artifact" in value or "ai味" in value or "ai 味" in value or "伪影" in value:
        return "artifact_risk"
    return value.replace(" ", "_")


def parse_markdown_tables(text: str) -> list[list[dict[str, str]]]:
    rows_by_table: list[list[dict[str, str]]] = []
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index].strip()
        if not line.startswith("|") or "|" not in line[1:]:
            index += 1
            continue
        if index + 1 >= len(lines) or not re.match(r"^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$", lines[index + 1]):
            index += 1
            continue
        headers = [normalize_header(cell) for cell in split_table_row(line)]
        table_rows: list[dict[str, str]] = []
        index += 2
        while index < len(lines) and lines[index].strip().startswith("|"):
            cells = split_table_row(lines[index])
            if len(cells) < 2:
                break
            row = {}
            for offset, header in enumerate(headers):
                row[header] = cells[offset].strip() if offset < len(cells) else ""
            if any(value for value in row.values()):
                table_rows.append(row)
            index += 1
        if table_rows:
            rows_by_table.append(table_rows)
    return rows_by_table


def split_table_row(line: str) -> list[str]:
    stripped = line.strip()
    if stripped.startswith("|"):
        stripped = stripped[1:]
    if stripped.endswith("|"):
        stripped = stripped[:-1]
    return [cell.strip() for cell in stripped.split("|")]


def parse_score(value: str) -> float | None:
    text = value.strip().lower()
    if not text:
        return None
    word_scores = {
        "low": 1.0,
        "medium": 2.5,
        "mid": 2.5,
        "high": 4.0,
        "none": 0.0,
        "pass": 4.0,
        "fail": 1.0,
        "yes": 4.0,
        "no": 1.0,
        "低": 1.0,
        "中": 2.5,
        "高": 4.0,
        "无": 0.0,
    }
    if text in word_scores:
        return word_scores[text]
    match = re.search(r"(\d+(?:\.\d+)?)", text)
    if not match:
        return None
    score = float(match.group(1))
    if score > 5.0 and score <= 100.0:
        score = score / 20.0
    return max(0.0, min(5.0, score))


def generation_audit_ready(project_root: Path) -> bool:
    text = (project_root / GENERATION_AUDIT).read_text(encoding="utf-8") if (project_root / GENERATION_AUDIT).exists() else ""
    if GENERATION_AUDIT_MARKER not in text:
        return False
    return all(term in text for term in GENERATION_AUDIT_REQUIRED_TERMS)


def load_project(project_root: Path) -> tuple[dict[str, dict[str, str]], dict[str, TakeScore], list[str]]:
    errors: list[str] = []
    ledger_rows: dict[str, dict[str, str]] = {}
    scores: dict[str, TakeScore] = {}

    ledger_path = project_root / TAKE_LEDGER
    generation_audit_path = project_root / GENERATION_AUDIT
    review_path = project_root / BLIND_REVIEW
    if not generation_audit_path.exists() or not generation_audit_ready(project_root):
        errors.append(f"missing or failed {GENERATION_AUDIT}; run tools/audit_music_generation_evidence.py before blind review")
    if audio_seed_required(project_root) and not audio_seed_audit_ready(project_root):
        errors.append(f"missing or failed {AUDIO_SEED_AUDIT}; run tools/audit_music_audio_seed_retention.py before ordinary blind review")
    if not ledger_path.exists():
        errors.append(f"missing {TAKE_LEDGER}")
    if not review_path.exists():
        errors.append(f"missing {BLIND_REVIEW}")
    if errors:
        return ledger_rows, scores, errors

    for table in parse_markdown_tables(ledger_path.read_text(encoding="utf-8")):
        for row in table:
            take_id = row.get("take") or row.get("blind_id") or ""
            take_id = take_id.strip()
            if not take_id or take_id.startswith("take id"):
                continue
            ledger_rows[take_id] = row

    for table in parse_markdown_tables(review_path.read_text(encoding="utf-8")):
        headers = set(table[0].keys()) if table else set()
        if "take" not in headers:
            continue
        score_headers = headers.intersection({"alignment", "preference", "hook", "vocal_identity", "groove", "form", "artifact_risk"})
        if not score_headers:
            continue
        for row in table:
            take_id = (row.get("take") or "").strip()
            if not take_id or take_id.lower() in {"take", "anonymous files"}:
                continue
            score = scores.setdefault(take_id, TakeScore(take_id=take_id))
            for field_name in score_headers:
                raw = row.get(field_name, "")
                parsed = parse_score(raw)
                if parsed is not None:
                    score.values[field_name] = parsed
                    score.raw[field_name] = raw
            score.raw["decision"] = row.get("decision", "")

    for take_id, row in ledger_rows.items():
        if take_id in scores:
            scores[take_id].ledger = row

    if not scores:
        errors.append("no scored take rows found in 06_review/blind-review.md")
    return ledger_rows, scores, errors


def route_for_take(take: TakeScore) -> list[str]:
    routes: list[str] = []
    if take.missing_score_fields:
        routes.append("complete missing blind-review score fields: " + ", ".join(take.missing_score_fields))
    if take.values.get("alignment", 5.0) < 3.5:
        routes.append("repair prompt package or brief alignment")
    if take.values.get("preference", 5.0) < 3.5:
        routes.append("repair song idea, hook payoff, or arrangement payoff")
    if take.values.get("hook", 5.0) < 3.8:
        routes.append("AI 音乐 Topline Hook 与旋律草稿工作流")
    if take.values.get("vocal_identity", 5.0) < 3.8:
        routes.append("AI 音乐声线身份与演唱表演工作流")
    if take.values.get("groove", 5.0) < 3.6:
        routes.append("AI 音乐乐器演奏真实感与 Groove Humanization 工作流")
    if take.values.get("form", 5.0) < 3.6:
        routes.append("AI 音乐结构动态与段落转场工作流")
    if take.artifact_risk is not None and take.artifact_risk > 2.0:
        routes.append("AI 音乐 AI味伪影诊断与修复路由工作流")
    if not routes:
        routes.append("post-review / stems / mix-master gate")
    return routes


def decision_for_take(take: TakeScore) -> str:
    if not take.values:
        return "insufficient evidence"
    if take.missing_score_fields:
        return "repair review evidence"
    if take.composite >= 4.3 and take.core_min >= 4.0 and (take.artifact_risk is None or take.artifact_risk <= 1.5):
        return "lock for post-production"
    if take.composite >= 3.8 and take.core_min >= 3.0 and (take.artifact_risk is None or take.artifact_risk <= 2.5):
        return "repair candidate"
    if take.composite >= 3.2:
        return "controlled regeneration"
    return "discard and repair brief"


def render_score(value: float | None) -> str:
    return "" if value is None else f"{value:.2f}"


def render_decision(project_root: Path, scores: dict[str, TakeScore], errors: list[str]) -> str:
    ranked = sorted(scores.values(), key=lambda item: (item.evidence_complete, item.composite), reverse=True)
    best = ranked[0] if ranked else None
    lines: list[str] = [
        "# Take Selection Decision",
        "",
        "Generated by: tools/review_music_takes.py",
        f"Project root: {project_root}",
        "",
    ]

    if errors:
        lines.extend(
            [
                "## Decision",
                "",
                "repair review evidence before choosing a take",
                "",
                "## Missing Evidence",
                "",
            ]
        )
        for error in errors:
            lines.append(f"- {error}")
        lines.append("")
        return "\n".join(lines)

    assert best is not None
    lines.extend(
        [
            "## Decision",
            "",
            f"Best take: {best.take_id}",
            f"Action: {decision_for_take(best)}",
            f"Evidence status: {'complete' if best.evidence_complete else 'incomplete'}",
            f"Missing score fields: {', '.join(best.missing_score_fields) if best.missing_score_fields else 'none'}",
            f"Composite score: {best.composite:.2f}",
            f"Core minimum: {best.core_min:.2f}",
            f"Primary route: {', '.join(route_for_take(best))}",
            "",
            "## Ranking",
            "",
            "| rank | take | evidence | missing score fields | composite | alignment | preference | hook | vocal identity | groove | form | artifact risk | action | route |",
            "|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---|---|",
        ]
    )
    for rank, take in enumerate(ranked, start=1):
        lines.append(
            "| "
            + " | ".join(
                [
                    str(rank),
                    take.take_id,
                    "complete" if take.evidence_complete else "incomplete",
                    ", ".join(take.missing_score_fields) if take.missing_score_fields else "none",
                    f"{take.composite:.2f}",
                    render_score(take.values.get("alignment")),
                    render_score(take.values.get("preference")),
                    render_score(take.values.get("hook")),
                    render_score(take.values.get("vocal_identity")),
                    render_score(take.values.get("groove")),
                    render_score(take.values.get("form")),
                    render_score(take.artifact_risk),
                    decision_for_take(take),
                    "; ".join(route_for_take(take)),
                ]
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Next Action",
            "",
        ]
    )
    action = decision_for_take(best)
    if action == "lock for post-production":
        lines.append("- Lock this take in `08_stems-daw/best-take-lock.md` before stems, DAW, mix, or master work.")
        lines.append("- Run a regression listen after any Replace/Extend/Studio or mix operation.")
    elif action == "repair review evidence":
        lines.append("- Complete every required score field in `06_review/blind-review.md` before choosing or routing a take.")
        lines.append("- Do not lock, repair-route, DAW-handoff, release, or catalog this take until score evidence is complete.")
    elif action == "repair candidate":
        lines.append("- Keep the best take, but repair only the routed problem layer before re-listening.")
        lines.append("- Do not widen the experiment until the weak layer improves.")
    elif action == "controlled regeneration":
        lines.append("- Preserve the strongest element, then run a single-variable regeneration batch.")
        lines.append("- Update `05_generations/take-ledger.md` with the changed variable.")
    else:
        lines.append("- Stop selecting takes and repair the brief, lyrics, hook, or prompt package first.")

    lines.extend(
        [
            "",
            "## Evidence Rules",
            "",
            "- This decision depends on the scored table in `06_review/blind-review.md`.",
            "- `05_generations/generation-evidence-audit.md` must be generated by `tools/audit_music_generation_evidence.py` with `Decision: pass` before blind review is trusted.",
            "- If a human audio seed, Audio Upload, Cover, Add Vocals, or nonzero Audio Influence is used, `06_review/audio-seed-retention-audit.md` must be generated by `tools/audit_music_audio_seed_retention.py` with `Decision: pass` before ordinary blind review.",
            "- Required score fields are alignment, preference, hook, vocal identity, groove, form, and artifact risk.",
            "- Missing `artifact risk` is not a pass; it blocks lock/release because AI-flavor risk has not been heard and named.",
            "- Audio files, prompt package, and provider settings must still be traceable through `05_generations/take-ledger.md`.",
            "- Release still requires rights, audio QC, and external listener gates.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, help="Song project root.")
    parser.add_argument("--output", default=DECISION_OUTPUT, help="Relative output path for the decision note.")
    parser.add_argument("--write", action="store_true", help="Write the decision note.")
    parser.add_argument("--allow-overwrite", action="store_true", help="Allow overwriting an existing decision note.")
    parser.add_argument("--strict", action="store_true", help="Return nonzero if evidence is missing or no take is lock/repair quality.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = Path(args.project_root).expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"error: project root not found: {project_root}", file=sys.stderr)
        return 2

    _, scores, errors = load_project(project_root)
    output = render_decision(project_root, scores, errors)
    if args.write:
        output_path = project_root / args.output
        if output_path.exists() and not args.allow_overwrite:
            print(f"error: output exists, use --allow-overwrite: {output_path}", file=sys.stderr)
            return 2
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(output, encoding="utf-8")
    else:
        print(output)

    if errors:
        for error in errors:
            print(f"review evidence error: {error}", file=sys.stderr)
        return 1 if args.strict else 0

    best = max(scores.values(), key=lambda item: (item.evidence_complete, item.composite))
    action = decision_for_take(best)
    print(f"best take: {best.take_id}")
    print(f"action: {action}")
    print(f"composite: {best.composite:.2f}")
    if args.strict and action not in {"lock for post-production", "repair candidate"}:
        print("error: no take reached lock or repair quality", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
