#!/usr/bin/env python3
"""Verify the AI music genre/lane authenticity gate."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
AUDIT = ROOT / "tools" / "audit_music_genre_lane_authenticity.py"
COMPILER = ROOT / "tools" / "compile_music_prompt_package.py"
WIKI_PROMPT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐 Prompt 编译与生成前预检工作流.md")
WIKI_PROJECT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
WIKI_STATUS = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲制作总控与阶段闸门工作流.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def run(cmd: list[str], cwd: Path = ROOT) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=cwd, text=True, capture_output=True)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def scaffold(tmp_path: Path) -> Path:
    cmd = [
        sys.executable,
        str(SCAFFOLD),
        "--output-dir",
        str(tmp_path),
        "--date",
        "20260625",
        "--language",
        "zh",
        "--lane",
        "pop",
        "--slug",
        "genre-lane",
        "--title",
        "Night Bus Confession",
        "--artist-project",
        "Example Test Artist",
        "--use-case",
        "demo",
    ]
    result = run(cmd)
    if result.returncode != 0:
        raise RuntimeError(result.stderr)
    return tmp_path / "20260625_zh-pop_genre-lane"


def specificity_pass(project: Path) -> str:
    return f"""# Prompt Specificity Budget Audit

Generated by: tools/audit_music_prompt_specificity_budget.py
Project root: {project}
Decision: pass

## Specificity Budget Evidence

Style source: 04_prompt/style-field-map.md
Budget source: 04_prompt/field-length-and-specificity-budget.md
Methodology transfer: pass
Style specificity tags: Mandarin night pop-rock, close mid-low female lead, live drums, melodic bass, clean electric guitar, dry verse vocal, wide but sparse chorus
Recording realism tags: dry, close, room, wide, tape
Performance realism tags: lead vocal, drums, bass, guitar, pocket
Section/director tags: verse, chorus, title phrase, hook
Field budget tags: must-hear=dry verse vocal, melodic bass, title phrase hook, decision=ready
Vague term removals: emotional, catchy, realistic
Protected identity check: pass
Prompt compile handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | specificity budget approved | prompt compile |
"""


def bad_style() -> str:
    return """# Style Field Map

Language: Mandarin
Genre lane: pop, rock, EDM, acoustic
genre: pop, rock, EDM, acoustic
tempo / meter: 100 BPM 4/4
vocal: emotional female vocal
instrumentation: guitar, synth, beat
production: wide reverb mix
mood: catchy and powerful
"""


def good_style() -> str:
    return """# Style Field Map

Language: Mandarin
Genre lane: Mandarin night pop-rock
genre: Mandarin night pop-rock, 96 BPM 4/4, 2020s urban band-pop
Secondary lane purpose: pop chorus compression with rock rhythm-section push; no EDM drop.
Era / scene anchor: 2020s Mandarin night-commute playlist, headphones and small livehouse-adjacent band texture.
tempo / meter: 96 BPM 4/4
vocal: close mid-low female lead, clear Mandarin diction, restrained verse, wider chorus doubles
drums / groove: live drum kit, tight backbeat, ghost-note hats
bass role: melodic bass locks to kick in chorus, sparse verse movement
instrumentation: clean electric guitar arpeggio, live drums, melodic bass, restrained synth pad
production: dry close verse vocal, small room reflections, wider chorus stereo, light tape saturation
mood: late-night confession, verse restraint, chorus lift
"""


def lyrics_context() -> str:
    return """# Lyrics Context Map

Narrator: first-person commuter
Situation: last bus after rain
Title phrase: 末班车还亮着
Hook mechanism: chorus repeats the title phrase on the longest note, final chorus answers it with a new object image.
Prosody notes: Mandarin tones stay on short notes in verses; title phrase lands on open vowels.

```text
[Verse 1 | dry close vocal | bus window image]
我把没发出的字 删到只剩一格光

[Chorus | main hook | wider mix | title phrase]
末班车还亮着 你别回头望

[Bridge | reduced drums | emotional pivot]
不是时间太短 是我太会躲藏
[End]
```
"""


def exclude_text() -> str:
    return """# Exclude Negative Aesthetic

Exclude: random genre switch, generic AI pop gloss, EDM drop, fake crowd, overproduced karaoke sheen, protected artist names
"""


def main() -> int:
    errors: list[str] = []
    with tempfile.TemporaryDirectory(prefix="ai-music-genre-lane-") as tmp:
        project = scaffold(Path(tmp))

        missing_specificity = run([sys.executable, str(AUDIT), "--project-root", str(project), "--strict"])
        if missing_specificity.returncode == 0:
            errors.append("genre/lane audit should fail when prompt specificity is missing")
        if "prompt_specificity_not_ready" not in (missing_specificity.stdout + missing_specificity.stderr):
            errors.append("missing-specificity failure should name prompt_specificity_not_ready")

        write(project / "04_prompt" / "prompt-specificity-budget-audit.md", specificity_pass(project))
        write(project / "04_prompt" / "style-field-map.md", bad_style())
        write(project / "04_prompt" / "lyrics-context-map.md", lyrics_context())
        write(project / "04_prompt" / "exclude-negative-aesthetic.md", exclude_text())

        bad = run([sys.executable, str(AUDIT), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"])
        if bad.returncode == 0:
            errors.append("genre soup without rationale should fail")
        for term in ["genre_soup_without_rationale", "scene_anchor_missing"]:
            if term not in (bad.stdout + bad.stderr):
                errors.append(f"bad genre/lane audit missing blocker: {term}")

        compile_without_audit = run([sys.executable, str(COMPILER), "--project-root", str(project), "--strict"])
        if "genre_lane_authenticity_audit" not in (compile_without_audit.stdout + compile_without_audit.stderr):
            errors.append("compiler should surface genre_lane_authenticity_audit when audit is absent or failed")

        write(project / "04_prompt" / "style-field-map.md", good_style())
        ok = run([sys.executable, str(AUDIT), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"])
        if ok.returncode != 0:
            errors.append(f"good genre/lane audit should pass: stdout={ok.stdout.strip()} stderr={ok.stderr.strip()}")
        audit_text = (project / "04_prompt" / "genre-lane-authenticity-audit.md").read_text(encoding="utf-8")
        for term in [
            "Generated by: tools/audit_music_genre_lane_authenticity.py",
            "Decision: pass",
            "Primary lane: Mandarin night pop-rock",
            "Genre/lane authenticity: pass",
            "Prompt compile handoff: pass",
        ]:
            if term not in audit_text:
                errors.append(f"genre/lane audit output missing term: {term}")

        no_overwrite = run([sys.executable, str(AUDIT), "--project-root", str(project), "--write"])
        if no_overwrite.returncode != 2:
            errors.append("genre/lane audit should refuse overwrite without --allow-overwrite")

        write(project / "04_prompt" / "style-field-map.md", good_style().replace("Mandarin night pop-rock", "Taylor Swift style Mandarin pop-rock"))
        protected = run([sys.executable, str(AUDIT), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"])
        if protected.returncode == 0:
            errors.append("protected identity in genre lane should fail")
        if "protected_identity_in_lane" not in (protected.stdout + protected.stderr):
            errors.append("protected-identity failure should name protected_identity_in_lane")

    compiler_source = COMPILER.read_text(encoding="utf-8")
    for term in ["genre_lane_authenticity_audit", "Genre/lane authenticity", "tools/audit_music_genre_lane_authenticity.py"]:
        if term not in compiler_source:
            errors.append(f"compiler missing genre/lane integration term: {term}")

    for path, label in [(WIKI_PROMPT, "prompt"), (WIKI_PROJECT, "project"), (WIKI_STATUS, "status")]:
        text = path.read_text(encoding="utf-8") if path.exists() else ""
        for term in ["tools/audit_music_genre_lane_authenticity.py", "genre-lane-authenticity-audit.md", "Genre/lane authenticity"]:
            if term not in text:
                errors.append(f"{label} wiki page missing genre/lane term: {term}")
    log_text = LOG.read_text(encoding="utf-8") if LOG.exists() else ""
    if "AI 音乐 Genre Lane Authenticity 工具闸门" not in log_text:
        errors.append("wiki log missing genre/lane authenticity gate entry")

    if errors:
        print("AI music genre/lane authenticity gate verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music genre/lane authenticity gate verification passed.")
    print(f"tool: {AUDIT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
