#!/usr/bin/env python3
"""Verify the AI music catalog memory writeback tool."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
TOOL = ROOT / "tools" / "prepare_music_catalog_memory.py"
LISTENER = ROOT / "tools" / "audit_music_release_listener_evidence.py"
POST_MIX = ROOT / "tools" / "audit_music_post_production_mix_lock.py"
WIKI_CATALOG = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐艺人身份与 Catalog Bible 工作流.md")
WIKI_TEMPLATE = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def release_audio_report(project: Path) -> str:
    return f"""# Release Audio Technical Inspection

Generated by: tools/inspect_music_release_audio.py
Project root: {project}
Decision: pass

## Results

| file | duration | sample rate | bit depth | channels | peak | RMS | DC offset | clipped ratio | status |
|---|---:|---:|---:|---:|---:|---:|---:|---:|---|
| 11_release/release_candidate/audio/night-bus-master.wav | 1.00s | 44100 | 16 | 2 | 0.3662 | 0.2589 | 0.00000 | 0.000000 | pass |

## Blocking Items

- none
"""


def release_audio_qc_report(project: Path) -> str:
    return f"""# Release Audio QC Report

Generated by: tools/prepare_music_release_audio_qc.py
Project root: {project}
Decision: pass

## Required Evidence

| evidence | file | status | decision | missing terms | blockers |
|---|---|---|---|---|---|
| loudness true peak report | 10_mix-master/loudness-true-peak-report.md | pass | pass |  |  |
| codec preview | 10_mix-master/codec-preview.md | pass | pass |  |  |
| translation listen matrix | 10_mix-master/translation-listen-matrix.md | pass | pass |  |  |
| mono phase low-end check | 10_mix-master/mono-phase-low-end-check.md | pass | pass |  |  |
| transient and limiter audit | 10_mix-master/transient-and-limiter-audit.md | pass | pass |  |  |

## Measurements

- integrated LUFS: -14.0
- LRA: 6.0
- True Peak: -1.0 dBTP
- clipped samples: 0
- sample rate: 44100
- bit depth: 16

## Listening

- loudness-matched reference A/B: pass
- codec preview: pass
- translation matrix: pass
- mono/phase: pass
- low end: pass
- intro/outro: pass

## AI Artifact Check

- vocal tail: pass
- cymbals: pass
- backing vocal smear: none
- stem bleed: none
- over-limiting: none

## Deliverable

- approved file: 11_release/release_candidate/audio/night-bus-master.wav
- rejected files: none
- platform notes: codec and platform previews passed

## Blocking Items

- none
"""


def generation_evidence_audit(project: Path) -> str:
    return f"""# Generation Evidence Audit

Generated by: tools/audit_music_generation_evidence.py
Project root: {project}
Decision: pass

## Generation Evidence

Take provenance tags: A02
Batch tags: candidate ids, takes per candidate, total takes, generation date, expected listen order, anonymization rule
Provider metadata tags: A02
Blind review handoff: ready
"""


def prompt_iteration_discipline_audit(project: Path) -> str:
    return f"""# Prompt Iteration Discipline Audit

Generated by: tools/audit_music_prompt_iteration_discipline.py
Project root: {project}
Decision: pass

## Prompt Iteration Discipline Evidence

Experiment question: compare C01 baseline with C02 Style Influence change
Frozen brief: complete
Allowed variable count: 1
Changed variables: style influence
Candidate hypotheses: present; candidates=C01, C02
Batch discipline: candidates=C01, C02, total=4
Attribution strength: strong
Generation evidence handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | no blocking findings | proceed |
"""


def post_production_mix_lock_audit(project: Path) -> str:
    return f"""# Post Production Mix Lock Audit

Generated by: tools/audit_music_post_production_mix_lock.py
Project root: {project}
Decision: pass

## Post Production Mix Lock Evidence

Locked take: A02
Arrangement density tags: sections=complete; action=yes
Vocal center: dry centered lead vocal stays above the guitar bed
Low-end/kick-bass: kick transient and bass sustain are separated
Space/dynamics automation: dry verse, wider chorus, pad ducking under vocal
Transition/outro: bridge breath and resolved final tail
AI artifact repair: cymbal smear and vocal tail blur resolved
Stem/DAW handoff: ready
Reference A/B: loudness-matched internal reference passed
Mix lock handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | no blocking findings | proceed |
"""


def write_listener_evidence(project: Path) -> None:
    write(
        project / "06_review" / "external-listener-panel.md",
        """# External Listener Panel

Target audience: late-night Mandarin pop listeners
Panel size: 6
Blind condition: prompt and provider hidden
AI flavor red flags: none
Release listener verdict: pass
Decision: pass
""",
    )
    write(
        project / "06_review" / "first-20-second-test.md",
        """# First 20 Second Test

Skip risk: low
First 20 second decision: pass
Synthetic / fake feeling: none
Decision: pass
""",
    )
    write(
        project / "06_review" / "hook-memory-test.md",
        """# Hook Memory Test

Hook recalled: yes
Title phrase remembered: 末班车还亮着
Memory result: pass
Decision: pass
""",
    )
    write(
        project / "06_review" / "ai-flavor-red-flag-survey.md",
        """# AI Flavor Red Flag Survey

AI flavor red flags: none
AI flavor release verdict: pass
Severity 0-3: 0
Decision: pass
""",
    )


def prompt_package_text(project: Path) -> str:
    return f"""# Prompt Package v001

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Decision: compile approved

## Metadata

- Title: Night Bus Confession
- Project: Example Test Artist
- Use case: release-single
- Audience: late-night Mandarin pop listeners
- Language: zh
- Lane: pop
- Version: v001
- Model: Suno current
- Weirdness: 25
- Style Influence: 70
- Audio Influence: 0
- Human Anchor Lane: text-only
- Voice Identity Source: none
- Persona Source: none
- Custom Model Source: none
- Custom Model Corpus: none
- My Taste State: off
- Prompt Boost State: off
- Exclude: awkward translated Mandarin, EDM festival drop

## Style Of Music

```text
genre: "Mandarin night pop-rock, 78 BPM"
vocal: "clear Mandarin diction, intimate verse, controlled chorus lift"
instrumentation: "live drums, melodic bass, clean electric guitar"
production: "dry verse vocal, wide but sparse chorus"
mood: "late-night confession with restrained release"
```

## Lyrics

```text
[Verse 1 | intimate vocal]
车窗把霓虹揉成一条河
[Chorus | 末班车还亮着]
末班车还亮着 可我没说破
[End]
```

## Prompt Rationale

- Narrator: first-person commuter
- Situation: last bus after rain
- Title phrase: 末班车还亮着
- Hook promise: title phrase lands on a long note
- Prosody notes: stable vowels on long notes
- Methodology transfer: pass
- Prompt specificity: pass
- Lyric narrative: pass
- Reference audit: pass
Prosody audit: pass
- Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass
- Genre anchor: Mandarin night pop-rock
- Vocal identity: clear Mandarin diction
- Core instruments: live drums, melodic bass, clean electric guitar
- Production texture: dry verse vocal, wide but sparse chorus
- Emotional arc: restrained release
- Why these exclusions: avoid translated Mandarin and EDM gloss

## Preflight Summary

| severity | code | message | route |
|---|---|---|---|
| pass | none | compile approved | experiment handoff |
"""


def prompt_preflight_text(project: Path) -> str:
    return f"""# Prompt Preflight Review

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Prompt package: 04_prompt/prompt-package-v001.md

Field completeness: pass
Style specificity: pass
Lyrics context: pass
Prosody risk: pass
Methodology transfer: pass
Prompt specificity: pass
Lyric narrative: pass
Reference audit: pass
Prosody audit: pass
Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass
Hook clarity: pass
Exclude rationale: pass
Slider intent: pass
Model/version: pass
Human anchor lane: pass
Identity routing: pass
My Taste / boost: pass
Identity / rights: pass
Variable discipline: review
Conflict check: pass

Decision: compile approved

Blockers: 0
Warnings: 0

## Issues

| severity | code | message | route |
|---|---|---|---|
| pass | none | compile approved | experiment handoff |
"""


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, TOOL, LISTENER, POST_MIX, WIKI_CATALOG, WIKI_TEMPLATE]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-catalog-memory-") as tmp:
        tmp_path = Path(tmp)
        scaffold = run(
            [
                sys.executable,
                str(SCAFFOLD),
                "--output-dir",
                str(tmp_path),
                "--date",
                "20260624",
                "--language",
                "zh",
                "--lane",
                "pop",
                "--slug",
                "night-bus",
                "--title",
                "Night Bus Confession",
                "--artist-project",
                "Example Test Artist",
                "--use-case",
                "release-single",
            ]
        )
        if scaffold.returncode != 0:
            errors.append(f"scaffold failed: {scaffold.stderr.strip()}")
            print("\n".join(errors), file=sys.stderr)
            return 1

        project = tmp_path / "20260624_zh-pop_night-bus"
        empty = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if empty.returncode == 0:
            errors.append("empty catalog writeback should fail in --strict mode")

        write(
            project / "04_prompt" / "prompt-package-v001.md",
            prompt_package_text(project),
        )
        incomplete = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if incomplete.returncode == 0:
            errors.append("catalog writeback should require prompt preflight and release audio evidence in strict mode")

        write(
            project / "04_prompt" / "prompt-preflight-review.md",
            prompt_preflight_text(project),
        )
        write(
            project / "05_generations" / "take-ledger.md",
            """| take id | prompt package | provider/model | settings | source audio | persona/voice | first impression | known issue | review status |
|---|---|---|---|---|---|---|---|---|
| A02 | 04_prompt/prompt-package-v001.md | Suno v5.5 | style 0.55 | none | none | strong chorus | hi-hat artifact | reviewed |
""",
        )
        write(project / "05_generations" / "prompt-iteration-discipline-audit.md", prompt_iteration_discipline_audit(project))
        write(project / "05_generations" / "generation-evidence-audit.md", generation_evidence_audit(project))
        write_listener_evidence(project)
        listener = run(
            [
                sys.executable,
                str(LISTENER),
                "--project-root",
                str(project),
                "--write",
                "--allow-overwrite",
                "--strict",
            ]
        )
        if listener.returncode != 0:
            errors.append(f"release listener evidence audit should pass: {listener.stderr.strip()}")
        write(
            project / "06_review" / "take-selection-decision.md",
            """# Take Selection Decision

Best take: A02
Action: lock for post-production
Composite score: 4.55
Core minimum: 4.10
Primary route: AI 音乐编曲密度与混音后期修作工作流
""",
        )
        write(
            project / "07_repair" / "repair-route-map.md",
            """| problem | layer | severity | repair route | expected output | regression listen |
|---|---|---:|---|---|---|
| hi-hat artifact | mix/post | 1 | AI 音乐编曲密度与混音后期修作工作流 | mix-plan.md | artifact lower, hook preserved |
""",
        )
        write(
            project / "11_release" / "release-candidate-rights-gate.md",
            """# Release Candidate Rights Gate

Decision: approve release-candidate
Blocking Items:
- none
""",
        )
        write(project / "08_stems-daw" / "session-pack.md", "# Session Pack\n\nDecision: pass\n")
        write(project / "10_mix-master" / "post-production-mix-lock-audit.md", post_production_mix_lock_audit(project))
        write(project / "10_mix-master" / "release-audio-technical-inspection.md", release_audio_report(project))
        write(project / "10_mix-master" / "release-audio-qc-report.md", release_audio_qc_report(project))
        handwritten_gate = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if handwritten_gate.returncode == 0:
            errors.append("catalog writeback should reject handwritten release approval without release-candidate pack evidence in strict mode")

        write(project / "11_release" / "release-candidate-evidence-audit.md", "# Release Candidate Evidence Audit\n\nGenerated by: tools/prepare_music_release_candidate.py\nDecision: approve release-candidate\nBlocking Items:\n- none\n")
        write(project / "11_release" / "release-candidate-package.md", "# Release Candidate Package\n\nGenerated by: tools/prepare_music_release_candidate.py\nDecision: approve release-candidate\n")
        write(project / "11_release" / "release_candidate" / "metadata" / "release-candidate-manifest.md", "# Release Candidate Manifest\n\nGenerated by: tools/prepare_music_release_candidate.py\nDecision: approve release-candidate\n")

        write(
            project / "10_mix-master" / "release-audio-technical-inspection.md",
            "# Release Audio Technical Inspection\n\nGenerated by: tools/inspect_music_release_audio.py\nDecision: pass\n",
        )
        fake_audio_report = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if fake_audio_report.returncode == 0:
            errors.append("catalog writeback should reject release audio technical inspection without metrics")
        fake_audio_report_text = fake_audio_report.stdout + "\n" + fake_audio_report.stderr
        for term in ["release-audio-technical-inspection.md", "Results metrics"]:
            if term not in fake_audio_report_text:
                errors.append(f"catalog fake audio inspection blocker missing term: {term}")
        write(project / "10_mix-master" / "release-audio-technical-inspection.md", release_audio_report(project))

        fake_release_gate = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if fake_release_gate.returncode == 0:
            errors.append("catalog writeback should reject handwritten release approval even when release-candidate pack exists")
        fake_release_gate_text = fake_release_gate.stdout + "\n" + fake_release_gate.stderr
        for term in ["release-candidate-rights-gate.md", "tools/prepare_music_release_candidate.py"]:
            if term not in fake_release_gate_text:
                errors.append(f"catalog fake release gate blocker missing term: {term}")
        write(
            project / "11_release" / "release-candidate-rights-gate.md",
            """# Release Candidate Rights Gate

Generated by: tools/prepare_music_release_candidate.py
Decision: approve release-candidate
Blocking Items:
- none
""",
        )

        real_qc_report = (project / "10_mix-master" / "release-audio-qc-report.md").read_text(encoding="utf-8")
        write(
            project / "10_mix-master" / "release-audio-qc-report.md",
            "# Release Audio QC Report\n\nDecision: pass\n",
        )
        fake_qc_report = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if fake_qc_report.returncode == 0:
            errors.append("catalog writeback should reject hand-written release audio QC evidence")
        fake_qc_report_text = fake_qc_report.stdout + "\n" + fake_qc_report.stderr
        for term in ["release-audio-qc-report.md", "tools/prepare_music_release_audio_qc.py"]:
            if term not in fake_qc_report_text:
                errors.append(f"catalog fake release audio QC blocker missing term: {term}")
        write(project / "10_mix-master" / "release-audio-qc-report.md", real_qc_report)

        real_post_mix = (project / "10_mix-master" / "post-production-mix-lock-audit.md").read_text(encoding="utf-8")
        write(
            project / "10_mix-master" / "post-production-mix-lock-audit.md",
            "# Post Production Mix Lock Audit\n\nDecision: pass\n",
        )
        fake_post_mix = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if fake_post_mix.returncode == 0:
            errors.append("catalog writeback should reject hand-written post-production mix-lock evidence")
        fake_post_mix_text = fake_post_mix.stdout + "\n" + fake_post_mix.stderr
        for term in ["post-production-mix-lock-audit.md", "tools/audit_music_post_production_mix_lock.py"]:
            if term not in fake_post_mix_text:
                errors.append(f"catalog fake post-production mix-lock blocker missing term: {term}")
        write(project / "10_mix-master" / "post-production-mix-lock-audit.md", real_post_mix)

        real_prompt_iteration = (project / "05_generations" / "prompt-iteration-discipline-audit.md").read_text(encoding="utf-8")
        write(
            project / "05_generations" / "prompt-iteration-discipline-audit.md",
            "# Prompt Iteration Discipline Audit\n\nDecision: pass\n",
        )
        fake_prompt_iteration = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if fake_prompt_iteration.returncode == 0:
            errors.append("catalog writeback should reject hand-written prompt iteration discipline evidence")
        fake_prompt_iteration_text = fake_prompt_iteration.stdout + "\n" + fake_prompt_iteration.stderr
        for term in ["prompt-iteration-discipline-audit.md", "tools/audit_music_prompt_iteration_discipline.py"]:
            if term not in fake_prompt_iteration_text:
                errors.append(f"catalog fake prompt iteration blocker missing term: {term}")
        write(project / "05_generations" / "prompt-iteration-discipline-audit.md", real_prompt_iteration)

        real_prompt_package = (project / "04_prompt" / "prompt-package-v001.md").read_text(encoding="utf-8")
        real_prompt_preflight = (project / "04_prompt" / "prompt-preflight-review.md").read_text(encoding="utf-8")
        write(
            project / "04_prompt" / "prompt-package-v001.md",
            "# Prompt Package v001\n\nDecision: compile approved\ngenre: Mandarin night pop-rock\nvocal: close vocal\n",
        )
        write(
            project / "04_prompt" / "prompt-preflight-review.md",
            "# Prompt Preflight Review\n\nDecision: compile approved\nField completeness: pass\nSlider intent: pass\n",
        )
        fake_prompt_report = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if fake_prompt_report.returncode == 0:
            errors.append("catalog writeback should reject hand-written prompt package/preflight evidence")
        fake_prompt_report_text = fake_prompt_report.stdout + "\n" + fake_prompt_report.stderr
        for term in ["prompt-package-v001.md", "tools/compile_music_prompt_package.py"]:
            if term not in fake_prompt_report_text:
                errors.append(f"catalog fake prompt evidence blocker missing term: {term}")

        write(
            project / "04_prompt" / "prompt-package-v001.md",
            f"""# Prompt Package v001

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Decision: compile approved

## Metadata

- Title: Night Bus Confession
- Model: Suno current
- Weirdness: 25
- Style Influence: 70
- Exclude: awkward translated Mandarin

## Style Of Music

```text
genre: "Mandarin night pop-rock"
vocal: "close vocal"
instrumentation: "live drums, melodic bass, clean electric guitar"
production: "dry verse vocal"
mood: "late-night confession"
```

## Lyrics

```text
[Verse 1]
line
[Chorus]
hook
[End]
```

## Prompt Rationale

- Why these exclusions: avoid generic gloss
- Methodology transfer: pass
- Prompt specificity: pass
- Lyric narrative: pass

## Preflight Summary

| severity | code | message | route |
|---|---|---|---|
| pass | none | compile approved | experiment handoff |
""",
        )
        write(
            project / "04_prompt" / "prompt-preflight-review.md",
            f"""# Prompt Preflight Review

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Prompt package: 04_prompt/prompt-package-v001.md

Field completeness: pass
Style specificity: pass
Lyrics context: pass
Prosody risk: pass
Methodology transfer: pass
Prompt specificity: pass
Lyric narrative: pass
Reference audit: pass
Prosody audit: pass
Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass
Hook clarity: pass
Exclude rationale: pass
Slider intent: pass
Model/version: pass
Human anchor lane: pass
Identity routing: pass
My Taste / boost: pass
Identity / rights: pass
Variable discipline: review
Conflict check: pass

Decision: compile approved

Blockers: 0

## Issues
""",
        )
        old_prompt_report = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if old_prompt_report.returncode == 0:
            errors.append("catalog writeback should reject old compiler prompt evidence without Human Anchor routing")
        old_prompt_report_text = old_prompt_report.stdout + "\n" + old_prompt_report.stderr
        for term in ["human anchor", "prompt-package-v001.md"]:
            if term not in old_prompt_report_text.lower():
                errors.append(f"catalog old prompt evidence blocker missing term: {term}")
        write(project / "04_prompt" / "prompt-package-v001.md", real_prompt_package)
        write(project / "04_prompt" / "prompt-preflight-review.md", real_prompt_preflight)

        ok = run(
            [
                sys.executable,
                str(TOOL),
                "--project-root",
                str(project),
                "--write",
                "--allow-overwrite",
                "--strict",
            ]
        )
        if ok.returncode != 0:
            errors.append(f"catalog writeback should pass: {ok.stderr.strip()}")

        expected = [
            "12_catalog-memory/catalog-memory-update.md",
            "12_catalog-memory/prompt-memory-update.md",
            "12_catalog-memory/artifact-memory-update.md",
            "12_catalog-memory/sonic-signature-update.md",
            "12_catalog-memory/lyric-universe-update.md",
            "12_catalog-memory/reference-boundary-update.md",
            "12_catalog-memory/postmortem-and-prompt-memory.md",
            "12_catalog-memory/next-song-brief-seed.md",
            "12_catalog-memory/catalog-writeback-manifest.md",
        ]
        for rel in expected:
            if not (project / rel).is_file():
                errors.append(f"missing output: {rel}")

        catalog = (project / "12_catalog-memory" / "catalog-memory-update.md").read_text(encoding="utf-8")
        for term in [
            "Catalog promotion: yes",
            "Locked take: A02",
            "release-candidate",
            "tools/prepare_music_catalog_memory.py",
            "Mandarin night pop-rock",
            "Prompt preflight: compile approved",
            "Prompt iteration discipline: pass",
            "Generation evidence: pass",
            "Audio seed retention: not applicable",
            "Release listener evidence: pass",
            "Post-production mix lock: pass",
            "Release audio technical inspection: pass",
            "Release audio QC: pass",
            "Release-candidate evidence audit: approve release-candidate",
            "Release-candidate package: approve release-candidate",
            "Release-candidate manifest: approve release-candidate",
        ]:
            if term not in catalog:
                errors.append(f"catalog memory missing term: {term}")

        next_song = (project / "12_catalog-memory" / "next-song-brief-seed.md").read_text(encoding="utf-8")
        for term in ["Next Song", "Do Not Repeat", "different title image", "Catalog promotion: yes"]:
            if term not in next_song:
                errors.append(f"next song seed missing term: {term}")

        no_overwrite = run([sys.executable, str(TOOL), "--project-root", str(project), "--write", "--strict"])
        if no_overwrite.returncode == 0:
            errors.append("catalog writeback should refuse overwrite without --allow-overwrite")

        write(
            project / "04_prompt" / "prompt-preflight-review.md",
            f"""# Prompt Preflight Review

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Prompt package: 04_prompt/prompt-package-v001.md

Field completeness: fail
Style specificity: pass
Lyrics context: pass
Prosody risk: pass
Methodology transfer: pass
Prompt specificity: pass
Lyric narrative: pass
Reference audit: pass
Prosody audit: pass
Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass
Hook clarity: pass
Exclude rationale: pass
Slider intent: pass
Model/version: pass
Human anchor lane: pass
Identity routing: pass
My Taste / boost: pass
Identity / rights: pass
Variable discipline: review
Conflict check: pass

Decision: repair before generation

Blockers: 1
Warnings: 0

## Issues

| severity | code | message | route |
|---|---|---|---|
| blocker | field_completeness | repair before generation | prompt compile |
""",
        )
        blocked_promotion = run(
            [
                sys.executable,
                str(TOOL),
                "--project-root",
                str(project),
                "--write",
                "--allow-overwrite",
                "--strict",
            ]
        )
        if blocked_promotion.returncode != 0:
            errors.append(f"failed-preflight projects should still write failure memory: {blocked_promotion.stderr.strip()}")
        blocked_catalog = (project / "12_catalog-memory" / "catalog-memory-update.md").read_text(encoding="utf-8")
        if "Catalog promotion: no" not in blocked_catalog:
            errors.append("failed prompt preflight must prevent catalog promotion")

        write(
            project / "04_prompt" / "prompt-preflight-review.md",
            prompt_preflight_text(project),
        )
        write(
            project / "11_release" / "release-candidate-rights-gate.md",
            """# Release Candidate Rights Gate

Decision: hold
Blocking Items:
- unresolved rights
""",
        )
        hold = run(
            [
                sys.executable,
                str(TOOL),
                "--project-root",
                str(project),
                "--write",
                "--allow-overwrite",
                "--strict",
            ]
        )
        if hold.returncode != 0:
            errors.append(f"hold projects should still write failure memory: {hold.stderr.strip()}")
        hold_catalog = (project / "12_catalog-memory" / "catalog-memory-update.md").read_text(encoding="utf-8")
        if "Catalog promotion: no" not in hold_catalog:
            errors.append("hold catalog memory should not promote to catalog standard")

    catalog_text = WIKI_CATALOG.read_text(encoding="utf-8")
    for term in [
        "tools/prepare_music_catalog_memory.py",
        "tools/audit_music_prompt_iteration_discipline.py",
        "prompt-iteration-discipline-audit.md",
        "tools/audit_music_generation_evidence.py",
        "generation-evidence-audit.md",
        "audio-seed-retention-audit.md",
        "tools/audit_music_audio_seed_retention.py",
        "tools/audit_music_release_listener_evidence.py",
        "release-listener-evidence-audit.md",
        "tools/audit_music_post_production_mix_lock.py",
        "post-production-mix-lock-audit.md",
        "prompt-preflight-review.md",
        "release-audio-technical-inspection.md",
        "release-audio-qc-report.md",
        "release-candidate-evidence-audit.md",
        "release-candidate-package.md",
        "release_candidate/metadata/release-candidate-manifest.md",
        "catalog-memory-update.md",
        "next-song-brief-seed.md",
        "catalog-writeback-manifest.md",
        "--strict",
    ]:
        if term not in catalog_text:
            errors.append(f"catalog workflow missing term: {term}")

    template_text = WIKI_TEMPLATE.read_text(encoding="utf-8")
    for term in [
        "tools/prepare_music_catalog_memory.py",
        "tools/audit_music_prompt_iteration_discipline.py",
        "prompt-iteration-discipline-audit.md",
        "tools/audit_music_generation_evidence.py",
        "generation-evidence-audit.md",
        "audio-seed-retention-audit.md",
        "tools/audit_music_audio_seed_retention.py",
        "tools/audit_music_release_listener_evidence.py",
        "release-listener-evidence-audit.md",
        "tools/audit_music_post_production_mix_lock.py",
        "post-production-mix-lock-audit.md",
        "next-song-brief-seed.md",
        "catalog-writeback-manifest.md",
        "release-candidate-evidence-audit.md",
        "release-candidate-package.md",
        "Catalog promotion",
    ]:
        if term not in template_text:
            errors.append(f"project template missing term: {term}")

    log_text = LOG.read_text(encoding="utf-8") if LOG.exists() else ""
    for term in ["AI 音乐 Catalog Memory 回写工具", "AI 音乐 Prompt Iteration Discipline 工具闸门", "AI 音乐 Generation Evidence 工具闸门", "AI 音乐 Audio Seed Retention 工具闸门", "AI 音乐 Post Production Mix Lock 工具闸门", "AI 音乐 Release Listener Evidence 工具闸门"]:
        if term not in log_text:
            errors.append(f"wiki log missing catalog memory writeback tool entry: {term}")

    if errors:
        print("AI music catalog memory writeback verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music catalog memory writeback verification passed.")
    print(f"tool: {TOOL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
