#!/usr/bin/env python3
"""Verify the AI music take review decision CLI."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
GENERATION_AUDIT = ROOT / "tools" / "audit_music_generation_evidence.py"
REVIEWER = ROOT / "tools" / "review_music_takes.py"
WIKI_REVIEW = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐盲听评审与版本归档工作流.md")
WIKI_PROJECT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_generation_evidence_inputs(project: Path) -> None:
    write(
        project / "04_prompt" / "prompt-package-v001.md",
        f"""# Prompt Package v001

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Decision: compile approved

## Metadata

- Model: Suno current
- Weirdness: 25
- Style Influence: 70
- Audio Influence: 0
- Human Anchor Lane: text-only
- Voice Identity Source: none
- Persona Source: none
- Custom Model Source: none
- Custom Model Corpus: none
- My Taste State: off
- Prompt Boost State: off
- Exclude: awkward translated Mandarin

## Style Of Music

```text
genre: "Mandarin night pop-rock"
vocal: "close mid-low female lead"
instrumentation: "live drums, melodic bass, clean electric guitar"
production: "dry verse vocal, wide but sparse chorus"
mood: "late-night confession"
```

## Lyrics

```text
[Verse 1]
line
[Chorus]
hook
[End]
```

## Prompt Rationale

- Reference audit: pass
Prosody audit: pass
- Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass

## Preflight Summary

| severity | code | message | route |
|---|---|---|---|
| pass | none | compile approved | experiment handoff |
""",
    )
    write(
        project / "04_prompt" / "prompt-preflight-review.md",
        f"""# Prompt Preflight Review

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Prompt package: 04_prompt/prompt-package-v001.md

Field completeness: pass
Lyrics context: pass
Reference audit: pass
Prosody audit: pass
Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass
Exclude rationale: pass
Slider intent: pass
Model/version: pass
Human anchor lane: pass
Identity routing: pass
My Taste / boost: pass
Identity / rights: pass
Conflict check: pass

Decision: compile approved

Blockers: 0

## Issues
""",
    )
    write(
        project / "05_generations" / "batch-generation-plan.md",
        """# Batch Generation Plan

Candidate IDs: C01
Takes per candidate: 3
Total takes: 3
Generation date: 2026-06-25
Expected listen order: A02, A01, A03
Anonymization rule: randomize filenames before blind review
""",
    )
    write(
        project / "05_generations" / "prompt-iteration-discipline-audit.md",
        f"""# Prompt Iteration Discipline Audit

Generated by: tools/audit_music_prompt_iteration_discipline.py
Project root: {project}
Decision: pass

## Prompt Iteration Discipline Evidence

Experiment question: compare baseline take spread for title hook retention
Frozen brief: complete
Allowed variable count: 1
Changed variables: style influence
Candidate hypotheses: present; candidates=C01
Batch discipline: candidates=C01, total=3
Attribution strength: strong
Generation evidence handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | no blocking findings | proceed |
""",
    )
    write(
        project / "05_generations" / "take-ledger.md",
        """# Take Ledger

| take id | prompt package | provider/model | settings | source audio | persona/voice | first impression | known issue | review status |
|---|---|---|---|---|---|---|---|---|
| A01 | 04_prompt/prompt-package-v001.md | Suno current | W25/S70/A0 | 05_generations/audio/A01.wav | fictional singer | pretty but generic | weak hook | reviewed |
| A02 | 04_prompt/prompt-package-v001.md | Suno current | W25/S70/A0 | 05_generations/audio/A02.wav | fictional singer | title hook lands | minor mix polish | reviewed |
| A03 | 04_prompt/prompt-package-v001.md | Suno current | W45/S55/A0 | 05_generations/audio/A03.wav | fictional singer | interesting texture | AI vocal tail | reviewed |
""",
    )
    write(
        project / "05_generations" / "provider-result-ledger.md",
        """# Provider Result Ledger

| take id | provider/model | settings | generated url | downloaded file | prompt package | metadata | status |
|---|---|---|---|---|---|---|---|
| A01 | Suno current | W25/S70/A0 | https://example.test/A01 | 05_generations/audio/A01.wav | 04_prompt/prompt-package-v001.md | 05_generations/metadata/A01-settings.md | exported |
| A02 | Suno current | W25/S70/A0 | https://example.test/A02 | 05_generations/audio/A02.wav | 04_prompt/prompt-package-v001.md | 05_generations/metadata/A02-settings.md | exported |
| A03 | Suno current | W45/S55/A0 | https://example.test/A03 | 05_generations/audio/A03.wav | 04_prompt/prompt-package-v001.md | 05_generations/metadata/A03-settings.md | exported |
""",
    )
    (project / "05_generations" / "audio").mkdir(parents=True, exist_ok=True)
    for take_id in ["A01", "A02", "A03"]:
        (project / "05_generations" / "audio" / f"{take_id}.wav").write_bytes(b"RIFF0000WAVE")
        write(project / "05_generations" / "metadata" / f"{take_id}-settings.md", f"Take: {take_id}\nSettings: W25/S70/A0\n")


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, GENERATION_AUDIT, REVIEWER, WIKI_REVIEW, WIKI_PROJECT, LOG]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-take-review-") as tmp:
        tmp_path = Path(tmp)
        scaffold = subprocess.run(
            [
                sys.executable,
                str(SCAFFOLD),
                "--output-dir",
                str(tmp_path),
                "--date",
                "20260624",
                "--language",
                "zh",
                "--lane",
                "pop",
                "--slug",
                "night-bus",
                "--title",
                "Night Bus Confession",
                "--artist-project",
                "Example Test Artist",
                "--use-case",
                "demo",
            ],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if scaffold.returncode != 0:
            errors.append(f"scaffold failed: {scaffold.stderr.strip()}")
            print("\n".join(errors), file=sys.stderr)
            return 1

        project = tmp_path / "20260624_zh-pop_night-bus"
        empty_review = subprocess.run(
            [sys.executable, str(REVIEWER), "--project-root", str(project), "--strict"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if empty_review.returncode == 0:
            errors.append("strict take reviewer should reject an empty scaffold review")

        write_generation_evidence_inputs(project)
        generation = subprocess.run(
            [
                sys.executable,
                str(GENERATION_AUDIT),
                "--project-root",
                str(project),
                "--write",
                "--allow-overwrite",
                "--strict",
            ],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if generation.returncode != 0:
            errors.append(f"generation evidence audit failed: stdout={generation.stdout.strip()} stderr={generation.stderr.strip()}")
        write(
            project / "06_review" / "blind-review.md",
            """# Blind Review

Hidden prompt: yes
Anonymous files: A01.wav, A02.wav, A03.wav

## Scores

| take | alignment | preference | hook | vocal identity | groove | form | artifact risk | decision |
|---|---:|---:|---:|---:|---:|---:|---:|---|
| A01 | 3.4 | 3.2 | 2.8 | 3.6 | 3.5 | 3.4 | 1.5 | reject |
| A02 | 4.5 | 4.4 | 4.6 | 4.2 | 4.3 | 4.4 | 1.0 | lock |
| A03 | 4.0 | 3.8 | 4.1 | 3.2 | 3.9 | 3.7 | 3.0 | repair |
""",
        )

        review = subprocess.run(
            [
                sys.executable,
                str(REVIEWER),
                "--project-root",
                str(project),
                "--write",
                "--allow-overwrite",
                "--strict",
            ],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if review.returncode != 0:
            errors.append(f"take reviewer failed: stdout={review.stdout.strip()} stderr={review.stderr.strip()}")

        decision_path = project / "06_review" / "take-selection-decision.md"
        if not decision_path.exists():
            errors.append("missing take-selection-decision.md output")
        else:
            decision = decision_path.read_text(encoding="utf-8")
            for term in [
                "Best take: A02",
                "lock for post-production",
                "Evidence status: complete",
                "Missing score fields: none",
                "Composite score",
                "AI 音乐 AI味伪影诊断与修复路由工作流",
                "05_generations/take-ledger.md",
                "05_generations/generation-evidence-audit.md",
                "06_review/blind-review.md",
                "Required score fields are alignment, preference, hook, vocal identity, groove, form, and artifact risk.",
            ]:
                if term not in decision:
                    errors.append(f"decision output missing term: {term}")

        no_overwrite = subprocess.run(
            [sys.executable, str(REVIEWER), "--project-root", str(project), "--write"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if no_overwrite.returncode != 2:
            errors.append("take reviewer should refuse to overwrite existing output without --allow-overwrite")

        write(
            project / "06_review" / "blind-review.md",
            """# Blind Review

## Scores

| take | alignment | preference | hook | artifact risk | decision |
|---|---:|---:|---:|---:|---|
| A02 | 4.8 | 4.7 | 4.8 | 0.8 | lock |
""",
        )
        incomplete_review = subprocess.run(
            [sys.executable, str(REVIEWER), "--project-root", str(project), "--strict"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if incomplete_review.returncode == 0:
            errors.append("strict take reviewer should reject incomplete score evidence")
        for term in ["repair review evidence", "Evidence status: incomplete", "Missing score fields: vocal_identity, groove, form"]:
            if term not in incomplete_review.stdout:
                errors.append(f"incomplete score review missing term: {term}")
        if "action: lock for post-production" in incomplete_review.stdout:
            errors.append("incomplete score evidence must not lock a take")

        write(
            project / "06_review" / "blind-review.md",
            """# Blind Review

## Scores

| take | alignment | preference | hook | vocal identity | groove | form | artifact risk | decision |
|---|---:|---:|---:|---:|---:|---:|---:|---|
| A02 | 4.8 | 4.6 | 2.5 | 4.7 | 4.6 | 4.6 | 0.5 | lock |
""",
        )
        low_core_review = subprocess.run(
            [sys.executable, str(REVIEWER), "--project-root", str(project), "--strict"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if low_core_review.returncode == 0:
            errors.append("strict take reviewer should reject a low-core-score best take")
        for term in ["controlled regeneration", "Core minimum: 2.50", "AI 音乐 Topline Hook 与旋律草稿工作流"]:
            if term not in low_core_review.stdout:
                errors.append(f"low-core-score review missing term: {term}")
        if "action: lock for post-production" in low_core_review.stdout:
            errors.append("low-core-score take must not lock")

        write(
            project / "06_review" / "blind-review.md",
            """# Blind Review

## Scores

| take | alignment | preference | hook | vocal identity | groove | form | artifact risk | decision |
|---|---:|---:|---:|---:|---:|---:|---:|---|
| A02 | 4.8 | 4.7 | 4.8 | 4.7 | 4.6 | 4.6 | 3.6 | lock |
""",
        )
        high_artifact_review = subprocess.run(
            [sys.executable, str(REVIEWER), "--project-root", str(project), "--strict"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if high_artifact_review.returncode == 0:
            errors.append("strict take reviewer should reject a high-artifact-risk best take")
        for term in ["controlled regeneration", "artifact risk", "AI 音乐 AI味伪影诊断与修复路由工作流"]:
            if term not in high_artifact_review.stdout:
                errors.append(f"high-artifact-risk review missing term: {term}")
        if "action: lock for post-production" in high_artifact_review.stdout:
            errors.append("high-artifact-risk take must not lock")

    review_page = WIKI_REVIEW.read_text(encoding="utf-8")
    project_page = WIKI_PROJECT.read_text(encoding="utf-8")
    log_text = LOG.read_text(encoding="utf-8")
    for term in [
        "tools/review_music_takes.py",
        "tools/audit_music_generation_evidence.py",
        "tools/audit_music_audio_seed_retention.py",
        "generation-evidence-audit.md",
        "audio-seed-retention-audit.md",
        "take-selection-decision.md",
        "--project-root",
        "--strict",
        "lock for post-production",
        "repair review evidence",
        "Required score fields",
    ]:
        if term not in review_page:
            errors.append(f"blind-review workflow missing reviewer term: {term}")
    for term in ["tools/review_music_takes.py", "tools/audit_music_generation_evidence.py", "tools/audit_music_audio_seed_retention.py", "generation-evidence-audit.md", "audio-seed-retention-audit.md", "take-selection-decision.md", "05_generations/take-ledger.md", "repair review evidence"]:
        if term not in project_page:
            errors.append(f"song project template missing reviewer term: {term}")
    for term in ["AI 音乐 Take 盲听决策工具", "AI 音乐 Take 盲听证据完整性闸门", "AI 音乐 Generation Evidence 工具闸门", "AI 音乐 Audio Seed Retention 工具闸门"]:
        if term not in log_text:
            errors.append(f"wiki log missing take reviewer entry: {term}")

    if errors:
        print("AI music take review decision verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music take review decision verification passed.")
    print(f"reviewer: {REVIEWER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
