#!/usr/bin/env python3
"""Verify the conditional human audio-seed retention gate."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
TOOL = ROOT / "tools" / "audit_music_audio_seed_retention.py"
WIKI_SEED = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐人类音频草稿到成品工作流.md")
WIKI_REVIEW = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐盲听评审与版本归档工作流.md")
WIKI_PROJECT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
WIKI_STATUS = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲制作总控与阶段闸门工作流.md")
WIKI_RIGHTS = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐权利发布与平台披露工作流.md")
WIKI_CATALOG = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐艺人身份与 Catalog Bible 工作流.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def scaffold_project(tmp_path: Path) -> Path:
    result = run(
        [
            sys.executable,
            str(SCAFFOLD),
            "--output-dir",
            str(tmp_path),
            "--date",
            "20260624",
            "--language",
            "zh",
            "--lane",
            "pop",
            "--slug",
            "night-bus",
            "--title",
            "Night Bus Confession",
            "--artist-project",
            "Example Test Artist",
            "--use-case",
            "demo",
        ]
    )
    if result.returncode != 0:
        raise AssertionError(result.stderr.strip())
    return tmp_path / "20260624_zh-pop_night-bus"


def mark_seed_required(project: Path) -> None:
    write(
        project / "04_prompt" / "persona-voice-model-routing.md",
        """# Persona Voice Model Routing

Human anchor lane: human audio seed
Feature type: Audio Upload
Voice identity source: none
Rights status: clear
""",
    )
    write(
        project / "04_prompt" / "prompt-package-v001.md",
        """# Prompt Package v001

Generated by: tools/compile_music_prompt_package.py
Decision: compile approved
Audio Influence: 65
Human Anchor Lane: human audio seed
""",
    )


def write_generation_audit(project: Path) -> None:
    write(
        project / "05_generations" / "generation-evidence-audit.md",
        f"""# Generation Evidence Audit

Generated by: tools/audit_music_generation_evidence.py
Project root: {project}
Decision: pass

## Generation Evidence

Take provenance tags: A01, A02
Batch tags: candidate ids, takes per candidate, total takes, generation date, expected listen order, anonymization rule
Provider metadata tags: A01, A02
Blind review handoff: ready
""",
    )


def write_passing_seed_evidence(project: Path) -> None:
    write(
        project / "02_references" / "human-seed-intent.md",
        """# Human Seed Intent

Seed purpose: melody
Why text prompt is not enough: the chorus title phrase needs a human-chosen contour
What must remain audible: title motif and phrase rhythm
""",
    )
    write(
        project / "02_references" / "audio-rights-ledger.md",
        """# Audio Rights Ledger

File: 02_references/audio/chorus-hum-v01.wav
Recorded by: Example Test Writer
Performer: Example Test Writer
Contains: vocal melody
Owner: Example Test Writer
Consent: yes
Commercial use: yes
Can upload to AI tool: yes
Can use in release: yes
Can use in Persona / Voice / Custom Model / Inspire: no
Third-party material: none
Tool: Audio Upload
Date: 2026-06-25
Reviewer: verifier
""",
    )
    write(
        project / "02_references" / "seed-type-classification.md",
        """# Seed Type Classification

Primary seed type: Melody seed
Secondary seed type: Vocal phrase
Section: chorus
Duration: 18s
Tempo / meter: 78 BPM / 4-4
Strongest audible feature: title motif lands on long vowel
Weakest audible feature: room noise
Keep: title motif, phrase rhythm, contour
May transform: arrangement, key, singer
Should ignore: room noise
""",
    )
    write(
        project / "02_references" / "capture-and-cleanup.md",
        """# Capture And Cleanup

Seed file: 02_references/audio/chorus-hum-v01.wav
Cleanup performed: trimmed silence and normalized level
What the model should hear: chorus motif
What the model should ignore: room tone
""",
    )
    write(
        project / "04_prompt" / "retention-target.md",
        """# Retention Target

Seed file: 02_references/audio/chorus-hum-v01.wav
Tool: Audio Upload
Primary retention: melody contour and phrase rhythm
Retention level: medium-high
Strict keep: title motif and long-note landing
Allowed transformations: key, arrangement, singer, production
Must change: demo noise and weak timing
Risk if over-retained: sounds like a raw memo expansion
Risk if under-retained: loses the human title hook
Listening proof: compare chorus A/B against seed after anonymized generation
""",
    )
    write(
        project / "04_prompt" / "prompt-pairing.md",
        """# Prompt Pairing

Audio seed: 02_references/audio/chorus-hum-v01.wav
Seed type: Melody seed
Retention target: keep title motif, phrase rhythm, long-note landing
Style prompt: Mandarin night pop-rock, live rhythm section, restrained chorus lift
Lyrics prompt: title phrase must land in chorus with stable vowels
Exclude: generic EDM drop, over-smoothed AI vocal, copied memo noise
Audio Influence: 65
""",
    )
    write_generation_audit(project)
    write(
        project / "06_review" / "anchor-retention-review.md",
        """# Anchor Retention Review

Seed: 02_references/audio/chorus-hum-v01.wav
Hidden take IDs: A01, A02
Seed identity: 4.2
Musical transformation: 4.0
Prosody fit: 4.3
Groove lock: 4.0
Vocal support: 4.1
Rights clarity: clear
Decision: keep
""",
    )


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, TOOL, WIKI_SEED, WIKI_REVIEW, WIKI_PROJECT, WIKI_STATUS, WIKI_RIGHTS, WIKI_CATALOG, LOG]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-audio-seed-") as tmp:
        project = scaffold_project(Path(tmp))

        no_seed = run([sys.executable, str(TOOL), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"])
        if no_seed.returncode != 0:
            errors.append(f"no-seed project should pass as not applicable: {no_seed.stderr.strip()}")
        no_seed_audit = (project / "06_review" / "audio-seed-retention-audit.md").read_text(encoding="utf-8")
        for term in ["Decision: not applicable", "Human audio seed required: no", "Blind review handoff: not applicable"]:
            if term not in no_seed_audit:
                errors.append(f"no-seed audit missing term: {term}")

        mark_seed_required(project)
        missing = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if missing.returncode == 0:
            errors.append("seeded project with missing evidence should fail strict mode")
        missing_text = missing.stdout + "\n" + missing.stderr
        for term in ["audio_rights_recorded_by_missing", "retention_target_seed_file_missing", "prompt_pairing_audio_seed_missing", "anchor_retention_review_seed_missing"]:
            if term not in missing_text:
                errors.append(f"missing seed evidence blocker absent: {term}")

        write_passing_seed_evidence(project)
        passing = run([sys.executable, str(TOOL), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"])
        if passing.returncode != 0:
            errors.append(f"complete seed evidence should pass: stdout={passing.stdout.strip()} stderr={passing.stderr.strip()}")
        audit_path = project / "06_review" / "audio-seed-retention-audit.md"
        audit = audit_path.read_text(encoding="utf-8")
        for term in [
            "Decision: pass",
            "## Audio Seed Evidence",
            "Seed rights tags:",
            "Retention target tags:",
            "Prompt pairing tags:",
            "Anchor retention tags:",
            "Blind review handoff: ready",
            "tools/audit_music_audio_seed_retention.py",
        ]:
            if term not in audit:
                errors.append(f"passing audit missing term: {term}")

        no_overwrite = run([sys.executable, str(TOOL), "--project-root", str(project), "--write", "--strict"])
        if no_overwrite.returncode != 2:
            errors.append("audio seed retention gate should refuse overwrite without --allow-overwrite")

        write(
            project / "06_review" / "anchor-retention-review.md",
            """# Anchor Retention Review

Seed: 02_references/audio/chorus-hum-v01.wav
Hidden take IDs: A01, A02
Seed identity: 2.0
Musical transformation: 2.5
Prosody fit: 3.5
Rights clarity: unknown
Decision: reseed
""",
        )
        blocked = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if blocked.returncode == 0:
            errors.append("bad anchor-retention scores and rights should fail strict mode")
        blocked_text = blocked.stdout + "\n" + blocked.stderr
        for term in ["seed_identity_below_floor", "musical_transformation_below_floor", "prosody_fit_below_floor", "anchor_retention_rights_not_clear", "anchor_retention_decision_not_keep"]:
            if term not in blocked_text:
                errors.append(f"bad anchor review blocker absent: {term}")

    for page, terms in [
        (WIKI_SEED, ["tools/audit_music_audio_seed_retention.py", "audio-seed-retention-audit.md", "anchor-retention-review.md"]),
        (WIKI_REVIEW, ["tools/audit_music_audio_seed_retention.py", "audio-seed-retention-audit.md", "anchor-retention-review.md"]),
        (WIKI_PROJECT, ["tools/audit_music_audio_seed_retention.py", "audio-seed-retention-audit.md", "audio-rights-ledger.md", "retention-target.md", "prompt-pairing.md"]),
        (WIKI_STATUS, ["audio-seed-retention-gate", "tools/audit_music_audio_seed_retention.py", "audio-seed-retention-audit.md"]),
        (WIKI_RIGHTS, ["tools/audit_music_audio_seed_retention.py", "audio-seed-retention-audit.md"]),
        (WIKI_CATALOG, ["tools/audit_music_audio_seed_retention.py", "audio-seed-retention-audit.md", "catalog-seed-hygiene.md"]),
    ]:
        text = page.read_text(encoding="utf-8")
        for term in terms:
            if term not in text:
                errors.append(f"{page.name} missing term: {term}")

    log_text = LOG.read_text(encoding="utf-8")
    if "AI 音乐 Audio Seed Retention 工具闸门" not in log_text:
        errors.append("wiki log missing Audio Seed Retention tool entry")

    if errors:
        print("AI music audio seed retention gate verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music audio seed retention gate verification passed.")
    print(f"tool: {TOOL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
