#!/usr/bin/env python3
"""Verify the AI music generation evidence gate."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
TOOL = ROOT / "tools" / "audit_music_generation_evidence.py"
WIKI_EXPERIMENT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐 Prompt 实验矩阵与版本收敛工作流.md")
WIKI_REVIEW = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐盲听评审与版本归档工作流.md")
WIKI_PROJECT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def prompt_package_text(project: Path) -> str:
    return f"""# Prompt Package v001

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Decision: compile approved

## Metadata

- Title: Night Bus Confession
- Model: Suno current
- Weirdness: 25
- Style Influence: 70
- Audio Influence: 0
- Human Anchor Lane: text-only
- Voice Identity Source: none
- Persona Source: none
- Custom Model Source: none
- Custom Model Corpus: none
- My Taste State: off
- Prompt Boost State: off
- Exclude: awkward translated Mandarin

## Style Of Music

```text
genre: "Mandarin night pop-rock"
vocal: "clear Mandarin diction, intimate verse"
instrumentation: "live drums, melodic bass, clean electric guitar"
production: "dry verse vocal, wide sparse chorus"
mood: "late-night confession"
```

## Lyrics

```text
[Verse 1]
line
[Chorus]
hook
[End]
```

## Prompt Rationale

- Reference audit: pass
Prosody audit: pass
- Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass

## Preflight Summary

| severity | code | message | route |
|---|---|---|---|
| pass | none | compile approved | experiment handoff |
"""


def prompt_preflight_text(project: Path) -> str:
    return f"""# Prompt Preflight Review

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Prompt package: 04_prompt/prompt-package-v001.md

Field completeness: pass
Lyrics context: pass
Reference audit: pass
Prosody audit: pass
Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass
Exclude rationale: pass
Slider intent: pass
Model/version: pass
Human anchor lane: pass
Identity routing: pass
My Taste / boost: pass
Identity / rights: pass
Conflict check: pass

Decision: compile approved

Blockers: 0

## Issues
"""


def prompt_iteration_discipline_audit(project: Path) -> str:
    return f"""# Prompt Iteration Discipline Audit

Generated by: tools/audit_music_prompt_iteration_discipline.py
Project root: {project}
Decision: pass

## Prompt Iteration Discipline Evidence

Experiment question: compare C01 baseline with C02 Style Influence change
Frozen brief: complete
Allowed variable count: 1
Changed variables: style influence
Candidate hypotheses: present; candidates=C01, C02
Batch discipline: candidates=C01, C02, total=4
Attribution strength: strong
Generation evidence handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | no blocking findings | proceed |
"""


def write_good_generation_evidence(project: Path) -> None:
    write(project / "04_prompt" / "prompt-package-v001.md", prompt_package_text(project))
    write(project / "04_prompt" / "prompt-preflight-review.md", prompt_preflight_text(project))
    write(project / "05_generations" / "prompt-iteration-discipline-audit.md", prompt_iteration_discipline_audit(project))
    write(
        project / "05_generations" / "batch-generation-plan.md",
        """# Batch Generation Plan

Candidate IDs: C01, C02
Takes per candidate: 1
Total takes: 2
Generation date: 2026-06-25
Expected listen order: A02, A01
Anonymization rule: randomize filenames before blind review

## Variables

- C01: baseline prompt
- C02: lower Weirdness, same lyrics
""",
    )
    write(
        project / "05_generations" / "take-ledger.md",
        """# Take Ledger

| take id | prompt package | provider/model | settings | source audio | persona/voice | first impression | known issue | review status |
|---|---|---|---|---|---|---|---|---|
| A01 | 04_prompt/prompt-package-v001.md | Suno current | W25/S70/A0 | 05_generations/audio/A01.wav | fictional singer | pretty but generic | weak hook | ready for blind review |
| A02 | 04_prompt/prompt-package-v001.md | Suno current | W25/S70/A0 | 05_generations/audio/A02.wav | fictional singer | title hook lands | none | reviewed |
""",
    )
    write(
        project / "05_generations" / "provider-result-ledger.md",
        """# Provider Result Ledger

| take id | provider/model | settings | generated url | downloaded file | prompt package | metadata | status |
|---|---|---|---|---|---|---|---|
| A01 | Suno current | W25/S70/A0 | https://example.test/A01 | 05_generations/audio/A01.wav | 04_prompt/prompt-package-v001.md | 05_generations/metadata/A01-settings.md | exported |
| A02 | Suno current | W25/S70/A0 | https://example.test/A02 | 05_generations/audio/A02.wav | 04_prompt/prompt-package-v001.md | 05_generations/metadata/A02-settings.md | exported |
""",
    )
    (project / "05_generations" / "audio").mkdir(parents=True, exist_ok=True)
    (project / "05_generations" / "audio" / "A01.wav").write_bytes(b"RIFF0000WAVE")
    (project / "05_generations" / "audio" / "A02.wav").write_bytes(b"RIFF0000WAVE")
    write(project / "05_generations" / "metadata" / "A01-settings.md", "Take: A01\nProvider/model: Suno current\nSettings: W25/S70/A0\nPrompt package: 04_prompt/prompt-package-v001.md\n")
    write(project / "05_generations" / "metadata" / "A02-settings.md", "Take: A02\nProvider/model: Suno current\nSettings: W25/S70/A0\nPrompt package: 04_prompt/prompt-package-v001.md\n")


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, TOOL, WIKI_EXPERIMENT, WIKI_REVIEW, WIKI_PROJECT, LOG]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-generation-evidence-") as tmp:
        tmp_path = Path(tmp)
        scaffold = run(
            [
                sys.executable,
                str(SCAFFOLD),
                "--output-dir",
                str(tmp_path),
                "--date",
                "20260624",
                "--language",
                "zh",
                "--lane",
                "pop",
                "--slug",
                "night-bus",
                "--title",
                "Night Bus Confession",
                "--artist-project",
                "Example Test Artist",
                "--use-case",
                "demo",
            ]
        )
        if scaffold.returncode != 0:
            errors.append(f"scaffold failed: {scaffold.stderr.strip()}")
            print("\n".join(errors), file=sys.stderr)
            return 1

        project = tmp_path / "20260624_zh-pop_night-bus"
        empty = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if empty.returncode == 0:
            errors.append("strict generation evidence audit should reject empty scaffold")
        empty_text = empty.stdout + "\n" + empty.stderr
        for term in ["prompt_iteration_discipline_not_passed", "prompt_package_not_approved", "batch_plan_missing", "no_take_rows"]:
            if term not in empty_text:
                errors.append(f"empty scaffold audit missing blocker: {term}")

        write_good_generation_evidence(project)
        ok = run(
            [
                sys.executable,
                str(TOOL),
                "--project-root",
                str(project),
                "--write",
                "--allow-overwrite",
                "--strict",
            ]
        )
        if ok.returncode != 0:
            errors.append(f"generation evidence audit should pass: stdout={ok.stdout.strip()} stderr={ok.stderr.strip()}")

        output = project / "05_generations" / "generation-evidence-audit.md"
        if not output.exists():
            errors.append("missing generation-evidence-audit.md output")
        else:
            text = output.read_text(encoding="utf-8")
            for term in [
                "Generation Evidence Audit",
                "Generated by: tools/audit_music_generation_evidence.py",
                "Decision: pass",
                "## Generation Evidence",
                "Take provenance tags: A01, A02",
                "Batch tags:",
                "Provider metadata tags: A01, A02",
                "Blind review handoff: ready",
                "## Repair Route",
            ]:
                if term not in text:
                    errors.append(f"generation evidence output missing term: {term}")

        no_overwrite = run([sys.executable, str(TOOL), "--project-root", str(project), "--write"])
        if no_overwrite.returncode != 2:
            errors.append("generation evidence audit should refuse overwrite without --allow-overwrite")

        real_prompt_iteration = (project / "05_generations" / "prompt-iteration-discipline-audit.md").read_text(encoding="utf-8")
        write(project / "05_generations" / "prompt-iteration-discipline-audit.md", "# Prompt Iteration Discipline Audit\n\nDecision: pass\n")
        fake_prompt_iteration = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if fake_prompt_iteration.returncode == 0:
            errors.append("generation evidence audit should reject hand-written prompt iteration discipline audit")
        fake_prompt_iteration_text = fake_prompt_iteration.stdout + "\n" + fake_prompt_iteration.stderr
        for term in ["tools/audit_music_prompt_iteration_discipline.py", "prompt_iteration_discipline_not_passed"]:
            if term not in fake_prompt_iteration_text:
                errors.append(f"fake prompt iteration audit blocker missing term: {term}")
        write(project / "05_generations" / "prompt-iteration-discipline-audit.md", real_prompt_iteration)

        write(
            project / "05_generations" / "take-ledger.md",
            """# Take Ledger

| take id | prompt package | provider/model | settings | source audio | persona/voice | first impression | known issue | review status |
|---|---|---|---|---|---|---|---|---|
| A01 | 04_prompt/prompt-package-v001.md | Suno current | W25/S70/A0 | 05_generations/audio/A01.wav | fictional singer | pretty | none | ready for blind review |
| A01 | 04_prompt/prompt-package-v001.md | Suno current | W25/S70/A0 | none | fictional singer | duplicate | weak hook | reviewed |
| A03 | 04_prompt/prompt-package-v001.md | Suno current | W25/S70/A0 | 05_generations/audio/A03.wav | fictional singer | interesting | AI vocal tail | reviewed |
""",
        )
        write(
            project / "05_generations" / "provider-result-ledger.md",
            """# Provider Result Ledger

| take id | provider/model | settings | generated url | downloaded file | prompt package | metadata | status |
|---|---|---|---|---|---|---|---|
| A01 | Suno current | W25/S70/A0 | https://example.test/A01 | 05_generations/audio/A01.wav | 04_prompt/prompt-package-v001.md | 05_generations/metadata/A01-settings.md | exported |
""",
        )
        bad = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if bad.returncode == 0:
            errors.append("generation evidence audit should reject duplicate/missing-source/provider gaps")
        bad_text = bad.stdout + "\n" + bad.stderr
        for term in ["duplicate_take_id", "take_source_missing", "provider_row_missing", "take_audio_file_missing"]:
            if term not in bad_text:
                errors.append(f"bad evidence audit missing blocker: {term}")

        write(project / "04_prompt" / "prompt-package-v001.md", "# Prompt Package v001\n\nDecision: compile approved\n")
        stale = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        stale_text = stale.stdout + "\n" + stale.stderr
        if "prompt_package_not_approved" not in stale_text:
            errors.append("stale prompt package should be rejected by generation evidence audit")

    experiment_page = WIKI_EXPERIMENT.read_text(encoding="utf-8")
    review_page = WIKI_REVIEW.read_text(encoding="utf-8")
    project_page = WIKI_PROJECT.read_text(encoding="utf-8")
    log_text = LOG.read_text(encoding="utf-8")
    for page, label in [(experiment_page, "experiment"), (review_page, "review"), (project_page, "project")]:
        for term in ["tools/audit_music_prompt_iteration_discipline.py", "prompt-iteration-discipline-audit.md", "tools/audit_music_generation_evidence.py", "generation-evidence-audit.md", "provider-result-ledger.md", "take-ledger.md"]:
            if term not in page:
                errors.append(f"{label} wiki page missing generation evidence term: {term}")
    for term in ["AI 音乐 Prompt Iteration Discipline 工具闸门", "AI 音乐 Generation Evidence 工具闸门"]:
        if term not in log_text:
            errors.append(f"wiki log missing generation evidence gate entry: {term}")

    if errors:
        print("AI music generation evidence gate verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music generation evidence gate verification passed.")
    print(f"tool: {TOOL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
