#!/usr/bin/env python3
"""Verify the AI music song project status audit tool."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
TOOL = ROOT / "tools" / "audit_music_song_project_status.py"
LISTENER = ROOT / "tools" / "audit_music_release_listener_evidence.py"
POST_MIX = ROOT / "tools" / "audit_music_post_production_mix_lock.py"
PROMPT_ITERATION = ROOT / "tools" / "audit_music_prompt_iteration_discipline.py"
WIKI_WORKFLOW = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲制作总控与阶段闸门工作流.md")
WIKI_TEMPLATE = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def generated_methodology_audit(project: Path) -> str:
    return f"""# Methodology Transfer Audit

Decision: pass

## Methodology Transfer Evidence

Local source root: /path/to/suno-prompt-methodology
Local source status: ready
External method claims: pass
Source confidence split: official facts, local local Suno prompt methodology, community/external candidates
Official control surfaces: Style of Music, Lyrics box, Exclude, Creative Sliders
Community candidates: candidate experiments only
Model/version rationale: Suno current for fixture; real projects recheck current model behavior
Primary tool route: Custom Mode text-only
Human-likeness transfer: dry close vocal, section tags, Exclude, one-variable iteration
Song-specific transfer: Mandarin night pop-rock title hook and close vocal prompt
Variable discipline: one primary variable, fixed title phrase and rights boundary
Anti-magic safeguards: reject guaranteed-hit tags and celebrity-copy prompts
Protected-identity safeguard: neutral style DNA only
Validation metric: blind title recall and AI-flavor survey
Rollback condition: return to style/exclude/slider inputs
Source freshness: checked 2026-06-25

Generated by: tools/audit_music_methodology_transfer.py
Project root: {project}
"""


def generated_specificity_audit(project: Path) -> str:
    return f"""# Prompt Specificity Budget Audit

Generated by: tools/audit_music_prompt_specificity_budget.py
Project root: {project}
Decision: pass

## Specificity Budget Evidence

Style source: 04_prompt/style-field-map.md
Budget source: 04_prompt/field-length-and-specificity-budget.md
Methodology transfer: pass
Style specificity tags: Mandarin night pop-rock, close mid-low female lead, live drums, melodic bass, clean electric guitar, dry verse vocal, wide but sparse chorus
Recording realism tags: dry, wide
Performance realism tags: lead vocal, drums, bass
Section/director tags: verse, chorus, title phrase, hook
Field budget tags: must-hear=dry verse vocal, melodic bass, title phrase hook, decision=ready
Vague term removals: none after replacement
Protected identity check: pass
Prompt compile handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | specificity budget approved | prompt compile |
"""


def generated_genre_lane_authenticity_audit(project: Path) -> str:
    return f"""# Genre Lane Authenticity Audit

Generated by: tools/audit_music_genre_lane_authenticity.py
Project root: {project}
Decision: pass

## Genre/Lane Evidence

Prompt specificity: pass
Primary lane: Mandarin night pop-rock
Genre terms detected: pop, rock
Language lane: Mandarin
Secondary lane purpose: pop hook compression with rock rhythm-section push
Era / scene anchor: 2020s Mandarin night-commute playlist
Tempo / meter: 96 BPM 4/4
Vocal lane: close mid-low female lead, clear Mandarin diction
Arrangement lane: live drums, melodic bass, clean electric guitar
Production lane: dry close verse vocal, wider chorus stereo
Lyric stance: first-person commuter
Hook mechanism: title phrase hook in chorus
Style-lyric fit: pass
Arrangement fit: pass
Production fit: pass
Anti-drift / exclude plan: random genre switch, generic AI pop gloss, EDM drop
Genre/lane authenticity: pass
Prompt compile handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | genre/lane authenticity approved | prompt compile |
"""


def generated_lyric_narrative_audit(project: Path) -> str:
    return f"""# Lyric Narrative Audit

Generated by: tools/audit_music_lyric_narrative.py
Project root: {project}
Decision: pass

## Lyric Narrative Evidence

Narrator/situation tags: first-person commuter; last bus after rain
Concrete image tags: bus window, unsent phone message, paper ticket, empty seat
Title phrase function: the bus light is the last chance to confess
Central metaphor: last bus light as held breath
Section information tags: verse 1, chorus, verse 2, bridge, final chorus
Cliche removal: removed=forever, lonely heart, replacements=unsent message, wet paper ticket
Verse 2 development: new information reveals the empty seat and unsent message
Bridge perspective: turn from blaming timing to admitting chosen silence
Lyrics rewrite handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | lyric narrative approved | prompt compile |
"""


def generated_prompt_package(project: Path) -> str:
    return f"""# Prompt Package v001

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Decision: compile approved

## Metadata

- Title: Night Bus Confession
- Model: Suno current
- Weirdness: 25
- Style Influence: 70
- Human Anchor Lane: text-only
- Voice Identity Source: none
- Persona Source: none
- Custom Model Source: none
- Custom Model Corpus: none
- My Taste State: off
- Prompt Boost State: off
- Exclude: awkward translated Mandarin
- Methodology transfer: pass
- Prompt specificity: pass
- Genre/lane authenticity: pass
- Lyric narrative: pass
- Reference audit: pass
Prosody audit: pass
- Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass

## Style Of Music

```text
genre: "Mandarin night pop-rock"
vocal: "close mid-low female lead"
instrumentation: "live drums, melodic bass, clean electric guitar"
production: "dry verse vocal, wide but sparse chorus"
mood: "late-night confession"
```

## Lyrics

```text
[Verse 1]
line
[Chorus]
hook
[End]
```

## Prompt Rationale

- Why these exclusions: avoid generic gloss

## Preflight Summary

| severity | code | message | route |
|---|---|---|---|
| pass | none | compile approved | experiment handoff |
"""


def generated_prompt_preflight(project: Path) -> str:
    return f"""# Prompt Preflight Review

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Prompt package: 04_prompt/prompt-package-v001.md

Field completeness: pass
Style specificity: pass
Lyrics context: pass
Prosody risk: pass
Methodology transfer: pass
Prompt specificity: pass
Genre/lane authenticity: pass
Lyric narrative: pass
Reference audit: pass
Prosody audit: pass
Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass
Hook clarity: pass
Exclude rationale: pass
Slider intent: pass
Model/version: pass
Human anchor lane: pass
Identity routing: pass
My Taste / boost: pass
Identity / rights: pass
Variable discipline: review
Conflict check: pass

Decision: compile approved

Blockers: 0

## Issues
"""


def release_audio_report(project: Path) -> str:
    return f"""# Release Audio Technical Inspection

Generated by: tools/inspect_music_release_audio.py
Project root: {project}
Decision: pass

## Results

| file | duration | sample rate | bit depth | channels | peak | RMS | DC offset | clipped ratio | status |
|---|---:|---:|---:|---:|---:|---:|---:|---:|---|
| 11_release/release_candidate/audio/night-bus-master.wav | 1.00s | 44100 | 16 | 2 | 0.3662 | 0.2589 | 0.00000 | 0.000000 | pass |

## Blocking Items

- none
"""


def release_audio_qc_report(project: Path) -> str:
    return f"""# Release Audio QC Report

Generated by: tools/prepare_music_release_audio_qc.py
Project root: {project}
Decision: pass

## Required Evidence

| evidence | file | status | decision | missing terms | blockers |
|---|---|---|---|---|---|
| loudness true peak report | 10_mix-master/loudness-true-peak-report.md | pass | pass |  |  |
| codec preview | 10_mix-master/codec-preview.md | pass | pass |  |  |
| translation listen matrix | 10_mix-master/translation-listen-matrix.md | pass | pass |  |  |
| mono phase low-end check | 10_mix-master/mono-phase-low-end-check.md | pass | pass |  |  |
| transient and limiter audit | 10_mix-master/transient-and-limiter-audit.md | pass | pass |  |  |

## Measurements

- integrated LUFS: -14.0
- LRA: 6.0
- True Peak: -1.0 dBTP
- clipped samples: 0
- sample rate: 44100
- bit depth: 16

## Listening

- loudness-matched reference A/B: pass
- codec preview: pass
- translation matrix: pass
- mono/phase: pass
- low end: pass
- intro/outro: pass

## AI Artifact Check

- vocal tail: pass
- cymbals: pass
- backing vocal smear: none
- stem bleed: none
- over-limiting: none

## Deliverable

- approved file: 11_release/release_candidate/audio/night-bus-master.wav
- rejected files: none
- platform notes: codec and platform previews passed

## Blocking Items

- none
"""


def generation_evidence_audit(project: Path) -> str:
    return f"""# Generation Evidence Audit

Generated by: tools/audit_music_generation_evidence.py
Project root: {project}
Decision: pass

## Generation Evidence

Take provenance tags: A01, A02
Batch tags: candidate ids, takes per candidate, total takes, generation date, expected listen order, anonymization rule
Provider metadata tags: A01, A02
Blind review handoff: ready
"""


def generated_prompt_iteration_discipline_audit(project: Path) -> str:
    return f"""# Prompt Iteration Discipline Audit

Generated by: tools/audit_music_prompt_iteration_discipline.py
Project root: {project}
Decision: pass

## Prompt Iteration Discipline Evidence

Experiment question: compare C01 baseline with C02 Style Influence change
Frozen brief: complete
Allowed variable count: 1
Changed variables: style influence
Candidate hypotheses: present; candidates=C01, C02
Batch discipline: candidates=C01, C02, total=4
Attribution strength: strong
Generation evidence handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | no blocking findings | proceed |
"""


def generated_post_production_mix_lock_audit(project: Path) -> str:
    return f"""# Post Production Mix Lock Audit

Generated by: tools/audit_music_post_production_mix_lock.py
Project root: {project}
Decision: pass

## Post Production Mix Lock Evidence

Locked take: A02
Arrangement density tags: sections=complete; action=yes
Vocal center: dry centered lead vocal stays above the guitar bed
Low-end/kick-bass: kick transient and bass sustain are separated
Space/dynamics automation: dry verse, wider chorus, pad ducking under vocal
Transition/outro: bridge breath and resolved final tail
AI artifact repair: cymbal smear and vocal tail blur resolved
Stem/DAW handoff: ready
Reference A/B: loudness-matched internal reference passed
Mix lock handoff: pass

## Findings

| severity | code | message | route |
|---|---|---|---|
| pass | none | no blocking findings | proceed |
"""


def write_listener_audit(project: Path) -> None:
    write(
        project / "06_review" / "external-listener-panel.md",
        """# External Listener Panel

Target audience: late-night Mandarin pop listeners
Panel size: 6
Blind condition: prompt and provider hidden
AI flavor red flags: none
Release listener verdict: pass
Decision: pass
""",
    )
    write(
        project / "06_review" / "first-20-second-test.md",
        """# First 20 Second Test

Skip risk: low
First 20 second decision: pass
Synthetic / fake feeling: none
Decision: pass
""",
    )
    write(
        project / "06_review" / "hook-memory-test.md",
        """# Hook Memory Test

Hook recalled: yes
Title phrase remembered: 末班车还亮着
Memory result: pass
Decision: pass
""",
    )
    write(
        project / "06_review" / "ai-flavor-red-flag-survey.md",
        """# AI Flavor Red Flag Survey

AI flavor red flags: none
AI flavor release verdict: pass
Severity 0-3: 0
Decision: pass
""",
    )
    result = run(
        [
            sys.executable,
            str(LISTENER),
            "--project-root",
            str(project),
            "--write",
            "--allow-overwrite",
            "--strict",
        ]
    )
    if result.returncode != 0:
        raise AssertionError(result.stderr.strip())


def audit(project: Path) -> str:
    result = run([sys.executable, str(TOOL), "--project-root", str(project), "--write", "--allow-overwrite"])
    if result.returncode != 0:
        raise AssertionError(result.stderr.strip())
    return (project / "00_admin" / "song-production-control-board.md").read_text(encoding="utf-8")


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, TOOL, LISTENER, POST_MIX, PROMPT_ITERATION, WIKI_WORKFLOW, WIKI_TEMPLATE]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-status-audit-") as tmp:
        tmp_path = Path(tmp)
        scaffold = run(
            [
                sys.executable,
                str(SCAFFOLD),
                "--output-dir",
                str(tmp_path),
                "--date",
                "20260624",
                "--language",
                "zh",
                "--lane",
                "pop",
                "--slug",
                "night-bus",
                "--title",
                "Night Bus Confession",
                "--artist-project",
                "Example Test Artist",
                "--use-case",
                "release-single",
            ]
        )
        if scaffold.returncode != 0:
            errors.append(f"scaffold failed: {scaffold.stderr.strip()}")
            print("\n".join(errors), file=sys.stderr)
            return 1
        project = tmp_path / "20260624_zh-pop_night-bus"

        board = audit(project)
        for term in ["Current stage: methodology-transfer-gate", "audit_music_methodology_transfer.py", "methodology transfer"]:
            if term not in board:
                errors.append(f"empty project board missing term: {term}")

        write(project / "04_prompt" / "methodology-transfer-audit.md", generated_methodology_audit(project))

        board = audit(project)
        for term in ["Current stage: prompt-specificity-gate", "audit_music_prompt_specificity_budget.py", "prompt specificity budget audit"]:
            if term not in board:
                errors.append(f"methodology-ready board missing specificity term: {term}")

        write(project / "04_prompt" / "prompt-specificity-budget-audit.md", generated_specificity_audit(project))

        board = audit(project)
        for term in ["Current stage: genre-lane-authenticity-gate", "audit_music_genre_lane_authenticity.py", "genre/lane authenticity"]:
            if term not in board:
                errors.append(f"specificity-ready board missing genre/lane authenticity term: {term}")

        write(project / "04_prompt" / "genre-lane-authenticity-audit.md", generated_genre_lane_authenticity_audit(project))

        board = audit(project)
        for term in ["Current stage: lyric-narrative-gate", "audit_music_lyric_narrative.py", "lyric narrative"]:
            if term not in board:
                errors.append(f"genre-lane-ready board missing lyric narrative term: {term}")

        write(project / "03_writing" / "lyric-narrative-audit.md", generated_lyric_narrative_audit(project))

        write(
            project / "04_prompt" / "prompt-package-v001.md",
            """# Prompt Package v001

genre: Mandarin night pop-rock
vocal: close mid-low female lead
instrumentation: live drums, melodic bass, clean electric guitar
production: dry verse vocal, wide but sparse chorus
mood: late-night confession
""",
        )
        board = audit(project)
        for term in ["Current stage: prompt-compile-gate", "prompt preflight"]:
            if term not in board:
                errors.append(f"package-without-preflight board missing term: {term}")

        write(
            project / "04_prompt" / "prompt-preflight-review.md",
            """# Prompt Preflight Review

Decision: compile approved
Field completeness: pass
Identity / rights: pass
Slider intent: pass
Model/version: pass
Conflict check: pass
""",
        )
        board = audit(project)
        for term in ["Current stage: prompt-compile-gate", "compiler-generated prompt package"]:
            if term not in board:
                errors.append(f"handwritten prompt evidence board missing term: {term}")
        if "review_music_takes.py" in board:
            errors.append("handwritten prompt package/preflight must not advance to take review")

        write(
            project / "04_prompt" / "prompt-package-v001.md",
            generated_prompt_package(project),
        )
        write(
            project / "04_prompt" / "prompt-preflight-review.md",
            """# Prompt Preflight Review

Generated by: tools/compile_music_prompt_package.py
Decision: compile approved
Field completeness: pass
Identity / rights: pass
Slider intent: fail
Model/version: fail
Conflict check: pass
""",
        )
        board = audit(project)
        for term in ["Current stage: prompt-compile-gate", "prompt preflight"]:
            if term not in board:
                errors.append(f"bad-slider-preflight board missing term: {term}")
        if "review_music_takes.py" in board:
            errors.append("bad slider preflight must not advance to take review")

        write(
            project / "04_prompt" / "prompt-preflight-review.md",
            """# Prompt Preflight Review

Generated by: tools/compile_music_prompt_package.py
Decision: compile approved
Field completeness: pass
Lyrics context: pass
Exclude rationale: pass
Slider intent: pass
Model/version: pass
Identity / rights: pass
Conflict check: pass
Blockers: 0

## Issues
""",
        )
        board = audit(project)
        for term in ["Current stage: prompt-compile-gate", "prompt preflight"]:
            if term not in board:
                errors.append(f"old-human-anchor-preflight board missing term: {term}")
        if "review_music_takes.py" in board:
            errors.append("old prompt preflight without human anchor fields must not advance to take review")

        write(
            project / "04_prompt" / "prompt-package-v001.md",
            """# Prompt Package v001

Generated by: tools/compile_music_prompt_package.py
Decision: compile approved

## Metadata

- Title: Night Bus Confession
- Model: Suno current
- Weirdness: 25
- Style Influence: 70
- Exclude: awkward translated Mandarin

## Style Of Music

```text
genre: "Mandarin night pop-rock"
vocal: "close mid-low female lead"
instrumentation: "live drums, melodic bass, clean electric guitar"
production: "dry verse vocal, wide but sparse chorus"
mood: "late-night confession"
```

## Lyrics

```text
[Verse 1]
line
[Chorus]
hook
[End]
```

## Prompt Rationale

- Why these exclusions: avoid generic gloss

## Preflight Summary
""",
        )
        write(
            project / "04_prompt" / "prompt-preflight-review.md",
            generated_prompt_preflight(project),
        )
        board = audit(project)
        for term in ["Current stage: prompt-compile-gate", "compiler-generated prompt package"]:
            if term not in board:
                errors.append(f"old-human-anchor-package board missing term: {term}")
        if "review_music_takes.py" in board:
            errors.append("old prompt package without human anchor fields must not advance to take review")

        write(project / "04_prompt" / "prompt-package-v001.md", generated_prompt_package(project))
        board = audit(project)
        for term in ["Current stage: prompt-iteration-discipline-gate", "audit_music_prompt_iteration_discipline.py", "prompt iteration discipline audit is missing or not passed"]:
            if term not in board:
                errors.append(f"prompt-ready-before-iteration-audit board missing term: {term}")

        write(project / "05_generations" / "prompt-iteration-discipline-audit.md", generated_prompt_iteration_discipline_audit(project))
        board = audit(project)
        for term in ["Current stage: prompt-experiment-gate", "audit_music_generation_evidence.py", "generation evidence audit is missing or not passed"]:
            if term not in board:
                errors.append(f"prompt-iteration-ready-before-generation-audit board missing term: {term}")

        write(project / "05_generations" / "generation-evidence-audit.md", generation_evidence_audit(project))
        board = audit(project)
        for term in ["Current stage: take-selection-gate", "review_music_takes.py"]:
            if term not in board:
                errors.append(f"generation-evidence-ready board missing term: {term}")

        write(
            project / "06_review" / "take-selection-decision.md",
            """# Take Selection Decision

Best take: A02
Action: repair review evidence
Evidence status: incomplete
Missing score fields: vocal_identity, groove, form, artifact_risk
Composite score: 4.55
Core minimum: 4.10
Primary route: complete missing blind-review score fields
""",
        )
        board = audit(project)
        for term in ["Current stage: take-selection-gate", "review_music_takes.py", "no scored best-take decision found"]:
            if term not in board:
                errors.append(f"incomplete take decision board missing term: {term}")
        if "route_music_repairs.py" in board:
            errors.append("incomplete take decision must not advance to repair routing")

        write(
            project / "06_review" / "take-selection-decision.md",
            """# Take Selection Decision

Best take: A02
Action: repair candidate
Composite score: 4.05
Core minimum: 3.70
Primary route: AI 音乐 Topline Hook 与旋律草稿工作流
""",
        )
        write(
            project / "07_repair" / "repair-route-map.md",
            """| problem | layer | severity | repair route | expected output | regression listen |
|---|---|---:|---|---|---|
| chorus hook or title phrase is weak | topline | 2 | AI 音乐 Topline Hook 与旋律草稿工作流 | 03_writing/topline-map.md | 20-30 second hook memory test improves |
""",
        )
        board = audit(project)
        for term in ["Current stage: repair-regression-gate", "regression-listen.md", "unresolved local repair route"]:
            if term not in board:
                errors.append(f"unverified local repair board missing term: {term}")
        if "prepare_music_release_candidate.py" in board or "prepare_music_daw_handoff.py" in board:
            errors.append("unverified local repair must not advance to DAW or release")

        write(
            project / "07_repair" / "regression-listen.md",
            """# Regression Listen

Decision: keep
Did issue improve? 0-3: 2.5
New artifacts introduced: no
Hook preserved: yes
Vocal identity preserved: yes
Groove preserved: yes
""",
        )
        board = audit(project)
        for term in ["Current stage: take-selection-gate", "repair regression passed", "review_music_takes.py"]:
            if term not in board:
                errors.append(f"verified local repair board missing term: {term}")
        if "prepare_music_release_candidate.py" in board:
            errors.append("verified repair still needs refreshed take review before release")

        write(
            project / "06_review" / "take-selection-decision.md",
            """# Take Selection Decision

Best take: A02
Action: lock for post-production
Composite score: 4.55
Core minimum: 4.10
Primary route: AI 音乐编曲密度与混音后期修作工作流
""",
        )
        write(project / "07_repair" / "repair-route-map.md", "# Repair Route Map\n\n")
        board = audit(project)
        for term in ["Current stage: repair-routing-gate", "route_music_repairs.py"]:
            if term not in board:
                errors.append(f"take-ready board missing term: {term}")

        write(
            project / "07_repair" / "repair-route-map.md",
            """| problem | layer | severity | repair route | expected output | regression listen |
|---|---|---:|---|---|---|
| hi-hat artifact | mix/post | 1 | AI 音乐编曲密度与混音后期修作工作流 | mix-plan.md | artifact lower, hook preserved |
""",
        )
        board = audit(project)
        for term in ["Current stage: daw-humanization-gate", "prepare_music_daw_handoff.py"]:
            if term not in board:
                errors.append(f"repair-ready board missing term: {term}")

        write(
            project / "08_stems-daw" / "session-pack.md",
            """# Session Pack

Generated by: tools/prepare_music_daw_handoff.py
Locked take: A02
""",
        )
        board = audit(project)
        for term in ["Current stage: post-production-mix-lock-gate", "audit_music_post_production_mix_lock.py", "post-production mix-lock audit"]:
            if term not in board:
                errors.append(f"daw-ready board missing post-production mix-lock term: {term}")

        write(project / "10_mix-master" / "post-production-mix-lock-audit.md", generated_post_production_mix_lock_audit(project))
        board = audit(project)
        for term in ["Current stage: release-listener-gate", "audit_music_release_listener_evidence.py"]:
            if term not in board:
                errors.append(f"post-production-ready board missing term: {term}")

        write_listener_audit(project)
        board = audit(project)
        for term in ["Current stage: release-rights-gate", "prepare_music_release_candidate.py"]:
            if term not in board:
                errors.append(f"listener-ready board missing term: {term}")

        write(
            project / "10_mix-master" / "release-audio-technical-inspection.md",
            """# Release Audio Technical Inspection

Decision: pass
Generated by: tools/inspect_music_release_audio.py
""",
        )
        write(
            project / "10_mix-master" / "release-audio-qc-report.md",
            release_audio_qc_report(project),
        )
        write(
            project / "11_release" / "release-candidate-rights-gate.md",
            """# Release Candidate Rights Gate

Generated by: tools/prepare_music_release_candidate.py
Decision: hold
Blocking Items:
- unresolved rights
""",
        )
        board = audit(project)
        for term in ["Current stage: release-rights-gate", "prepare_music_release_candidate.py"]:
            if term not in board:
                errors.append(f"hold release gate board missing term: {term}")
        if "prepare_music_catalog_memory.py" in board:
            errors.append("hold release gate must not advance to catalog memory")

        write(
            project / "11_release" / "release-candidate-rights-gate.md",
            """# Release Candidate Rights Gate

Generated by: tools/prepare_music_release_candidate.py
Decision: approve release-candidate
""",
        )
        board = audit(project)
        for term in ["Current stage: release-rights-gate", "release-candidate audit/package/manifest"]:
            if term not in board:
                errors.append(f"approved release without generated pack board missing term: {term}")
        if "prepare_music_catalog_memory.py" in board:
            errors.append("approved release gate without generated release pack must not advance to catalog memory")

        write(
            project / "11_release" / "release-candidate-evidence-audit.md",
            """# Release Candidate Evidence Audit

Generated by: tools/prepare_music_release_candidate.py
Decision: approve release-candidate
Blocking Items:
- none
""",
        )
        write(
            project / "11_release" / "release-candidate-package.md",
            """# Release Candidate Package

Generated by: tools/prepare_music_release_candidate.py
Decision: approve release-candidate
""",
        )
        write(
            project / "11_release" / "release_candidate" / "metadata" / "release-candidate-manifest.md",
            """# Release Candidate Manifest

Generated by: tools/prepare_music_release_candidate.py
Decision: approve release-candidate
""",
        )
        board = audit(project)
        for term in ["Current stage: release-rights-gate", "release-audio-technical-inspection.md is not tool-generated with metrics"]:
            if term not in board:
                errors.append(f"approved release with fake audio inspection board missing term: {term}")
        if "prepare_music_catalog_memory.py" in board:
            errors.append("approved release gate with fake audio inspection must not advance to catalog memory")

        write(project / "10_mix-master" / "release-audio-technical-inspection.md", release_audio_report(project))
        write(
            project / "11_release" / "release-candidate-rights-gate.md",
            """# Release Candidate Rights Gate

Decision: approve release-candidate
""",
        )
        board = audit(project)
        for term in ["Current stage: release-rights-gate", "not generated by tools/prepare_music_release_candidate.py"]:
            if term not in board:
                errors.append(f"handwritten approved release gate board missing term: {term}")
        if "prepare_music_catalog_memory.py" in board:
            errors.append("handwritten approved release gate must not advance to catalog memory")

        write(
            project / "11_release" / "release-candidate-rights-gate.md",
            """# Release Candidate Rights Gate

Generated by: tools/prepare_music_release_candidate.py
Decision: approve release-candidate
""",
        )
        write(
            project / "10_mix-master" / "release-audio-qc-report.md",
            """# Release Audio QC Report

Decision: pass
""",
        )
        board = audit(project)
        for term in ["Current stage: release-rights-gate", "release-audio-qc-report.md is not tool-generated with QC evidence"]:
            if term not in board:
                errors.append(f"handwritten release audio QC board missing term: {term}")
        if "prepare_music_catalog_memory.py" in board:
            errors.append("handwritten release audio QC must not advance to catalog memory")

        write(
            project / "10_mix-master" / "release-audio-qc-report.md",
            release_audio_qc_report(project),
        )
        board = audit(project)
        for term in ["Current stage: catalog-memory-gate", "prepare_music_catalog_memory.py"]:
            if term not in board:
                errors.append(f"release-ready board missing term: {term}")

        write(
            project / "12_catalog-memory" / "catalog-writeback-manifest.md",
            """# Catalog Writeback Manifest

Generated by: tools/prepare_music_catalog_memory.py
Catalog promotion: yes
""",
        )
        board = audit(project)
        for term in ["Status: catalog-updated", "human review", "Gate Evidence"]:
            if term not in board:
                errors.append(f"catalog-ready board missing term: {term}")

        audit_file = project / "00_admin" / "project-status-audit.md"
        next_action = project / "00_admin" / "next-action.md"
        for path in [audit_file, next_action]:
            if not path.is_file():
                errors.append(f"missing audit output: {path}")

        no_overwrite = run([sys.executable, str(TOOL), "--project-root", str(project), "--write"])
        if no_overwrite.returncode == 0:
            errors.append("status audit should refuse overwrite without --allow-overwrite")

    workflow = WIKI_WORKFLOW.read_text(encoding="utf-8")
    for term in [
        "tools/audit_music_song_project_status.py",
        "project-status-audit.md",
        "next-action.md",
        "audit_music_external_method_claims.py",
        "external-method-claim-audit.md",
        "methodology-transfer-gate",
        "audit_music_methodology_transfer.py",
        "methodology-transfer-audit.md",
        "prompt-specificity-gate",
        "audit_music_prompt_specificity_budget.py",
        "prompt-specificity-budget-audit.md",
        "genre-lane-authenticity-gate",
        "audit_music_genre_lane_authenticity.py",
        "genre-lane-authenticity-audit.md",
        "lyric-narrative-gate",
        "audit_music_lyric_narrative.py",
        "lyric-narrative-audit.md",
        "compile_music_prompt_package.py",
        "prompt-iteration-discipline-gate",
        "tools/audit_music_prompt_iteration_discipline.py",
        "prompt-iteration-discipline-audit.md",
        "audit_music_generation_evidence.py",
        "generation-evidence-audit.md",
        "audio-seed-retention-gate",
        "tools/audit_music_audio_seed_retention.py",
        "audio-seed-retention-audit.md",
        "post-production-mix-lock-gate",
        "tools/audit_music_post_production_mix_lock.py",
        "post-production-mix-lock-audit.md",
        "release-listener-gate",
        "tools/audit_music_release_listener_evidence.py",
        "release-listener-evidence-audit.md",
        "prompt-experiment-gate",
        "prepare_music_catalog_memory.py",
        "Decision: approve release-candidate",
        "release-candidate-evidence-audit.md",
        "release-candidate-package.md",
        "release_candidate/metadata/release-candidate-manifest.md",
        "repair-regression-gate",
        "regression-listen.md",
    ]:
        if term not in workflow:
            errors.append(f"single production workflow missing term: {term}")

    template = WIKI_TEMPLATE.read_text(encoding="utf-8")
    for term in ["tools/audit_music_song_project_status.py", "project-status-audit.md", "next-action.md", "audit_music_external_method_claims.py", "external-method-claim-audit.md", "audit_music_methodology_transfer.py", "methodology-transfer-audit.md", "audit_music_prompt_specificity_budget.py", "prompt-specificity-budget-audit.md", "audit_music_genre_lane_authenticity.py", "genre-lane-authenticity-audit.md", "audit_music_lyric_narrative.py", "lyric-narrative-audit.md", "prompt-iteration-discipline-gate", "tools/audit_music_prompt_iteration_discipline.py", "prompt-iteration-discipline-audit.md", "audit_music_generation_evidence.py", "generation-evidence-audit.md", "tools/audit_music_audio_seed_retention.py", "audio-seed-retention-audit.md", "tools/audit_music_post_production_mix_lock.py", "post-production-mix-lock-audit.md", "post-production-mix-lock-gate", "tools/audit_music_release_listener_evidence.py", "release-listener-evidence-audit.md", "repair-regression-gate", "regression-listen.md"]:
        if term not in template:
            errors.append(f"project template missing term: {term}")

    log_text = LOG.read_text(encoding="utf-8") if LOG.exists() else ""
    for term in ["AI 音乐单曲项目状态审计工具", "AI 音乐 External Method Claim 工具闸门", "AI 音乐 Prompt Specificity Budget 工具闸门", "AI 音乐 Genre Lane Authenticity 工具闸门", "AI 音乐 Lyric Narrative 工具闸门", "AI 音乐 Repair Regression 闸门", "AI 音乐 Prompt Iteration Discipline 工具闸门", "AI 音乐 Generation Evidence 工具闸门", "AI 音乐 Audio Seed Retention 工具闸门", "AI 音乐 Post Production Mix Lock 工具闸门", "AI 音乐 Release Listener Evidence 工具闸门"]:
        if term not in log_text:
            errors.append(f"wiki log missing status audit tool entry: {term}")

    if errors:
        print("AI music song project status audit verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music song project status audit verification passed.")
    print(f"tool: {TOOL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
