#!/usr/bin/env python3
"""Verify the AI music vocal identity and performance audit gate."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
VOCAL_AUDIT = ROOT / "tools" / "audit_music_vocal_identity.py"
WIKI_VOCAL = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐声线身份与演唱表演工作流.md")
WIKI_PROMPT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐 Prompt 编译与生成前预检工作流.md")
WIKI_PROJECT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def scaffold_project(tmp_path: Path) -> Path:
    cmd = [
        sys.executable,
        str(SCAFFOLD),
        "--output-dir",
        str(tmp_path),
        "--date",
        "20260625",
        "--language",
        "zh",
        "--lane",
        "pop",
        "--slug",
        "night-bus",
        "--title",
        "Night Bus Confession",
        "--artist-project",
        "Example Test Artist",
        "--use-case",
        "demo",
    ]
    result = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr)
    return tmp_path / "20260625_zh-pop_night-bus"


def fill_passing_dependencies(project: Path) -> None:
    write(project / "03_writing" / "lyrics-prosody-audit.md", "# Lyrics Prosody Audit\n\nGenerated by: tools/audit_music_lyrics_prosody.py\nDecision: pass\n\n## Section Metrics\n\nLyrics tags: clear Mandarin title phrase\nBlind-listening red flags: none\n")
    write(project / "03_writing" / "topline-hook-audit.md", "# Topline Hook Audit\n\nGenerated by: tools/audit_music_topline_hook.py\nDecision: pass\n\n## Hook Design\n\nTopline tags: title lands on long note\nBlind hook test: title recalled\n")
    write(project / "03_writing" / "structure-dynamics-audit.md", "# Structure Dynamics Audit\n\nGenerated by: tools/audit_music_structure_dynamics.py\nDecision: pass\n\n## Structure Design\n\nStructure tags: final chorus peak\nSection tags: bridge turn and clean outro\nStructure blind test: passed\n")


def fill_good_vocal(project: Path) -> None:
    write(project / "04_prompt" / "persona-voice-model-routing.md", "# Persona Voice Model Routing\n\nHuman anchor lane: text-only\nVoice identity source: none\nPersona source: none\nCustom Model source: none\nCustom model corpus: none\nVoice verification: n/a\nMy Taste state: off\nPrompt boost state: off\nRights status: no voice/persona/custom model source used\n")
    write(
        project / "03_writing" / "singer-brief.md",
        """# Singer Brief

Song: Night Bus Confession
Language: zh
Narrator: first-person commuter
Vocal role: lead solo fictional singer
Range / tessitura: close mid-low alto, comfortable mixed voice in chorus
Register plan: low intimate verse, controlled mixed voice chorus, straight bridge
Timbre: warm dry close-mic voice with slight breath edge and clear center
Diction: clear Mandarin consonants, stable vowels on title phrase
Breath: audible breath before chorus title, short breath after long phrase
Vibrato / straight tone: straight tone in verse and bridge, restrained vibrato only on title long note
Dynamics: quiet verse, lifted pre-chorus, open but controlled chorus, softer outro
Emotional restraint: no theatrical crying, held-back confession until final chorus
Must not sound like: anonymous vocalist, excessive vocal runs, unclear diction, over-autotuned vocal, fake gasping, same tail every line, choir pad everywhere
Rights source: fictional text-only singer brief, no voice/persona/custom model source used
""",
    )
    write(
        project / "03_writing" / "vocal-performance-map.md",
        """# Vocal Performance Map

[Verse 1]
Performance: close-mic low register, almost spoken, clear consonants

[Pre-Chorus]
Performance: fewer words, audible breath before title, slight intensity rise

[Chorus]
Performance: lead centered, controlled mixed voice, restrained vibrato on title only

[Verse 2]
Performance: same singer identity, slightly more confidence, tighter rhythm

[Bridge]
Performance: stripped straight tone, dry vocal, less reverb, new perspective

[Final Chorus]
Performance: same hook preserved, one restrained ad-lib after title

[Outro]
Performance: soft final title tag, clean consonant ending, short breath tail
""",
    )
    write(project / "03_writing" / "vocal-arrangement-map.md", "# Vocal Arrangement Map\n\nLead vocal: fictional lead stays center and carries all title phrases\nDoubles: none in verse, light double behind chorus, wider only in final chorus\nHarmonies: support the title phrase tail only, never louder than lead\nAd-libs: one restrained ad-lib after final chorus title phrase\nDuet / group vocal: none\nLead center: lead remains intelligible over all doubles and harmonies\nDo not: choir pad everywhere, excessive vocal runs, lead buried by doubles\n")


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, VOCAL_AUDIT, WIKI_VOCAL, WIKI_PROMPT, WIKI_PROJECT, LOG]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-vocal-gate-") as tmp:
        project = scaffold_project(Path(tmp))

        empty = subprocess.run([sys.executable, str(VOCAL_AUDIT), "--project-root", str(project), "--strict"], cwd=ROOT, text=True, capture_output=True)
        if empty.returncode == 0:
            errors.append("strict vocal audit should reject empty scaffold")
        empty_text = empty.stdout + "\n" + empty.stderr
        for term in ["vocal_role_missing", "range_missing", "prosody_audit_missing", "structure_audit_missing"]:
            if term not in empty_text:
                errors.append(f"empty vocal audit missing blocker term: {term}")

        fill_passing_dependencies(project)
        fill_good_vocal(project)
        good = subprocess.run(
            [sys.executable, str(VOCAL_AUDIT), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if good.returncode != 0:
            errors.append(f"good vocal audit failed: stdout={good.stdout.strip()} stderr={good.stderr.strip()}")
        audit_path = project / "03_writing" / "vocal-identity-audit.md"
        if not audit_path.exists():
            errors.append("vocal audit did not write output")
        else:
            audit_text = audit_path.read_text(encoding="utf-8")
            for term in ["Generated by: tools/audit_music_vocal_identity.py", "Decision: pass", "Vocal tags:", "Vocal performance tags:", "Vocal arrangement tags:", "Vocal blind test:", "## Vocal Design", "close mid-low alto"]:
                if term not in audit_text:
                    errors.append(f"vocal audit output missing term: {term}")

        no_overwrite = subprocess.run([sys.executable, str(VOCAL_AUDIT), "--project-root", str(project), "--write", "--strict"], cwd=ROOT, text=True, capture_output=True)
        if no_overwrite.returncode == 0 or "output exists" not in no_overwrite.stderr:
            errors.append("vocal audit should refuse overwrite without --allow-overwrite")

        write(project / "03_writing" / "singer-brief.md", "# Singer Brief\n\nTimbre: female vocal\n")
        write(project / "03_writing" / "vocal-performance-map.md", "# Vocal Performance Map\n\n[Verse 1]\nPerformance: same intensity\n")
        write(project / "03_writing" / "vocal-arrangement-map.md", "# Vocal Arrangement Map\n\nLead vocal: lead\n")
        bad = subprocess.run([sys.executable, str(VOCAL_AUDIT), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"], cwd=ROOT, text=True, capture_output=True)
        if bad.returncode == 0:
            errors.append("strict vocal audit should reject incomplete vocal maps")
        bad_text = bad.stdout + "\n" + bad.stderr
        for term in ["range_missing", "diction_missing", "chorus_performance_missing", "doubles_plan_missing"]:
            if term not in bad_text:
                errors.append(f"bad vocal audit missing blocker term: {term}")

    docs = {
        WIKI_VOCAL: ["tools/audit_music_vocal_identity.py", "vocal-identity-audit.md"],
        WIKI_PROMPT: ["tools/audit_music_vocal_identity.py", "Vocal audit"],
        WIKI_PROJECT: ["vocal-identity-audit.md", "audit_music_vocal_identity.py"],
        LOG: ["AI 音乐 Vocal Identity 工具闸门"],
    }
    for path, terms in docs.items():
        text = path.read_text(encoding="utf-8")
        for term in terms:
            if term not in text:
                errors.append(f"{path} missing doc term: {term}")

    if errors:
        print("AI music vocal identity gate verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music vocal identity gate verification passed.")
    print(f"tool: {VOCAL_AUDIT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
