#!/usr/bin/env python3
"""Verify the AI music structure dynamics audit gate."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
STRUCTURE_AUDIT = ROOT / "tools" / "audit_music_structure_dynamics.py"
WIKI_STRUCTURE = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐结构动态与段落转场工作流.md")
WIKI_PROMPT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐 Prompt 编译与生成前预检工作流.md")
WIKI_PROJECT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def scaffold_project(tmp_path: Path) -> Path:
    cmd = [
        sys.executable,
        str(SCAFFOLD),
        "--output-dir",
        str(tmp_path),
        "--date",
        "20260625",
        "--language",
        "zh",
        "--lane",
        "pop",
        "--slug",
        "night-bus",
        "--title",
        "Night Bus Confession",
        "--artist-project",
        "Example Test Artist",
        "--use-case",
        "demo",
    ]
    result = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr)
    return tmp_path / "20260625_zh-pop_night-bus"


def fill_passing_groove_audit(project: Path) -> None:
    write(
        project / "03_writing" / "groove-humanization-audit.md",
        """# Groove Humanization Audit

Generated by: tools/audit_music_groove_humanization.py
Decision: pass

## Groove Design

Groove tags: laid-back verse pocket, straighter chorus, bass locks with kick
Instrument performance tags: playable piano, muted guitar answers, controlled velocity
Rhythm-section blind test: passed
""",
    )


def fill_good_structure(project: Path) -> None:
    write(
        project / "01_brief" / "song-brief.md",
        """# Song Brief

Song: Night Bus Confession
Language: zh
Genre lane: Mandarin pop ballad
Use case: demo
Title phrase: 末班车还亮着
""",
    )
    write(
        project / "04_prompt" / "lyrics-context-map.md",
        """# Lyrics Context Map

```text
[Verse 1 | intimate vocal | bus-window image]
车窗把霓虹揉成一条河
[Pre-Chorus | fewer words | breath before chorus]
我把讯息停在发送之前
[Chorus | title phrase on a long note]
末班车还亮着 可我没说破
[Verse 2 | new detail | groove deepens]
座位空着 像你还会经过
[Bridge | stripped piano | new perspective]
我终于承认 不只是路过
[Final Chorus | warmer harmony | title phrase returns softer]
末班车还亮着 我把名字收着
[Outro | clean ending]
[End]
```
""",
    )
    write(
        project / "03_writing" / "structure-brief.md",
        """# Structure Brief

Project: Night Bus Confession
Language: zh
Genre: Mandarin pop ballad
Tempo / meter: 78 BPM 4/4
Target length: 3:20 full single
Use case: demo
Core hook: 末班车还亮着 title phrase
Narrative arc: bus-window restraint to finally admitting the feeling
Emotional arc: intimate verse, rising pre, warm chorus, stripped bridge, full final payoff
Highest energy section: Final Chorus
Highest tension section: Bridge
Must have: Verse 2 development, bridge turn, final chorus payoff, clean outro
Must avoid: flat energy throughout, same arrangement every section, random genre switch, endless outro, sudden cutoff
Exact structure required?: no
If exact: n/a
""",
    )
    write(
        project / "03_writing" / "energy-map.md",
        """# Energy Map

| Section | Energy 1-9 | Tension 1-9 | Density | Vocal intensity | Width | Low-end |
|---|---:|---:|---|---|---|---|
| Intro | 2 | 2 | sparse motif | low | narrow | none |
| Verse 1 | 3 | 4 | sparse | intimate | narrow | light |
| Pre-Chorus | 5 | 7 | rising | focused | medium | rising |
| Chorus | 7 | 5 | open | mid-high | wide | locked |
| Verse 2 | 4 | 5 | slightly deeper | intimate | medium | muted |
| Chorus 2 | 7 | 5 | added harmony | mid-high | wide | locked |
| Bridge | 4 | 8 | stripped | close | narrow | drop out |
| Final Chorus | 8 | 6 | full band | strongest | widest | locked |
| Outro | 2 | 1 | short tag | soft | narrow | tonic |

Energy rule: verse restrained, pre raises tension, chorus releases, bridge lowers density but raises tension, final chorus peaks.
Where should the listener lean in: pre-chorus breath before title phrase and stripped bridge first line
Where should the listener feel release: chorus title landing and final chorus return
Where should the song breathe: bridge first half and short outro tag
""",
    )
    write(
        project / "03_writing" / "section-function-map.md",
        """# Section Function Map

Verse 1:
- information: narrator hides the message while watching neon through the bus window

Pre-Chorus:
- tension method: bass climb and fewer words create breath before title

Chorus:
- title hook: 末班车还亮着
- arrival method: tonic landing with wider band

Verse 2:
- new information: empty seat image suggests the other person might still appear
- new arrangement detail: muted bass answer and subtle guitar counterline
- what stays from Verse 1: intimate vocal and bus imagery

Bridge:
- contrast method: stripped piano, half-time drums, reduced bass
- new perspective: narrator admits the feeling is not just passing by
- return cue: held vocal pickup into final chorus downbeat

Final Chorus:
- what repeats: same title hook and contour
- what develops: wider harmony and one restrained ad-lib
- payoff: confession finally feels possible without burying the vocal

Outro:
- ending logic: short title tag resolves to tonic
- last sound: clean piano/bell cadence
""",
    )
    write(project / "03_writing" / "contrast-continuity-matrix.md", "# Contrast Continuity Matrix\n\nKeep across song: tempo, singer identity, title hook, night-bus motif\nChange by section: lyric information, drum density, bass movement, width, bridge texture, final harmony\nNever change: language, title phrase identity, core groove family, vocal intimacy\nAllowed surprise: stripped bridge with half-time drums and dry vocal\n")
    write(project / "03_writing" / "transition-cue-sheet.md", "# Transition Cue Sheet\n\nIntro -> Verse: bell motif decays into first vocal breath\nVerse -> Pre: bass starts climbing and hats open slightly\nPre -> Chorus: short snare pickup, one-beat breath, title lands on downbeat\nChorus -> Verse 2: drums drop back, guitar leaves one answer phrase\nChorus 2 -> Bridge: reverb tail and bass dropout\nBridge -> Final Chorus: held vocal pickup and tom fill into full band\nFinal Chorus -> Outro: band cuts to short title tag and clean cadence\nAllowed cues: drum fill, vocal pickup, bass climb, one-bar break, harmonic hold, guitar fill, reverb tail, silence\nForbidden cues: random genre switch, overblown riser, endless outro, sudden cutoff, fake crowd\n")
    write(project / "03_writing" / "second-verse-development.md", "# Second Verse Development\n\nNew information: empty seat and passing stop add a concrete consequence after Verse 1\nNew arrangement detail: muted bass answer and one subtle guitar counterline\nWhat stays from Verse 1: intimate vocal, restrained drums, bus-window imagery\n")
    write(project / "03_writing" / "bridge-turn-plan.md", "# Bridge Turn Plan\n\nBridge reveals: the feeling is not temporary and cannot be explained away as a commute\nMusical contrast: stripped piano, half-time drums, bass drops out\nLyric contrast: direct admission instead of image-only restraint\nReturn cue to final chorus: held vocal pickup into full-band downbeat\nDo not: third verse disguised as bridge, random key change, genre switch\n")
    write(project / "03_writing" / "final-chorus-payoff.md", "# Final Chorus Payoff\n\nWhat repeats exactly: title hook and main contour\nWhat changes: wider harmony and warmer backing vocal\nNew layer: one restrained guitar/piano lift after the title\nVocal payoff: one controlled ad-lib after the held title word\nMix payoff: wider band without burying lead vocal\nFinal line: title phrase returns softer\nEnding cue: short tag into clean tonic cadence\n")
    write(project / "03_writing" / "outro-end-plan.md", "# Outro End Plan\n\nEnding logic: short title tag after final chorus resolves the confession\nLast sound: clean piano/bell tonic cadence\nOutro length: under 10 seconds\nFade / stop / tag: short tag, no long fade\nDo not: endless instrumental jam, sudden cutoff, new lyric information\n")


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, STRUCTURE_AUDIT, WIKI_STRUCTURE, WIKI_PROMPT, WIKI_PROJECT, LOG]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-structure-gate-") as tmp:
        project = scaffold_project(Path(tmp))

        empty = subprocess.run([sys.executable, str(STRUCTURE_AUDIT), "--project-root", str(project), "--strict"], cwd=ROOT, text=True, capture_output=True)
        if empty.returncode == 0:
            errors.append("strict structure audit should reject empty scaffold")
        empty_text = empty.stdout + "\n" + empty.stderr
        for term in ["target_length_missing", "core_hook_missing", "groove_audit_missing", "verse2_development_missing"]:
            if term not in empty_text:
                errors.append(f"empty structure audit missing blocker term: {term}")

        fill_passing_groove_audit(project)
        fill_good_structure(project)
        good = subprocess.run(
            [sys.executable, str(STRUCTURE_AUDIT), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if good.returncode != 0:
            errors.append(f"good structure audit failed: stdout={good.stdout.strip()} stderr={good.stderr.strip()}")
        audit_path = project / "03_writing" / "structure-dynamics-audit.md"
        if not audit_path.exists():
            errors.append("structure audit did not write output")
        else:
            audit_text = audit_path.read_text(encoding="utf-8")
            for term in ["Generated by: tools/audit_music_structure_dynamics.py", "Decision: pass", "Structure tags:", "Section tags:", "Structure blind test:", "## Structure Design", "Final Chorus"]:
                if term not in audit_text:
                    errors.append(f"structure audit output missing term: {term}")

        no_overwrite = subprocess.run(
            [sys.executable, str(STRUCTURE_AUDIT), "--project-root", str(project), "--write", "--strict"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if no_overwrite.returncode == 0 or "output exists" not in no_overwrite.stderr:
            errors.append("structure audit should refuse overwrite without --allow-overwrite")

        for rel in [
            "structure-brief.md",
            "section-function-map.md",
            "contrast-continuity-matrix.md",
            "transition-cue-sheet.md",
            "second-verse-development.md",
            "bridge-turn-plan.md",
            "final-chorus-payoff.md",
            "outro-end-plan.md",
        ]:
            write(project / "03_writing" / rel, f"# {rel}\n\n")
        write(project / "03_writing" / "energy-map.md", "# Energy Map\n\nVerse 1\nChorus\n")
        bad = subprocess.run(
            [sys.executable, str(STRUCTURE_AUDIT), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"],
            cwd=ROOT,
            text=True,
            capture_output=True,
        )
        if bad.returncode == 0:
            errors.append("strict structure audit should reject incomplete structure maps")
        bad_text = bad.stdout + "\n" + bad.stderr
        for term in ["highest_energy_missing", "transition_cues_missing", "bridge_turn_missing", "final_chorus_payoff_missing"]:
            if term not in bad_text:
                errors.append(f"bad structure audit missing blocker term: {term}")

    docs = {
        WIKI_STRUCTURE: ["tools/audit_music_structure_dynamics.py", "structure-dynamics-audit.md"],
        WIKI_PROMPT: ["tools/audit_music_structure_dynamics.py", "Structure audit"],
        WIKI_PROJECT: ["structure-dynamics-audit.md", "audit_music_structure_dynamics.py"],
        LOG: ["AI 音乐 Structure Dynamics 工具闸门"],
    }
    for path, terms in docs.items():
        text = path.read_text(encoding="utf-8")
        for term in terms:
            if term not in text:
                errors.append(f"{path} missing doc term: {term}")

    if errors:
        print("AI music structure dynamics gate verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music structure dynamics gate verification passed.")
    print(f"tool: {STRUCTURE_AUDIT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
