#!/usr/bin/env python3
"""Verify the AI music post-production mix-lock gate."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
TOOL = ROOT / "tools" / "audit_music_post_production_mix_lock.py"
WIKI_POST = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐编曲密度与混音后期修作工作流.md")
WIKI_TEMPLATE = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
WIKI_WORKFLOW = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲制作总控与阶段闸门工作流.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def scaffold_project(tmp_path: Path) -> Path:
    result = run(
        [
            sys.executable,
            str(SCAFFOLD),
            "--output-dir",
            str(tmp_path),
            "--date",
            "20260624",
            "--language",
            "zh",
            "--lane",
            "pop",
            "--slug",
            "night-bus",
            "--title",
            "Night Bus Confession",
            "--artist-project",
            "Example Test Artist",
            "--use-case",
            "release-single",
        ]
    )
    if result.returncode != 0:
        raise AssertionError(result.stderr.strip())
    return tmp_path / "20260624_zh-pop_night-bus"


def write_good_evidence(project: Path) -> None:
    write(
        project / "06_review" / "take-selection-decision.md",
        """# Take Selection Decision

Best take: A02
Action: lock for post-production
Composite score: 4.55
Core minimum: 4.10
Primary route: AI 音乐编曲密度与混音后期修作工作流
""",
    )
    write(
        project / "07_repair" / "repair-route-map.md",
        """| problem | layer | severity | repair route | expected output | regression listen |
|---|---|---:|---|---|---|
| chorus vocal masking and hi-hat smear | mix/post | 1 | AI 音乐编曲密度与混音后期修作工作流 | mix-plan.md | artifact lower, hook preserved |
""",
    )
    write(
        project / "08_stems-daw" / "best-take-lock.md",
        """# Best Take Lock

Locked take: A02
Take action: lock for post-production
Source provider/model: Suno current
Prompt package: 04_prompt/prompt-package-v001.md
""",
    )
    write(
        project / "08_stems-daw" / "session-pack.md",
        """# Session Pack

Generated by: tools/prepare_music_daw_handoff.py
Locked take: A02
""",
    )
    write(
        project / "08_stems-daw" / "final-humanized-master-review.md",
        """# Final Humanized Master Review

Decision: pass
Lead vocal identity: pass
Hook preserved: pass
Groove preserved: pass
AI artifacts: resolved
""",
    )
    write(
        project / "10_mix-master" / "post-review.md",
        """# Post Review

Locked take: A02
Keep: title hook, close vocal identity, late-night groove pocket
Must repair: pad clutter, chorus vocal masking, short outro cutoff
Decision: ready for mix lock
""",
    )
    write(
        project / "10_mix-master" / "arrangement-density-triage.md",
        """# Arrangement Density Triage

| section | density issue | action | keep |
|---|---|---|---|
| Verse 1 | pad and guitar fill compete with lead vocal | muted pad on every other phrase | close vocal breath |
| Chorus | backing stack masks title phrase | ducked wide pad and carved 2-4k around lead | title hook |
| Bridge | texture needs contrast before final chorus | removed extra shaker and left space before pickup | emotional turn |
| Final Chorus | lift without mud | thinned low piano left hand and automated width | payoff |
""",
    )
    write(
        project / "10_mix-master" / "mix-plan.md",
        """# Mix Plan

Vocal center: lead vocal stays dry, centered, and 1 dB above guitar/synth bed through title phrase.
Low-end / kick-bass: kick owns transient, bass follows sustained notes, sub is mono and leaves vocal pocket clean.
Space / reverb / width: verse is narrow and dry, chorus widens guitars and backing vocal plate without washing consonants.
Dynamics / automation: pads duck under lead, pre-chorus rises 1.5 dB, final chorus widens without brickwall limiting.
Transition/outro: bridge breath before final chorus, outro resolves on last vocal tail instead of abrupt cutoff.
AI artifact repair: cymbal smear, vocal tail blur, and stem bleed were checked and resolved or low-risk.
Reference A/B: loudness-matched internal reference confirms vocal center, low-end balance, and chorus width.
""",
    )
    write(
        project / "10_mix-master" / "mix-lock-preflight.md",
        """# Mix Lock Preflight

Lead vocal clear: pass
Hook/title clear: pass
Low end controlled: pass
Space/dynamics: pass
Transition/outro: pass
AI artifacts: pass
Mono/phase: pass
Over-limiting: none
Decision: pass
""",
    )


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, TOOL, WIKI_POST, WIKI_TEMPLATE, WIKI_WORKFLOW]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-post-mix-lock-") as tmp:
        project = scaffold_project(Path(tmp))

        empty = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if empty.returncode == 0:
            errors.append("empty post-production mix-lock audit should fail in strict mode")
        empty_text = empty.stdout + "\n" + empty.stderr
        for term in ["locked_take_missing", "post_review", "mix_lock_decision_missing"]:
            if term not in empty_text:
                errors.append(f"empty strict failure missing term: {term}")

        write_good_evidence(project)
        write(
            project / "10_mix-master" / "arrangement-density-triage.md",
            """# Arrangement Density Triage

| section | density issue | action | keep |
|---|---|---|---|
| Verse 1 | pad and guitar fill compete with lead vocal | muted pad on every other phrase | close vocal breath |
""",
        )
        bad_density = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if bad_density.returncode == 0:
            errors.append("post-production mix-lock audit should reject incomplete section-density evidence")
        bad_density_text = bad_density.stdout + "\n" + bad_density.stderr
        if "density_sections_missing" not in bad_density_text:
            errors.append("bad density blocker missing density_sections_missing")

        write_good_evidence(project)
        write(
            project / "10_mix-master" / "mix-plan.md",
            """# Mix Plan

Vocal center: pass
Space / reverb / width: pass
Dynamics / automation: pass
Transition/outro: pass
AI artifact repair: pass
Reference A/B: pass
""",
        )
        bad_low_end = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if bad_low_end.returncode == 0:
            errors.append("post-production mix-lock audit should reject missing kick/bass low-end evidence")
        bad_low_end_text = bad_low_end.stdout + "\n" + bad_low_end.stderr
        if "low_end_missing" not in bad_low_end_text:
            errors.append("bad low-end blocker missing low_end_missing")

        write_good_evidence(project)
        ok = run(
            [
                sys.executable,
                str(TOOL),
                "--project-root",
                str(project),
                "--write",
                "--allow-overwrite",
                "--strict",
            ]
        )
        if ok.returncode != 0:
            errors.append(f"post-production mix-lock audit should pass: {ok.stderr.strip()}")
        output = project / "10_mix-master" / "post-production-mix-lock-audit.md"
        if not output.is_file():
            errors.append("missing post-production mix-lock audit output")
        else:
            text = output.read_text(encoding="utf-8")
            for term in [
                "Decision: pass",
                "tools/audit_music_post_production_mix_lock.py",
                "Post Production Mix Lock Evidence",
                "Locked take: A02",
                "Arrangement density tags:",
                "Vocal center:",
                "Low-end/kick-bass:",
                "Space/dynamics automation:",
                "Transition/outro:",
                "AI artifact repair:",
                "Stem/DAW handoff: ready",
                "Reference A/B:",
                "Mix lock handoff: pass",
            ]:
                if term not in text:
                    errors.append(f"post-production audit output missing term: {term}")

        no_overwrite = run([sys.executable, str(TOOL), "--project-root", str(project), "--write", "--strict"])
        if no_overwrite.returncode == 0:
            errors.append("post-production mix-lock audit should refuse overwrite without --allow-overwrite")

    for page, terms in [
        (
            WIKI_POST,
            [
                "tools/audit_music_post_production_mix_lock.py",
                "post-production-mix-lock-audit.md",
                "Post Production Mix Lock",
                "Arrangement density tags",
                "Low-end/kick-bass",
            ],
        ),
        (
            WIKI_TEMPLATE,
            [
                "post-production-mix-lock-audit.md",
                "tools/audit_music_post_production_mix_lock.py",
                "post-production-mix-lock-gate",
            ],
        ),
        (
            WIKI_WORKFLOW,
            [
                "post-production-mix-lock-gate",
                "tools/audit_music_post_production_mix_lock.py",
                "release-listener-gate",
            ],
        ),
    ]:
        text = page.read_text(encoding="utf-8")
        for term in terms:
            if term not in text:
                errors.append(f"{page.name} missing term: {term}")

    log_text = LOG.read_text(encoding="utf-8") if LOG.exists() else ""
    if "AI 音乐 Post Production Mix Lock 工具闸门" not in log_text:
        errors.append("wiki log missing post-production mix-lock tool entry")

    if errors:
        print("AI music post-production mix-lock verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music post-production mix-lock verification passed.")
    print(f"script: {TOOL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
