#!/usr/bin/env python3
"""Verify the AI music prompt iteration discipline gate."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
TOOL = ROOT / "tools" / "audit_music_prompt_iteration_discipline.py"
WIKI_EXPERIMENT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐 Prompt 实验矩阵与版本收敛工作流.md")
WIKI_TEMPLATE = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
WIKI_WORKFLOW = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲制作总控与阶段闸门工作流.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def scaffold_project(tmp_path: Path) -> Path:
    result = run(
        [
            sys.executable,
            str(SCAFFOLD),
            "--output-dir",
            str(tmp_path),
            "--date",
            "20260624",
            "--language",
            "zh",
            "--lane",
            "pop",
            "--slug",
            "night-bus",
            "--title",
            "Night Bus Confession",
            "--artist-project",
            "Example Test Artist",
            "--use-case",
            "release-single",
        ]
    )
    if result.returncode != 0:
        raise AssertionError(result.stderr.strip())
    return tmp_path / "20260624_zh-pop_night-bus"


def prompt_package_text(project: Path) -> str:
    return f"""# Prompt Package v001

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Decision: compile approved

## Metadata

- Title: Night Bus Confession
- Model: Suno current
- Weirdness: 25
- Style Influence: 70
- Audio Influence: 0
- Human Anchor Lane: text-only
- Voice Identity Source: none
- Persona Source: none
- Custom Model Source: none
- Custom Model Corpus: none
- My Taste State: off
- Prompt Boost State: off
- Exclude: awkward translated Mandarin

## Style Of Music

```text
genre: "Mandarin night pop-rock"
vocal: "clear Mandarin diction, intimate verse"
instrumentation: "live drums, melodic bass, clean electric guitar"
production: "dry verse vocal, wide sparse chorus"
mood: "late-night confession"
```

## Lyrics

```text
[Verse 1]
line
[Chorus]
hook
[End]
```

## Prompt Rationale

- Methodology transfer: pass
- Prompt specificity: pass
- Lyric narrative: pass
- Reference audit: pass
- Prosody audit: pass
- Topline audit: pass
- Harmony/Bass audit: pass
- Groove audit: pass
- Structure audit: pass
- Vocal audit: pass

## Preflight Summary

| severity | code | message | route |
|---|---|---|---|
| pass | none | compile approved | experiment handoff |
"""


def prompt_preflight_text(project: Path) -> str:
    return f"""# Prompt Preflight Review

Generated by: tools/compile_music_prompt_package.py
Project root: {project}
Prompt package: 04_prompt/prompt-package-v001.md

Field completeness: pass
Lyrics context: pass
Methodology transfer: pass
Prompt specificity: pass
Lyric narrative: pass
Reference audit: pass
Prosody audit: pass
Topline audit: pass
Harmony/Bass audit: pass
Groove audit: pass
Structure audit: pass
Vocal audit: pass
Exclude rationale: pass
Slider intent: pass
Model/version: pass
Human anchor lane: pass
Identity routing: pass
My Taste / boost: pass
Identity / rights: pass
Conflict check: pass

Decision: compile approved

Blockers: 0

## Issues
"""


def write_good_discipline(project: Path, *, changed_variables: str = "Style Influence", phase: str = "convergence", baseline: bool = True) -> None:
    write(project / "04_prompt" / "prompt-package-v001.md", prompt_package_text(project))
    write(project / "04_prompt" / "prompt-preflight-review.md", prompt_preflight_text(project))
    write(
        project / "04_prompt" / "experiment-handoff.md",
        """# Experiment Handoff

Next test: compare C01 baseline with C02 Style Influence change while keeping lyrics and Exclude fixed
What to test first: chorus title recall and vocal identity stability
""",
    )
    write(
        project / "05_generations" / "experiment-intent.md",
        f"""# Experiment Intent

Experiment question: Does changing {changed_variables} improve style adherence without making the vocal generic?
Success metric: alignment, title hook recall, low AI-flavor flags
Stop condition: lock if C02 wins blind review; abandon if hook memory falls
Experiment phase: {phase}
Attribution goal: strong single-variable attribution
""",
    )
    write(
        project / "05_generations" / "brief-freeze.md",
        """# Brief Freeze

Use case: release-single
Language: zh
Audience: late-night Mandarin pop listeners
Genre lane: Mandarin night pop-rock
Artist / catalog lane: fictional test artist
Narrator: first-person commuter
Title phrase: 末班车还亮着
Tempo / groove: 78 BPM restrained pop-rock
Vocal identity: clear Mandarin diction, intimate verse, controlled chorus
Instrumentation: live drums, melodic bass, clean electric guitar
Production space: dry verse vocal, wider chorus
Must keep: title phrase, narrator, language, groove family
Must avoid: EDM drop, glossy choir pad, celebrity voice
Rights boundary: no artist names, no uploaded third-party audio
""",
    )
    write(
        project / "05_generations" / "variable-inventory.md",
        f"""# Variable Inventory

Changed variables: {changed_variables}

| variable | allowed this round | reason | notes |
|---|---|---|---|
| Style prompt | no | keep genre text fixed | |
| Lyrics text | no | keep title and lines fixed | |
| Lyrics context | no | keep section tags fixed | |
| Exclude | no | keep failure map fixed | |
| Model | no | current model fixed | |
| Weirdness | no | keep W25 fixed | |
| Style Influence | yes | single variable under test | S70 vs S80 |
| Audio Influence | no | no audio upload | |
| Persona / Voice | no | no identity variable | |
| Audio Upload seed | no | no seed | |
""",
    )
    baseline_block = """Candidate ID: C01
Candidate type: baseline
Hypothesis: baseline should preserve title hook and close vocal
What this tests: baseline prompt quality before slider change
What it keeps constant: brief, lyrics, exclude, model, weirdness, persona
What it changes: none
Risk: may remain too loose in style adherence
""" if baseline else ""
    matrix_rows = [
        "| candidate id | type | hypothesis | changed variable | keeps constant | risk |",
        "|---|---|---|---|---|---|",
    ]
    if baseline:
        matrix_rows.append("| C01 | baseline | baseline title hook | none | brief/lyrics/exclude/model | generic |")
    matrix_rows.append(f"| C02 | slider ablation | lane adherence improves | {changed_variables} | brief/lyrics/exclude/model | flatter vocal |")
    write(
        project / "05_generations" / "prompt-candidate-set.md",
        f"""# Prompt Candidate Set

{baseline_block}
Candidate ID: C02
Candidate type: slider ablation
Hypothesis: higher Style Influence improves lane adherence without hurting hook memory
What this tests: {changed_variables}
What it keeps constant: brief, lyrics, exclude, model, weirdness, persona
What it changes: {changed_variables}
Risk: higher style adherence may flatten vocal identity

## Candidate Matrix

{chr(10).join(matrix_rows)}

Boosted comparison: not used
""",
    )
    write(
        project / "05_generations" / "batch-generation-plan.md",
        f"""# Batch Generation Plan

Candidate IDs: C01, C02
Takes per candidate: 2
Total takes: 4
Generation date: 2026-06-25
Expected listen order: randomized A02, A04, A01, A03
Anonymization rule: hide candidate ids until reverse caption
Experiment phase: {phase}
Changed variables: {changed_variables}

## Variable Discipline

| candidate | changed variable | keep fixed | reason | expected risk |
|---|---|---|---|---|
| C01 | none | brief, lyrics, exclude, model, W25 | baseline | generic |
| C02 | {changed_variables} | brief, lyrics, exclude, model, W25 | test one variable | flatter vocal |
""",
    )


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, TOOL, WIKI_EXPERIMENT, WIKI_TEMPLATE, WIKI_WORKFLOW]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-prompt-iteration-") as tmp:
        project = scaffold_project(Path(tmp))

        empty = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if empty.returncode == 0:
            errors.append("empty prompt iteration discipline audit should fail in strict mode")
        empty_text = empty.stdout + "\n" + empty.stderr
        for term in ["prompt_package_not_approved", "experiment_question_missing", "changed_variables_missing"]:
            if term not in empty_text:
                errors.append(f"empty strict failure missing term: {term}")

        write_good_discipline(project, changed_variables="Style prompt, Lyrics text, Exclude, Weirdness", phase="convergence")
        too_many = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if too_many.returncode == 0:
            errors.append("convergence prompt iteration audit should reject too many changed variables")
        too_many_text = too_many.stdout + "\n" + too_many.stderr
        if "too_many_changed_variables" not in too_many_text:
            errors.append("too-many-vars blocker missing too_many_changed_variables")

        write_good_discipline(project, baseline=False)
        no_baseline = run([sys.executable, str(TOOL), "--project-root", str(project), "--strict"])
        if no_baseline.returncode == 0:
            errors.append("prompt iteration audit should reject a candidate set without baseline")
        no_baseline_text = no_baseline.stdout + "\n" + no_baseline.stderr
        if "baseline_candidate_missing" not in no_baseline_text:
            errors.append("no-baseline blocker missing baseline_candidate_missing")

        write_good_discipline(project)
        ok = run(
            [
                sys.executable,
                str(TOOL),
                "--project-root",
                str(project),
                "--write",
                "--allow-overwrite",
                "--strict",
            ]
        )
        if ok.returncode != 0:
            errors.append(f"prompt iteration discipline audit should pass: {ok.stderr.strip()}")
        output = project / "05_generations" / "prompt-iteration-discipline-audit.md"
        if not output.is_file():
            errors.append("missing prompt iteration discipline audit output")
        else:
            text = output.read_text(encoding="utf-8")
            for term in [
                "Decision: pass",
                "tools/audit_music_prompt_iteration_discipline.py",
                "Prompt Iteration Discipline Evidence",
                "Experiment question:",
                "Frozen brief: complete",
                "Allowed variable count: 1",
                "Changed variables: style influence",
                "Candidate hypotheses: present",
                "Batch discipline:",
                "Attribution strength: strong",
                "Generation evidence handoff: pass",
            ]:
                if term not in text:
                    errors.append(f"prompt iteration audit output missing term: {term}")

        no_overwrite = run([sys.executable, str(TOOL), "--project-root", str(project), "--write", "--strict"])
        if no_overwrite.returncode == 0:
            errors.append("prompt iteration discipline audit should refuse overwrite without --allow-overwrite")

    for page, terms in [
        (
            WIKI_EXPERIMENT,
            [
                "tools/audit_music_prompt_iteration_discipline.py",
                "prompt-iteration-discipline-audit.md",
                "prompt-iteration-discipline-gate",
                "Changed variables",
                "Attribution strength",
            ],
        ),
        (
            WIKI_TEMPLATE,
            [
                "experiment-intent.md",
                "brief-freeze.md",
                "variable-inventory.md",
                "prompt-candidate-set.md",
                "prompt-iteration-discipline-audit.md",
                "tools/audit_music_prompt_iteration_discipline.py",
            ],
        ),
        (
            WIKI_WORKFLOW,
            [
                "prompt-iteration-discipline-gate",
                "tools/audit_music_prompt_iteration_discipline.py",
                "prompt-experiment-gate",
            ],
        ),
    ]:
        text = page.read_text(encoding="utf-8")
        for term in terms:
            if term not in text:
                errors.append(f"{page.name} missing term: {term}")

    log_text = LOG.read_text(encoding="utf-8") if LOG.exists() else ""
    if "AI 音乐 Prompt Iteration Discipline 工具闸门" not in log_text:
        errors.append("wiki log missing prompt iteration discipline tool entry")

    if errors:
        print("AI music prompt iteration discipline verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music prompt iteration discipline verification passed.")
    print(f"script: {TOOL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
