#!/usr/bin/env python3
"""Verify the AI music DAW handoff CLI."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path("/path/to/suno-music-producer")
SCAFFOLD = ROOT / "tools" / "create_music_song_project.py"
TAKE_REVIEW = ROOT / "tools" / "review_music_takes.py"
REPAIR_ROUTER = ROOT / "tools" / "route_music_repairs.py"
HANDOFF = ROOT / "tools" / "prepare_music_daw_handoff.py"
WIKI_DAW = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐 DAW 复刻与真人重录工作流.md")
WIKI_PROJECT = Path("/path/to/obsidian-vault/wiki/分析/音乐/AI 音乐单曲项目文件夹与证据包模板.md")
LOG = Path("/path/to/obsidian-vault/wiki/log.md")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)


def generation_evidence_audit(project: Path) -> str:
    return f"""# Generation Evidence Audit

Generated by: tools/audit_music_generation_evidence.py
Project root: {project}
Decision: pass

## Generation Evidence

Take provenance tags: A01, A02, A03
Batch tags: candidate ids, takes per candidate, total takes, generation date, expected listen order, anonymization rule
Provider metadata tags: A01, A02, A03
Blind review handoff: ready
"""


def main() -> int:
    errors: list[str] = []
    for path in [SCAFFOLD, TAKE_REVIEW, REPAIR_ROUTER, HANDOFF, WIKI_DAW, WIKI_PROJECT, LOG]:
        if not path.exists():
            errors.append(f"missing required file: {path}")
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory(prefix="ai-music-daw-handoff-") as tmp:
        tmp_path = Path(tmp)
        scaffold = run(
            [
                sys.executable,
                str(SCAFFOLD),
                "--output-dir",
                str(tmp_path),
                "--date",
                "20260624",
                "--language",
                "zh",
                "--lane",
                "pop",
                "--slug",
                "night-bus",
                "--title",
                "Night Bus Confession",
                "--artist-project",
                "Example Test Artist",
                "--use-case",
                "demo",
            ]
        )
        if scaffold.returncode != 0:
            errors.append(f"scaffold failed: {scaffold.stderr.strip()}")
            print("\n".join(errors), file=sys.stderr)
            return 1

        project = tmp_path / "20260624_zh-pop_night-bus"
        empty_handoff = run([sys.executable, str(HANDOFF), "--project-root", str(project), "--strict"])
        if empty_handoff.returncode == 0:
            errors.append("strict DAW handoff should reject missing take decision and repair route")

        write(
            project / "04_prompt" / "prompt-compile-brief.md",
            """# Prompt Compile Brief

Project: Example Test Artist
Song: Night Bus Confession
Language: zh
Genre lane: Mandarin pop ballad
""",
        )
        write(
            project / "05_generations" / "take-ledger.md",
            """# Take Ledger

| take id | prompt package | provider/model | settings | source audio | persona/voice | first impression | known issue | review status |
|---|---|---|---|---|---|---|---|---|
| A01 | 04_prompt/prompt-package-v001.md | Suno current | W25/S70/A0 | none | fictional singer | pretty but generic | weak hook | reviewed |
| A02 | 04_prompt/prompt-package-v001.md | Suno current | W25/S70/A0 | none | fictional singer | strong chorus and believable groove | minor mix polish | reviewed |
| A03 | 04_prompt/prompt-package-v001.md | Suno current | W45/S55/A0 | none | fictional singer | interesting texture | AI vocal tail | reviewed |
""",
        )
        write(project / "05_generations" / "generation-evidence-audit.md", generation_evidence_audit(project))
        write(
            project / "06_review" / "blind-review.md",
            """# Blind Review

## Scores

| take | alignment | preference | hook | vocal identity | groove | form | artifact risk | decision |
|---|---:|---:|---:|---:|---:|---:|---:|---|
| A01 | 3.4 | 3.2 | 2.8 | 3.6 | 3.5 | 3.4 | 1.5 | reject |
| A02 | 4.6 | 4.5 | 4.7 | 4.3 | 4.4 | 4.5 | 1.0 | lock |
| A03 | 4.0 | 3.8 | 4.1 | 3.2 | 3.9 | 3.7 | 3.0 | repair |
""",
        )
        review = run([sys.executable, str(TAKE_REVIEW), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"])
        if review.returncode != 0:
            errors.append(f"take review failed: stdout={review.stdout.strip()} stderr={review.stderr.strip()}")

        route = run([sys.executable, str(REPAIR_ROUTER), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"])
        if route.returncode != 0:
            errors.append(f"repair router failed: stdout={route.stdout.strip()} stderr={route.stderr.strip()}")

        handoff = run([sys.executable, str(HANDOFF), "--project-root", str(project), "--write", "--allow-overwrite", "--strict"])
        if handoff.returncode != 0:
            errors.append(f"DAW handoff failed: stdout={handoff.stdout.strip()} stderr={handoff.stderr.strip()}")

        expected = [
            "08_stems-daw/best-take-lock.md",
            "08_stems-daw/daw-handoff-intent.md",
            "08_stems-daw/export-and-stems-ledger.md",
            "08_stems-daw/tempo-map-and-section-grid.md",
            "08_stems-daw/lead-sheet-and-chord-chart.md",
            "08_stems-daw/midi-transcription-and-correction.md",
            "08_stems-daw/stem-quality-triage.md",
            "08_stems-daw/human-overdub-priority.md",
            "08_stems-daw/vocal-rerecord-plan.md",
            "08_stems-daw/rhythm-section-rerecord-plan.md",
            "08_stems-daw/hybrid-arrangement-session.md",
            "08_stems-daw/mix-replacement-map.md",
            "08_stems-daw/session-versioning.md",
            "08_stems-daw/human-contribution-and-rights-link.md",
            "08_stems-daw/final-humanized-master-review.md",
            "08_stems-daw/session-pack.md",
        ]
        for rel in expected:
            if not (project / rel).exists():
                errors.append(f"missing DAW handoff output: {rel}")

        session_pack = project / "08_stems-daw" / "session-pack.md"
        if session_pack.exists():
            text = session_pack.read_text(encoding="utf-8")
            for term in [
                "Locked take: A02",
                "08_stems-daw/best-take-lock.md",
                "human-contribution-and-rights-link.md",
                "tools/prepare_music_daw_handoff.py",
                "what to keep from AI",
            ]:
                if term not in text:
                    errors.append(f"session pack missing term: {term}")

        rights_link = project / "08_stems-daw" / "human-contribution-and-rights-link.md"
        if rights_link.exists():
            text = rights_link.read_text(encoding="utf-8")
            for term in ["Human contribution ledger", "AI contribution", "Rights gate", "11_release/human-contribution-ledger.md"]:
                if term not in text:
                    errors.append(f"rights link missing term: {term}")

        no_overwrite = run([sys.executable, str(HANDOFF), "--project-root", str(project), "--write"])
        if no_overwrite.returncode != 2:
            errors.append("DAW handoff should refuse to overwrite existing outputs without --allow-overwrite")

    daw_page = WIKI_DAW.read_text(encoding="utf-8")
    project_page = WIKI_PROJECT.read_text(encoding="utf-8")
    log_text = LOG.read_text(encoding="utf-8")
    for term in [
        "tools/prepare_music_daw_handoff.py",
        "daw-handoff-intent.md",
        "session-pack.md",
        "human-contribution-and-rights-link.md",
        "--strict",
    ]:
        if term not in daw_page:
            errors.append(f"DAW workflow missing handoff term: {term}")
    for term in ["tools/prepare_music_daw_handoff.py", "08_stems-daw/session-pack.md", "human-contribution-and-rights-link.md"]:
        if term not in project_page:
            errors.append(f"song project template missing handoff term: {term}")
    if "AI 音乐 DAW 交接包工具" not in log_text:
        errors.append("wiki log missing DAW handoff entry")

    if errors:
        print("AI music DAW handoff verification failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print("AI music DAW handoff verification passed.")
    print(f"handoff: {HANDOFF}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
